Repository crystal-lang/crystal, pull requests merged in 2018-04, with the labels that each got.

#5893 Format: fix indentation in collection with comment after beginning delimiter
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#5159 Prevent invoking `method_added` macro hook recursively
  spec/compiler/semantic/hooks_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:feature, topic:compiler, topic:macros

#5901 Format: fix indentation after backslash newline
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#5899 Use LibCrystalMain.__crystal_main directly
  src/crystal/main.cr
Labels: kind:refactor, topic:stdlib

#5902 Colorize: abstract colors and support 8bit and true color
  spec/std/colorize_spec.cr
  src/colorize.cr
Labels: kind:feature, topic:stdlib

#5906 Pass an unhandled exception to at_exit block as second argument
  spec/std/kernel_spec.cr
  src/kernel.cr
Labels: kind:feature, topic:stdlib

#5909 Fix #5907 formatter bug
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
  src/float/printer/grisu3.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#5896 Refactor out variable name
  src/pretty_print.cr
Labels: kind:refactor, topic:stdlib

#5912 fix example codes (2018-04)
  src/complex.cr
  src/exception.cr
  src/http/common.cr
  src/http/formdata.cr
  src/http/formdata/builder.cr
  src/http/formdata/parser.cr
  src/http/multipart/builder.cr
  src/http/params.cr
  src/openssl/digest/digest_io.cr
  src/regex.cr
  src/spec.cr
  src/static_array.cr
  src/string.cr
  src/string_scanner.cr
  src/time.cr
  src/time/location.cr
Labels: kind:bug, topic:docs, topic:stdlib

#5894 Remove duplicated indefinite articles 'a a' in char.cr doc
  src/char.cr
Labels: kind:bug, topic:docs

#5922 Format: fix formatter bug on nesting begin/end
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:formatter

#5810 Ensure cleanup tempfile after some specs
  spec/compiler/codegen/private_spec.cr
  spec/compiler/compiler_spec.cr
  spec/std/callstack_spec.cr
  spec/std/process_spec.cr
  spec/std/tempfile_spec.cr
Labels: kind:bug, topic:compiler, topic:specs, topic:stdlib

#4196 Refactor Colorize#surround
  spec/std/colorize_spec.cr
  src/colorize.cr
  src/compiler/crystal/tools/print_hierarchy.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#5855 Format: fix formatting call having trailing comma with block
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#5726 Re-raise exceptions in the parallel macro, add documentation
  spec/std/concurrent_spec.cr
  src/concurrent.cr
Labels: kind:bug, topic:stdlib

#5760 Add Hash#last_key and Hash#last_value
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib

#5485 Work String#starts_with? with regex
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib

#5575 Alter logic in Time.leap_year? for performance
  spec/std/time/time_spec.cr
  src/time.cr
Labels: kind:refactor, topic:stdlib

#2543 Add IDNA support and integrate with DNS lookup
  spec/std/uri/punycode_spec.cr
  src/socket/addrinfo.cr
  src/uri/punycode.cr
Labels: status:accepted, topic:stdlib

#5644 init: Turn fork URL into a Markdown link
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/init/template/readme.md.ecr
Labels: kind:feature, topic:compiler, topic:tools

#5928 Improve HTTP::ChunkedContent implementation
  spec/std/http/chunked_content_spec.cr
  src/http/common.cr
  src/http/content.cr
Labels: kind:bug, kind:feature, topic:stdlib

#5785 Move Time::Location spec additions to spec_helper
  spec/std/time/location_spec.cr
  spec/std/time/spec_helper.cr
  spec/std/time/time_spec.cr
Labels: kind:bug, topic:specs, topic:stdlib

#5809 CHANGELOG: Add missing links to Github issues
  CHANGELOG.md
Labels: kind:bug, topic:infrastructure

#5606 Markdown: fix handling of code fences appearing on the same line
  spec/std/markdown/markdown_spec.cr
  src/markdown/parser.cr
Labels: kind:bug, topic:stdlib

#5839 Update CI distribution scripts
  .circleci/config.yml
Labels: kind:bug, topic:infrastructure

#5935 Include type restriction on getters in JSON/mapping
  spec/std/json/mapping_spec.cr
  src/json/mapping.cr
Labels: kind:feature, topic:stdlib

#5866 Fix codegen/asm and codegen/sizeof specs
  spec/compiler/codegen/asm_spec.cr
  spec/compiler/codegen/sizeof_spec.cr
Labels: kind:bug, topic:compiler, topic:specs

#5816 Refactor docs generator HTML scaffold
  src/compiler/crystal/tools/doc/html/_head.html
  src/compiler/crystal/tools/doc/html/_list_items.html
  src/compiler/crystal/tools/doc/html/_method_detail.html
  src/compiler/crystal/tools/doc/html/_method_summary.html
  src/compiler/crystal/tools/doc/html/_methods_inherited.html
  src/compiler/crystal/tools/doc/html/_other_types.html
  src/compiler/crystal/tools/doc/html/_sidebar.html
  src/compiler/crystal/tools/doc/html/css/style.css
  src/compiler/crystal/tools/doc/html/js/doc.js
  src/compiler/crystal/tools/doc/html/main.html
  src/compiler/crystal/tools/doc/html/type.html
  src/compiler/crystal/tools/doc/templates.cr
Labels: kind:refactor, topic:tools

#5719 Improve Ctrl-C handling of spec
  src/spec/context.cr
  src/spec/dsl.cr
Labels: kind:refactor, topic:specs

#5420 Parser: make an error on unbalanced end brace '}' in macro body
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:parser

#5930 Raise syntax error when method argument name is keyword
  spec/compiler/parser/parser_spec.cr
  spec/std/spec_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/token.cr
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:bug, topic:compiler

#5914 added documentation for Kernel#sprintf method (fixes #3124)
  src/io.cr
  src/kernel.cr
Labels: topic:docs

#5869 Add path to UNIXSocket created by UNIXServer
  spec/std/socket_spec.cr
  src/socket/unix_server.cr
  src/socket/unix_socket.cr
Labels: kind:bug, topic:stdlib

#5808 Semantic: Allow macro overload on named args
  spec/compiler/semantic/macro_overload_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler

#5584 Rename and rework File::Stat as File::Info
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/compiler/crystal/codegen/cache_dir.cr
  src/compiler/crystal/macros/macros.cr
  src/crystal/system/file_info.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/file_info.cr
  src/crystal/system/unix/getrandom.cr
  src/crystal/system/unix/urandom.cr
  src/dir.cr
  src/dir/glob.cr
  src/file.cr
  src/file/info.cr
  src/file/stat.cr
  src/file_utils.cr
  src/http/server/handlers/static_file_handler.cr
  src/io/file_descriptor.cr
  src/tempfile.cr
  src/time/location/loader.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#5577 Adds `Process.chroot`
  spec/spec_helper.cr
  spec/std/kernel_spec.cr
  spec/std/process_spec.cr
  src/lib_c/aarch64-linux-gnu/c/unistd.cr
  src/lib_c/aarch64-linux-musl/c/unistd.cr
  src/lib_c/amd64-unknown-openbsd/c/unistd.cr
  src/lib_c/arm-linux-gnueabihf/c/unistd.cr
  src/lib_c/i686-linux-gnu/c/unistd.cr
  src/lib_c/i686-linux-musl/c/unistd.cr
  src/lib_c/x86_64-linux-gnu/c/unistd.cr
  src/lib_c/x86_64-linux-musl/c/unistd.cr
  src/lib_c/x86_64-macosx-darwin/c/unistd.cr
  src/lib_c/x86_64-portbld-freebsd/c/unistd.cr
  src/process.cr
Labels: kind:feature, topic:stdlib

#5949 Fix linking to openssl
  src/openssl/lib_crypto.cr
Labels: kind:bug, topic:stdlib

#5947 Implement blocking ::sleep for win32
  src/lib_c/x86_64-windows-msvc/c/synchapi.cr
  src/prelude.cr
  src/windows_stubs.cr
Labels: kind:feature, topic:stdlib, topic:windows

#5776 Refactor `HTTP::Server` to bind to multiple addresses
  samples/http_server.cr
  spec/std/http/server/server_spec.cr
  spec/std/http/web_socket_spec.cr
  src/compiler/crystal/tools/playground/server.cr
  src/compiler/crystal/tools/playground/views/_about.html
  src/http/formdata.cr
  src/http/server.cr
Labels: breaking-change, kind:feature, topic:stdlib

#5963 Use Char instead of String in split/join calls whenever possible
  spec/compiler/codegen/macro_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/std/file_spec.cr
  spec/std/string_spec.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/config.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/tools/init.cr
  src/crypto/bcrypt/password.cr
  src/option_parser.cr
  src/regex.cr
  src/semantic_version.cr
Labels: kind:refactor, topic:stdlib

#5842 Fix ASTNode#to_s to use escape sequence correctly
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
  src/regex.cr
Labels: kind:bug, topic:compiler

#4635 [WIP] Added --include and --exclude options to format tool
  src/compiler/crystal/command/format.cr
Labels: kind:feature, topic:formatter

#5964 Fix Object.delegate to setter
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib

#4584 Implement no-copy subarray iteration (Implements #3386)
  spec/std/indexable_spec.cr
  src/indexable.cr
Labels: kind:refactor, topic:stdlib

#5968 Remove TODOs from class spec
  spec/std/class_spec.cr
Labels: kind:refactor, topic:stdlib

#5973 Fix OpenSSL binding C preprocesor hack failing on absence of headers
  src/openssl/lib_crypto.cr
Labels: kind:bug, topic:stdlib

#5962 Expand Regex to allow querying for metacharacters
  spec/std/regex_spec.cr
  src/regex.cr
Labels: kind:feature, topic:stdlib

#5977 Fix typo 'stritc' in PrettyPrint spec
  spec/std/pretty_print_spec.cr
Labels: kind:refactor, topic:compiler

#5978 pp: fix the width and indentation of second and later line contents
  spec/std/pretty_print_spec.cr
  src/macros.cr
  src/pretty_print.cr
Labels: kind:bug, topic:stdlib

#5981 Don't parse NamedTuple type without comma seperator
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler, topic:parser

#5932 Add context to errors in JSON.mapping
  spec/std/json/mapping_spec.cr
  src/json.cr
  src/json/mapping.cr
Labels: kind:feature, topic:stdlib

#5998 Adds ability to use custom separators in CSV.build
  src/csv.cr
  src/csv/builder.cr
Labels: kind:feature, topic:stdlib

#6008 Add missing tests for CSV.build with custom separator/quote_char
  spec/std/csv/csv_build_spec.cr
Labels: kind:feature, topic:specs, topic:stdlib

#6004 Remove dependency on libxml from spec runner
  spec/std/spec/junit_formatter_spec.cr
  src/spec/junit_formatter.cr
Labels: kind:refactor, topic:specs, topic:stdlib

#5794 Improve #inspect format for Time types
  spec/std/time/location_spec.cr
  spec/std/time/time_spec.cr
  src/time.cr
  src/time/format/formatter.cr
  src/time/location.cr
Labels: kind:refactor, topic:stdlib

#6013 Formatter: fix call args indent in case of backslash follows method name
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter

#5327 Improve WebSocket handshake validation
  spec/std/http/server/handlers/websocket_handler_spec.cr
  spec/std/http/web_socket_spec.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/web_socket/protocol.cr
Labels: kind:refactor, topic:stdlib

#3700 docs command: don't show error on console when not a git repository
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:bug, topic:compiler, topic:tools

#6026 Remove block argument from `loop`
  src/kernel.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#5881 Spec: add expectations starts_with, ends_with
  spec/std/spec/expectations_spec.cr
  src/spec/expectations.cr
Labels: kind:feature, topic:specs, topic:stdlib
