Repository crystal-lang/crystal, pull requests merged in 2018-05, with the labels that each got.

#6033 Fix typo in lexer_string_spec.cr
  spec/compiler/lexer/lexer_string_spec.cr
Labels: kind:refactor, topic:specs

#6036 Remove `Tempfile#unlink` dead alias
  spec/std/process_spec.cr
  src/tempfile.cr
Labels: breaking-change, topic:stdlib

#6027 Improve WebSocket handshake validation (fixed)
  spec/std/http/server/handlers/websocket_handler_spec.cr
  spec/std/http/web_socket_spec.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/web_socket/protocol.cr
Labels: kind:refactor, topic:stdlib

#5192 Disallow typeof in type restrictions
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: breaking-change, topic:stdlib

#6046 Parser: fix parsing of macro argument followed by a newline
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler

#6044 Let `p` use inspect, `pp` just pretty print values, and introduce `p!` and `pp!` which also show the expression to print
  src/kernel.cr
  src/macros.cr
Labels: kind:feature, kind:refactor, topic:stdlib

#6045 Compiler: don't fail when typeof argument doesn't have a type
  spec/compiler/semantic/primitives_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler

#5946 Fix link in openssl.cr
  src/openssl.cr
Labels: topic:docs, topic:stdlib

#6079 Optimize Tuple#to_a by preallocate Array
  src/deque.cr
  src/indexable.cr
Labels: kind:feature, topic:performance, topic:stdlib

#6077 Bug: initialize with {% @type %}
  spec/compiler/semantic/instance_var_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: kind:bug, topic:compiler

#6074 Explosive birth of automatic casts!
  spec/compiler/codegen/automatic_cast.cr
  spec/compiler/normalize/def_spec.cr
  spec/compiler/semantic/automatic_cast.cr
  spec/compiler/semantic/def_spec.cr
  spec/compiler/semantic/uninitialized_spec.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/class_vars_initializer_visitor.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/cover.cr
  src/compiler/crystal/semantic/default_arguments.cr
  src/compiler/crystal/semantic/instance_vars_initializer_visitor.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/match.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/semantic/to_s.cr
  src/compiler/crystal/semantic/transformer.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/types.cr
  src/llvm/lib_llvm.cr
  src/llvm/value_methods.cr
Labels: kind:feature, topic:compiler

#6084 Formatter: correctly handle annotation path
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#6106 Fix: annotation check failure when other annotations are present
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler, topic:macros

#6111 Fix: faster compilation for JSON::MappingError
  src/json/mapping.cr
Labels: kind:refactor, topic:compiler

#6118 Fix Time.new and Time.utc
  src/time.cr
Labels: kind:bug, topic:stdlib

#6123 Fix: can't require after annotation
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler

#6127 Fix incorrect formatting of ending expression after heredoc
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter

#6131 OptionParser documentation improvement
  src/option_parser.cr
Labels: kind:feature, topic:docs

#6141 Fix #6136. Remove no longer used Dockerfile
  Dockerfile
  Dockerfile.release
Labels: topic:infrastructure

#6142 Fixes documentation of Char.hex?
  src/char.cr
Labels: kind:bug, topic:docs, topic:stdlib
