Repository crystal-lang/crystal, pull requests merged in 2018-09, with the labels that each got.

#6538 Fix ASTNode#to_s of non-unary operator call without argument
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#6633 Compiler: improve error traces regarding `return`, `next` and `break`
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:feature, topic:compiler

#6638 Compiler: fix `super` inside macros not working correctly
  spec/compiler/semantic/super_spec.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/semantic/normalizer.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
Labels: kind:bug, topic:stdlib

#6654 Restrict Enum#parse to String
  src/enum.cr
Labels: topic:docs, topic:stdlib

#6658 Update CI to use 0.26.1
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#6667 Fix formatting `{% verbatim do %} ... {% end %}` outside macro
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:macros

#6666 Fix `ASTNode#to_s` for multiline macro expression
  spec/compiler/parser/to_s_spec.cr
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler, topic:macros

#5145 Demonstrate Parameters for HTTP::Client
  src/http/client.cr
Labels: topic:docs

#6680 Support multiple output values in inline asm
  spec/compiler/codegen/asm_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/codegen/asm.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/syntax/transformer.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:compiler

#6649 Simplify windows rescue block codegen
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/exception.cr
Labels: kind:bug, topic:compiler, topic:windows

#6682 Add missing type declaration in property? docs
  src/object.cr
Labels: kind:bug, topic:docs

#6688 Make asm parsing and formatting more robust
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler

#6628 Fix to_h inspect in NamedTuple
  spec/compiler/semantic/named_tuple_spec.cr
  spec/std/named_tuple_spec.cr
  src/named_tuple.cr
Labels: kind:refactor, topic:stdlib

#6659 Clean up tuple elements after unreachable
  spec/compiler/codegen/def_spec.cr
  spec/compiler/semantic/cleanup_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler

#5958 Add spec for HTTP::Server#close
  spec/std/http/server/server_spec.cr
Labels: kind:feature, topic:specs, topic:stdlib

#6594 Unify way of printing exceptions from within fibers
  src/fiber.cr
  src/kernel.cr
Labels: kind:refactor, topic:stdlib

#6689 Fix `==` and `!=` when comparing signed vs unsigned integers
  spec/std/float_printer/diy_fp_spec.cr
  spec/std/int_spec.cr
  src/compiler/crystal/codegen/primitives.cr
  src/iconv.cr
  src/io/encoding.cr
  src/llvm/generic_value.cr
  src/string.cr
Labels: breaking-change, kind:bug, topic:compiler

#6678 Fix Int#downto with unsigned int going down to 0.
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:bug, topic:stdlib

#6641 Don't try to mess with closed FDs when creating a subprocess
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/io/file_descriptor.cr
  src/process.cr
Labels: kind:bug, topic:stdlib

#6699 Remove deprecated alias HTTP::Server#bind_ssl
  spec/std/http/server/server_spec.cr
  src/http/server.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#6665 Fix `ASTNode#to_s` for `{% verbatim do %} ... {% end %}`
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler, topic:macros

#6703 Fix Crystal::System::FileDescriptor to use @fd ivar directly
  src/crystal/system/unix/file_descriptor.cr
Labels: kind:refactor, topic:stdlib

#6700 Refactor: Split socket_spec.cr into separate files
  spec/std/socket/address_spec.cr
  spec/std/socket/addrinfo_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/spec_helper.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
  spec/std/socket/unix_server_spec.cr
  spec/std/socket/unix_socket_spec.cr
  spec/std/socket_spec.cr
Labels: kind:refactor, topic:specs, topic:stdlib

#6706 Fix Socket#reuse_port? if SO_REUSEPORT is not supported
  src/socket.cr
Labels: kind:bug, topic:stdlib

#6712 Add caller file and line to Nil#not_nil!
  src/nil.cr
Labels: kind:feature, topic:compiler

#6714 Channel: make some methods protected and mark some others as nodoc
  src/concurrent/channel.cr
Labels: topic:docs, topic:stdlib

#6427 Add :default to colorize and document ColorRGB, Color256
  src/colorize.cr
Labels: kind:bug, topic:stdlib

#6732 Allow `it` and `pending` to be used without blocks
  src/spec/methods.cr
Labels: kind:feature, topic:specs, topic:stdlib

#6738 Support OpenSSL 1.1.1
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/bio.cr
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
Labels: kind:feature, topic:stdlib

#6739 Fix build in travis due to git checkout depth
  .travis.yml
Labels: kind:bug, topic:infrastructure

#6740 Fix spec for Time::Location.load_local with TZ=nil
  spec/std/time/location_spec.cr
Labels: kind:refactor, topic:specs

#6743 Switch order of "xmlns" and prefix in XML::Builder#namespace
  spec/std/xml/builder_spec.cr
  src/xml/builder.cr
Labels: kind:bug, topic:stdlib

#6719 Add Hash/Indexable#dig/dig?
  spec/std/hash_spec.cr
  spec/std/indexable_spec.cr
  spec/std/json/any_spec.cr
  spec/std/named_tuple_spec.cr
  spec/std/yaml/any_spec.cr
  src/hash.cr
  src/indexable.cr
  src/json/any.cr
  src/named_tuple.cr
  src/yaml/any.cr
Labels: kind:feature, topic:stdlib

#6297 Remove :nodoc: from singular method aliases, add Int#microsecond alias
  src/time/span.cr
Labels: topic:docs, topic:stdlib

#6788 Add support for specifying the build date
  src/compiler/crystal/config.cr
Labels: topic:infrastructure

#5438 Improve readability of Float::Printer::* docs
  src/float/printer.cr
  src/float/printer/diy_fp.cr
  src/float/printer/grisu3.cr
  src/float/printer/ieee.cr
Labels: kind:feature, topic:docs, topic:stdlib

#6790 Fix YAML::Schema::FailSafe.parse and parse_all and add specs
  spec/std/yaml/schema/fail_safe_spec.cr
  src/yaml/schema/fail_safe.cr
Labels: kind:bug, topic:stdlib

#6778 Use the third person in method docs
  src/crystal/system/dir.cr
  src/file.cr
  src/http/client.cr
  src/http/cookie.cr
  src/http/params.cr
  src/http/request.cr
  src/io/syscall.cr
  src/iterator.cr
  src/object.cr
  src/openssl/ssl/context.cr
  src/regex.cr
  src/regex/match_data.cr
Labels: kind:bug, topic:docs

#6889 Fix ChecksumReader.write error
  src/zip/checksum_reader.cr
  src/zip/zip.cr
Labels: kind:bug, topic:docs
