Repository crystal-lang/crystal, pull requests merged in 2018-06, with the labels that each got.

#6150 Drop 'when _' support
  spec/compiler/normalize/case_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: breaking-change, topic:compiler

#3652 Add button in playground to run formatter
  src/compiler/crystal/tools/playground/public/application.css
  src/compiler/crystal/tools/playground/public/session.js
  src/compiler/crystal/tools/playground/server.cr
  src/compiler/crystal/tools/playground/views/_index.html
  src/compiler/crystal/tools/playground/views/layout.html.ecr
Labels: kind:feature, topic:playground

#6147 Allow HTTP::Client to use ipv6 addresses
  spec/std/http/client/client_spec.cr
  spec/std/uri_spec.cr
  src/http/client.cr
  src/uri.cr
Labels: kind:bug, topic:stdlib

#6161 Add File.same?(path1, path2) with follow_symlinks option
  spec/std/file_spec.cr
  src/crystal/system/unix/file_info.cr
  src/file.cr
  src/file/info.cr
Labels: kind:feature, topic:stdlib

#4787 Added Float32 and Float64 consts
  spec/std/float_spec.cr
  src/float.cr
Labels: kind:feature, topic:stdlib

#5380 Execute 128bits Hasher specs that are now passing
  spec/std/crystal/hasher_spec.cr
Labels: kind:feature, topic:specs, topic:stdlib

#6082 JSON::Serializable
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json.cr
  src/json/next/serialization.cr
  src/yaml.cr
  src/yaml/next/serialization.cr
Labels: kind:feature, topic:stdlib

#6166 Update to codemirror 5.38.0
  src/compiler/crystal/tools/playground/public/vendor/codemirror-5.38.0/addon/comment/comment.js
  src/compiler/crystal/tools/playground/public/vendor/codemirror-5.38.0/lib/codemirror.css
  src/compiler/crystal/tools/playground/public/vendor/codemirror-5.38.0/lib/codemirror.js
  src/compiler/crystal/tools/playground/public/vendor/codemirror-5.38.0/mode/crystal/crystal.js
  src/compiler/crystal/tools/playground/public/vendor/codemirror-5.38.0/theme/neat.css
  src/compiler/crystal/tools/playground/views/layout.html.ecr
Labels: topic:playground

#6160 Allow redefining None to 0 for @[Flags] enum
  spec/compiler/semantic/enum_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:compiler

#5123 Add custom time format implementations
  spec/std/http/http_spec.cr
  spec/std/http/server/handlers/static_file_handler_spec.cr
  spec/std/json/serialization_spec.cr
  spec/std/time/custom_formats_spec.cr
  spec/std/time/time_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/http/common.cr
  src/http/cookie.cr
  src/http/server/handlers/static_file_handler.cr
  src/json/from_json.cr
  src/json/to_json.cr
  src/time.cr
  src/time/format.cr
  src/time/format/custom/http_date.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/custom/rfc_2822.cr
  src/time/format/custom/rfc_3339.cr
  src/time/format/custom/yaml_date.cr
  src/time/format/formatter.cr
  src/time/format/parser.cr
  src/time/format/pattern.cr
  src/yaml/schema/core.cr
  src/yaml/schema/core/time_parser.cr
  src/yaml/to_yaml.cr
Labels: breaking-change, kind:feature, topic:stdlib

#6167 Add Time#at_{beginning,end}_of_second
  spec/std/time/time_spec.cr
  src/time.cr
Labels: kind:feature, topic:stdlib

#6178 Fix Object.delegate for []=
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib

#6179 Fix docs for new HTTP::Server API
  src/http/server.cr
Labels: kind:bug, topic:docs, topic:stdlib

#5736 Add copy method to record macro.
  spec/std/record_spec.cr
  src/macros.cr
Labels: kind:feature, status:discussion, topic:stdlib

#6187 Fix regex in "cannot find -lsome-lib" hint
  src/compiler/crystal/compiler.cr
Labels: kind:feature, topic:compiler

#6184 Fix: use Crystal::System::Random in Crystal::Hasher
  src/crystal/hasher.cr
Labels: kind:refactor, topic:stdlib

#6192 Fix formatting semicolon after block paren
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter

#5734 Documenting `Indexable#zip` and `Indexable#zip?` methods.
  src/indexable.cr
Labels: topic:docs

#6193 Increase no_output_timeout to 20m for linux builds
  .circleci/config.yml
Labels: topic:infrastructure

#6174 Add specs for Time parser to raise when time zone is missing
  spec/std/time/time_spec.cr
  src/time/format.cr
Labels: kind:refactor, topic:stdlib

#6211 Update CI to use 0.25.0
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#6208 Fix examples in Formatting and Parsing Time
  src/time.cr
Labels: topic:docs

#6209 Serializable, remove version conditions
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json.cr
  src/json/serialization.cr
  src/yaml.cr
  src/yaml/serialization.cr
Labels: kind:refactor, topic:stdlib

#5951 Add tempfile and datapath helpers to specs
  spec/compiler/compiler_spec.cr
  spec/compiler/crystal/tools/init_spec.cr
  spec/compiler/spec_helper.cr
  spec/std/callstack_spec.cr
  spec/std/data/cipher_spec.ciphertext
  spec/std/data/openssl/openssl.crt
  spec/std/data/openssl/openssl.key
  spec/std/data/static_file_handler/test.txt
  spec/std/dir_spec.cr
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
  spec/std/http/server/handlers/static_file_handler_spec.cr
  spec/std/http/web_socket_spec.cr
  spec/std/ini_spec.cr
  spec/std/io/argf_spec.cr
  spec/std/io/io_spec.cr
  spec/std/kernel_spec.cr
  spec/std/openssl/cipher_spec.cr
  spec/std/openssl/ssl/context_spec.cr
  spec/std/process_spec.cr
  spec/std/socket_spec.cr
  spec/std/spec_helper.cr
  spec/std/time/location_spec.cr
  spec/std/time/spec_helper.cr
  spec/std/zip/zip_file_spec.cr
  spec/std/zip/zip_spec.cr
  spec/support/tempfile.cr
Labels: kind:refactor, topic:specs

#6218 Add missing JSON field to docs generator output for constants
  src/compiler/crystal/tools/doc/constant.cr
  src/compiler/crystal/tools/doc/html/type.html
Labels: kind:bug, topic:docs

#6232 Macro: add missing document for ArrayLiteral#push and #unshift
  src/compiler/crystal/macros.cr
Labels: topic:docs

#6221 Finish the \a escape sequence
  spec/compiler/lexer/lexer_spec.cr
  spec/std/char_spec.cr
  spec/std/string_spec.cr
  src/char.cr
  src/compiler/crystal/syntax/lexer.cr
  src/string.cr
Labels: kind:refactor

#6222 Fix heredoc start + comma formatter
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter, topic:tools

#6244 Allow p! pp! macros to be used with tuples
  spec/std/pp_spec.cr
  src/macros.cr
Labels: kind:bug, topic:stdlib

#6234 Handle File.extname edge case
  spec/std/file_spec.cr
  src/file.cr
Labels: kind:bug, topic:stdlib

#6246 Docs: Prevent virtual types reaching docs generator
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:bug, topic:compiler, topic:docs, topic:tools

#6261 Use Exception#inspect_with_backtrace where sensible
  src/compiler/crystal/command.cr
  src/spec/context.cr
Labels: kind:refactor, topic:compiler, topic:stdlib

#6097 Added example of nesting mappings to YAML builder
  src/yaml/builder.cr
Labels: kind:feature, topic:docs

#6260 Update to latest distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#6266 Add dup and clone for JSON::Any and YAML::Any
  spec/std/json/any_spec.cr
  spec/std/yaml/any_spec.cr
  src/json/any.cr
  src/yaml/any.cr
Labels: topic:stdlib

#6274 Formatter: fix for begin ... rescue ... end
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:formatter

#6269 IO#write: return early if slice is empty
  src/crystal/system/win32/file_descriptor.cr
  src/flate/writer.cr
  src/gzip/writer.cr
  src/http/server/response.cr
  src/http/web_socket/protocol.cr
  src/io/buffered.cr
  src/io/hexdump.cr
  src/io/multi_writer.cr
  src/io/stapled.cr
  src/io/syscall.cr
  src/openssl/digest/digest_io.cr
  src/openssl/ssl/socket.cr
  src/string/builder.cr
  src/zip/checksum_writer.cr
  src/zlib/writer.cr
Labels: kind:bug, topic:stdlib

#6272 Add Time::Span#microseconds, Int#microseconds and Float#microseconds
  spec/std/time/span_spec.cr
  src/time.cr
  src/time/span.cr
Labels: kind:feature, topic:stdlib

#6267 Require "big" if requiring any "big" file
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
Labels: kind:feature, topic:stdlib

#6259 Docs: Update man page with new options (#5554)
  man/crystal.1
  src/compiler/crystal/command.cr
Labels: topic:docs, topic:infrastructure

#6277 Fix: generic Socket#accept? is broken
  spec/std/socket_spec.cr
  src/socket.cr
Labels: kind:bug, topic:stdlib

#6282 Correctly parse \A (and others) inside %r{...} inside macros
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler

#6292 Don't find unbound type parameter in main code inside generic type
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_lookup.cr
Labels: kind:bug, topic:compiler
