Repository crystal-lang/crystal, pull requests merged in 2018-10, with the labels that each got.

#6764 removed filter/blur properties
  src/compiler/crystal/tools/doc/html/css/style.css
Labels: topic:docs

#6904 Fix CSV.build about the corner case of quoting Chars and Symbols
  spec/std/csv/csv_build_spec.cr
  src/csv/builder.cr
Labels: kind:bug, topic:stdlib

#6909 Refactor HTTP client spec to remove inheritance for test server
  spec/std/http/client/client_spec.cr
Labels: kind:refactor, topic:specs, topic:stdlib

#6915 Fix empty case statement normalizes to condition expression
  spec/compiler/codegen/case_spec.cr
  spec/compiler/normalize/case_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler

#6897 Fiber/Scheduler refactorings
  src/channel.cr
  src/concurrent.cr
  src/crystal/event.cr
  src/crystal/event_loop.cr
  src/crystal/lib_event2.cr
  src/crystal/scheduler.cr
  src/crystal/system/unix/file_descriptor.cr
  src/docs_main.cr
  src/fiber.cr
  src/fiber/aarch64.cr
  src/fiber/arm.cr
  src/fiber/i686.cr
  src/fiber/x86_64.cr
  src/io/syscall.cr
  src/kernel.cr
  src/lib_c/amd64-unknown-openbsd/c/pthread.cr
  src/lib_c/amd64-unknown-openbsd/c/sys/types.cr
  src/mutex.cr
  src/socket.cr
  src/thread.cr
  src/thread/linked_list.cr
Labels: kind:refactor, topic:stdlib

#6555 Change Time::DayOfWeek to ISO ordinal numbering based on Monday = 1
  spec/std/time/time_spec.cr
  src/crystal/system/win32/time.cr
  src/time.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/formatter.cr
Labels: kind:feature, topic:stdlib

#6711 Improve socket specs
  spec/std/socket/socket_spec.cr
  spec/std/socket/spec_helper.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
  spec/std/socket/unix_server_spec.cr
Labels: kind:refactor, topic:specs, topic:stdlib

#6911 Update Contributing section in README.md
  README.md
Labels: topic:docs

#6926 Accessibility Fix in Doc Generation HTML
  src/compiler/crystal/tools/doc/html/_sidebar.html
Labels: topic:docs

#6927 Improve support for parsing and formatting //
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter

#6891 Add floor divisions operator
  spec/std/float_spec.cr
  spec/std/int_spec.cr
  src/float.cr
  src/int.cr
Labels: kind:feature, topic:stdlib

#6925 Fix 4 typos in StringLiteral#gsub and #tr errors
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:compiler

#6930 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#6758 Improve sprintf docs, minor String::Formatter refactors
  src/kernel.cr
  src/string/formatter.cr
Labels: kind:bug, topic:docs

#6681 Add support for ISO calendar week to Time
  spec/std/time/format_spec.cr
  spec/std/time/time_spec.cr
  src/time.cr
  src/time/format.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/formatter.cr
  src/time/format/parser.cr
  src/time/format/pattern.cr
Labels: kind:feature, topic:stdlib

#6720 Treat untyped element in tuple and named tuple
  spec/compiler/semantic/named_tuple_spec.cr
  spec/compiler/semantic/tuple_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler

#6744 Refactor Process in preparation for Windows support
  src/io/file_descriptor.cr
  src/process.cr
Labels: breaking-change, kind:refactor, topic:stdlib, topic:windows

#6928 Detect and warn on stack overflow
  spec/std/kernel_spec.cr
  src/fiber.cr
  src/lib_c/aarch64-linux-gnu/c/sys/resource.cr
  src/lib_c/aarch64-linux-musl/c/sys/resource.cr
  src/lib_c/amd64-unknown-openbsd/c/sys/resource.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/resource.cr
  src/lib_c/i686-linux-gnu/c/sys/resource.cr
  src/lib_c/i686-linux-musl/c/sys/resource.cr
  src/lib_c/x86_64-linux-gnu/c/sys/resource.cr
  src/lib_c/x86_64-linux-musl/c/sys/resource.cr
  src/lib_c/x86_64-macosx-darwin/c/sys/resource.cr
  src/lib_c/x86_64-portbld-freebsd/c/sys/resource.cr
  src/signal.cr
Labels: kind:feature, topic:stdlib

#6917 Fixed OpenSSL bindings to work with LibreSSL
  spec/std/openssl/ssl/context_spec.cr
  src/openssl.cr
  src/openssl/bio.cr
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
  src/openssl/ssl/socket.cr
Labels: kind:feature, topic:stdlib

#6940 Fix passing reuse_port in TCPServer's listen backlog parameter
  src/http/server.cr
  src/socket.cr
  src/socket/tcp_server.cr
  src/socket/unix_server.cr
Labels: kind:bug, topic:stdlib

#6710 Add Socket::IPAddress predicates and constants
  spec/std/socket/address_spec.cr
  src/compiler/crystal/tools/playground/server.cr
  src/http/server.cr
  src/socket/address.cr
Labels: kind:feature, topic:stdlib

#6944 POSIX threads corrections & enhancements
  spec/std/thread/condition_variable_spec.cr
  spec/std/thread/mutex_spec.cr
  spec/std/thread_spec.cr
  src/gc/boehm.cr
  src/lib_c/aarch64-linux-gnu/c/pthread.cr
  src/lib_c/aarch64-linux-gnu/c/sched.cr
  src/lib_c/aarch64-linux-musl/c/pthread.cr
  src/lib_c/aarch64-linux-musl/c/sched.cr
  src/lib_c/amd64-unknown-openbsd/c/pthread.cr
  src/lib_c/amd64-unknown-openbsd/c/sched.cr
  src/lib_c/arm-linux-gnueabihf/c/pthread.cr
  src/lib_c/arm-linux-gnueabihf/c/sched.cr
  src/lib_c/i686-linux-gnu/c/pthread.cr
  src/lib_c/i686-linux-gnu/c/sched.cr
  src/lib_c/i686-linux-musl/c/pthread.cr
  src/lib_c/i686-linux-musl/c/sched.cr
  src/lib_c/x86_64-linux-gnu/c/pthread.cr
  src/lib_c/x86_64-linux-gnu/c/sched.cr
  src/lib_c/x86_64-linux-musl/c/pthread.cr
  src/lib_c/x86_64-linux-musl/c/sched.cr
  src/lib_c/x86_64-macosx-darwin/c/pthread.cr
  src/lib_c/x86_64-macosx-darwin/c/sched.cr
  src/lib_c/x86_64-portbld-freebsd/c/pthread.cr
  src/lib_c/x86_64-portbld-freebsd/c/sched.cr
  src/thread.cr
  src/thread/condition_variable.cr
  src/thread/mutex.cr
Labels: kind:feature, kind:refactor, topic:stdlib

#6946 Optimized Array#skip
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:feature, topic:performance, topic:stdlib

#6950 Fix JSON::Serializable docs.
  src/json/serialization.cr
Labels: kind:bug, topic:docs

#6916 Let Zlib::Reader, Gzip::Reader and Flate::Reader include IO::Buffered for optimized performance
  spec/std/flate/flate_spec.cr
  spec/std/gzip/gzip_spec.cr
  spec/std/zlib/reader_spec.cr
  src/flate/reader.cr
  src/gzip/reader.cr
  src/zlib/reader.cr
Labels: topic:performance, topic:stdlib

#6958 Use check_open in {Zlib,Gzip,Flate}::Reader#unbuffered_rewind
  src/flate/reader.cr
  src/gzip/reader.cr
  src/zlib/reader.cr
Labels: kind:refactor, topic:stdlib

#6963 Fix typos
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/exception.cr
  src/file.cr
  src/io/file_descriptor.cr
  src/io/stapled.cr
  src/json/from_json.cr
  src/process.cr
  src/semantic_version.cr
  src/socket/addrinfo.cr
  src/spec/expectations.cr
  src/string.cr
  src/time.cr
  src/tuple.cr
  src/zip/writer.cr
Labels: kind:bug, topic:docs, topic:stdlib

#6966 Add VERSION file
  .circleci/config.yml
  .travis.yml
  Makefile
  VERSION
  bin/ci
  spec/compiler/compiler_spec.cr
  src/compiler/crystal/config.cr
  src/compiler/crystal/program.cr
Labels: topic:infrastructure

#6995 fix failing SIGSEGV spec
  spec/std/kernel_spec.cr
Labels: kind:bug, topic:specs, topic:stdlib

#6296 Replace `Indexable#at` with `#fetch`
  samples/2048.cr
  spec/std/array_spec.cr
  spec/std/deque_spec.cr
  spec/std/hash_spec.cr
  spec/std/http/headers_spec.cr
  spec/std/http/params_spec.cr
  spec/std/indexable_spec.cr
  src/array.cr
  src/bit_array.cr
  src/deque.cr
  src/hash.cr
  src/http/headers.cr
  src/http/params.cr
  src/indexable.cr
  src/slice.cr
  src/static_array.cr
  src/string/formatter.cr
  src/tuple.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#7005 Improve Contributors section of README template
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/init/template/readme.md.ecr
Labels: kind:refactor, topic:tools

#6994 allow pointer/UInt subtraction
  spec/std/pointer_spec.cr
  src/pointer.cr
Labels: kind:bug, topic:stdlib

#6971 Document Top Level Namespace constants
  src/kernel.cr
Labels: topic:docs, topic:stdlib

#6629 Check for FreeBSD 11.x instead of 12
  src/compiler/crystal/semantic/flags.cr
  src/lib_c/x86_64-portbld-freebsd/c/dirent.cr
  src/lib_c/x86_64-portbld-freebsd/c/sys/stat.cr
  src/lib_c/x86_64-portbld-freebsd/c/sys/types.cr
Labels: kind:feature, topic:stdlib
