Repository crystal-lang/crystal, pull requests merged in 2018-08, with the labels that each got.

#6466 Fix Dir.glob to list broken symlinks
  spec/std/dir_spec.cr
  src/dir/glob.cr
Labels: kind:bug, topic:stdlib

#6369 Add location as required argument for Time.parse
  spec/std/time/time_spec.cr
  src/time.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#6286 Add TAP formatter to spec suite
  spec/std/spec/tap_formatter_spec.cr
  src/spec.cr
  src/spec/context.cr
  src/spec/dsl.cr
  src/spec/formatter.cr
  src/spec/junit_formatter.cr
  src/spec/tap_formatter.cr
Labels: kind:feature, topic:stdlib

#6322 JSON/YAML: error if a maximum nesting is reached (prevents stack overflow)
  spec/std/json/builder_spec.cr
  spec/std/yaml/builder_spec.cr
  src/json/builder.cr
  src/yaml/builder.cr
Labels: breaking-change, kind:feature, topic:stdlib

#6474 Docs: minor edit in IO::Buffered related to #read_buffering?
  src/io/buffered.cr
Labels: topic:docs

#6476 Add API docs for pp, p! and pp! macro methods
  src/compiler/crystal/macros.cr
Labels: kind:refactor, topic:docs

#6477 Add closed state to HTTP::Server::Response
  spec/std/http/server/server_spec.cr
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib

#6315 fix example codes (2018-06)
  src/concurrent.cr
  src/file.cr
  src/file_utils.cr
  src/http/common.cr
  src/json/mapping.cr
  src/json/serialization.cr
  src/time.cr
  src/time/format/custom/http_date.cr
  src/time/location.cr
Labels: topic:docs

#6488 Fix typo in StaticArray docs
  src/static_array.cr
Labels: topic:docs

#5960 Add OpenSSL::SSL::Server and HTTP::Server#bind_ssl
  spec/std/http/server/server_spec.cr
  spec/std/http/web_socket_spec.cr
  spec/std/openssl/ssl/server_spec.cr
  spec/support/ssl.cr
  src/http/server.cr
  src/openssl/ssl/server.cr
  src/socket/server.cr
Labels: breaking-change, kind:feature, topic:stdlib

#6491 Fix typo in serialization docs
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: topic:docs

#6487 Fix Char docs
  src/char.cr
Labels: kind:refactor, topic:docs

#6489 Fix identical link generation prevention for the "Defined in" section (docs)
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/types.cr
Labels: kind:refactor, topic:compiler, topic:docs

#6453 rename alias HTTP::Handler::Proc to HTTP::Handler::HandlerProc
  spec/std/http/server/handlers/compress_handler_spec.cr
  spec/std/http/server/handlers/websocket_handler_spec.cr
  src/http/server.cr
  src/http/server/handler.cr
  src/http/server/request_processor.cr
Labels: kind:refactor, topic:stdlib

#6311 added syntax sugar to check if URI is absolute or relative
  spec/std/uri_spec.cr
  src/uri.cr
Labels: kind:feature, topic:stdlib

#6494 Fixes a typo
  src/pointer.cr
Labels: topic:docs

#6419 Support exception handling on windows
  spec/compiler/codegen/exception_spec.cr
  spec/std/dir_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/dir.cr
  src/llvm/function.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
  src/raise.cr
Labels: kind:feature, topic:compiler, topic:windows

#6493 Removes unnecessary addition
  src/array.cr
Labels: kind:refactor, topic:stdlib

#6481 Set default host in HTTP::Client#exec
  spec/std/http/client/client_spec.cr
  src/http/client.cr
Labels: kind:bug, topic:stdlib

#6501 Add raise Errno if Process.new fails to exec
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:bug, topic:stdlib

#6496 Fix docs of UUID enums
  src/uuid.cr
Labels: topic:docs

#6324 Fix: Disallow setters with multiple arguments
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/object.cr
Labels: kind:bug, topic:compiler

#6504 Fix: type var that resolves to number in restriction didn't work
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/semantic/type_lookup.cr
Labels: kind:bug, topic:compiler

#6530 Fix HTTP::Server specs to use free ports in expectations
  spec/std/http/server/server_spec.cr
Labels: kind:refactor, topic:specs

#6515 Use enum (flags) instead of hardcoded string values for emit kinds
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
Labels: kind:refactor, topic:compiler

#6533 Add tls scheme to HTTP::Server#bind and rename HTTP::Server#bind_ssl
  spec/std/http/server/server_spec.cr
  spec/std/http/web_socket_spec.cr
  src/http/server.cr
Labels: breaking-change, kind:refactor, topic:stdlib

#6531 Fix Object#def_hash when passing Symbols
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib

#6535 Format: fix formatting newline before &.method in call
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler, topic:formatter

#4385 Add Hash#transform_keys and Hash#transform_values
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib

#6550 Update CI to use 0.26.0
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#6551 Restore #bind_ssl as deprecated api
  spec/std/http/server/server_spec.cr
  src/http/server.cr
Labels: topic:stdlib

#6518 Reopen standard handles when they are a TTY
  src/crystal/main.cr
  src/io/file_descriptor.cr
  src/kernel.cr
  src/lib_c/aarch64-linux-gnu/c/unistd.cr
  src/lib_c/aarch64-linux-musl/c/unistd.cr
  src/lib_c/amd64-unknown-openbsd/c/unistd.cr
  src/lib_c/arm-linux-gnueabihf/c/unistd.cr
  src/lib_c/i686-linux-gnu/c/unistd.cr
  src/lib_c/i686-linux-musl/c/unistd.cr
  src/lib_c/x86_64-linux-gnu/c/unistd.cr
  src/lib_c/x86_64-linux-musl/c/unistd.cr
  src/lib_c/x86_64-macosx-darwin/c/unistd.cr
  src/lib_c/x86_64-portbld-freebsd/c/unistd.cr
  src/process.cr
  src/signal.cr
Labels: kind:feature, topic:stdlib

#6562 Spec: fix DotFormatter to flush after every spec
  src/spec/formatter.cr
Labels: kind:bug, topic:specs, topic:stdlib

#6541 Allow to call `~` with `foo.~` style
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#6567 Fix formatting empty heredoc
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:formatter

#6587 Macros: evaluate yield expressions
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:bug, topic:compiler

#6596 Fix typo in Crystal playground
  src/compiler/crystal/tools/playground/public/application.js
Labels: kind:bug, topic:playground

#6497 Make Spec compile on win32
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/spec.cr
  src/spec/dsl.cr
Labels: topic:specs, topic:stdlib, topic:windows

#6578 Fix Time::Format API doc
  src/time/format/custom/http_date.cr
  src/time/format/custom/rfc_2822.cr
  src/time/format/custom/rfc_3339.cr
Labels: kind:bug, topic:docs

#6610 Fix zlib missing handling of buffer error
  spec/std/zlib/reader_spec.cr
  src/flate/flate.cr
  src/flate/reader.cr
  src/flate/writer.cr
  src/lib_z/lib_z.cr
Labels: kind:bug, topic:stdlib

#6612 Bump distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#6458 Fix JSON::Serializable with 2 args, and YAML::Serializable with 3 arg…
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib

#6574 Reorganize Time specs
  spec/std/time/format_spec.cr
  spec/std/time/location_spec.cr
  spec/std/time/span_spec.cr
  spec/std/time/spec_helper.cr
  spec/std/time/time_spec.cr
Labels: kind:refactor, topic:specs

#6583 Make String::Builder#chomp! returns self
  spec/std/string_builder_spec.cr
  src/string/builder.cr
Labels: kind:feature, topic:stdlib

#6539 Remove {% if properties.size > 0 %} conditions
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:refactor, topic:compiler

#6514 Parser: give syntax error on comma after newline in argument list
  spec/compiler/crystal/tools/playground_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: breaking-change, topic:compiler

#6617 Compiler: resolve generics in macros, and add `Genreic#resolve` and `Generic#resolve?` macro methods
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, kind:feature, topic:compiler

#6614 Spec: add expectation be_empty
  spec/std/spec/expectations_spec.cr
  src/spec/expectations.cr
Labels: kind:feature, topic:specs, topic:stdlib

#6485 Remove Tempfile
  spec/compiler/codegen/private_spec.cr
  spec/spec_helper.cr
  spec/std/dir_spec.cr
  spec/std/file/tempfile_spec.cr
  spec/std/file_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/tempfile_spec.cr
  spec/support/tempfile.cr
  src/compiler/crystal/tools/playground/server.cr
  src/crystal/system/unix/dir.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/dir.cr
  src/crystal/system/win32/file.cr
  src/dir.cr
  src/docs_main.cr
  src/file.cr
  src/file/tempfile.cr
  src/http/formdata.cr
  src/tempfile.cr
Labels: breaking-change, kind:feature, topic:stdlib

#6363 Enable Time::Location loader on win32
  spec/std/time/location_spec.cr
  spec/std/time/time_spec.cr
  src/time/location.cr
  src/time/location/loader.cr
Labels: kind:feature, topic:stdlib, topic:windows
