Repository crystal-lang/crystal, pull requests merged in 2019-01, with the labels that each got.

#7246 Update LICENSE's copyright year
  LICENSE
Labels: kind:docs

#6556 Standardize methods between JSON::Any/YAML::Any
  spec/std/json/any_spec.cr
  spec/std/yaml/any_spec.cr
  src/json/any.cr
  src/yaml/any.cr
Labels: kind:feature, kind:refactor, topic:stdlib:serialization

#6702 Add Errno#errno_message getter
  src/errno.cr
Labels: kind:feature, topic:stdlib

#7240 Format: fix to format newline after &.foo in call
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#7239 Implement StringLiteral#count
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#7250 Specs: Add missing tempfile cleanup
  spec/std/file/tempfile_spec.cr
Labels: kind:specs, topic:stdlib:files

#6968 Remove quotes from overflow symbols in formatter spec
  spec/compiler/formatter/formatter_spec.cr
Labels: kind:refactor, topic:tools:formatter

#6975 Expose LibCrypt's PKCS5_PBKDF2_HMAC
  spec/std/openssl/hmac_spec.cr
  spec/std/openssl/pkcs5_spec.cr
  src/oauth2/access_token/mac.cr
  src/openssl/algorithm.cr
  src/openssl/hmac.cr
  src/openssl/lib_crypto.cr
  src/openssl/pkcs5.cr
Labels: kind:feature, topic:stdlib:crypto

#6894 Allow creating sockets from raw file descriptors
  src/socket.cr
  src/socket/tcp_server.cr
  src/socket/tcp_socket.cr
  src/socket/unix_server.cr
  src/socket/unix_socket.cr
Labels: kind:feature, topic:stdlib:networking

#7226 Add unsafe number ops
  spec/compiler/codegen/convert_spec.cr
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/big/big_rational_spec.cr
  spec/std/int_spec.cr
  spec/std/number_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
  src/compiler/crystal/codegen/primitives.cr
  src/enum.cr
  src/float.cr
  src/int.cr
  src/primitives.cr
Labels: kind:feature, topic:compiler, topic:stdlib:numeric

#7131 Improve too big tuple and named tuple error message
  spec/compiler/semantic/tuple_spec.cr
  src/compiler/crystal/semantic/bindings.cr
Labels: kind:feature, topic:compiler:semantic

#7256 Overflow prepare stdlib
  spec/std/hash_spec.cr
  spec/std/number_spec.cr
  src/base64.cr
  src/char/reader.cr
  src/crypto/bcrypt.cr
  src/crypto/bcrypt/base64.cr
  src/crypto/blowfish.cr
  src/crystal/hasher.cr
  src/debug/dwarf/info.cr
  src/debug/dwarf/line_numbers.cr
  src/digest/md5.cr
  src/digest/sha1.cr
  src/float/printer/grisu3.cr
  src/float/printer/ieee.cr
  src/hash.cr
  src/iconv.cr
  src/json/from_json.cr
  src/json/lexer.cr
  src/json/pull_parser.cr
  src/number.cr
  src/pointer.cr
  src/random.cr
  src/random/isaac.cr
  src/random/pcg32.cr
  src/string.cr
  src/time/span.cr
  src/yaml/from_yaml.cr
Labels: kind:refactor, topic:stdlib

#7266 Compiler: error if defining initialize inside enum
  spec/compiler/codegen/enum_spec.cr
  spec/compiler/semantic/enum_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler, topic:lang

#7262 Overflow prepare compiler
  spec/compiler/codegen/alias_spec.cr
  spec/compiler/codegen/array_literal_spec.cr
  spec/compiler/codegen/block_spec.cr
  spec/compiler/codegen/c_struct_spec.cr
  spec/compiler/codegen/class_spec.cr
  spec/compiler/codegen/class_var_spec.cr
  spec/compiler/codegen/closure_spec.cr
  spec/compiler/codegen/const_spec.cr
  spec/compiler/codegen/def_spec.cr
  spec/compiler/codegen/double_splat_spec.cr
  spec/compiler/codegen/enum_spec.cr
  spec/compiler/codegen/extern_spec.cr
  spec/compiler/codegen/generic_class_spec.cr
  spec/compiler/codegen/hash_literal_spec.cr
  spec/compiler/codegen/hooks_spec.cr
  spec/compiler/codegen/is_a_spec.cr
  spec/compiler/codegen/macro_spec.cr
  spec/compiler/codegen/magic_constants_spec.cr
  spec/compiler/codegen/method_missing_spec.cr
  spec/compiler/codegen/module_spec.cr
  spec/compiler/codegen/named_args_spec.cr
  spec/compiler/codegen/named_tuple_spec.cr
  spec/compiler/codegen/new_spec.cr
  spec/compiler/codegen/next_spec.cr
  spec/compiler/codegen/op_assign_spec.cr
  spec/compiler/codegen/pointer_spec.cr
  spec/compiler/codegen/previous_def_spec.cr
  spec/compiler/codegen/primitives_spec.cr
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/codegen/splat_spec.cr
  spec/compiler/codegen/ssa_spec.cr
  spec/compiler/codegen/super_spec.cr
  spec/compiler/codegen/tuple_spec.cr
  spec/compiler/codegen/uninitialized_spec.cr
  spec/compiler/codegen/union_type_spec.cr
  spec/compiler/codegen/until_spec.cr
  spec/compiler/codegen/var_spec.cr
  spec/compiler/codegen/virtual_spec.cr
  spec/compiler/codegen/while_spec.cr
  spec/compiler/codegen/yield_with_scope_spec.cr
  spec/compiler/semantic/c_struct_spec.cr
  spec/compiler/semantic/lib_spec.cr
  src/compiler/crystal/semantic/conversions.cr
  src/compiler/crystal/semantic/lib.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/types.cr
  src/llvm/generic_value.cr
Labels: kind:refactor, topic:compiler

#6735 Give proper error when trying to instantiate Module
  spec/compiler/semantic/module_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:feature, topic:compiler

#7288 Compiler: only give named args errors when there's a single overload
  spec/compiler/semantic/named_args_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler

#7291 Get SNI for OpenSSL
  spec/std/openssl/ssl/server_spec.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/socket.cr
Labels: kind:feature, topic:stdlib:networking

#7077 Add MIME::MediaType
  spec/std/http/client/response_spec.cr
  spec/std/http/multipart/builder_spec.cr
  spec/std/mime/media_type_spec.cr
  src/http/client/response.cr
  src/http/common.cr
  src/http/multipart.cr
  src/http/multipart/builder.cr
  src/mime/media_type.cr
Labels: kind:feature, topic:stdlib

#7295 Class: let `to_s` be independent of the `name` method
  spec/std/class_spec.cr
  src/class.cr
Labels: kind:feature, topic:stdlib

#7301 Update ISSUE_TEMPLATE to include forum
  ISSUE_TEMPLATE.md
Labels: kind:docs

#6664 Add docs for file open modes
  src/crystal/system/file.cr
  src/file.cr
Labels: kind:docs, topic:stdlib:files

#7310 Compiler: fix automatic casting didn't work for private top-level methods
  spec/compiler/semantic/automatic_cast.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler

#7313 Refactor getter/property macros to work properly with Bool types
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib:macros

#7317 Compiler: Restore usage of embedded default_target_triple
  src/compiler/crystal/codegen/target.cr
Labels: kind:bug, topic:compiler

#7331 String: Fixed typos in docs
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#7206 Add overflow detection with preview opt-in
  Makefile
  spec/compiler/codegen/arithmetics_spec.cr
  spec/spec_helper.cr
  src/big/big_decimal.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/primitives.cr
  src/crystal/compiler_rt.cr
  src/exception.cr
  src/int.cr
  src/llvm/lib_llvm.cr
  src/primitives.cr
  src/raise.cr
Labels: kind:feature, topic:compiler, topic:stdlib:numeric

#7251 Improve HTTP::Server docs
  src/http/server.cr
Labels: kind:docs, topic:stdlib:networking

#7335 Workaround buggy offset debug info values
  src/compiler/crystal/codegen/debug.cr
Labels: kind:bug, topic:compiler:debugger

#7263 CI: Disable linux 32 bits travis build
  .travis.yml
Labels: topic:infrastructure

#7297 Detect nesting `it` and `pending` at run-time
  spec/std/array_spec.cr
  spec/std/char_spec.cr
  spec/std/deque_spec.cr
  spec/std/float_spec.cr
  spec/std/spec_spec.cr
  src/spec/context.cr
  src/spec/dsl.cr
  src/spec/expectations.cr
  src/spec/methods.cr
Labels: kind:feature, topic:stdlib:specs

#7330 Make Nil#not_nil! raise NilAssertionError
  src/exception.cr
  src/nil.cr
  src/object.cr
Labels: kind:refactor, topic:stdlib

#7343 Parser: comma is required between block args
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#3947 add sort_by macro method
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, pr:needs-review, topic:stdlib:macros
