Repository crystal-lang/crystal, pull requests merged in 2019-02, with the labels that each got.

#7347 Fix formatting of `1\n.as(Int32)`
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#7359 Update CI to use 0.27.1
  .circleci/config.yml
  VERSION
  bin/ci
Labels: topic:infrastructure

#7372 Fix/ssl shutdown
  spec/manual/https_client_spec.cr
  src/openssl/ssl/socket.cr
Labels: kind:bug, topic:stdlib:networking

#7371 http client: Fallback to default mime type 'application/octet-stream'
  spec/std/http/client/client_spec.cr
  src/http/common.cr
Labels: kind:bug, topic:stdlib:networking

#7373 Fix: integer overflow in main thread stack base detection
  src/fiber.cr
  src/lib_c/aarch64-linux-gnu/c/pthread.cr
  src/lib_c/aarch64-linux-gnu/c/sys/resource.cr
  src/lib_c/aarch64-linux-musl/c/pthread.cr
  src/lib_c/aarch64-linux-musl/c/sys/resource.cr
  src/lib_c/arm-linux-gnueabihf/c/pthread.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/resource.cr
  src/lib_c/i386-linux-gnu/c/pthread.cr
  src/lib_c/i386-linux-gnu/c/sys/resource.cr
  src/lib_c/i386-linux-musl/c/pthread.cr
  src/lib_c/i386-linux-musl/c/sys/resource.cr
  src/lib_c/x86_64-darwin/c/pthread.cr
  src/lib_c/x86_64-freebsd/c/pthread.cr
  src/lib_c/x86_64-freebsd/c/sys/resource.cr
  src/lib_c/x86_64-linux-gnu/c/pthread.cr
  src/lib_c/x86_64-linux-gnu/c/sys/resource.cr
  src/lib_c/x86_64-linux-musl/c/pthread.cr
  src/lib_c/x86_64-linux-musl/c/sys/resource.cr
  src/lib_c/x86_64-openbsd/c/pthread.cr
  src/lib_c/x86_64-openbsd/c/signal.cr
  src/lib_c/x86_64-openbsd/c/sys/resource.cr
  src/lib_c/x86_64-openbsd/c/unistd.cr
  src/thread.cr
Labels: kind:bug, topic:stdlib:runtime

#7379 spawn: give compile error if passing an exp and a block
  src/concurrent.cr
Labels: kind:feature, topic:stdlib:concurrency

#7381 Update CI to use 0.27.2
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#7375 Make OverflowError's message a bit more detailed
  src/exception.cr
Labels: kind:refactor, topic:stdlib:numeric

#7377 Fix windows monotonic time bug
  src/crystal/system/win32/time.cr
Labels: kind:bug, platform:windows, topic:stdlib:time

#7388 CI: Add homebrew cache for osx builds
  .circleci/config.yml
Labels: topic:infrastructure

#7387 CI: Avoid duplicate runs in maintenance branches
  .circleci/config.yml
Labels: topic:infrastructure

#7386 Compiler: fix wrong exception type thrown on missing require
  spec/compiler/semantic/require_spec.cr
  src/compiler/crystal/crystal_path.cr
Labels: kind:bug, topic:compiler

#7354 add DTLS support
  src/openssl/lib_ssl.cr
Labels: kind:feature, topic:stdlib:networking

#7390 Run formatter in travis. Update /bin/ci usage instructions
  .travis.yml
  bin/ci
Labels: topic:infrastructure

#7389 CI: Test linux 64 bits package using docker image recent build
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#7361 Correct misspellings throughout the codebase
  CHANGELOG.md
  spec/compiler/crystal_path/crystal_path_spec.cr
  spec/compiler/semantic/instance_var_spec.cr
  spec/compiler/semantic/lib_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/ecr/ecr_lexer_spec.cr
  spec/std/enum_spec.cr
  spec/std/float_printer/ieee_spec.cr
  spec/std/indexable_spec.cr
  spec/std/iterator_spec.cr
  spec/std/number_spec.cr
  spec/std/thread/condition_variable_spec.cr
  spec/std/time/time_spec.cr
  src/char/reader.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/hooks.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/doc/html/js/_search.js
  src/compiler/crystal/tools/playground/views/_about.html
  src/concurrent.cr
  src/crystal/system/unix/getrandom.cr
  src/ecr/lexer.cr
  src/ecr/processor.cr
  src/enum.cr
  src/file.cr
  src/float/printer/diy_fp.cr
  src/float/printer/ieee.cr
  src/io/hexdump.cr
  src/iterator.cr
  src/json/lexer.cr
  src/llvm/type.cr
  src/mime/media_type.cr
  src/openssl/hmac.cr
  src/pointer.cr
  src/process.cr
  src/socket/server.cr
  src/time.cr
  src/time/location.cr
  src/time/span.cr
Labels: kind:docs, kind:refactor

#7081 Use read_file macro in Crystal::Config.version
  src/compiler/crystal/config.cr
Labels: kind:refactor, topic:compiler

#7085 Move HTTP::Multipart to MIME::Multipart
  spec/std/mime/multipart/builder_spec.cr
  spec/std/mime/multipart/parser_spec.cr
  spec/std/mime/multipart_spec.cr
  src/http/formdata.cr
  src/http/formdata/builder.cr
  src/http/formdata/parser.cr
  src/mime/multipart.cr
  src/mime/multipart/builder.cr
  src/mime/multipart/parser.cr
Labels: breaking-change, kind:refactor, status:accepted, topic:stdlib:networking

#6945 Prevent static linking segfaults
  src/callstack/lib_unwind.cr
Labels: kind:feature, topic:compiler

#7397 Avoid fork and spawn when `--threads=1` and use that for CI
  bin/ci
  src/compiler/crystal/compiler.cr
Labels: performance, topic:compiler, topic:infrastructure

#7398 Implement BigDecimal.from_yaml
  spec/std/yaml/serialization_spec.cr
  src/big/yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#7179 Add begin-less and end-less ranges
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  spec/std/array_spec.cr
  spec/std/bit_array_spec.cr
  spec/std/indexable_spec.cr
  spec/std/number_spec.cr
  spec/std/range_spec.cr
  spec/std/string_spec.cr
  src/array.cr
  src/bit_array.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/indexable.cr
  src/number.cr
  src/range.cr
  src/string.cr
Labels: kind:feature, topic:compiler, topic:stdlib

#7403 Specs: avoid GC finalization warning in Thread specs
  spec/std/thread_spec.cr
Labels: kind:bug, kind:specs

#7409 Fix `Signal::CHLD.reset` not clearing previously set handler, and fix related race condition in spec
  spec/std/signal_spec.cr
  src/signal.cr
Labels: kind:bug, kind:specs, topic:stdlib:runtime

#7366 make wait_readable and wait_writable public
  src/io/syscall.cr
Labels: kind:feature, topic:stdlib:networking

#7055 Fix RequestProcessor connection reuse with unconsumed requests
  spec/std/http/server/server_spec.cr
  src/http/content.cr
  src/http/server.cr
  src/http/server/request_processor.cr
Labels: breaking-change, security, status:accepted, topic:stdlib

#7405 Parse IIS Set-Cookie date format
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
  src/time/format/custom/http_date.cr
Labels: kind:bug, topic:stdlib:networking

#6598 Add Time#shift for changing a time instance by calendar units
  spec/std/time/time_spec.cr
  src/time.cr
  src/time/format/parser.cr
Labels: breaking-change, topic:stdlib

#7402 HTTP::Client spec: don't write server response if expecting read timeout
  spec/std/http/client/client_spec.cr
Labels: kind:bug, topic:stdlib:specs

#7233 Enumerable#each_cons support for accepting deque as a reuse buffer
  spec/std/enumerable_spec.cr
  spec/std/iterator_spec.cr
  src/enumerable.cr
  src/iterator.cr
Labels: kind:feature, performance, topic:stdlib:collection

#7328 Add String#rchop? and String#lchop?
  spec/std/string_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/util.cr
  src/spec/source.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#7416 Callstack: Fix confused block variable naming.
  src/callstack.cr
Labels: topic:stdlib

#5346 Rename Time constructors
  spec/std/file_spec.cr
  spec/std/http/cookie_spec.cr
  spec/std/http/http_spec.cr
  spec/std/oauth2/session_spec.cr
  spec/std/time/format_spec.cr
  spec/std/time/location_spec.cr
  spec/std/time/time_spec.cr
  spec/std/zip/zip_spec.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/tools/init/template/license.ecr
  src/crystal/system/win32/time.cr
  src/file.cr
  src/file/tempfile.cr
  src/file_utils.cr
  src/gzip/header.cr
  src/http/cookie.cr
  src/logger.cr
  src/oauth/oauth.cr
  src/oauth2/access_token/access_token.cr
  src/oauth2/access_token/mac.cr
  src/oauth2/session.cr
  src/object.cr
  src/socket.cr
  src/socket/server.cr
  src/time.cr
  src/time/format/parser.cr
  src/time/location.cr
  src/time/span.cr
  src/zip/file_info.cr
  src/zip/writer.cr
Labels: breaking-change, kind:refactor, topic:stdlib:time

#7427 Compiler specs: avoid executing subprocess for spec that doesn't need it
  spec/compiler/semantic/macro_spec.cr
Labels: kind:refactor, kind:specs

#7426 Spec: do Fiber.yield after each test
  src/spec/methods.cr
Labels: kind:feature, kind:specs

#7413 Optimize dwarf line numbers decoding
  src/callstack.cr
  src/debug/dwarf/info.cr
  src/debug/dwarf/line_numbers.cr
  src/debug/dwarf/strings.cr
  src/debug/elf.cr
  src/debug/mach_o.cr
Labels: performance, topic:stdlib

#6516 Allow creating None enum flag with Enum.from_value
  spec/std/enum_spec.cr
  src/debug/elf.cr
  src/enum.cr
Labels: breaking-change, kind:refactor, status:accepted, topic:stdlib

#7384 Compiler: always mention the scope (and with ... yield scope, if any) on undefined method error
  spec/compiler/semantic/did_you_mean_spec.cr
  spec/compiler/semantic/module_spec.cr
  spec/compiler/semantic/yield_with_scope_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:feature, topic:compiler

#7138 add default `script` to template `travis.yml`
  src/compiler/crystal/tools/init/template/travis.yml.ecr
Labels: kind:feature, topic:tools

#6668 Add compile-time flag to docs generator
  src/compiler/crystal/command/docs.cr
Labels: kind:feature, topic:tools:docs

#7322 Add lazy versions of Object#getter?/property? macros
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:feature, topic:stdlib

#7439 Add `Slice#[](Range)`
  spec/std/slice_spec.cr
  src/slice.cr
Labels: kind:feature, topic:stdlib:collection

#7438 Fix: Removes overriding local var
  src/compiler/crystal/command/docs.cr
Labels: kind:bug, topic:tools:docs

#7450 Format: fix indent of nested array elements
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#7468 Compiler: give parser error when assigning a constant inside a multiassign
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:semantic

#7475 Compiler: fix a couple of issues with `as`, `as?` and unions
  spec/compiler/semantic/cast_spec.cr
  spec/compiler/semantic/nilable_cast_spec.cr
  spec/compiler/semantic/union_spec.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#7469 Handle signals in a separate fiber
  src/signal.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:stdlib:runtime

#7326 Implement #annotations
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:lang

#7424 Implement resource owner credentials
  spec/std/http/spec_helper.cr
  spec/std/oauth2/client_spec.cr
  src/oauth2/client.cr
Labels: kind:feature, topic:stdlib:networking

#7477 XML: workaround for bug in libxml2 2.9.9
  src/xml/reader.cr
Labels: kind:bug, topic:stdlib:serialization

#7440 Iterator: remove `rewind`. Implement `cycle` by storing elements in an array
  spec/std/array_spec.cr
  spec/std/bit_array_spec.cr
  spec/std/csv/csv_parse_spec.cr
  spec/std/deque_spec.cr
  spec/std/enumerable_spec.cr
  spec/std/hash_spec.cr
  spec/std/int_spec.cr
  spec/std/io/io_spec.cr
  spec/std/iterator_spec.cr
  spec/std/number_spec.cr
  spec/std/range_spec.cr
  spec/std/set_spec.cr
  spec/std/slice_spec.cr
  spec/std/static_array_spec.cr
  spec/std/string_spec.cr
  spec/std/tuple_spec.cr
  src/array.cr
  src/csv/lexer.cr
  src/csv/lexer/io_based.cr
  src/csv/lexer/string_based.cr
  src/csv/parser.cr
  src/dir.cr
  src/hash.cr
  src/indexable.cr
  src/int.cr
  src/io.cr
  src/iterator.cr
  src/number.cr
  src/range.cr
  src/string.cr
Labels: breaking-change, kind:feature, kind:refactor, topic:stdlib:collection

#7467 OAuth2: don't parse error as JSON
  src/oauth2/client.cr
  src/oauth2/error.cr
Labels: breaking-change, kind:bug, topic:stdlib:networking

#7484 Fix expected error in tcp_server_spec for musl
  spec/std/socket/tcp_server_spec.cr
Labels: kind:bug, platform, topic:stdlib:networking
