Repository crystal-lang/crystal, pull requests merged in 2019-03, with the labels that each got.

#7334 Fix parsing and behaviour of `->foo.[]` and other operators
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/syntax/parser.cr
  src/llvm/parameter_collection.cr
Labels: kind:bug, topic:compiler:parser, topic:compiler:semantic

#7277 Allow different values than only -1, 0 and 1 to be returned by <=>
  spec/std/array_spec.cr
  src/array.cr
  src/char.cr
  src/comparable.cr
  src/compiler/crystal/macros.cr
  src/number.cr
  src/partial_comparable.cr
  src/pointer.cr
  src/semantic_version.cr
  src/string.cr
  src/symbol.cr
  src/tuple.cr
Labels: kind:docs, topic:stdlib

#7479 Add detection of linux environment in compiler config
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/config.cr
  src/compiler/crystal/crystal_path.cr
  src/compiler/crystal/program.cr
Labels: kind:feature, platform, topic:compiler

#7417 Extract Fiber::StackPool
  src/fiber.cr
  src/fiber/stack_pool.cr
  src/kernel.cr
Labels: kind:refactor, topic:stdlib:concurrency

#7525 Number: let `inspect` not show the type suffix
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/big/big_rational_spec.cr
  spec/std/float_spec.cr
  spec/std/int_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/float.cr
  src/int.cr
  src/object.cr
  src/reference.cr
Labels: kind:refactor, topic:stdlib

#7527 Compiler: merge procs with the same arguments type and Nil | T return type to Nil return type
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/type_merge.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:compiler:semantic

#7510 Compiler: let `protected initialize` define a protected `new`
  spec/compiler/semantic/visibility_modifiers_spec.cr
  src/compiler/crystal/semantic/new.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#7529 Compiler: fix named args type matching
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/method_lookup.cr
Labels: kind:bug, topic:compiler:semantic

#7495 Implement Set#add? method
  spec/std/set_spec.cr
  src/set.cr
Labels: kind:feature, topic:stdlib:collection

#7511 Add command and args to execvp error message
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:feature, topic:stdlib:system

#6314 Human readable formatting for numbers
  spec/std/benchmark_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/http/server/handlers/log_handler_spec.cr
  spec/std/humanize_spec.cr
  src/benchmark/ips.cr
  src/http/server/handlers/log_handler.cr
  src/humanize.cr
  src/prelude.cr
Labels: kind:feature, topic:stdlib:text

#7537 Fix GenericClassType vs GenericClassInstanceType restrictions
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#7536 Fix restriction of valid type vs free vars
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#6611 Let Array#sort only use `<=>`, and let `<=>` return `nil` for partial comparability
  spec/compiler/macro/macro_methods_spec.cr
  spec/std/array_spec.cr
  spec/std/comparable_spec.cr
  spec/std/float_spec.cr
  src/array.cr
  src/comparable.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/syntax/location.cr
  src/docs_main.cr
  src/int.cr
  src/number.cr
Labels: breaking-change, kind:bug, kind:feature, status:accepted, topic:stdlib

#7555 YAML: fix test checking serialization of slices for libyaml 0.2.2
  spec/std/yaml/builder_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/yaml.cr
Labels: breaking-change, kind:bug, kind:specs, topic:stdlib:serialization

#7505 Refactor IO::Syscall as IO::Evented
  src/crystal/event_loop.cr
  src/crystal/system/unix/file_descriptor.cr
  src/io/evented.cr
  src/io/file_descriptor.cr
  src/socket.cr
Labels: kind:refactor, topic:stdlib:concurrency

#7560 Fix formatting absolute paths
  src/compiler/crystal/command/format.cr
Labels: kind:bug, topic:tools:formatter

#7552 Change the font-weight used in Playground
  src/compiler/crystal/tools/playground/public/application.css
Labels: kind:refactor, topic:tools:playground

#7564 Add missing `require` statements for the API
  src/benchmark.cr
  src/big/big_int.cr
  src/big/big_rational.cr
  src/bit_array.cr
  src/colorize.cr
  src/complex.cr
  src/crypto/bcrypt/password.cr
  src/csv.cr
  src/digest/base.cr
  src/file_utils.cr
  src/html.cr
  src/http/client.cr
  src/http/common.cr
  src/http/cookie.cr
  src/http/formdata.cr
  src/http/formdata/builder.cr
  src/http/formdata/parser.cr
  src/http/headers.cr
  src/http/params.cr
  src/http/server.cr
  src/http/server/handler.cr
  src/http/web_socket.cr
  src/ini.cr
  src/json/any.cr
  src/json/serialization.cr
  src/levenshtein.cr
  src/mime.cr
  src/mime/media_type.cr
  src/mime/multipart.cr
  src/mime/multipart/builder.cr
  src/mime/multipart/parser.cr
  src/option_parser.cr
  src/socket.cr
  src/socket/address.cr
  src/socket/addrinfo.cr
  src/socket/udp_socket.cr
  src/socket/unix_socket.cr
  src/string_pool.cr
  src/string_scanner.cr
  src/uri.cr
  src/weak_ref.cr
  src/xml/node.cr
  src/yaml/schema/core.cr
  src/yaml/serialization.cr
  src/zip/file.cr
  src/zip/reader.cr
  src/zip/writer.cr
Labels: kind:docs, topic:stdlib

#7575 Don't include private constants in the docs
  spec/compiler/crystal/tools/doc/generator_spec.cr
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:bug, topic:tools:docs

#7591 Fix Slice#clone for non-primitive types and deep copy
  spec/std/slice_spec.cr
  src/slice.cr
Labels: kind:bug, topic:stdlib:collection

#7562 Add CRYSTAL_LIBRARY_PATH for lookup static libraries
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/config.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:feature, topic:compiler

#7470 IO: remove `flush_on_newline` and only `sync` on TTY devices
  spec/std/io/buffered_spec.cr
  src/http/server/response.cr
  src/io/buffered.cr
  src/io/file_descriptor.cr
  src/kernel.cr
  src/process.cr
Labels: breaking-change, kind:feature, topic:stdlib:files

#5635 Implement Path type
  spec/std/file_spec.cr
  spec/std/path_spec.cr
  src/docs_main.cr
  src/file.cr
  src/path.cr
  src/prelude.cr
Labels: kind:feature, topic:stdlib:files

#7453 Move `zip` and `zip?` to `Enumerable` and make it work with any number of `Indexable` or `Iterable` or `Iterator`
  spec/std/array_spec.cr
  src/enumerable.cr
  src/indexable.cr
Labels: kind:feature, topic:stdlib:collection

#7605 Fix a couple of formatter issues
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#7607 Parser: disallow space between enum members
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser
