Repository crystal-lang/crystal, pull requests merged in 2019-11, with the labels that each got.

#8394 Change `&block` to `&` for yielding method in docs
  spec/compiler/crystal/tools/doc/method_spec.cr
  src/compiler/crystal/tools/doc/method.cr
Labels: kind:feature, topic:tools:docs

#8332 Add Enumerable#each_cons_pair and Iterator#cons_pair yielding a tuple
  spec/std/enumerable_spec.cr
  spec/std/iterator_spec.cr
  src/enumerable.cr
  src/iterator.cr
Labels: kind:feature, topic:stdlib:collection

#7996 Integer: Improve #gcd types and improve performance a bit.
  spec/std/big/big_int_spec.cr
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:bug, performance, topic:stdlib:numeric

#8417 Compiler: notify generic type subtypes, and handle empty subtypes
  spec/compiler/codegen/generic_class_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#8419 Move gcd implementation doc inside def
  src/int.cr
Labels: kind:docs, topic:stdlib:numeric

#8421 Fix GZip Reader and Writer to handle large data sizes
  spec/manual/gzip_large_file_spec.cr
  src/gzip/reader.cr
  src/gzip/writer.cr
Labels: kind:bug, topic:stdlib

#8389 Allow constants to use ditto
  spec/compiler/semantic/doc_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:feature, topic:compiler:semantic, topic:tools:docs

#8439 CI: Update osx & Xcode used in CircleCI
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#8450 Fix Hash#rehash
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:bug, topic:stdlib:collection

#8242 Add specs for Spec filters
  spec/std/spec/context_spec.cr
  spec/std/spec/filters_spec.cr
  spec/std/spec/spec_helper.cr
  src/spec/dsl.cr
  src/spec/filters.cr
Labels: kind:specs, topic:stdlib:specs

#8453 Fix spec --fail-fast
  src/spec/dsl.cr
Labels: kind:bug, kind:specs

#8380 Add missing documentation to Hash.merge!(other : Hash, &block)
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#8451 Hash compare by identity
  spec/std/hash_spec.cr
  spec/std/set_spec.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/fix_missing_types.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/tools/context.cr
  src/compiler/crystal/tools/formatter.cr
  src/hash.cr
  src/set.cr
Labels: kind:feature, topic:stdlib:collection

#8156 Allowing JSON.mapping & YAML.mapping converter attribute to be applied to Array and Hashes.
  spec/std/json/mapping_spec.cr
  spec/std/yaml/mapping_spec.cr
  src/json/from_json.cr
  src/json/to_json.cr
  src/yaml/from_yaml.cr
  src/yaml/to_yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#8310 Spec: Add ability to randomize specs
  spec/std/spec/context_spec.cr
  src/spec.cr
  src/spec/context.cr
  src/spec/dsl.cr
Labels: kind:feature, topic:stdlib:specs

#5716 Add `Enum.valid?`
  spec/std/enum_spec.cr
  src/enum.cr
Labels: kind:feature, topic:stdlib

#8412 Spec: restrict the type returned by `should_not be_nil` and others
  spec/std/spec/expectations_spec.cr
  src/spec/expectations.cr
Labels: kind:feature, kind:specs

#8400 Implement string interpolation as a call to String.interpolation
  spec/compiler/normalize/string_interpolation_spec.cr
  spec/std/string_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/string.cr
Labels: breaking-change, kind:refactor, performance

#8415 Fix bug in Path.dirname
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, topic:stdlib:files

#7903 Remove expand home (`~`) by default in File.expand_path and Path#expand, now opt-in argument
  spec/std/file_spec.cr
  spec/std/path_spec.cr
  src/file.cr
  src/path.cr
Labels: breaking-change, kind:feature, topic:stdlib:files

#8363 Add --mcmodel option to compiler
  man/crystal.1
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
Labels: kind:feature, topic:compiler

#8442 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#8464 Return nil (and don't raise) when "Content-Type" header is an empty string.
  spec/std/http/client/response_spec.cr
  src/http/client/response.cr
Labels: kind:bug, topic:stdlib:networking

#8465 Don't close pipes used for signal handlers in MT
  src/signal.cr
Labels: kind:bug, topic:stdlib:system

#8452 Deprecate Enumerable#grep
  src/enumerable.cr
Labels: breaking-change, kind:feature, topic:stdlib:collection

#8406 JSON/YAML: add `use_discriminator`
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: pr:wip, status:discussion, status:draft, topic:stdlib:serialization

#8448 Add doc to Regex::Options
  src/regex.cr
Labels: kind:docs, topic:stdlib

#8445 Implement .! in compiler
  spec/compiler/normalize/case_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser

#8429 Support named arguments in macro methods
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:lang:macros, topic:stdlib:macros

#8378 Only add some example to document Enumerable.reduce behavior
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:docs, kind:specs, topic:stdlib:collection

#8322 Channel refactor and optimize
  spec/std/channel_spec.cr
  spec/std/crystal/pointer_linked_list_spec.cr
  src/channel.cr
  src/crystal/pointer_linked_list.cr
Labels: kind:refactor, performance, topic:stdlib:concurrency

#8068 Add ability to tag specs
  spec/std/spec/context_spec.cr
  spec/std/spec/filters_spec.cr
  spec/std/spec/spec_helper.cr
  src/spec.cr
  src/spec/context.cr
  src/spec/dsl.cr
  src/spec/example.cr
  src/spec/filters.cr
  src/spec/item.cr
  src/spec/methods.cr
Labels: kind:feature, topic:stdlib:specs

#8475 Deprecate String#codepoint_at
  src/string.cr
Labels: breaking-change, kind:feature, topic:stdlib:text

#8501 Formatter: check open/close parens in Generic
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#8502 Docs: correctly attach docs in multiple macro invocations
  spec/compiler/semantic/doc_spec.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
Labels: kind:bug, topic:tools:docs

#8489 Remove self restriction from Object.from_{json,yaml}
  src/json/from_json.cr
  src/yaml/from_yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#8490 Issue 8440: Inconsistent `Enumerable#minmax`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:bug, topic:stdlib:collection

#8510 Allow warnings in specs
  Makefile
Labels: topic:infrastructure

#8356 Add documentation for Channel#send and Channel#close (crystal-lang#8346)
  spec/std/channel_spec.cr
  src/channel.cr
Labels: kind:docs, topic:stdlib:concurrency

#8519 Fix make Thread#gc_thread_handler portable
  src/crystal/system/thread.cr
  src/crystal/system/unix/pthread.cr
Labels: kind:bug, platform:windows

#8528 Do not collapse whitespaces in playground sidebar.
  src/compiler/crystal/tools/playground/public/application.css
Labels: kind:bug, topic:tools:playground

#3628 mention that there are many other options, not shown in the default help
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler

#8508 Use String/Nil#presence in a few places throughout stdlib
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/tools/doc/macro.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/doc/type.cr
  src/http/client.cr
  src/http/request.cr
  src/llvm.cr
  src/mime/multipart.cr
  src/oauth/signature.cr
  src/socket/address.cr
Labels: kind:refactor

#8481 Some misbehaving SSL servers hang at the end instead of responding wi…
  spec/std/openssl/ssl/socket_spec.cr
  src/openssl/ssl/socket.cr
Labels: kind:bug, topic:stdlib:networking

#8513 Fix incorrectly initializing win32 fiber stack
  src/fiber/context/x86_64-microsoft.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime

#8491 Improve documentation for pseudo methods
  src/docs_pseudo_methods.cr
Labels: kind:docs, kind:feature

#8522 move clamp from number to comparable
  spec/std/comparable_spec.cr
  spec/std/number_spec.cr
  src/comparable.cr
  src/number.cr
Labels: kind:feature, topic:stdlib
