Repository crystal-lang/crystal, pull requests merged in 2019-10, with the labels that each got.

#8256 Compiler: consume previous macro pragmas
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler

#8258 Compiler: fix overload of union type through alias against type
  spec/compiler/semantic/alias_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#8251 Update CI to use 0.31.1
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#8265 Optimized version of `Tuple#to_a`
  spec/std/tuple_spec.cr
  src/tuple.cr
Labels: performance, topic:stdlib:collection

#8273 Compiler: sizeof(Bool) must be 1, not 0
  spec/compiler/codegen/sizeof_spec.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler:semantic

#7656 Textual improvements
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
  src/array.cr
  src/big/big_decimal.cr
  src/bit_array.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/hooks.cr
  src/compiler/crystal/syntax/ast.cr
  src/file.cr
  src/file/info.cr
  src/int.cr
  src/io/memory.cr
  src/mime.cr
  src/mime/media_type.cr
  src/prelude.cr
  src/string_pool.cr
  src/time/format/custom/rfc_2822.cr
  src/yaml/nodes/nodes.cr
Labels: kind:docs

#8281 GC: profiling stats and warning bindings
  src/gc.cr
  src/gc/boehm.cr
  src/gc/none.cr
Labels: kind:feature, topic:stdlib:runtime

#8280 GC: Fix gc_none with preview_mt
  src/gc/none.cr
Labels: kind:bug, topic:stdlib:runtime

#8264 Add `offset` argument to all `map_with_index` methods
  spec/std/array_spec.cr
  spec/std/enumerable_spec.cr
  spec/std/pointer_spec.cr
  spec/std/slice_spec.cr
  spec/std/static_array_spec.cr
  spec/std/string_spec.cr
  spec/std/tuple_spec.cr
  src/array.cr
  src/enumerable.cr
  src/pointer.cr
  src/slice.cr
  src/static_array.cr
  src/string.cr
  src/tuple.cr
Labels: kind:feature, topic:stdlib:collection

#8282 Fix parser crash for 'alias Foo?'
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#8200 Add name to error message in non-nil asserting getters
  spec/std/object_spec.cr
  src/object.cr
Labels: breaking-change, kind:feature, topic:stdlib

#8284 Fix : Channel can send successfully but raise
  spec/std/channel_spec.cr
  src/channel.cr
Labels: kind:bug, topic:stdlib:concurrency

#8283 CI: Avoid 32 bits failures and improve behavior when failures happen
  .circleci/config.yml
Labels: topic:infrastructure

#8295 Faster mutex implementation (optionally reentrant)
  spec/std/mutex_spec.cr
  src/crystal/once.cr
  src/mutex.cr
Labels: breaking-change, kind:feature, performance, topic:stdlib:concurrency

#8249 Keep Channel#close thread-safety
  src/channel.cr
Labels: kind:bug, topic:stdlib:concurrency

#8296 Add class info to not-nil assertion of getter!
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:feature, topic:stdlib:macros

#8270 Remove duplicated defs
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/warnings.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/types.cr
  src/compiler/crystal/util.cr
  src/io/byte_format.cr
  src/llvm/builder.cr
  src/mime/multipart.cr
  src/string/builder.cr
  src/uri.cr
  src/uuid.cr
  src/xml/node.cr
Labels: kind:refactor

#8304 Fix select with receive? and closed channels
  spec/compiler/normalize/select_spec.cr
  spec/std/channel_spec.cr
  spec/std/concurrent/select_spec.cr
  spec/std/spec_helper.cr
  src/channel.cr
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:stdlib:concurrency

#8315 Format: Fix indent in arguments
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#8320 Parse newline before clsoing paren of pseudo method call
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#8312 Remove original backers from repo
  BACKERS.md
Labels: kind:docs

#8337 Fix uuid/json.cr shadowing uuid.cr docs.
  src/uuid/json.cr
Labels: kind:bug, kind:docs

#8308 Refactor callstack_spec using compile and run helper
  spec/std/callstack_spec.cr
Labels: kind:refactor, kind:specs, topic:stdlib:runtime

#8330 [compiler] Fix detect musl libc at runtime
  spec/compiler/config_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/config.cr
Labels: kind:feature, kind:refactor, kind:specs, platform:linux-musl, topic:compiler

#8347 Array: fix range assignment index out of bounds
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#8342 update mime type of .js files to text/javascript
  src/mime.cr
Labels: kind:feature, topic:stdlib:networking

#8215 Remove newlines from base64digest
  spec/std/openssl/digest_spec.cr
  src/openssl/digest/digest_base.cr
Labels: breaking-change, kind:feature, topic:stdlib:crypto

#8345 Added String#presence
  spec/std/string_spec.cr
  src/nil.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#8358 Add missing LLVM::Attribute members
  src/llvm/enums.cr
Labels: kind:bug, topic:compiler

#8364 Remove Readline from std-lib
  spec/std/readline_spec.cr
  src/docs_main.cr
  src/readline.cr
Labels: breaking-change, topic:stdlib

#8327 [Compiler] Insert documentation for pseudo methods
  spec/compiler/crystal/tools/doc/generator_spec.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/method.cr
  src/docs_main.cr
  src/docs_pseudo_methods.cr
Labels: kind:docs, kind:feature, topic:tools:docs

#7995 Implement fibers for win32
  spec/std/concurrent_spec.cr
  src/crystal/scheduler.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/fiber.cr
  src/crystal/system/print_error.cr
  src/crystal/system/thread.cr
  src/crystal/system/thread_linked_list.cr
  src/crystal/system/thread_mutex.cr
  src/crystal/system/unix/event_libevent.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/crystal/system/unix/fiber.cr
  src/crystal/system/unix/getrandom.cr
  src/crystal/system/unix/lib_event2.cr
  src/crystal/system/unix/pthread.cr
  src/crystal/system/unix/pthread_condition_variable.cr
  src/crystal/system/unix/pthread_mutex.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/fiber.cr
  src/crystal/system/win32/thread.cr
  src/crystal/system/win32/thread_mutex.cr
  src/docs_main.cr
  src/fiber.cr
  src/fiber/context/x86_64-microsoft.cr
  src/fiber/context/x86_64-sysv.cr
  src/fiber/stack_pool.cr
  src/gc/boehm.cr
  src/lib_c/x86_64-windows-msvc/c/memoryapi.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/prelude.cr
  src/spec/example.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#8371 Fix method names incorrectly stripped in doc generator
  spec/compiler/crystal/tools/doc/generator_spec.cr
  src/compiler/crystal/tools/doc/method.cr
Labels: kind:bug, topic:tools:docs

#8386 Add documentation for undocumented methods in Levenshtein module
  src/levenshtein.cr
Labels: kind:docs

#8339 Use constant for websocket protocol GUID string
  src/http/web_socket/protocol.cr
Labels: kind:refactor, topic:stdlib:networking

#8165 Add `Int#bits` for accessing bit ranges
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:feature, topic:stdlib:numeric

#8302 Spec hooks
  spec/std/spec/context_spec.cr
  src/spec/context.cr
  src/spec/example.cr
  src/spec/example/procsy.cr
  src/spec/example_group/procsy.cr
  src/spec/filters.cr
  src/spec/item.cr
  src/spec/methods.cr
Labels: kind:feature, kind:specs

#8395 Remove debug-leftovers
  spec/std/callstack_spec.cr
Labels: kind:bug, kind:specs

#8368 Address FIXME
  src/box.cr
Labels: kind:refactor, topic:stdlib

#8399 Compiler: disallow instance_sizeof on union
  spec/compiler/semantic/sizeof_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler:semantic

#8348 [Compiler] Add sitemap to doc generator
  Makefile
  man/crystal.1
  spec/compiler/crystal/tools/doc/generator_spec.cr
  spec/compiler/crystal/tools/doc/macro_spec.cr
  spec/compiler/crystal/tools/doc/method_spec.cr
  spec/compiler/crystal/tools/doc/type_spec.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/html/_head.html
  src/compiler/crystal/tools/doc/html/main.html
  src/compiler/crystal/tools/doc/html/sitemap.xml
  src/compiler/crystal/tools/doc/html/type.html
  src/compiler/crystal/tools/doc/templates.cr
Labels: kind:feature, topic:tools:docs

#8404 ARGF: remove unnecessary operations about `read_count`.
  src/io/argf.cr
Labels: kind:refactor, topic:stdlib

#8405 Get the class variables of some Type in a macro
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:lang:macros
