Repository crystal-lang/crystal, pull requests merged in 2019-04, with the labels that each got.

#7197 Fix leaks in HTTP::Server specs
  spec/std/http/client/client_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/http/web_socket_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/tcp_server_spec.cr
  src/http/server.cr
Labels: kind:bug, kind:refactor, topic:stdlib, topic:stdlib:concurrency

#5822 Change Time#date to return a Tuple of year, month, day instead of Time
  spec/std/time/time_spec.cr
  src/time.cr
Labels: breaking-change, kind:refactor, status:accepted, topic:stdlib

#7610 Add HTTP::Request#remote_address
  spec/std/http/server/server_spec.cr
  spec/std/http/spec_helper.cr
  src/http/request.cr
  src/openssl/ssl/socket.cr
Labels: kind:feature, topic:stdlib:networking

#7594 Improve documentation of Hash
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#7568 Compiler: fix passing recursive alias to proc
  spec/compiler/semantic/alias_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#7580 Restriction update: generic vs path - specs
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#7589 New offsetof expression
  spec/compiler/crystal/tools/doc/highlighter_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/lexer/lexer_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/instance_var_spec.cr
  spec/compiler/semantic/offsetof_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/syntax/transformer.cr
  src/compiler/crystal/tools/doc/highlighter.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:compiler:semantic, topic:lang

#7419 Improve specs and docs for #each_line
  spec/std/io/io_spec.cr
  src/io.cr
  src/string.cr
Labels: kind:docs, kind:refactor, kind:specs, pr:needs-review, topic:stdlib:text

#7374 Add `options` argument to String#camelcase and String#underscore
  src/string.cr
Labels: kind:feature, pr:needs-review, topic:stdlib:text

#7338 Add nillable range fetching
  spec/std/array_spec.cr
  spec/std/string_spec.cr
  src/array.cr
  src/compiler/crystal/command.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:collection

#7596 Quality checks / Deprecated methods
  etc/completion.bash
  spec/compiler/codegen/warnings_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/warnings.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/util.cr
Labels: kind:feature, topic:compiler

#7623 Docs: Include crystal built-in constants in docs
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:bug, topic:tools:docs

#7622 Bump distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#7626 Compiler: Avoid showing duplicate entries as warnings
  spec/compiler/codegen/warnings_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/codegen/warnings.cr
Labels: kind:bug, pr:wip, topic:compiler

#6237 Use more chars instead of strings
  samples/2048.cr
  samples/havlak.cr
  samples/llvm/brainfuck.cr
  samples/meteor.cr
  spec/compiler/crystal/tools/context_spec.cr
  spec/compiler/crystal/tools/expand_spec.cr
  spec/compiler/crystal/tools/implementations_spec.cr
  spec/compiler/lexer/lexer_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/tools/doc/macro.cr
  src/compiler/crystal/tools/doc/method.cr
  src/string.cr
  src/uri/punycode.cr
Labels: kind:refactor

#7247 Replace #status_code with #status
  spec/std/http/client/response_spec.cr
  spec/std/http/http_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/http/status_spec.cr
  src/http/client/response.cr
  src/http/common.cr
  src/http/formdata.cr
  src/http/server/handler.cr
  src/http/server/handlers/error_handler.cr
  src/http/server/handlers/static_file_handler.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/server/response.cr
  src/http/status.cr
  src/http/web_socket/protocol.cr
  src/oauth2/client.cr
Labels: breaking-change, kind:feature, kind:refactor, pr:needs-review, topic:stdlib

#6581 Refactor Time methods
  spec/std/time/time_spec.cr
  src/time.cr
Labels: kind:refactor, topic:stdlib:time

#7627 Fix infinite loop in asm with 3 colons and a variable
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#6323 Refactor and improve URI implementation
  spec/std/http/request_spec.cr
  spec/std/uri/uri_parser_spec.cr
  spec/std/uri_spec.cr
  src/http/request.cr
  src/oauth/consumer.cr
  src/oauth2/client.cr
  src/socket/address.cr
  src/uri.cr
  src/uri/uri_parser.cr
Labels: breaking-change, kind:bug, kind:refactor, kind:specs, topic:stdlib

#7352 Optimize String#compare in case of ASCII only
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:refactor, performance, topic:stdlib:text

#7617 Mention git pre-commit hook in CONTRIBUTING.md
  CONTRIBUTING.md
  scripts/git/pre-commit
Labels: kind:docs

#7513 Document Unicode::CaseOptions enum
  src/docs_main.cr
  src/unicode/unicode.cr
Labels: kind:docs, pr:needs-review, topic:stdlib:text

#7646 Allow Spec's .pending and .it to accept constant
  src/spec/methods.cr
Labels: kind:feature, topic:stdlib:specs

#7638 Add Big*#//, BigInt#&-ops and missing #floor, #ceil, #trunc
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/big/big_rational_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
Labels: kind:feature, topic:stdlib:numeric

#7264 Expose LibCrypt's PKCS5_PBKDF2_HMAC
  spec/std/openssl/hmac_spec.cr
  spec/std/openssl/pkcs5_spec.cr
  src/oauth2/access_token/mac.cr
  src/openssl/algorithm.cr
  src/openssl/hmac.cr
  src/openssl/lib_crypto.cr
  src/openssl/pkcs5.cr
Labels: breaking-change, kind:feature, status:accepted, topic:stdlib:crypto

#7661 Make compiler warnings opt-in
  src/annotations.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
  src/docs_main.cr
  src/prelude.cr
Labels: kind:feature, topic:compiler

#7628 Pending leftovers to support // and &-ops in multiple places
  spec/compiler/codegen/const_spec.cr
  spec/compiler/crystal/tools/doc/highlighter_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/semantic/const_spec.cr
  spec/compiler/semantic/static_array_spec.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/math_interpreter.cr
  src/compiler/crystal/tools/doc/highlighter.cr
  src/symbol.cr
Labels: kind:feature, topic:compiler

#7653 Display deprecated label when @[Deprecated] is used
  src/compiler/crystal/tools/doc/constant.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/macro.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:feature, topic:tools:docs

#7586 Add deprecation notice for Time.now
  src/time.cr
Labels: kind:feature, topic:stdlib:time

#7667 Fix &block restriction for documentation
  src/io.cr
  src/string.cr
Labels: kind:docs

#7668 Restore Time.new as deprecated method
  src/time.cr
Labels: kind:feature, topic:stdlib:time

#7618 Remove comma as enum member delimiter
  spec/compiler/codegen/c_enum_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/c_enum_spec.cr
  spec/compiler/semantic/instance_var_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: breaking-change, topic:compiler:parser, topic:lang, topic:tools:formatter

#7639 Int div deprecation
  spec/std/deque_spec.cr
  spec/std/enumerable_spec.cr
  spec/std/int_spec.cr
  spec/std/random/secure_spec.cr
  src/array.cr
  src/base64.cr
  src/big/big_int.cr
  src/bit_array.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/tools/table_print.cr
  src/compiler/crystal/types.cr
  src/crystal/compiler_rt.cr
  src/crystal/event.cr
  src/crystal/hasher.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/time.cr
  src/debug/dwarf/line_numbers.cr
  src/deque.cr
  src/fiber/stack_pool.cr
  src/float/printer/cached_powers.cr
  src/float/printer/grisu3.cr
  src/humanize.cr
  src/int.cr
  src/io/buffered.cr
  src/llvm/abi.cr
  src/llvm/abi/aarch64.cr
  src/llvm/abi/arm.cr
  src/llvm/abi/x86_64.cr
  src/llvm/target_data.cr
  src/number.cr
  src/random.cr
  src/random/pcg32.cr
  src/range.cr
  src/string.cr
  src/string_pool.cr
  src/time.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/formatter.cr
  src/time/location.cr
  src/time/span.cr
  src/uri/punycode.cr
  src/zip/file_info.cr
Labels: kind:refactor, topic:stdlib:numeric

#7664 Add deprecation message to PartialComparable
  src/partial_comparable.cr
Labels: kind:feature, topic:stdlib:collection

#7665 Add documentation for Flags and Link annotations
  src/annotations.cr
Labels: kind:docs, topic:stdlib

#7669 Restore Time.new(Location) as deprecated method
  src/time.cr
Labels: kind:feature, topic:stdlib:time

#7651 add bool types to Bool
  src/bool.cr
Labels: topic:stdlib:runtime

#7674 Restore File.join for single arguments
  spec/std/file_spec.cr
  src/file.cr
Labels: kind:feature, topic:stdlib:files

#7546 MT GC
  samples/mt_gc_test.cr
  src/crystal/scheduler.cr
  src/fiber.cr
  src/fiber/aarch64.cr
  src/fiber/arm.cr
  src/fiber/context.cr
  src/fiber/context/aarch64.cr
  src/fiber/context/arm.cr
  src/fiber/context/i686.cr
  src/fiber/context/x86_64.cr
  src/fiber/i686.cr
  src/fiber/x86_64.cr
  src/gc/boehm.cr
  src/gc/none.cr
  src/thread.cr
Labels: kind:feature, topic:stdlib:concurrency

#7663 Release 0.28.0
  CHANGELOG.md
  VERSION
Labels: kind:docs

#7640 Refactor StaticFileHandler specs for Last-Modified header
  spec/std/http/server/handlers/static_file_handler_spec.cr
Labels: kind:refactor, kind:specs, topic:stdlib:networking

#7635 Improve URI#normalize
  spec/std/uri_spec.cr
  src/uri.cr
Labels: kind:feature, topic:stdlib:networking

#7703 Fix offsetof not being usable with macros
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#7705 Upgrade CI to use Crystal 0.28.0
  .circleci/config.yml
  Makefile
  VERSION
  bin/ci
Labels: topic:infrastructure

#7699 Format: remove old code to format &.[]
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, kind:refactor, topic:tools:formatter

#7720 Fix Unicode not showing up in the API docs
  scripts/unicode_data.ecr
  src/unicode/data.cr
Labels: kind:bug, kind:docs
