Repository crystal-lang/crystal, pull requests merged in 2019-06, with the labels that each got.

#7418 Atomic::Flag
  spec/std/atomic_spec.cr
  src/atomic.cr
  src/signal.cr
Labels: kind:feature, topic:stdlib:concurrency

#7582 Disallow '!' or '?' at the end of the LHS in an assignment
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/syntax/parser.cr
Labels: breaking-change, topic:lang

#7854 Fix Def#to_s with **options and &block
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#7423 add support for UDP multicast
  spec/std/socket/udp_socket_spec.cr
  src/lib_c/aarch64-linux-gnu/c/netinet/in.cr
  src/lib_c/aarch64-linux-musl/c/netinet/in.cr
  src/lib_c/arm-linux-gnueabihf/c/netinet/in.cr
  src/lib_c/i386-linux-gnu/c/netinet/in.cr
  src/lib_c/i386-linux-musl/c/netinet/in.cr
  src/lib_c/x86_64-darwin/c/netinet/in.cr
  src/lib_c/x86_64-freebsd/c/netinet/in.cr
  src/lib_c/x86_64-linux-gnu/c/netinet/in.cr
  src/lib_c/x86_64-linux-musl/c/netinet/in.cr
  src/lib_c/x86_64-openbsd/c/netinet/in.cr
  src/socket/udp_socket.cr
Labels: kind:feature, pr:needs-review, topic:stdlib:networking

#7673 Add docs for Channel
  src/channel.cr
Labels: kind:docs, topic:stdlib:concurrency

#7492 Fix time format RFC 3339 to not include offset seconds
  spec/std/json/serialization_spec.cr
  spec/std/time/custom_formats_spec.cr
  src/time/format/formatter.cr
  src/time/format/parser.cr
Labels: kind:bug, topic:stdlib:serialization, topic:stdlib:time

#7852 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#7863 Update CI to use 0.29.0
  .circleci/config.yml
  bin/ci
  src/VERSION
Labels: topic:infrastructure

#7871 Fix cipher expectation in OpenSSL Socket spec
  spec/std/openssl/ssl/socket_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:crypto

#7879 thread: Fix sysconf call on OpenBSD
  src/thread.cr
Labels: kind:bug, topic:stdlib:runtime

#7886 Fix edge cases in code parser and stringifier (found by fuzzing)
  spec/compiler/lexer/lexer_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:parser

#7881 Compiler: fix enum overflow math
  spec/compiler/semantic/enum_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#7898 Fixed typo in Logger API docs
  src/logger.cr
Labels: kind:bug, kind:docs

#7893 Build: Automated snap publishing
  .circleci/config.yml
Labels: topic:infrastructure

#7820 forward read_/write_timeout in ssl socket to underlaying socket
  src/openssl/ssl/socket.cr
Labels: kind:feature, topic:stdlib:networking

#7906 Parser: slash after end is not regex
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#7907 Compiler: fix top-level private const not working
  spec/compiler/semantic/private_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#7908 HTTP::Server: don't double-close response
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#7916 Compiler: fix generic metaclass inheritance
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#7891 Compiler: fix annotation lookup on generic types
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#7889 Formatter: format top-level inline macros
  spec/compiler/crystal/tools/expand_spec.cr
  spec/compiler/crystal/tools/format_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/std/llvm/aarch64_spec.cr
  spec/std/llvm/arm_abi_spec.cr
  spec/std/llvm/x86_64_abi_spec.cr
  spec/std/llvm/x86_abi_spec.cr
  src/callstack/lib_unwind.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
  src/crystal/lib_event2.cr
  src/dir/glob.cr
  src/openssl.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
  src/readline.cr
  src/yaml/lib_yaml.cr
Labels: kind:feature, topic:tools:formatter

#7901 Fix: UUID#to_slice returns a dangling pointer
  spec/std/uuid_spec.cr
  src/uuid.cr
Labels: breaking-change, kind:bug, topic:stdlib

#7899 Allow setting default capacity for StringPool
  spec/std/string_pool_spec.cr
  src/string_pool.cr
Labels: kind:feature, topic:stdlib

#7924 Fix unicode alternate ranges generation
  scripts/generate_unicode_data.cr
  spec/std/string_spec.cr
  src/unicode/data.cr
Labels: kind:bug, topic:stdlib:text

#7921 Implement Enumerable#tally
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection

#7862 Adds support to HTTP::Params.encode encode an arrays of values for a key.
  spec/std/http/params_spec.cr
  src/http/params.cr
Labels: kind:feature, topic:stdlib

#7935 Add debug log helper function for codegen
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/phi.cr
  src/llvm/basic_block.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm_ext.cr
Labels: kind:feature, topic:compiler

#7938 YAML: deserialize String last in a union type
  spec/std/yaml/serialization_spec.cr
  src/yaml/from_yaml.cr
Labels: kind:bug, topic:stdlib:serialization
