Repository crystal-lang/crystal, pull requests merged in 2020-03, with the labels that each got.

#8869 Update the cant_infer_block_return_type URL
  src/compiler/crystal/semantic/call.cr
Labels: kind:bug, topic:compiler

#8857 Allow Time::Span.new with positional + nanoseconds
  spec/std/time/span_spec.cr
  src/time/span.cr
Labels: topic:stdlib:time

#8863 Use flag?(:i386) instead of i686
  spec/compiler/codegen/asm_spec.cr
  src/callstack.cr
  src/fiber/context/i386.cr
  src/intrinsics.cr
  src/lib_c.cr
Labels: kind:bug, platform, topic:stdlib

#8860 Update future.cr
  src/concurrent/future.cr
Labels: kind:docs, topic:stdlib:concurrency

#8879 Wait for server to start listening on web socket specs
  spec/std/http/web_socket_spec.cr
Labels: kind:specs, topic:multithreading, topic:stdlib:networking

#8884 Make Reflect an Enumerable private definition
  src/enumerable.cr
  src/prelude.cr
  src/reflect.cr
Labels: kind:refactor, topic:stdlib:collection

#8882 Remove DL module
  src/dl.cr
  src/docs_main.cr
Labels: breaking-change, topic:stdlib

#8883 Move AtExitHandlers to Crystal namespace
  src/crystal/at_exit_handlers.cr
  src/crystal/main.cr
  src/kernel.cr
Labels: kind:refactor, topic:stdlib:runtime

#8873 IO: Set fd to -1 on closed File/Socket
  spec/std/socket/unix_server_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/file.cr
  src/file/preader.cr
  src/io/file_descriptor.cr
  src/socket.cr
Labels: kind:bug, topic:multithreading, topic:stdlib:files, topic:stdlib:networking

#8870 Compiler: don't say "undefined method" on abstract leaf types
  spec/compiler/semantic/class_spec.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#8880 Show warnings on docs command
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/warnings.cr
  src/compiler/crystal/syntax/exception.cr
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:feature, topic:tools:docs

#8876 Add flush to many builders
  src/csv.cr
  src/ini.cr
  src/json/builder.cr
  src/xml/builder.cr
  src/yaml/builder.cr
Labels: kind:feature, topic:stdlib:serialization

#8881 Move Adler32 and CRC32 to Digest
  spec/std/digest/adler32_spec.cr
  spec/std/digest/crc32_spec.cr
  spec/std/zip/zip_spec.cr
  src/adler32/adler32.cr
  src/crc32/crc32.cr
  src/digest/adler32.cr
  src/digest/crc32.cr
  src/gzip/gzip.cr
  src/gzip/reader.cr
  src/gzip/writer.cr
  src/zip/checksum_reader.cr
  src/zip/checksum_writer.cr
  src/zip/zip.cr
  src/zlib/reader.cr
  src/zlib/writer.cr
  src/zlib/zlib.cr
Labels: breaking-change, topic:stdlib

#8890 Move Iconv to Crystal namespace
  src/crystal/iconv.cr
  src/io/encoding.cr
  src/prelude.cr
  src/string.cr
Labels: kind:refactor, topic:stdlib:text

#8894 Fix document of Int#gcd
  src/int.cr
Labels: kind:bug, kind:docs

#8892 Deprecate top-level with_color. Add Colorize.with
  spec/std/colorize_spec.cr
  src/colorize.cr
  src/compiler/crystal/exception.cr
  src/compiler/crystal/tools/print_hierarchy.cr
Labels: breaking-change, kind:refactor, topic:stdlib:text

#8900 Use CRYSTAL_OPTS env variable as default compiler options
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler

#8902 Revert "Deprecate String#codepoint_at"
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#8896 Rename YAML::Builder.new with block to YAML::Builder.build
  spec/std/yaml/builder_spec.cr
  src/yaml/builder.cr
Labels: breaking-change, kind:refactor, topic:stdlib:serialization

#8911 Fix File.dirname with unicode chars
  spec/std/file_spec.cr
  src/path.cr
Labels: kind:bug, topic:stdlib:files

#8906 Unicode: update to version 13.0.0
  scripts/generate_unicode_data.cr
  src/unicode/data.cr
Labels: kind:feature, topic:stdlib:text

#8899 Avoid using the default --exclude-warnings value if some is specified
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler

#8912 Add CSV#rewind
  spec/std/csv/csv_spec.cr
  src/csv.cr
  src/csv/lexer.cr
  src/csv/lexer/io_based.cr
  src/csv/lexer/string_based.cr
  src/csv/parser.cr
Labels: kind:feature, topic:stdlib:serialization

#8915 Fix broken link to ruby's prettyprint source
  src/pretty_print.cr
Labels: kind:bug, kind:docs

#8923 Add String overloads for ljust, rjust and center that take an IO
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#8908 IO::Hexdump: forward missing methods to underlaying IO
  src/io/hexdump.cr
Labels: kind:feature, topic:stdlib:files

#8924 Add Int#bit_length
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:feature, topic:stdlib:numeric

#8927 Make OptionParser example to exit on --help
  src/option_parser.cr
Labels: kind:docs, topic:stdlib

#8847 Log module
  spec/compiler/crystal/tools/playground_spec.cr
  spec/std/log/broadcast_backend_spec.cr
  spec/std/log/builder_spec.cr
  spec/std/log/context_spec.cr
  spec/std/log/env_config_spec.cr
  spec/std/log/io_backend_spec.cr
  spec/std/log/log_spec.cr
  spec/std/log/main_spec.cr
  src/compiler/crystal.cr
  src/compiler/crystal/command/playground.cr
  src/compiler/crystal/tools/playground/server.cr
  src/crystal/datum.cr
  src/docs_main.cr
  src/log.cr
  src/log/backend.cr
  src/log/broadcast_backend.cr
  src/log/builder.cr
  src/log/context.cr
  src/log/entry.cr
  src/log/env_config.cr
  src/log/io_backend.cr
  src/log/log.cr
  src/log/main.cr
  src/log/memory_backend.cr
  src/logger.cr
Labels: breaking-change, kind:feature, topic:stdlib

#8931 Correctly implement bit_length for BigIng
  spec/std/int_spec.cr
  src/big/big_int.cr
  src/big/lib_gmp.cr
  src/int.cr
Labels: kind:bug, performance, topic:stdlib:numeric

#8940 LLVM 10 support
  src/llvm/ext/find-llvm-config
Labels: kind:feature, topic:compiler

#8935 Add `IO::Buffered#flush_on_newline` back and set it to true for non-tty
  spec/std/io/buffered_spec.cr
  src/http/server/response.cr
  src/io/buffered.cr
  src/io/file_descriptor.cr
  src/kernel.cr
Labels: topic:stdlib:files

#8941 Fix typo on "iterate"
  src/compiler/crystal/macros/interpreter.cr
Labels: topic:compiler

#8942 Windows: Remove the workaround using vsnprintf.
  src/lib_c/x86_64-windows-msvc/c/stdio.cr
Labels: platform:windows

#8948 Compiler: Honor LIBRARY_PATH as default library path
  src/compiler/crystal/codegen/link.cr
Labels: kind:feature, topic:compiler

#8678 Add type annotation to tls argument in http
  src/http/client.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/web_socket.cr
  src/http/web_socket/protocol.cr
Labels: kind:refactor, topic:stdlib:networking

#8966 Add Time::Span#total_microseconds
  spec/std/time/span_spec.cr
  src/time/span.cr
Labels: kind:feature, topic:stdlib:time

#8969 Compiler: let Proc(T) pass a restriction of Proc(Nil)
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: topic:compiler:semantic

#8970 Compiler: allow assigning Proc(R) to Proc(Nil)
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_merge.cr
Labels: kind:bug, kind:feature

#8960 Add Enumerable#empty? method
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection
