Repository crystal-lang/crystal, pull requests merged in 2020-07, with the labels that each got.

#9543 Allow HTTP::Client to work with any IO
  spec/std/http/client/client_spec.cr
  spec/std/http/server/server_spec.cr
  src/http/client.cr
Labels: kind:feature, topic:stdlib:networking

#9360 Port to NetBSD
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/semantic/flags.cr
  src/crystal/iconv.cr
  src/crystal/system.cr
  src/crystal/system/random.cr
  src/crystal/system/unix/arc4random.cr
  src/crystal/system/unix/pthread.cr
  src/crystal/system/unix/sysconf_cpucount.cr
  src/crystal/system/unix/sysctl_cpucount.cr
  src/crystal/system/unix/urandom.cr
  src/errno.cr
  src/lib_c/x86_64-netbsd/c/arpa/inet.cr
  src/lib_c/x86_64-netbsd/c/dirent.cr
  src/lib_c/x86_64-netbsd/c/dlfcn.cr
  src/lib_c/x86_64-netbsd/c/elf.cr
  src/lib_c/x86_64-netbsd/c/errno.cr
  src/lib_c/x86_64-netbsd/c/fcntl.cr
  src/lib_c/x86_64-netbsd/c/grp.cr
  src/lib_c/x86_64-netbsd/c/iconv.cr
  src/lib_c/x86_64-netbsd/c/link.cr
  src/lib_c/x86_64-netbsd/c/netdb.cr
  src/lib_c/x86_64-netbsd/c/netinet/in.cr
  src/lib_c/x86_64-netbsd/c/netinet/tcp.cr
  src/lib_c/x86_64-netbsd/c/pthread.cr
  src/lib_c/x86_64-netbsd/c/pwd.cr
  src/lib_c/x86_64-netbsd/c/sched.cr
  src/lib_c/x86_64-netbsd/c/signal.cr
  src/lib_c/x86_64-netbsd/c/stdarg.cr
  src/lib_c/x86_64-netbsd/c/stddef.cr
  src/lib_c/x86_64-netbsd/c/stdint.cr
  src/lib_c/x86_64-netbsd/c/stdio.cr
  src/lib_c/x86_64-netbsd/c/stdlib.cr
  src/lib_c/x86_64-netbsd/c/string.cr
  src/lib_c/x86_64-netbsd/c/sys/file.cr
  src/lib_c/x86_64-netbsd/c/sys/mman.cr
  src/lib_c/x86_64-netbsd/c/sys/resource.cr
  src/lib_c/x86_64-netbsd/c/sys/select.cr
  src/lib_c/x86_64-netbsd/c/sys/socket.cr
  src/lib_c/x86_64-netbsd/c/sys/stat.cr
  src/lib_c/x86_64-netbsd/c/sys/time.cr
  src/lib_c/x86_64-netbsd/c/sys/types.cr
  src/lib_c/x86_64-netbsd/c/sys/un.cr
  src/lib_c/x86_64-netbsd/c/sys/wait.cr
  src/lib_c/x86_64-netbsd/c/sysctl.cr
  src/lib_c/x86_64-netbsd/c/termios.cr
  src/lib_c/x86_64-netbsd/c/time.cr
  src/lib_c/x86_64-netbsd/c/unistd.cr
  src/math/libm.cr
  src/process/executable_path.cr
  src/socket/address.cr
  src/socket/tcp_socket.cr
  src/termios.cr
Labels: kind:feature, platform, pr:ready-to-merge

#9220 Print original exception after failing to raise it
  src/raise.cr
Labels: kind:feature, topic:stdlib:runtime

#9538 Fix: `Socket#accept` obeys `read_timeout`
  spec/std/socket/socket_spec.cr
  src/io/evented.cr
  src/socket.cr
Labels: kind:bug, topic:stdlib:networking

#9502 Reject annotations on ivars defined in base class
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: breaking-change, kind:bug, topic:compiler:semantic

#9566 Make specs pending instead of failing in no multicast environments
  spec/std/socket/udp_socket_spec.cr
  src/spec/dsl.cr
  src/spec/example.cr
  src/spec/methods.cr
Labels: kind:bug, kind:specs

#9508 AArch64 CI
  .github/workflows/aarch64.yml
  spec/std/http/web_socket_spec.cr
Labels: kind:feature, platform:aarch64

#9432 Logging dispatcher
  spec/std/http/server/handlers/log_handler_spec.cr
  spec/std/log/dispatch_spec.cr
  spec/std/log/io_backend_spec.cr
  spec/support/retry.cr
  src/log.cr
  src/log/backend.cr
  src/log/broadcast_backend.cr
  src/log/builder.cr
  src/log/dispatch.cr
  src/log/io_backend.cr
  src/log/log.cr
  src/log/main.cr
  src/log/memory_backend.cr
Labels: kind:feature, performance, topic:stdlib:log

#9564 Hide Channel internal implementation methods
  spec/std/channel_spec.cr
  src/channel.cr
Labels: breaking-change, kind:refactor, topic:stdlib:concurrency

#8516 Array rotate optimization
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:refactor, performance, topic:stdlib:collection

#9592 Use content instead of value when inspect XML::Attribute
  spec/std/xml/xml_spec.cr
  src/xml/node.cr
Labels: kind:feature, topic:stdlib

#9609 Use 'brew bundle' to install macOS dependencies in CI
  .circleci/config.yml
  .github/workflows/macos.yml
  Brewfile
  bin/ci
Labels: platform:darwin, topic:infrastructure

#9615 String: don't materialize Regex match[0] if not needed
  src/string.cr
Labels: performance, topic:stdlib:text

#9605 HTTP::Params: `#[]=` replaces all values.
  spec/std/http/params_spec.cr
  spec/std/http/request_spec.cr
  src/http/params.cr
Labels: breaking-change, kind:bug, topic:stdlib:networking

#9610 Compiler: try literal type in autocast first
  spec/compiler/codegen/automatic_cast.cr
  spec/compiler/semantic/automatic_cast_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#9612 Fix HTTP::FormData.parse documentation
  src/http/formdata.cr
Labels: kind:bug, kind:docs

#9398 Add various `String#delete_at` methods
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#9603 OptionParser: don't call handler if value is given to none value handler
  spec/std/option_parser_spec.cr
  src/option_parser.cr
Labels: kind:bug, topic:stdlib

#9624 Compiler: consider `select` as an openning keyword in macros
  spec/compiler/lexer/lexer_macro_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#9627 Replace "whitelisting" with "filtering"
  src/http/server/handler.cr
Labels: kind:docs, kind:refactor

#9585 Check abstract def implementations with splats, default values and keyword arguments
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
Labels: breaking-change, kind:feature, topic:compiler:semantic

#9629 Fix ASTNode#to_s for parenthesized expression in block
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:semantic

#9632 Allow overriding CRYSTAL_PATH in the wrapper script
  .circleci/config.yml
  bin/crystal
Labels: topic:infrastructure

#9571 Remove unnecessary fallback 'def ==(other)'
  spec/std/bit_array_spec.cr
  spec/std/deque_spec.cr
  spec/std/http/params_spec.cr
  spec/std/socket/address_spec.cr
  src/bit_array.cr
  src/deque.cr
  src/http/params.cr
  src/socket/address.cr
Labels: kind:refactor, topic:stdlib

#9625 Delay setup of HTTP::CompressHandler until content is written
  spec/std/http/server/handlers/compress_handler_spec.cr
  spec/std/http/web_socket_spec.cr
  src/http/server/handlers/compress_handler.cr
Labels: kind:bug, topic:stdlib:networking

#9642 Run `brew update --preinstall` before installing
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#9630 Attach doc comment to annotation in macro expansion
  spec/compiler/semantic/doc_spec.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
Labels: kind:bug, topic:compiler:semantic
