Repository crystal-lang/crystal, pull requests merged in 2020-01, with the labels that each got.

#8640 Remove fixed date in spec
  spec/std/http/cookie_spec.cr
Labels: kind:specs, topic:stdlib:networking

#8641 CI: use lld if present (Linux only)
  Makefile
Labels: topic:infrastructure

#8617 Add CircleCI test summaries
  .circleci/config.yml
  bin/ci
  spec/std/string_spec.cr
Labels: topic:infrastructure

#8643 Fix mutex specs race condition on mt
  spec/std/mutex_spec.cr
Labels: kind:specs, topic:stdlib:concurrency

#8646 Remove some deprecated methods and modules
  src/crypto/bcrypt/password.cr
  src/http/server/response.cr
  src/json/pull_parser.cr
  src/json/token.cr
  src/string.cr
  src/time.cr
  src/uri/encoding.cr
Labels: breaking-change, topic:stdlib

#8650 Fix #8649: Future(Nil).get when the future raises
  spec/std/concurrent/future_spec.cr
  src/concurrent/future.cr
Labels: kind:bug, topic:stdlib:concurrency

#8651 make wait_readable and wait_writable public
  src/io/evented.cr
Labels: topic:stdlib:files

#8506 Allow timeout in select statements
  spec/std/channel_spec.cr
  spec/std/spec_helper.cr
  src/channel.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/unix/event_libevent.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/fiber.cr
Labels: kind:feature, topic:stdlib:concurrency

#8619 Formatter: remove unnecessary escape sequences
  spec/compiler/crystal/tools/doc/generator_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  spec/compiler/semantic/responds_to_spec.cr
  spec/std/ecr/ecr_spec.cr
  spec/std/spec/junit_formatter_spec.cr
  spec/std/string_spec.cr
  spec/std/xml/builder_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/token.cr
  src/compiler/crystal/tools/formatter.cr
  src/regex.cr
Labels: kind:feature, topic:tools:formatter

#8657 Drop support for comma separators in enums and other cleanups
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/c_enum_spec.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
  src/primitives.cr
Labels: breaking-change, topic:compiler

#8498 Improve error message for getaddrinfo failure
  spec/std/socket/addrinfo_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  src/socket/addrinfo.cr
Labels: kind:feature, topic:stdlib:networking

#8484 Improve documentation for `Random::Secure`
  src/random/secure.cr
Labels: kind:docs, topic:stdlib:crypto

#6467 Validate Crypto::Bcrypt::Password is a valid hash
  spec/std/crypto/bcrypt/password_spec.cr
  src/crypto/bcrypt/password.cr
Labels: kind:feature, topic:stdlib:crypto

#8661 Enable System for win32 in prelude
  src/prelude.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#8667 Fix unforgiving ENV["HOME"] in Path spec
  spec/std/path_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:files

#8664 Add list of specs working on win32 in std_spec
  spec/generate_windows_spec.sh
  spec/spec_helper.cr
  spec/std/crystal/hasher_spec.cr
  spec/std/int_spec.cr
  spec/std/spec/tap_formatter_spec.cr
  spec/std_spec.cr
  spec/win32_std_spec.cr
  src/http.cr
  src/http/common.cr
Labels: kind:specs, platform:windows

#8672 Refactor StaticFileHandler to use Path
  src/http/server/handlers/static_file_handler.cr
  src/http/server/handlers/static_file_handler.html
Labels: kind:refactor, platform:windows, topic:stdlib:networking

#6362 Remove `ditto` and `nodoc` without colons
  spec/compiler/semantic/doc_spec.cr
  src/array.cr
  src/big/big_int.cr
  src/bit_array.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/path_lookup.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/complex.cr
  src/csv/builder.cr
  src/dir/glob.cr
  src/humanize.cr
  src/io.cr
  src/iterator.cr
  src/json/builder.cr
  src/kernel.cr
  src/math/math.cr
  src/named_tuple.cr
  src/path.cr
  src/string.cr
  src/time/span.cr
  src/tuple.cr
  src/xml/builder.cr
  src/xml/node.cr
Labels: breaking-change, pr:needs-work, topic:compiler

#8605 Simplify LLVM_CONFIG shell macro
  .circleci/config.yml
  Makefile
  src/llvm/ext/find-llvm-config
  src/llvm/lib_llvm.cr
Labels: kind:refactor, topic:infrastructure

#8670 Fix specs on win32
  spec/std/concurrent_spec.cr
  spec/std/crystal/hasher_spec.cr
  spec/std/dir_spec.cr
  spec/std/file_spec.cr
  spec/std/float_printer_spec.cr
  spec/std/int_spec.cr
  spec/std/path_spec.cr
  spec/std/raise_spec.cr
  spec/std/spec_helper.cr
  src/dir/glob.cr
Labels: kind:bug, kind:specs, platform:windows

#8668 Refactor Dir.mkdir_p to use Path#each_parent
  spec/std/dir_spec.cr
  spec/std/file_utils_spec.cr
  spec/support/tempfile.cr
  src/dir.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#8679 Print built sample command in CI.
  bin/ci
Labels: topic:infrastructure

#8674 Fix multi_writer specs to close file before reading/deleting it
  spec/std/io/multi_writer_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:files

#8483 Allow getting a TypeNode's name without type vars
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:lang:macros

#8535 Add VaList#next
  spec/compiler/codegen/primitives_spec.cr
  spec/compiler/semantic/primitives_spec.cr
  spec/manual/valist_spec.cr
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/intrinsics.cr
  src/llvm/builder.cr
  src/llvm/lib_llvm.cr
  src/va_list.cr
Labels: kind:feature, topic:compiler

#8688 Move VaList va_arg spec to codegen/primitives_spec.cr
  spec/compiler/codegen/primitives_spec.cr
  spec/manual/valist_spec.cr
Labels: kind:refactor, kind:specs

#8692 Spec::JUnitFormatter: Allow output directory as --junit_output
  src/spec/junit_formatter.cr
Labels: kind:bug, topic:stdlib:specs

#8695 Compiler: check typeof dependencies before cleanup
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler:semantic

#8697 Formatter: fix bug related to comment after macro
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#8705 Fix typo in example
  src/channel.cr
Labels: kind:bug, kind:docs

#8702 Fix TCPServer spec to not assume error message for double binding
  spec/std/socket/tcp_server_spec.cr
Labels: kind:bug, kind:specs, platform:linux-gnu, topic:stdlib:networking

#8708 [CI] Build Alpine Docker images
  .circleci/config.yml
Labels: kind:feature, topic:infrastructure

#8689 JSON: improved deserialization into union types
  spec/std/json/serialization_spec.cr
  src/json/from_json.cr
Labels: kind:bug, topic:stdlib:serialization

#8707 IO: Detect closed IO when resuming readable/writable event
  spec/std/io/io_spec.cr
  spec/std/socket/udp_socket_spec.cr
  src/crystal/system/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/io/evented.cr
  src/io/file_descriptor.cr
  src/signal.cr
  src/socket.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:stdlib:networking

#8720 Add Object#in?
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:feature, topic:stdlib:collection

#8699 Fix expected error message in libxml2 error spec
  spec/std/xml/xml_spec.cr
Labels: kind:bug, kind:specs

#8662 Numbers: Use binary primitive for Float#fdiv
  src/big/number.cr
  src/float.cr
  src/primitives.cr
Labels: kind:refactor, topic:stdlib:numeric

#8710 Raise exception in case of wrongly normalized target triple
  src/compiler/crystal/codegen/target.cr
Labels: kind:bug, topic:compiler

#8676 Add continuous testing on Windows using GitHub Actions
  .github/workflows/win.yml
Labels: platform:windows, topic:infrastructure

#8723 Use Object#in? throughout the stdlib
  samples/2048.cr
  spec/compiler/crystal/tools/implementations_spec.cr
  spec/std/bit_array_spec.cr
  spec/std/string_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/init.cr
  src/crystal/system/unix/file.cr
  src/dir/glob.cr
  src/ecr/process.cr
  src/html.cr
  src/http/server/handlers/static_file_handler.cr
  src/string.cr
  src/time/format/parser.cr
  src/time/location/loader.cr
  src/uri/encoding.cr
Labels: kind:refactor, topic:stdlib

#8724 Ensure sending fiber finished in select specs
  spec/std/concurrent/select_spec.cr
Labels: kind:specs, topic:stdlib:concurrency
