Repository crystal-lang/crystal, pull requests merged in 2020-02, with the labels that each got.

#7420 Add test_alpine to circleci config
  .circleci/config.yml
  bin/ci
  spec/std/kernel_spec.cr
Labels: kind:feature, platform:linux-musl, topic:infrastructure

#8007 Rework File::Info user and group methods
  spec/std/file_spec.cr
  src/crystal/system/unix/file_info.cr
  src/crystal/system/unix/user.cr
  src/crystal/system/win32/file_info.cr
  src/file/info.cr
  src/system/group.cr
  src/system/user.cr
Labels: breaking-change, kind:feature, topic:stdlib

#8681 update `crystal init` to handle `.`
  src/compiler/crystal/tools/init.cr
Labels: kind:feature, pr:needs-work, topic:compiler

#8654 Fix error when raising a macro exception with empty message
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/semantic/exception.cr
Labels: kind:bug, topic:compiler

#8728 Ensure LibUnwind::Exception struct is not atomic
  spec/std/data/collect_within_ensure
  spec/std/exception_spec.cr
  src/callstack/lib_unwind.cr
  src/raise.cr
Labels: kind:bug, topic:stdlib:runtime

#8747 Use a high-res logo in README.md
  README.md
Labels: kind:docs

#8746 Codegen: Use llvm memset and memcpy matching arch
  spec/llvm-ir/memcpy.cr
  spec/llvm-ir/memset.cr
  spec/llvm-ir/test.sh
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler

#8743 Handle exceptions raised at `__crystal_sigfault_handler`
  src/signal.cr
Labels: kind:bug, topic:stdlib:system

#8742 Fix Time#shift over date boundaries with zone offset
  spec/std/time/time_spec.cr
  src/time.cr
Labels: kind:bug, topic:stdlib:time

#8739 Add documentation to Fiber
  src/fiber.cr
Labels: kind:docs, topic:stdlib:concurrency

#8752 Change CRYSTAL_PATH to allow shards to hide std-lib
  bin/crystal
Labels: kind:bug, topic:compiler

#8757 Compiler: virtualize type of Proc pointer
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/bindings.cr
Labels: kind:bug, topic:compiler:semantic

#8758 Compiler: fix type of vars after begin/rescue if all rescue unreachable
  spec/compiler/semantic/exception_spec.cr
  spec/compiler/semantic/ssa_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#8762 Compiler: propagate visibility to macro expansions in all cases
  spec/compiler/semantic/private_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:semantic

#8760 Compiler: fix bug parsing macro with "eenum" in it
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#8759 HTTP::Cookie: parse max-age as Int64, not Int32
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:bug, topic:stdlib:networking

#8698 `JSON::PullParser` overflow handling
  spec/std/json/pull_parser_spec.cr
  spec/std/json/serialization_spec.cr
  src/json/from_json.cr
  src/json/pull_parser.cr
Labels: kind:bug, topic:stdlib:serialization

#8768 Formatter: format `exp.!`
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#8763 Add BigInt#unsafe_shr
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
Labels: kind:bug, topic:stdlib:numeric

#8753 Fix Path.new receiving Path as first argument
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, topic:stdlib:files

#8761 Rewrite block buffered channel spec
  spec/std/channel_spec.cr
Labels: kind:specs, topic:stdlib:concurrency

#8745 Guard against non-structure values in {JSON,YAML}::Any#dig?
  spec/std/json/any_spec.cr
  spec/std/yaml/any_spec.cr
  src/json/any.cr
  src/yaml/any.cr
Labels: kind:bug, topic:stdlib:collection, topic:stdlib:serialization

#8778 Formatter: properly indent comments at the end of a proc literal
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#8779 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#8786 Allow Crystal::System.print_error to use printf like format
  src/callstack.cr
  src/crystal/scheduler.cr
  src/crystal/system/print_error.cr
  src/raise.cr
  src/signal.cr
Labels: kind:feature, topic:stdlib:runtime

#8733 IO: Polish IO closing for MT
  spec/std/io/io_spec.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/thread_local_value.cr
  src/io/evented.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:stdlib:networking

#8787 Try to open stdio in non-blocking mode
  spec/spec_helper.cr
  spec/std/io/file_descriptor_spec.cr
  src/io/file_descriptor.cr
Labels: kind:bug, topic:stdlib:files

#8782 Drop uppercase F32 and F64 float number suffixes
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: breaking-change, topic:compiler:parser

#8735 Top level exception handler
  src/crystal/main.cr
  src/signal.cr
Labels: kind:bug, topic:stdlib:runtime

#8791 Some rework of top level error handling
  src/crystal/main.cr
  src/crystal/system/print_error.cr
  src/kernel.cr
Labels: kind:bug, kind:refactor, topic:stdlib:runtime

#8796 Compiler: fix inherited visibility of macro hooks
  spec/compiler/semantic/private_spec.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#8804 Update CI to use 0.33.0
  .circleci/config.yml
  .github/workflows/win.yml
  bin/ci
  spec/std/int_spec.cr
  src/VERSION
Labels: topic:infrastructure

#8800 Docs: Add `from_yaml` description & example
  src/yaml/from_yaml.cr
Labels: kind:docs, topic:stdlib:serialization

#8801 Disable Thread specs on musl
  spec/std/thread/condition_variable_spec.cr
  spec/std/thread/mutex_spec.cr
  spec/std/thread_spec.cr
Labels: kind:specs, platform:linux-musl, topic:stdlib:concurrency

#8805 Fix typo on src/signal.cr: 'corrpution'
  src/signal.cr
Labels: kind:bug, topic:stdlib:system

#8811 Win CI: Use latest versions of libraries
  .github/workflows/win.yml
Labels: platform:windows, topic:infrastructure

#8755 Ensure UNIXServer is accepting before closing in specs
  spec/std/channel_spec.cr
  spec/std/concurrent/select_spec.cr
  spec/std/io/io_spec.cr
  spec/std/mutex_spec.cr
  spec/std/socket/unix_server_spec.cr
  spec/std/spec_helper.cr
  spec/support/fibers.cr
Labels: kind:specs, topic:stdlib:networking

#8737 Refactor Crystal::Init adding name validation
  man/crystal.1
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/tools/init/template/readme.md.ecr
Labels: kind:feature, kind:refactor, topic:tools

#8813 Add XML.build_fragment
  spec/std/xml/xml_spec.cr
  src/xml/builder.cr
Labels: kind:feature, topic:stdlib:serialization

#8816 Fix pretty_json outdated sample
  samples/pretty_json.cr
Labels: kind:bug

#8772 Remove obsolete TODOs
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/semantic/flags.cr
  src/range.cr
Labels: breaking-change, topic:compiler

#8257 Improve Time::Span initialization API
  spec/std/time/span_spec.cr
  spec/std/time/time_spec.cr
  src/time.cr
  src/time/span.cr
Labels: breaking-change, topic:stdlib:time

#8683 Enable more win32 specs
  .github/workflows/win.yml
  spec/generate_windows_spec.sh
  spec/std/http/client/response_spec.cr
  spec/std/http/cookie_spec.cr
  spec/std/http/formdata/builder_spec.cr
  spec/std/http/formdata/parser_spec.cr
  spec/std/http/formdata_spec.cr
  spec/std/http/http_spec.cr
  spec/std/http/server/handlers/error_handler_spec.cr
  spec/std/http/server/handlers/handler_spec.cr
  spec/std/http/server/handlers/log_handler_spec.cr
  spec/std/http/server/handlers/static_file_handler_spec.cr
  spec/std/http/server/request_processor_spec.cr
  spec/std/json/any_spec.cr
  spec/std/json/mapping_spec.cr
  spec/std/json/serializable_spec.cr
  spec/std/json/serialization_spec.cr
  spec/std/mime/media_type_spec.cr
  spec/std/random_spec.cr
  spec/std/range_spec.cr
  spec/std/spec/junit_formatter_spec.cr
  spec/std/spec_helper.cr
  spec/std/string_spec.cr
  spec/std/struct_spec.cr
  spec/std/system_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/win32/file.cr
  src/http.cr
  src/http/client/response.cr
  src/http/common.cr
  src/http/cookie.cr
  src/http/server.cr
  src/http/server/context.cr
  src/http/server/handler.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/server/request_processor.cr
  src/http/server/response.cr
  src/logger.cr
  src/spec/junit_formatter.cr
  src/windows_stubs.cr
Labels: kind:specs, platform:windows

#8817 Fix UDP specs in the case of a local firewall
  spec/std/socket/udp_socket_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:networking

#8819 feat: add Complex.round
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:feature, topic:stdlib:numeric

#8822 Enable IO specs on win32
  spec/std/io/buffered_spec.cr
  spec/std/io/io_spec.cr
  spec/std/io/memory_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: kind:specs, platform:windows

#8795 Fix MIME spec examples to not collide with actual registry
  spec/std/mime_spec.cr
Labels: kind:bug, topic:stdlib:networking

#8826 Raise on `Big*#to_u` with negative values
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
Labels: kind:bug, topic:stdlib:numeric

#8838 Explicitly Convert `Float32` to `Float64` Before Call
  spec/std/float_printer_spec.cr
  src/float/printer.cr
Labels: kind:bug, topic:stdlib:numeric

#8750 Close underlying WebSocket connection when connection is closed
  src/http/server/handlers/websocket_handler.cr
  src/http/web_socket.cr
  src/http/web_socket/protocol.cr
Labels: kind:bug, topic:stdlib:networking

#8850 Deque#from_json/to_json
  spec/std/json/serialization_spec.cr
  src/json/from_json.cr
  src/json/to_json.cr
Labels: kind:feature, topic:stdlib:serialization
