Repository crystal-lang/crystal, pull requests merged in 2020-06, with the labels that each got.

#9383 Add Int#digits
  spec/std/big/big_int_spec.cr
  spec/std/int_spec.cr
  src/big/big_int.cr
  src/int.cr
Labels: breaking-change, kind:feature, topic:stdlib:numeric

#9300 Fix double string escape in XML::Node#content=
  spec/std/xml/xml_spec.cr
  src/xml/node.cr
Labels: kind:bug, topic:stdlib:serialization

#9388 Allow calling `at_exit` inside `at_exit`
  spec/std/kernel_spec.cr
  src/crystal/at_exit_handlers.cr
  src/kernel.cr
Labels: kind:bug, topic:stdlib:runtime

#9268 Parser: allow ->@ivar.foo and ->@@cvar.foo
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser, topic:compiler:semantic

#9319 Remove HTTP::Params::Builder#to_s
  src/http/params.cr
Labels: kind:refactor, topic:stdlib:networking

#9320 Fix flush methods to always flush underlying IO
  src/compress/deflate/writer.cr
  src/pretty_print.cr
  src/xml/builder.cr
  src/yaml/builder.cr
Labels: kind:bug, topic:stdlib:files, topic:stdlib:networking

#9059 Add file and line references in spec_helper asserts
  spec/spec_helper.cr
Labels: kind:refactor, kind:specs

#9302 Doc: show input type path instead of full qualified path on generic
  spec/compiler/crystal/tools/doc/type_spec.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:bug, topic:tools:docs

#9344 Improve File.utime precision from second to 100-nanosecond on Windows
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/time.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, platform:windows, topic:stdlib:files, topic:stdlib:time

#9391 Format: fix formatting `&.!`
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#9382 Format: avoid formatter crash on heredoc having interpolation of sting literal
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#9393 Make compiler specs use locally build crystal
  spec/compiler/config_spec.cr
Labels: kind:refactor, kind:specs, topic:compiler

#9384 Split general ABI specs from x86_64-specific ones, run on every platform
  spec/compiler/codegen/c_abi/c_abi_spec.cr
  spec/compiler/codegen/c_abi/c_abi_x86_64_spec.cr
Labels: kind:refactor, kind:specs

#9395 Specify pkgconfig name for libevent
  src/crystal/system/unix/lib_event2.cr
Labels: topic:stdlib:runtime

#9399 Array: fix delete_at bug with negative start index
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#9400 Log: check severity before backend
  src/log/log.cr
Labels: kind:refactor, topic:stdlib:log

#9351 Improve spec helpers, prepare for compiler specs on Windows
  spec/compiler/codegen/private_spec.cr
  spec/compiler/compiler_spec.cr
  spec/compiler/util_spec.cr
  spec/spec_helper.cr
  spec/std/spec_helper.cr
  spec/support/tempfile.cr
  spec/support/win32.cr
  src/compiler/crystal/util.cr
  src/prelude.cr
Labels: kind:refactor, kind:specs, platform:windows, topic:compiler

#9410 Hide internal __ fun from docs
  src/crystal/compiler_rt/mulodi4.cr
  src/crystal/once.cr
Labels: kind:docs

#9408 Minor INI improvements
  src/ini.cr
Labels: breaking-change

#9407 Fix compile time checking of method definition
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/time.cr
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:bug, platform

#9387 Basic support for Win64 C lib ABI
  spec/compiler/codegen/c_abi/c_abi_spec.cr
  spec/compiler/codegen/c_abi/c_abi_x86_64_spec.cr
  spec/compiler/codegen/extern_spec.cr
  spec/compiler/codegen/primitives_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/llvm/abi.cr
  src/llvm/abi/x86.cr
  src/llvm/abi/x86_64.cr
  src/llvm/abi/x86_win64.cr
  src/llvm/target_machine.cr
Labels: platform:windows, topic:compiler:codegen

#9412 Fix http specs on mt
  spec/std/http/spec_helper.cr
  spec/support/fibers.cr
Labels: kind:specs, topic:multithreading, topic:stdlib:networking

#9313 WebSocket shouldn't reply with same close code
  src/http/web_socket.cr
Labels: kind:bug, topic:stdlib:networking

#9161 Ensure `type_vars` works for generic modules.
  spec/compiler/codegen/macro_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:compiler:semantic

#9257 Implement File#fsync on Windows
  src/crystal/system/win32/file.cr
  src/file.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#9171 Improve compiler single-file run syntax
  spec/compiler/compiler_spec.cr
  spec/compiler/data/args_test
  src/compiler/crystal/command.cr
Labels: breaking-change, kind:feature, topic:compiler

#9403 Fix overflow checking for operations with mixed sign
  spec/std/overflow_spec.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/program.cr
Labels: kind:bug, topic:compiler:codegen

#9423 Tidy up Makefile and crystal env output
  Makefile
  bin/crystal
  src/compiler/crystal/crystal_path.cr
Labels: topic:infrastructure

#9402 Remove redundant spec relying on crystal being in PATH
  spec/std/process_spec.cr
Labels: kind:refactor, kind:specs

#9418 Ignore response body during WebSocket handshake
  spec/std/http/web_socket_spec.cr
  src/http/web_socket/protocol.cr
Labels: kind:bug, topic:stdlib:networking

#9426 Specify pkgconfig name for libyaml
  src/yaml/lib_yaml.cr
Labels: topic:stdlib:serialization

#9420 Add support for Path pattern to Dir.glob
  spec/std/dir_spec.cr
  src/dir/glob.cr
Labels: kind:feature, topic:stdlib:files

#9417 Compiler: fix incorrect type generated with `as?` when type is a union
  spec/compiler/codegen/nilable_cast_spec.cr
  src/compiler/crystal/program.cr
Labels: kind:bug, topic:compiler:semantic

#9428 Use `Process.quote` for `crystal env` output
  src/compiler/crystal/command/env.cr
Labels: breaking-change, kind:bug, topic:compiler

#9409 Allow executing OpAssign (+=, ||=, etc.) inside macros
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:bug, topic:lang:macros

#9436 Specify pkgconfig name for libxml2
  src/xml/libxml2.cr
Labels: topic:stdlib:serialization

#9427 Make YAML specs robust against libyaml 0.2.5
  spec/std/yaml/serializable_spec.cr
  spec/std/yaml/serialization_spec.cr
Labels: kind:bug, topic:stdlib:specs

#9433 Compiler: don't duplicate instance var in inherited generic type
  spec/compiler/codegen/generic_class_spec.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: kind:bug, topic:compiler:semantic

#9435 Compiler: preserve all union types in `as?`
  spec/compiler/semantic/nilable_cast_spec.cr
  src/compiler/crystal/program.cr
Labels: kind:bug, topic:compiler:semantic

#9434 Make IOBackend formatter a named argument
  src/log/io_backend.cr
Labels: kind:refactor, topic:stdlib:log

#9458 Parser: fix parsing of proc in hash `of` key type
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#9459 Use less strict cipher compatibility for OpenSSL client context
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/ssl/context.cr
Labels: kind:feature, topic:stdlib:crypto

#9461 Compiler: show warnings even if there are errors
  spec/compiler/codegen/warnings_spec.cr
  spec/compiler/semantic/warnings_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/warnings.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/command/eval.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/warnings.cr
Labels: topic:compiler

#9470 [ci skip] Fix Log.context.set docs for hash based data
  src/log/main.cr
Labels: kind:docs, topic:stdlib:log

#9469 Revert IO#write changes in 0.35.0 and let it return Nil
  spec/std/http/chunked_content_spec.cr
  spec/std/http/request_spec.cr
  spec/std/http/server/response_spec.cr
  spec/std/io/buffered_spec.cr
  spec/std/io/io_spec.cr
  spec/std/io/memory_spec.cr
  spec/std/io/sized_spec.cr
  spec/std/io/stapled_spec.cr
  spec/support/io.cr
  src/compress/deflate/writer.cr
  src/compress/gzip/writer.cr
  src/compress/zip/checksum_writer.cr
  src/compress/zlib/writer.cr
  src/float.cr
  src/http/content.cr
  src/http/server/response.cr
  src/http/web_socket/protocol.cr
  src/int.cr
  src/io.cr
  src/io/buffered.cr
  src/io/byte_format.cr
  src/io/delimited.cr
  src/io/encoding.cr
  src/io/hexdump.cr
  src/io/memory.cr
  src/io/multi_writer.cr
  src/io/sized.cr
  src/io/stapled.cr
  src/openssl/digest/digest_io.cr
  src/string/builder.cr
Labels: topic:stdlib:networking

#9500 Fix Digest::Base block argument type restrictions
  spec/std/digest/md5_spec.cr
  spec/std/digest/sha1_spec.cr
  spec/std/digest/spec_helper.cr
  src/digest/base.cr
Labels: kind:bug, topic:stdlib:crypto

#9507 Win CI: Avoid looking for globally installed libs
  .github/workflows/win.yml
Labels: kind:bug, platform:windows

#9513 Remove Travis IRC notifications
  .travis.yml
Labels: topic:infrastructure

#9468 here is gone
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:refactor, pr:ready-to-merge, topic:compiler:parser

#9515 Document how to generate the SNAPCRAFT_TOKEN
  .circleci/config.yml
Labels: topic:infrastructure

#9422 Fix VaList and disable va_arg for AArch64
  spec/compiler/codegen/primitives_spec.cr
  spec/spec_helper.cr
  spec/std/spec_helper.cr
  spec/std/va_list_spec.cr
  spec/support/tempfile.cr
  spec/win32_std_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/lib_c/aarch64-linux-gnu/c/stdarg.cr
  src/lib_c/aarch64-linux-musl/c/stdarg.cr
  src/va_list.cr
Labels: kind:bug, platform:aarch64, topic:compiler

#9520 Fix bug with passing many args then a struct in Win64 C lib ABI
  spec/compiler/codegen/c_abi/c_abi_spec.cr
  src/llvm/abi/x86_win64.cr
Labels: kind:bug, platform:windows

#9514 GitHub Actions
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  bin/ci
  src/spec/formatter.cr
Labels: topic:infrastructure

#9430 Fix C ABI for AArch64
  spec/compiler/codegen/c_abi/c_abi_spec.cr
  spec/std/llvm/aarch64_spec.cr
  src/llvm/abi/aarch64.cr
Labels: kind:bug, platform:aarch64

#9497 Docs: Add a note regarding Log.setup
  src/log.cr
Labels: kind:docs, pr:ready-to-merge

#9448 Update installation link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind:docs

#9505 Prevent recursive call in bin/crystal wrapper
  bin/crystal
Labels: kind:bug, pr:ready-to-merge

#9376 Extract helper methods in call_error.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:refactor, pr:ready-to-merge, topic:compiler:semantic

#9361 Use function attribute "frame-pointer"
  src/compiler/crystal/codegen/fun.cr
Labels: topic:compiler

#9380 Add Crystal::Path#name_size implementation
  src/compiler/crystal/syntax/ast.cr
Labels: kind:bug, topic:compiler:parser

#9438 Make specs pass in non-IPv6 environments
  spec/std/http/client/client_spec.cr
  spec/std/oauth2/client_spec.cr
  spec/std/openssl/ssl/server_spec.cr
  spec/std/openssl/ssl/socket_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/spec_helper.cr
Labels: kind:bug, kind:specs

#9348 Win CI: Fix and enable compiler specs
  .github/workflows/win.yml
  spec/compiler/codegen/extern_spec.cr
  spec/compiler/codegen/lib_spec.cr
  spec/compiler/codegen/special_vars_spec.cr
  spec/compiler/codegen/thread_local_spec.cr
  spec/compiler/compiler_spec.cr
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  spec/compiler/crystal/tools/format_spec.cr
  spec/compiler/crystal/tools/init_spec.cr
  spec/compiler/crystal/tools/playground_spec.cr
  spec/compiler/crystal_path/crystal_path_spec.cr
  spec/compiler/semantic/generic_class_spec.cr
  spec/compiler/semantic/primitives_spec.cr
  spec/std/exception/call_stack_spec.cr
  spec/std/io/file_descriptor_spec.cr
  spec/support/tempfile.cr
  spec/win32_std_spec.cr
  src/empty.cr
Labels: kind:feature, platform:windows, pr:ready-to-merge

#9489 Fix type of HTTP::Server::Response#closed? to Bool
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#9530 Drop deprecated CRC32, Adler32 top-level
  spec/std/adler32_spec.cr
  spec/std/crc32_spec.cr
  spec/win32_std_spec.cr
  src/adler32/adler32.cr
  src/crc32/crc32.cr
  src/docs_main.cr
Labels: breaking-change, topic:stdlib

#9529 Drop deprecated Flate, Gzip, Zip, Zlib top-level
  spec/std/flate/flate_spec.cr
  spec/std/gzip/gzip_spec.cr
  spec/std/zip/zip_file_spec.cr
  spec/std/zip/zip_spec.cr
  spec/std/zlib/reader_spec.cr
  spec/std/zlib/stress_spec.cr
  spec/std/zlib/writer_spec.cr
  spec/win32_std_spec.cr
  src/docs_main.cr
  src/flate.cr
  src/gzip.cr
  src/zip.cr
  src/zlib.cr
Labels: breaking-change, topic:stdlib

#9471 Makefile: support changing the current crystal via env var and argument
  Makefile
  bin/crystal
Labels: topic:infrastructure

#9518 Fix `CRYSTAL_OPTS` parsing
  spec/std/process_spec.cr
  src/compiler/crystal/command.cr
  src/process/shell.cr
Labels: kind:feature, topic:stdlib:system

#9531 Drop deprecated with_color top-level method
  samples/2048.cr
  samples/pretty_json.cr
  spec/std/colorize_spec.cr
  src/colorize.cr
Labels: breaking-change, topic:stdlib

#9465 Fix OptionParser to handle sub-commands with hyphen
  spec/std/option_parser_spec.cr
  src/option_parser.cr
Labels: kind:bug, topic:stdlib

#9559 fix "Log" docs
  src/log.cr
Labels: kind:bug, kind:docs

#9557 Update YAML::Field(converter) argument docs
  src/yaml/serialization.cr
Labels: kind:bug, kind:docs, topic:stdlib:serialization

#9550 Add `dup` to BitArray
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: kind:feature, topic:stdlib

#9549 Remove Reference to `Kernel`.
  src/io.cr
  src/string.cr
Labels: kind:bug, kind:docs

#9401 Disable LLVM Global Isel
  spec/std/llvm/aarch64_spec.cr
  spec/std/llvm/arm_abi_spec.cr
  spec/std/llvm/x86_64_abi_spec.cr
  spec/std/llvm/x86_abi_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/jit_compiler.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/target_machine.cr
Labels: kind:bug, platform:aarch64

#9506 Compiler: add a few missing `expanded.transform self`
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler:semantic

#9528 Make `Socket::IpAddress` a bit more type-friendly
  src/socket/address.cr
  src/socket/udp_socket.cr
Labels: kind:refactor, topic:stdlib:networking

#9560 Enable newly passing special var specs
  spec/compiler/codegen/special_vars_spec.cr
Labels: kind:specs, platform:windows, topic:compiler:codegen

#9443 Channel#close returns boolean
  spec/std/channel_spec.cr
  src/channel.cr
Labels: kind:feature, topic:multithreading

#9511 Use unchecked arithmetics in `Int#times`
  src/int.cr
Labels: performance, topic:stdlib

#9558 Fix: cache corrupted when compilation is cancelled
  src/compiler/crystal/compiler.cr
Labels: kind:bug, topic:compiler:codegen
