Repository crystal-lang/crystal, pull requests merged in 2020-08, with the labels that each got.

#9527 Drop deprecated JSON.mapping
  spec/std/json/mapping_spec.cr
  spec/std/json/serializable_spec.cr
  spec/win32_std_spec.cr
  src/json/mapping.cr
  src/json/serialization.cr
Labels: breaking-change, topic:stdlib

#9526 Drop deprecated YAML.mapping
  spec/std/yaml/mapping_spec.cr
  spec/win32_std_spec.cr
  src/yaml/mapping.cr
Labels: breaking-change, topic:stdlib

#9525 Drop deprecated logger
  spec/std/logger_spec.cr
  spec/win32_std_spec.cr
  src/docs_main.cr
  src/logger.cr
Labels: breaking-change, topic:stdlib

#9633 Check abstract def implementations with double splats
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
Labels: kind:feature, topic:compiler:semantic

#9640 fetch git config correctly
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/tools/init/template/license.ecr
Labels: kind:bug, topic:tools

#9663 Update distribution-scripts and publish nightly packages to bintray
  .circleci/config.yml
Labels: topic:infrastructure

#9570 Take timestamp as an argument in Log::Entry initializer
  src/log/entry.cr
Labels: kind:feature, topic:stdlib:log

#9262 Add HTTP::Cookie::SameSite::None
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#9626 HTTP::StaticFileHandler serve pre-gzipped content
  spec/std/data/static_file_handler/test.txt.gz
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/http/server/handlers/static_file_handler.cr
Labels: kind:feature, topic:stdlib:networking

#9668 bug-fix: VerifyMode::FAIL_IF_NO_PEER_CERT
  src/openssl/ssl/context.cr
Labels: kind:bug, security, topic:stdlib:crypto

#9652 Parser: fix `a-b -c` incorrectly parsed as `a - (b - c)`
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: breaking-change, kind:bug, topic:compiler:parser

#9690 Fix String#rindex default offset for matching empty regex correctly
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:text

#9659 Marks else branch of exhaustive case as unreachable
  spec/compiler/semantic/cast_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#9701 Compiler: make inherited hook work through generic instances
  spec/compiler/semantic/hooks_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:generics, topic:compiler:semantic

#9704 Disallow keywords as block argument name
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/digest/md5.cr
Labels: kind:bug, topic:compiler:parser

#9713 Fix `String#index` not working well for broken UTF-8 sequences
  spec/std/char/reader_spec.cr
  spec/std/string/utf16_spec.cr
  spec/std/string_spec.cr
  src/char/reader.cr
  src/path.cr
  src/string.cr
Labels: breaking-change, kind:bug, topic:stdlib:text

#9717 fix spelling mistake in http/server.cr
  src/http/server.cr
Labels: kind:docs, topic:stdlib:networking

#9653 Raise if passing null Pointer to String
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text
