Repository crystal-lang/crystal, pull requests merged in 2020-10, with the labels that each got.

#9788 Fix `Iterator#cons_pair` return type
  spec/std/iterator_spec.cr
  src/iterator.cr
Labels: kind:bug, topic:stdlib:collection

#9684 Make `**` be right associative
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: breaking-change, topic:compiler:parser

#9801 Codegen: don't use init check for consts that are declared before read
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/types.cr
Labels: performance, topic:compiler:codegen

#9792 Use Dwarf information on Exception::CallStack.print_frame
  src/exception/call_stack.cr
Labels: topic:stdlib:runtime

#9806 Allow -Dgc_none to "work" with weak_ref
  src/gc/none.cr
Labels: topic:stdlib:runtime

#9810 Make abstract def return type warning an error
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
Labels: breaking-change, topic:compiler:semantic

#9815 Force secure renegotiation on server
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
Labels: security, topic:stdlib:crypto

#9814 Add OpenSSL::SSL::Context#cipher_suites= and OpenSSL::SSL::Context::CIPHER_SUITES_* constants
  scripts/generate_ssl_server_defaults.cr
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
  src/openssl/ssl/defaults.cr
Labels: kind:feature, topic:stdlib:crypto

#9840 Spelling error
  src/json/serialization.cr
Labels: kind:docs

#9831 Add OpenSSL::SSL::Context#security_level
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
Labels: kind:feature, topic:stdlib:crypto

#9834 Compiler: correctly pass named arguments for previous_def and super
  spec/compiler/codegen/previous_def_spec.cr
  src/compiler/crystal/semantic/normalizer.cr
Labels: kind:bug, topic:compiler:semantic

#9824 Compiler: turn proc pointer into proc literal in some cases
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/semantic/closure_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/fix_missing_types.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#9850 CI: Migrate `::set-env` -> `$GITHUB_ENV`
  .github/workflows/win.yml
Labels: platform:windows, topic:infrastructure

#9851 YAML: allow using disciminator in contained types
  spec/std/yaml/serializable_spec.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization

#9852 Rework dwarf eager loading (follow up to #9792)
  src/exception/call_stack.cr
  src/exception/call_stack/dwarf.cr
  src/exception/call_stack/elf.cr
  src/exception/call_stack/mach_o.cr
  src/kernel.cr
Labels: kind:refactor, topic:stdlib:runtime

#9794 Moving File#fsync, File#flock_exclusive, File#flock_shared, and File#flock_unlock methods to IO::FileDescriptor - Fixes #9793
  src/file.cr
  src/io/file_descriptor.cr
Labels: kind:refactor, topic:stdlib:files

#9567 add support for selective JSON and YAML serialization
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:feature, topic:stdlib:serialization

#9534 C ABI: Add a spec for accepting a large struct - failing on win32, aarch64
  spec/compiler/codegen/c_abi/c_abi_spec.cr
Labels: kind:bug, platform

#9860 Docs: fix Enumerable#sum(initial, &)
  src/enumerable.cr
Labels: kind:docs, topic:stdlib:collection

#9858 Compiler: correctly compute line number afte macro escape
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#9634 Fix: raise error when abstract def implementation adds a type restriction
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
Labels: kind:bug, topic:compiler:semantic

#9854 Fix spelling errors (2)
  src/array.cr
  src/compiler/crystal/codegen/ast.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/formatter.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/compiler/crystal/semantic/new.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/types.cr
  src/csv.cr
  src/fiber/context/aarch64.cr
  src/hash.cr
  src/log/metadata.cr
  src/mime/media_type.cr
  src/number.cr
  src/process.cr
  src/signal.cr
  src/string.cr
  src/string/utf16.cr
  src/struct.cr
  src/time/location.cr
  src/time/span.cr
Labels: kind:docs

#9733 Handle namespaced defaults in {JSON,YAML}::Serializable
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization

#9656 Exhaustive case near and far
  samples/llvm/brainfuck.cr
  samples/sdl/fire.cr
  src/channel.cr
  src/char.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/class_var.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/codegen/types.cr
  src/compiler/crystal/exception.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/class_vars_initializer_visitor.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/lib.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/semantic/type_lookup.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/context.cr
  src/compiler/crystal/tools/doc/markdown/parser.cr
  src/compiler/crystal/tools/doc/type.cr
  src/compiler/crystal/tools/formatter.cr
  src/csv/lexer/string_based.cr
  src/dir/glob.cr
  src/http/server/request_processor.cr
  src/llvm/abi/aarch64.cr
  src/log/entry.cr
  src/string.cr
Labels: kind:refactor

#9808 Codegen: don't use init flag for string constants
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/types.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/types.cr
Labels: performance, topic:compiler:codegen
