Repository crystal-lang/crystal, pull requests merged in 2020-04, with the labels that each got.

#8503 HTTP::Client: don't turn body_io into nil if content-length is zero
  spec/std/http/client/response_spec.cr
  src/http/common.cr
Labels: kind:bug, topic:stdlib:networking

#8975 Correctly support websocket close codes
  spec/std/http/web_socket_spec.cr
  src/compiler/crystal/tools/playground/server.cr
  src/http/web_socket.cr
  src/http/web_socket/close_codes.cr
  src/http/web_socket/protocol.cr
Labels: breaking-change, kind:bug, kind:feature, topic:stdlib:networking

#8982 Install LLVM 10 for OSX CI
  bin/ci
Labels: topic:infrastructure

#8978 Fix Windows codegen (LLVM globals) in non-singlemodule mode
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/primitives.cr
Labels: kind:bug, platform:windows, topic:compiler

#8988 CI: Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#8986 Add missing `Regex#hash` and `Regex::MatchData#hash`
  spec/std/match_data_spec.cr
  spec/std/regex_spec.cr
  src/regex.cr
  src/regex/match_data.cr
Labels: kind:feature, topic:stdlib:text

#8991 Make `SemanticVersion::Prerelease` comparable
  spec/std/semantic_version_spec.cr
  src/semantic_version.cr
Labels: kind:feature, topic:stdlib

#8992 add Location to HTTP::Request common header names
  src/http/common.cr
Labels: kind:feature, topic:stdlib:networking

#9012 Update CI to use 0.34.0
  .circleci/config.yml
  .github/workflows/win.yml
  bin/ci
  src/VERSION
Labels: topic:infrastructure

#9010 Replace old-style `Regex::MatchData` inspection in docs examples
  src/enumerable.cr
  src/regex.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#8781 Remove redundant case-when statement
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:refactor, topic:compiler:parser

#8887 Update hash.cr
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#9018 Document an integrate CRYSTAL_OPTS
  etc/completion.zsh
  man/crystal.1
  src/compiler/crystal/command/env.cr
Labels: kind:docs, kind:feature, topic:compiler

#9006 Rename Process kill methods to signal [by @jan-zajic]
  spec/std/process_spec.cr
  spec/std/signal_spec.cr
  src/compiler/crystal/tools/playground/server.cr
  src/concurrent/future.cr
  src/process.cr
Labels: breaking-change, kind:refactor, topic:stdlib:system

#9017 Fix `RegexLiteral#to_s` output when first character of literal is whitespace
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:semantic

#8447 Add missing documentation to String methods
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#9015 Fix File#pos, File#seek and File#truncate over 2G on Windows
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: platform:windows, topic:stdlib:files

#9024 Compiler: parse `{% unless ~ end %}` as Unless instead of swapped If
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, topic:tools:formatter

#9033 Parser: correctly parse `foo:"bar"` inside call or named tuple
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#9038 Make File.rename overwrite the destination file on Windows, like elsewhere
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
Labels: platform:windows

#9031 Allow building compiler without 'playground', to avoid dependency on sockets
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/tools/playground/agent.cr
  src/compiler/crystal/tools/playground/agent_instrumentor_transformer.cr
  src/compiler/crystal/tools/playground/server.cr
Labels: kind:feature, platform:windows, topic:tools:playground

#9003 Regenerate implementation tool sample
  samples/impl.cr
Labels: kind:bug, kind:docs

#3903 Fix LICENSE and add NOTICE file
  LICENSE
  NOTICE.md
Labels: kind:feature, topic:infrastructure

#8989 Add `Regex#matches?` and `String#matches?`
  spec/std/regex_spec.cr
  spec/std/string_spec.cr
  src/regex.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#9019 Define PID type as Int64
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:refactor, platform, topic:stdlib:system

#9037 Fix file_spec and related exception types on Windows
  spec/std/file_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
  src/file.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:specs, platform:windows

#9034 Add Log handler for HTTP::Server
  src/http/server.cr
Labels: kind:feature, topic:stdlib:networking

#9021 Make Process::Status Windows-compatible
  src/process/status.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#9028 Add support to jquery version 3
  src/compiler/crystal/tools/playground/public/application.js
  src/compiler/crystal/tools/playground/public/session.js
Labels: kind:feature, topic:tools:playground

#9035 Add Crystal::System::Process to split out system-specific implementations
  src/crystal/system/process.cr
  src/crystal/system/unix/process.cr
  src/process.cr
Labels: platform:windows, topic:stdlib:runtime

#9026 Update SSL server secure defaults
  scripts/generate_ssl_server_defaults.cr
  scripts/test_ssl_server.cr
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/ssl/context.cr
  src/openssl/ssl/defaults.cr
Labels: security, topic:stdlib:networking

#9058 Add Log#with_context
  spec/std/log/context_spec.cr
  src/log/main.cr
Labels: kind:feature, topic:stdlib

#9061 Treat cookies which expire in this instant as expired
  src/http/cookie.cr
Labels: kind:bug, topic:stdlib:networking

#9063 Set default values directly on record ivars
  spec/std/record_spec.cr
  src/macros.cr
Labels: kind:bug, topic:stdlib:serialization

#9047 Minimal Windows support for Process
  spec/std/process_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/process.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/stdlib.cr
  src/lib_c/x86_64-windows-msvc/c/synchapi.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/prelude.cr
  src/process.cr
  src/windows_stubs.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#9066 Reference global Spec in `be_a` macro
  src/spec/expectations.cr
Labels: kind:bug, topic:stdlib:specs

#8792 Add project name and version to API docs
  Makefile
  man/crystal.1
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/html/_sidebar.html
  src/compiler/crystal/tools/doc/html/css/style.css
  src/compiler/crystal/tools/doc/html/js/_search.js
  src/compiler/crystal/tools/doc/html/main.html
  src/compiler/crystal/tools/doc/html/type.html
  src/compiler/crystal/tools/doc/project_info.cr
  src/compiler/crystal/tools/doc/templates.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:feature, topic:tools:docs

#9081 Benchmark::IPS::Entry: promote bytes_per_op to UInt64
  src/benchmark/ips.cr
Labels: kind:bug, topic:stdlib

#9068 Fix/update URI::Puncycode documentation
  src/uri/punycode.cr
Labels: kind:bug, kind:docs, topic:stdlib:networking

#9062 Pass the command line to cl.exe through a file
  src/compiler/crystal/compiler.cr
Labels: kind:refactor, topic:compiler

#9082 Remove README link in API docs
  src/compiler/crystal/tools/doc/html/_sidebar.html
  src/compiler/crystal/tools/doc/html/css/style.css
  src/compiler/crystal/tools/doc/html/js/_search.js
Labels: kind:feature, topic:tools:docs

#9085 Remove top-level assert_responds_to macro
  src/macros.cr
Labels: breaking-change, topic:stdlib:macros

#9076 Move CallStack to Exception::CallStack
  spec/std/exception/call_stack_spec.cr
  src/crystal/system/unix/process.cr
  src/exception.cr
  src/exception/call_stack.cr
  src/exception/lib_unwind.cr
  src/raise.cr
  src/signal.cr
  src/windows_stubs.cr
Labels: kind:refactor, topic:stdlib:runtime

#9087 Correct duplicated articles/prepositions in comments
  src/compiler/crystal/command.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/http/cookie.cr
Labels: kind:bug, kind:docs

#9070 Refactor is_crystal_repo based on project name
  spec/compiler/crystal/tools/doc/generator_spec.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/doc/project_info.cr
Labels: kind:feature, topic:tools:docs

#9083 Remove special handling for version tags in docs generator
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  src/compiler/crystal/tools/doc/project_info.cr
Labels: kind:bug, topic:tools:docs

#8538 Improve debugging support
  etc/lldb/crystal_formatters.py
  spec/debug/driver.cr
  spec/debug/strings.cr
  spec/debug/test.sh
  spec/debug/top_level.cr
  spec/spec_helper.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/context.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/fun.cr
  src/llvm/basic_block_collection.cr
  src/llvm/di_builder.cr
  src/llvm/enums.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/function.cr
  src/llvm/instruction_collection.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/value_methods.cr
Labels: kind:feature, topic:compiler:debugger

#9097 Drop top-level parallel macro
  spec/std/channel_spec.cr
  spec/std/concurrent_spec.cr
  src/concurrent.cr
Labels: breaking-change, topic:stdlib:concurrency, topic:stdlib:macros

#9098 XML: Use Fiber level Mutex instead of Thread::Mutex
  src/xml/node.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:stdlib:serialization

#9106 Also expand `subcommands` in Windows linker flags
  src/compiler/crystal/compiler.cr
  src/llvm/lib_llvm.cr
Labels: kind:feature, platform:windows, topic:compiler:codegen

#9105 Add Log::IOBackend#new with formatter
  spec/std/log/io_backend_spec.cr
  src/log/io_backend.cr
Labels: kind:feature, topic:stdlib:log

#9117 Log: fix types referred in documentation
  src/crystal/datum.cr
  src/log/context.cr
Labels: kind:docs, topic:stdlib:log

#9009 OptionParser rewrite with subcommands
  spec/std/option_parser_spec.cr
  src/option_parser.cr
Labels: kind:feature, topic:stdlib

#9079 Parse `\ ` (backslash + space) inside regex literal to ` ` (space)
  spec/compiler/lexer/lexer_string_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#9093 Drop Concurrent::Future and top-level methods delay, future, lazy
  spec/std/concurrent/future_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/io/io_spec.cr
  spec/std/socket/unix_server_spec.cr
  spec/support/channel.cr
  spec/win32_std_spec.cr
  src/concurrent.cr
  src/concurrent/error.cr
  src/concurrent/future.cr
Labels: breaking-change, topic:stdlib:concurrency

#9109 Format: re-tokenize `/` as regex delimiter if regex literal is needed
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#9129 CI: Ensure python@2 is gone and z3 is available for llvm@10
  .circleci/config.yml
  bin/ci
Labels: topic:infrastructure

#9045 Compiler: turn exhaustive case warnings into errors
  spec/compiler/codegen/case_spec.cr
  spec/compiler/codegen/void_spec.cr
  spec/compiler/normalize/case_spec.cr
  spec/compiler/semantic/case_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/exhaustiveness_checker.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/to_s.cr
  src/compiler/crystal/semantic/transformer.cr
Labels: kind:feature, topic:compiler:semantic

#9125 Compiler: don't bleed annotations into other scopes
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#9121 Log: allow nil as context raw values
  spec/std/log/context_spec.cr
  src/crystal/datum.cr
  src/log/context.cr
Labels: kind:feature, topic:stdlib:log

#9004 Compiler: fix autocasting in multidispatch
  spec/compiler/codegen/automatic_cast.cr
  spec/compiler/semantic/automatic_cast.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/match.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#9113 Parser: allow combination of anonymous splat and block arg
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#9112 Fix handle leaks when neither Process#close nor #wait is called on Windows
  src/crystal/system/win32/process.cr
  src/process.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime

#9101 Allow to_json for Log::Context
  spec/std/log/context_spec.cr
  src/log/context.cr
  src/log/json.cr
Labels: kind:feature, status:duplicate, topic:stdlib:log

#9118 Log: validate Fiber.logging_context is a hash
  spec/std/log/context_spec.cr
  src/log/context.cr
Labels: kind:bug, topic:stdlib:log

#9107 Move verbose to a lower level than debug
  spec/std/log/broadcast_backend_spec.cr
  spec/std/log/log_spec.cr
  src/log.cr
  src/log/entry.cr
  src/log/io_backend.cr
  src/log/log.cr
  src/log/main.cr
Labels: kind:feature, kind:refactor, topic:stdlib:log

#9130 Update docs for and slightly improve readability of HTTP::WebSocketHandler
  src/http/server/handlers/websocket_handler.cr
Labels: kind:docs, kind:refactor, topic:stdlib:networking

#9114 Move recent additions to DIBuilder to LLVMExt
  spec/debug/blocks.cr
  spec/debug/test.sh
  src/llvm/di_builder.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
Labels: kind:bug, topic:compiler:debugger

#9123 Win CI: Bootstrap Crystal, build things *on* Windows, publish the binary
  .github/workflows/win.yml
Labels: platform:windows, topic:infrastructure

#9146 Log: Allow override context within logging calls
  spec/std/log/log_spec.cr
  src/log/log.cr
Labels: kind:feature, topic:stdlib:log

#9140 Object: fix lazy property not forwarding annotations
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib:macros

#9150 Log: empty singleton context
  spec/std/log/broadcast_backend_spec.cr
  spec/std/log/context_spec.cr
  src/log/context.cr
  src/log/main.cr
Labels: kind:feature, performance, topic:stdlib:log

#9155 Win CI: Use image that already has LLVM
  .github/workflows/win.yml
Labels: kind:refactor, platform:windows, topic:infrastructure

#9126 Fix Enum#to_s for private enum
  spec/std/enum_spec.cr
  src/enum.cr
Labels: kind:bug, topic:stdlib

#9157 Fix stack overflow in MT when initializing Log::Context.empty
  src/log/context.cr
Labels: kind:bug, topic:multithreading, topic:stdlib:log, topic:stdlib:runtime

#9141 Remove Process.run("which") from compiler
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/tools/init.cr
Labels: kind:refactor, topic:compiler, topic:tools

#9133 Refactor preserving state out of OptionParser#parse
  src/option_parser.cr
Labels: kind:refactor, topic:stdlib

#9149 Implement Process.times on Windows.
  src/crystal/system/win32/process.cr
  src/crystal/system/win32/time.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/process.cr
Labels: platform:windows, topic:stdlib:system

#9138 Add Path#each_part iterator
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:feature, topic:stdlib:files

#9136 Deprecate top-level fork
  src/compiler/crystal/compiler.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/kernel.cr
  src/process.cr
Labels: breaking-change, topic:stdlib:runtime

#9164 Add -h short flag to spec runner
  src/spec.cr
Labels: kind:feature, topic:stdlib:specs

#9144 Win CI: Enable more specs, add zlib and yaml
  .github/workflows/win.yml
  spec/generate_windows_spec.sh
  spec/std/big/number_spec.cr
  spec/std/crystal/hasher_spec.cr
  spec/std/file/tempfile_spec.cr
  spec/std/float_printer_spec.cr
  spec/std/yaml/serialization_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:feature, platform:windows, topic:stdlib:files, topic:stdlib:serialization

#9156 Add JSON and YAML serialization to Path
  spec/std/json/serialization_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/json/from_json.cr
  src/json/to_json.cr
  src/yaml/from_yaml.cr
  src/yaml/to_yaml.cr
Labels: kind:feature, topic:stdlib:files, topic:stdlib:serialization

#9074 Add version selector to API docs
  man/crystal.1
  scripts/docs-versions.sh
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/tools/doc/html/_head.html
  src/compiler/crystal/tools/doc/html/css/style.css
  src/compiler/crystal/tools/doc/html/js/_navigator.js
  src/compiler/crystal/tools/doc/html/js/_search.js
  src/compiler/crystal/tools/doc/html/js/_versions.js
  src/compiler/crystal/tools/doc/html/js/doc.js
  src/compiler/crystal/tools/doc/html/main.html
  src/compiler/crystal/tools/doc/html/type.html
  src/compiler/crystal/tools/doc/project_info.cr
  src/compiler/crystal/tools/doc/templates.cr
Labels: kind:feature, topic:tools:docs

#9132 Add binding to biginteger factorial in GMP
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
  src/big/lib_gmp.cr
Labels: kind:feature, topic:stdlib:numeric

#9176 Move Debug to Crystal namespace
  src/crystal/dwarf.cr
  src/crystal/dwarf/abbrev.cr
  src/crystal/dwarf/info.cr
  src/crystal/dwarf/line_numbers.cr
  src/crystal/dwarf/strings.cr
  src/crystal/elf.cr
  src/crystal/mach_o.cr
  src/exception/call_stack.cr
Labels: breaking-change, topic:stdlib:runtime

#9153 Add support for Path arguments to more methods
  spec/std/dir_spec.cr
  spec/std/process_spec.cr
  src/dir.cr
  src/file.cr
  src/process/executable_path.cr
Labels: kind:feature, topic:stdlib:files

#9177 HTTP server do SSL handshake in client fiber
  spec/std/http/server/server_spec.cr
  spec/std/openssl/ssl/server_spec.cr
  spec/std/openssl/ssl/socket_spec.cr
  src/http/server.cr
  src/openssl/ssl/server.cr
  src/openssl/ssl/socket.cr
Labels: topic:stdlib:crypto, topic:stdlib:networking

#9120 Add .each and .each_with_index to various macro types
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:lang:macros

#9169 Add Path#relative_to
  spec/std/path_spec.cr
  src/exception/call_stack.cr
  src/path.cr
  src/spec/junit_formatter.cr
Labels: kind:feature, topic:stdlib:files

#9145 Log: rework setup_from_env and defaults
  spec/std/log/env_config_spec.cr
  src/compiler/crystal.cr
  src/log.cr
  src/log/builder.cr
  src/log/env_config.cr
  src/log/setup.cr
Labels: kind:feature, topic:stdlib:log

#8999 Add `Enumerable#first` with fallback block
  spec/std/array_spec.cr
  spec/std/deque_spec.cr
  spec/std/enumerable_spec.cr
  src/enumerable.cr
  src/indexable.cr
Labels: breaking-change, kind:feature, topic:stdlib:collection

#9195 Refactor: Use Set#add? in compiler
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/recursive_struct_checker.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
Labels: kind:refactor, topic:compiler
