Repository crystal-lang/crystal, pull requests merged in 2020-11, with the labels that each got.

#9871 Fix Hash#dup and Hash#clone to return correct type for subclasses
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib:collection

#9859 Compiler: assorted fixed regarding generics and splats
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#9822 Correctly render underscores in code blocks
  src/compiler/crystal/tools/doc/highlighter.cr
Labels: kind:bug, topic:tools:docs

#9838 Fix Socket to allow datagram over unix sockets
  spec/std/socket/socket_spec.cr
  src/socket.cr
Labels: kind:bug, topic:stdlib:networking

#9884 Parser: fix end_location of Var nodes followed by plus or minus
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#9739 Complex: moving math methods to Math
  spec/std/complex_spec.cr
  src/complex.cr
Labels: breaking-change, topic:stdlib:numeric

#9868 Fix semantic version
  spec/std/semantic_version_spec.cr
  src/semantic_version.cr
Labels: breaking-change

#9273 Standardize YAML error location
  spec/std/csv/csv_lex_spec.cr
  spec/std/csv/csv_parse_spec.cr
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/csv/error.cr
  src/ini.cr
  src/json.cr
Labels: kind:refactor, topic:stdlib:serialization

#9467 Parser: support heredoc literal in macro
  spec/compiler/codegen/macro_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/token.cr
Labels: kind:bug, topic:compiler:parser

#9864 Refactor Digest
  spec/std/base64_spec.cr
  spec/std/crystal/digest/md5_spec.cr
  spec/std/crystal/digest/sha1_spec.cr
  spec/std/digest/io_digest_spec.cr
  spec/std/digest/md5_spec.cr
  spec/std/digest/sha256_spec.cr
  spec/std/digest/sha512_spec.cr
  spec/std/digest/spec_helper.cr
  spec/std/openssl/digest_io_spec.cr
  spec/std/openssl/digest_spec.cr
  spec/win32_std_spec.cr
  src/compiler/crystal/compiler.cr
  src/compress/gzip/reader.cr
  src/compress/gzip/writer.cr
  src/compress/zip/checksum_reader.cr
  src/compress/zip/checksum_writer.cr
  src/compress/zlib/reader.cr
  src/compress/zlib/writer.cr
  src/crystal/digest/md5.cr
  src/crystal/digest/sha1.cr
  src/digest.cr
  src/digest/adler32.cr
  src/digest/crc32.cr
  src/digest/digest.cr
  src/digest/io_digest.cr
  src/digest/md5.cr
  src/digest/sha1.cr
  src/digest/sha256.cr
  src/digest/sha512.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/web_socket/protocol.cr
  src/openssl.cr
  src/openssl/digest.cr
  src/openssl/digest/digest_base.cr
  src/openssl/digest/digest_io.cr
  src/openssl/lib_ssl.cr
Labels: breaking-change, topic:stdlib:crypto

#9818 examples: fix (2020-10)
  src/file.cr
  src/file_utils.cr
  src/http/params.cr
  src/http/status.cr
  src/http/web_socket.cr
  src/json/to_json.cr
  src/log/format.cr
  src/string.cr
  src/yaml/to_yaml.cr
Labels: kind:docs, topic:stdlib

#9894 Add note about raising IO::Error to Process methods
  src/process.cr
Labels: kind:docs, topic:stdlib:system

#9866 Fix Command#report_warnings to gracefully handle missing Compiler#program
  src/compiler/crystal/semantic/warnings.cr
Labels: kind:bug, topic:compiler

#9817 Linkification in docs: refactor, fix edge cases and add specs
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  src/compiler/crystal/tools/doc/markdown/doc_renderer.cr
Labels: kind:bug, topic:tools:docs

#9893 Fix Process.run uses in compiler to handle exec failure
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/tools/doc/project_info.cr
  src/compiler/crystal/tools/git.cr
  src/compiler/crystal/tools/init.cr
Labels: kind:bug, topic:compiler

#9897 Fix #9715: BigDecimal.to_s
  spec/std/big/big_decimal_spec.cr
  src/big/big_decimal.cr
Labels: kind:bug, topic:stdlib:numeric

#9877 Fix Dir.glob when readdir doesn't report file type
  src/crystal/system/dir.cr
  src/crystal/system/unix/dir.cr
  src/dir/glob.cr
  src/lib_c/aarch64-linux-gnu/c/dirent.cr
  src/lib_c/aarch64-linux-musl/c/dirent.cr
  src/lib_c/arm-linux-gnueabihf/c/dirent.cr
  src/lib_c/i386-linux-gnu/c/dirent.cr
  src/lib_c/i386-linux-musl/c/dirent.cr
  src/lib_c/x86_64-darwin/c/dirent.cr
  src/lib_c/x86_64-dragonfly/c/dirent.cr
  src/lib_c/x86_64-freebsd/c/dirent.cr
  src/lib_c/x86_64-linux-gnu/c/dirent.cr
  src/lib_c/x86_64-linux-musl/c/dirent.cr
  src/lib_c/x86_64-netbsd/c/dirent.cr
  src/lib_c/x86_64-openbsd/c/dirent.cr
Labels: kind:bug, topic:stdlib:files

#9906 CI: Bump GH action versions
  .github/workflows/macos.yml
  .github/workflows/win.yml
Labels: topic:infrastructure

#9911 Init: git_config should strip line breaks
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/git.cr
Labels: kind:bug, topic:tools

#9907 Win CI: Patch LLVM to fix broken build
  .github/workflows/win.yml
Labels: topic:infrastructure

#9912 Win CI: Fix for download-artifact@v2 change
  .github/workflows/win.yml
Labels: topic:infrastructure

#9913 Disable spec that gets stuck on Windows
  spec/compiler/crystal/tools/doc/project_info_spec.cr
Labels: kind:specs, platform:windows

#9878 Remove delete_if
  spec/std/deque_spec.cr
  src/deque.cr
  src/hash.cr
Labels: breaking-change, topic:stdlib:collection

#9321 Add IO flush to builder finish methods
  src/json/builder.cr
  src/mime/multipart/builder.cr
  src/yaml/builder.cr
Labels: kind:feature, pr:needs-review, topic:stdlib:files, topic:stdlib:networking

#9865 Specs: add global timeout to individual specs on mt
  spec/std_spec.cr
  spec/support/mt_abort_timeout.cr
Labels: kind:specs, topic:multithreading

#9902 Fix and enable FileUtils specs on Windows
  spec/std/file_utils_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:specs, platform:windows, topic:stdlib:files

#9904 Make Hash#reject!, Hash#select!, and Hash#compact! consistent with Array
  spec/std/hash_spec.cr
  src/hash.cr
Labels: breaking-change, topic:stdlib:collection

#9819 Exclude types from docs who are in nodoc namespaces
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:tools:docs

#9918 Fix some HTML in docs generator
  src/compiler/crystal/tools/doc/html/_head.html
  src/compiler/crystal/tools/doc/html/_sidebar.html
  src/compiler/crystal/tools/doc/html/js/doc.js
  src/compiler/crystal/tools/doc/html/main.html
  src/compiler/crystal/tools/doc/html/type.html
Labels: kind:bug, topic:tools:docs-generator

#9441 Use Set#add in Set#add documentation.
  src/set.cr
Labels: kind:docs, kind:refactor

#9931 [DocsGenerator] Fix link generation for lib type reference
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:bug, topic:tools:docs-generator

#9811 Support More Literals Inside Macros
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:feature, topic:compiler:parser, topic:lang:macros

#9741 Format: reduce redundant newlines at end of `begin ... end`
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#9495 Fix key type restriction of `Hash#merge` block
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:bug, topic:stdlib:collection

#9440 Allow executing MultiAssign inside macros
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:feature, topic:lang:macros

#9590 Change Set#delete to return Bool
  spec/std/set_spec.cr
  src/set.cr
Labels: breaking-change, topic:stdlib:collection

#9944 Allow `Iterator#zip` to take multiple `Iterator` arguments
  spec/std/iterator_spec.cr
  src/iterator.cr
Labels: kind:feature, topic:stdlib:collection

#5212 HTTP: delete `Content-Encoding` and `Content-Length` headers after decompression
  spec/std/http/client/response_spec.cr
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/http/common.cr
Labels: kind:feature, topic:stdlib:networking

#9984 Add security policy
  SECURITY.md
Labels: topic:infrastructure
