Repository crystal-lang/crystal, pull requests merged in 2021-08, with the labels that each got.

#10997 Add type restriction and conversion to `YAML::PullParser#location`
  src/yaml/pull_parser.cr
Labels: breaking-change, kind:bug, topic:stdlib:serialization

#11039 Compiler: carry FileModule information inside Block
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#10873 Add support for LLVM 12
  spec/compiler/codegen/c_abi/c_abi_x86_64_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/fun.cr
  src/llvm/enums.cr
  src/llvm/ext/llvm-versions.txt
  src/llvm/ext/llvm_ext.cc
  src/llvm/function.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/value_methods.cr
Labels: kind:feature, topic:compiler

#11040 Use markd for markdown rendering in the compiler
  lib/markd/.github/workflows/linux-ci.yml
  lib/markd/.github/workflows/release-version.yml
  lib/markd/.gitignore
  lib/markd/.vscode/launch.json
  lib/markd/CHANGELOG.md
  lib/markd/LICENSE
  lib/markd/README.md
  lib/markd/shard.yml
  lib/markd/spec/api_spec.cr
  lib/markd/spec/fixtures/regression.txt
  lib/markd/spec/fixtures/smart_punct.txt
  lib/markd/spec/fixtures/spec.txt
  lib/markd/spec/markd_spec.cr
  lib/markd/spec/spec_helper.cr
  lib/markd/src/markd.cr
  lib/markd/src/markd/html_entities.cr
  lib/markd/src/markd/mappings/decode.cr
  lib/markd/src/markd/mappings/entities.cr
  lib/markd/src/markd/mappings/legacy.cr
  lib/markd/src/markd/node.cr
  lib/markd/src/markd/options.cr
  lib/markd/src/markd/parser.cr
  lib/markd/src/markd/parsers/block.cr
  lib/markd/src/markd/parsers/inline.cr
  lib/markd/src/markd/renderer.cr
  lib/markd/src/markd/renderers/html_renderer.cr
  lib/markd/src/markd/rule.cr
  lib/markd/src/markd/rules/block_quote.cr
  lib/markd/src/markd/rules/code_block.cr
  lib/markd/src/markd/rules/document.cr
  lib/markd/src/markd/rules/heading.cr
  lib/markd/src/markd/rules/html_block.cr
  lib/markd/src/markd/rules/item.cr
  lib/markd/src/markd/rules/list.cr
  lib/markd/src/markd/rules/paragraph.cr
  lib/markd/src/markd/rules/thematic_break.cr
  lib/markd/src/markd/utils.cr
  lib/markd/src/markd/version.cr
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  spec/compiler/crystal/tools/doc/generator_spec.cr
  spec/compiler/crystal/tools/doc/markdown_spec.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/doc/markd_doc_renderer.cr
  src/compiler/crystal/tools/doc/markdown/html_renderer.cr
  src/compiler/crystal/tools/doc/markdown/markdown.cr
  src/compiler/crystal/tools/doc/markdown/parser.cr
  src/compiler/crystal/tools/doc/markdown/renderer.cr
  src/compiler/crystal/tools/playground/server.cr
Labels: kind:bug, topic:tools:docs-generator

#10623 Change nonsense return types to Nil in formatter classes
  src/mime/multipart/builder.cr
  src/option_parser.cr
  src/pretty_print.cr
  src/string/formatter.cr
  src/time.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/formatter.cr
Labels: breaking-change, kind:bug, kind:docs, topic:stdlib:networking, topic:stdlib:time

#10622 Change nonsense return types to Nil: JSON and YAML
  src/big/json.cr
  src/compiler/crystal/tools/doc/type.cr
  src/json/builder.cr
  src/json/pull_parser.cr
  src/json/to_json.cr
  src/oauth2/access_token/bearer.cr
  src/oauth2/access_token/mac.cr
  src/uuid/json.cr
  src/yaml/any.cr
  src/yaml/builder.cr
  src/yaml/nodes/parser.cr
  src/yaml/parser.cr
  src/yaml/pull_parser.cr
  src/yaml/schema/core/parser.cr
  src/yaml/schema/fail_safe.cr
Labels: breaking-change, kind:bug, kind:docs, kind:refactor, topic:compiler:parser

#10624 Change nonsense return types to Nil in HTTP-related methods and Log
  src/http/client.cr
  src/http/cookie.cr
  src/http/formdata/builder.cr
  src/http/server.cr
  src/http/server/handlers/error_handler.cr
  src/http/server/handlers/log_handler.cr
  src/http/server/handlers/static_file_handler.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/server/request_processor.cr
  src/http/server/response.cr
  src/log/broadcast_backend.cr
  src/log/dispatch.cr
  src/log/format.cr
  src/log/io_backend.cr
  src/log/main.cr
  src/log/memory_backend.cr
  src/oauth/params.cr
  src/oauth2/session.cr
Labels: breaking-change, kind:bug, kind:docs, topic:stdlib:networking

#10625 Change nonsense return types to Nil: uncategorized
  src/benchmark/ips.cr
  src/bit_array.cr
  src/compress/zip/writer.cr
  src/csv/builder.cr
  src/csv/lexer.cr
  src/csv/lexer/io_based.cr
  src/csv/lexer/string_based.cr
  src/csv/parser.cr
  src/deque.cr
  src/exception/call_stack.cr
  src/fiber/stack_pool.cr
  src/file.cr
  src/file_utils.cr
  src/io/console.cr
  src/io/encoding.cr
  src/io/evented.cr
Labels: breaking-change, kind:bug, kind:docs, topic:stdlib

#10621 Change nonsense return types to Nil in IO-related methods
  src/compress/deflate/reader.cr
  src/compress/deflate/writer.cr
  src/compress/gzip/reader.cr
  src/compress/gzip/writer.cr
  src/compress/zip/file.cr
  src/compress/zip/reader.cr
  src/compress/zip/writer.cr
  src/compress/zlib/reader.cr
  src/compress/zlib/writer.cr
  src/csv.cr
  src/file/preader.cr
  src/http/server/response.cr
  src/http/web_socket.cr
  src/http/web_socket/protocol.cr
  src/io/delimited.cr
  src/io/memory.cr
  src/io/sized.cr
  src/io/stapled.cr
  src/mime/multipart/builder.cr
  src/openssl/ssl/socket.cr
  src/pretty_print.cr
  src/xml/builder.cr
Labels: breaking-change, kind:bug, kind:docs, topic:stdlib:files

#11048 Tag std specs that need network access
  spec/std/socket/addrinfo_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
Labels: kind:feature, kind:specs, topic:stdlib:networking

#11029 Refactor sort methods to `#sort` and `#unstable_sort`
  spec/std/array_spec.cr
  spec/std/slice_spec.cr
  src/array.cr
  src/compiler/crystal/tools/doc/type.cr
  src/slice.cr
Labels: kind:refactor, topic:stdlib:collection

#10934 Attach debug locations to generated internal LLVM functions
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/codegen/class_var.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/match.cr
  src/compiler/crystal/codegen/primitives.cr
Labels: kind:feature, topic:compiler:codegen, topic:compiler:debugger

#4665 Add helpful error message for invalid number literal like '.42'
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:refactor, topic:compiler

#11030 Add `CrystalPath.expand_paths`, expand relative to compiler path
  Makefile
  bin/crystal
  man/crystal.1
  spec/compiler/crystal_path/crystal_path_spec.cr
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/crystal_path.cr
Labels: kind:feature, topic:compiler

#11053 Update previous release Crystal 1.1.1
  .circleci/config.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#10809 Fix overflow in `BitArray#[](Int, Int)` for sizes between 33 and 64
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: kind:bug, topic:stdlib:collection

#10597 Formatter: Handle leading tuple literals in multi-expression `return`/`break`/`next` properly
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#11050 Add base64 to prelude
  src/prelude.cr
Labels: kind:feature, topic:stdlib

#11065 Allow `Enumerable(T)#reduce`'s return type to differ from `T`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
  src/tuple.cr
Labels: kind:feature, topic:stdlib:collection

#11075 Fix `File.match?` to accept `Path` type as `path` argument
  spec/std/file_spec.cr
  src/file.cr
Labels: kind:bug, topic:stdlib:files

#11072 XML Namespace improvements
  spec/std/xml/xml_spec.cr
  src/xml/node.cr
Labels: kind:feature, topic:stdlib:serialization

#10987 Add FileUtils method specs with String and Path arguments
  spec/std/file_utils_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:files

#10193 Splat values correctly inside return/break/next statements
  spec/compiler/codegen/return_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/return_spec.cr
  spec/compiler/semantic/splat_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:semantic

#11063 Fix `BigInt#to_s` emitting null bytes for certain values
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
Labels: kind:bug, topic:stdlib:numeric, kind:regression

#11008 Handle already stripped column numbers in exceptions
  src/compiler/crystal/exception.cr
Labels: kind:bug, topic:compiler

#11051 Rename `IO#write_utf8` to `#write_string`.
  src/big/big_int.cr
  src/big/big_rational.cr
  src/char.cr
  src/float/printer.cr
  src/int.cr
  src/io.cr
  src/string.cr
  src/string/builder.cr
  src/string/formatter.cr
Labels: kind:refactor, breaking-change, topic:stdlib:files

#10554 Improve detection of instance variables in extended modules
  spec/compiler/semantic/module_spec.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: kind:bug, topic:compiler:semantic

#11000 Don't compute instance variable initializers on unbound generic instances
  spec/compiler/codegen/generic_class_spec.cr
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#11062 Make `#is_a?` in macros respect the AST node hierarchy
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/syntax/ast.cr
Labels: kind:feature, topic:lang:macros

#11083 Fix trailing rescue syntax
  src/http/server.cr
Labels: kind:bug, topic:stdlib:networking

#11045 fix typo: contains -> contain
  bin/crystal
Labels: kind:bug, topic:infrastructure

#11002 SystemError: Fix inconsistent signature.
  spec/std/system_error_spec.cr
  src/system_error.cr
Labels: kind:bug, topic:stdlib:system

#11011 Use `#write_string` instead of `#write` whenever writing strings to unknown `IO`s
  spec/std/humanize_spec.cr
  spec/std/json/builder_spec.cr
  spec/std/slice_spec.cr
  spec/std/uuid_spec.cr
  spec/std/xml/builder_spec.cr
  spec/std/xml/xml_spec.cr
  spec/std/yaml/builder_spec.cr
  spec/support/string.cr
  src/humanize.cr
  src/json/builder.cr
  src/llvm.cr
  src/slice.cr
  src/uuid.cr
  src/xml/builder.cr
  src/xml/node.cr
  src/yaml/builder.cr
Labels: kind:bug, topic:stdlib:text

#10919 Quote the named tuple's keys on deserialization
  spec/std/json/serialization_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/json/from_json.cr
  src/yaml/from_yaml.cr
Labels: kind:bug, topic:stdlib:serialization

#11093 Improve Int parsing performance
  src/string.cr
Labels: performance, topic:stdlib:numeric

#10990 Fix `CrystalPath#each_file_expansion` spec
  spec/compiler/crystal_path/crystal_path_spec.cr
Labels: kind:bug, topic:compiler, kind:specs

#10975 Syntax errors for invalid 128-bit integer literals
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#10922 Implement `Enumerable#tally_by`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection

#10251 Support auto-splatting in captured block literals
  spec/compiler/semantic/block_spec.cr
  spec/compiler/semantic/closure_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/call.cr
Labels: kind:bug, topic:compiler:semantic

#10451 Make `Int#chr` reject surrogate halves
  spec/std/base64_spec.cr
  spec/std/char_spec.cr
  spec/std/int_spec.cr
  src/char.cr
  src/http/common.cr
  src/int.cr
  src/primitives.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:text

#10529 Detect cyclic includes between generic modules
  spec/compiler/semantic/module_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#10498 Add stricter checks for arguments to macro methods on AST nodes
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, pr:needs-review, kind:refactor, topic:compiler:semantic, topic:lang:macros

#10446 Make `IO#read_char`'s default behaviour UTF-8-strict
  spec/std/io/io_spec.cr
  src/char/reader.cr
  src/io.cr
Labels: kind:bug, topic:stdlib:files

#10564 Proper handling of max-age and expires for cookies
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#11148 Add missing require in iterator_spec
  spec/std/iterator_spec.cr
Labels: kind:bug, topic:stdlib:specs

#11147 Primitive annotations for interpreter
  spec/compiler/codegen/primitives_spec.cr
  spec/compiler/semantic/primitives_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:feature, topic:interpreter

#11128 Fix spec for HTTP::Params can't run on its own
  spec/std/http/params_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:networking

#10378 Clarify usage of "arguments" and "parameters" in error messages
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/block_spec.cr
  spec/compiler/semantic/closure_spec.cr
  spec/compiler/semantic/generic_class_spec.cr
  spec/compiler/semantic/hooks_spec.cr
  spec/compiler/semantic/initialize_spec.cr
  spec/compiler/semantic/lib_spec.cr
  spec/compiler/semantic/macro_spec.cr
  spec/compiler/semantic/method_missing_spec.cr
  spec/compiler/semantic/named_args_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/lib.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/type_declaration_visitor.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/types.cr
  src/http/client.cr
Labels: kind:feature, topic:compiler:semantic

#9298 Add docs to string methods in `SymbolLiteral` and `MacroId`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:lang:macros

#11152 Add missing requires to run a couple of specs standalone
  spec/std/mutex_spec.cr
  spec/std/openssl/digest_spec.cr
Labels: kind:bug, topic:stdlib:specs
