Repository crystal-lang/crystal, pull requests merged in 2021-05, with the labels that each got.

#10673 Update distribution scripts
  .circleci/config.yml
Labels: kind:bug, topic:infrastructure

#9934 Added OpenSSL::Cipher Documentation
  src/openssl/cipher.cr
Labels: kind:docs, topic:stdlib:crypto

#10692 Add free variables to "no overload matches" errors
  spec/compiler/semantic/def_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler:semantic

#10682 Add @top_level to access the top-level scope in macros
  spec/compiler/codegen/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/program.cr
Labels: kind:feature, pr:needs-review, topic:lang:macros

#10705 Fix format of src/openssl/cipher.cr
  src/openssl/cipher.cr
Labels: kind:bug, topic:stdlib:crypto

#10684 [CI] Publish nightly builds to OBS
  .circleci/config.yml
Labels: kind:feature, topic:infrastructure

#10656 Restrict MatchData#begin and #end to Int32
  src/regex/match_data.cr
Labels: kind:bug, topic:stdlib:text

#10664 [doc] Remove superclass from ASTNode in API docs
  spec/compiler/crystal/tools/doc/type_spec.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:bug, pr:ready-to-merge, topic:tools:docs-generator

#10650 Port `Socket::Addrinfo` to win32
  spec/std/socket/addrinfo_spec.cr
  spec/win32_std_spec.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
  src/lib_c/x86_64-windows-msvc/c/ws2def.cr
  src/lib_c/x86_64-windows-msvc/c/ws2tcpip.cr
  src/socket.cr
  src/socket/addrinfo.cr
  src/socket/common.cr
Labels: kind:feature, platform:windows, pr:needs-review, topic:stdlib:networking

#10706 Extract system-specifics from Socket
  src/crystal/system/socket.cr
  src/crystal/system/unix/socket.cr
  src/socket.cr
  src/socket/ip_socket.cr
  src/socket/tcp_server.cr
  src/socket/tcp_socket.cr
  src/socket/udp_socket.cr
  src/socket/unix_server.cr
Labels: kind:refactor, platform, topic:stdlib:networking

#10725 Make `WinError` portable and add it to prelude
  src/crystal/system/win32/time.cr
  src/prelude.cr
  src/system_error.cr
  src/winerror.cr
Labels: kind:feature, platform, topic:stdlib:runtime

#10712 Add `Array#truncate`
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:feature, topic:stdlib:collection

#10633 Fix return type restriction for `Number#humanize` overload
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#10716 Fix double flushing json/yaml builders
  src/json/builder.cr
  src/yaml/builder.cr
Labels: kind:bug, topic:stdlib:serialization

#10683 Add section about pull requests to the contributing guide
  CONTRIBUTING.md
Labels: kind:docs

#10729 Run instance variable initializers on instantiated generic superclasses only
  spec/compiler/codegen/generic_class_spec.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler:generics, topic:compiler:semantic

#10732 Remove #check_needs_resize from IO::Memory, String::Builder
  spec/std/io/io_spec.cr
  src/io/memory.cr
  src/string/builder.cr
Labels: kind:refactor, topic:stdlib:files, topic:stdlib:text

#10654 Improve error handling for `load_localtime` on unix
  src/crystal/system/unix/time.cr
Labels: kind:bug, platform:unix, pr:needs-review, topic:stdlib:time

#10738 Use only last sub-expression of `Expressions` nodes for conditional type filters
  spec/compiler/semantic/if_spec.cr
  spec/compiler/semantic/while_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#10742 Devirtualize types in `TypeNode#==(other : TypeNode)` and `#!=`
  spec/compiler/codegen/generic_class_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:compiler:semantic

#10594 Add type restrictions for splat-less overloads of some methods
  src/array.cr
  src/io.cr
  src/object.cr
Labels: kind:docs, kind:refactor, pr:needs-review, topic:stdlib:collection

#10733 Allow `previous_def` to init superclass's non-nilable ivars
  spec/compiler/semantic/instance_var_spec.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: kind:bug, topic:compiler:semantic

#10744 Always copy `Hash`'s default block on `#dup` and `#clone`
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:bug, topic:stdlib:collection

#10739 Don't compute type filters inside `typeof`'s argument
  spec/compiler/semantic/if_spec.cr
  spec/compiler/semantic/while_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#10519 Fix type restriction logic for generic module instances
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#10758 Avoid union type in Char::Reader#decode_char_at
  src/char/reader.cr
Labels: topic:stdlib:text

#10755 Remove deprecated `ditto` doc directive
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: breaking-change, kind:refactor, topic:tools:docs-generator

#10726 Improve portability of `SystemError`
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/unix/pthread.cr
  src/crystal/system/unix/pthread_condition_variable.cr
  src/crystal/system/unix/pthread_mutex.cr
  src/crystal/system/win32/dir.cr
  src/crystal/system/win32/env.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
  src/errno.cr
  src/file/error.cr
  src/gc/boehm.cr
  src/socket/common.cr
  src/system_error.cr
  src/winerror.cr
Labels: kind:feature, kind:refactor, platform, topic:stdlib:runtime

#10724 Refine documentation for Random#urlsafe_base64
  src/random.cr
Labels: kind:docs, topic:stdlib:crypto

#10754 Bump distribuion-scripts
  .circleci/config.yml
Labels: topic:infrastructure
