Repository crystal-lang/crystal, pull requests merged in 2021-10, with the labels that each got.

#11269 Add `inject_primitives: false` to macro_spec
  spec/compiler/semantic/macro_spec.cr
Labels: performance, kind:refactor, topic:compiler:semantic, kind:specs

#11282 [CI] Pin macOS runner to 10.15
  .github/workflows/macos.yml
Labels: kind:bug, topic:infrastructure

#11285 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#11377 Restrict virtual metaclasses to themselves against `Class`
  spec/compiler/semantic/virtual_metaclass_spec.cr
  src/compiler/crystal/semantic/type_intersect.cr
Labels: kind:bug, topic:compiler:semantic, kind:regression

#11369 Resolve some TODOs
  spec/std/big/big_float_spec.cr
  spec/std/file_spec.cr
  spec/std/http/server/server_spec.cr
  src/crystal/system/unix/lib_event2.cr
  src/http/request.cr
  src/xml/libxml2.cr
  src/yaml/lib_yaml.cr
Labels: topic:stdlib, kind:refactor

#11374 Replace lib version comparisons by functional feature checks
  src/openssl.cr
  src/openssl/bio.cr
  src/openssl/pkcs5.cr
  src/openssl/ssl/context.cr
  src/openssl/ssl/socket.cr
  src/openssl/x509/certificate.cr
Labels: kind:bug, topic:stdlib:crypto, kind:refactor
