Repository crystal-lang/crystal, pull requests merged in 2021-03, with the labels that each got.

#10470 Fix SDL examples crashes
  samples/sdl/fire.cr
  samples/sdl/sdl/surface.cr
  samples/sdl/tv.cr
Labels: kind:bug, kind:docs

#10482 Correct expectation to ensure set identifier
  spec/std/set_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:collection

#10436 Use class instead of struct for objects in XML module.
  src/xml/attributes.cr
  src/xml/builder.cr
  src/xml/namespace.cr
  src/xml/node.cr
  src/xml/node/type.cr
  src/xml/node_set.cr
  src/xml/reader.cr
  src/xml/reader/type.cr
  src/xml/xpath_context.cr
Labels: kind:refactor, topic:stdlib:serialization

#10386 Drop deprecated definitions
  spec/compiler/codegen/macro_spec.cr
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  spec/std/compress/zlib/stress_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/http/request_spec.cr
  spec/std/http/server/handlers/log_handler_spec.cr
  spec/std/int_spec.cr
  spec/std/set_spec.cr
  spec/std/string_spec.cr
  spec/std/time/span_spec.cr
  spec/std/uri_spec.cr
  spec/std/yaml/builder_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/dir.cr
  src/file/info.cr
  src/hash.cr
  src/http/request.cr
  src/http/server/handlers/log_handler.cr
  src/http/web_socket.cr
  src/int.cr
  src/log/setup.cr
  src/option_parser.cr
  src/process.cr
  src/set.cr
  src/spec/expectations.cr
  src/static_array.cr
  src/string.cr
  src/time.cr
  src/time/span.cr
  src/uri.cr
  src/yaml/builder.cr
Labels: breaking-change, topic:stdlib

#10477 Fix doc Set#each returns `nil` instead of `self`
  src/set.cr
Labels: kind:bug, kind:docs, topic:stdlib:collection

#10483 Exclude abstract defs from "no overload matches" errors
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler:semantic

#10485 Remove implicit en-/decoding for cookie values
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: breaking-change, kind:feature, topic:stdlib:networking

#10486 Split `HTTP::Cookies.from_headers` into separate methods for server/client
  spec/std/http/cookie_spec.cr
  src/http/client/response.cr
  src/http/cookie.cr
  src/http/request.cr
Labels: breaking-change, kind:bug, topic:stdlib:networking

#10488 Minor performance improvements to `HTTP::Cookies`
  src/http/cookie.cr
Labels: performance, topic:stdlib:networking

#10479 Fix using roundeven intrinsic on darwin
  .circleci/config.yml
  src/float.cr
  src/math/libm.cr
Labels: kind:bug, platform:darwin, topic:stdlib:numeric

#10494 Bump distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#10476 [CI] Re-enable test_darwin on circle-ci
  bin/ci
Labels: platform:darwin, topic:infrastructure

#10508 Change default rounding mode to `TIES_EVEN`
  spec/std/benchmark_spec.cr
  spec/std/complex_spec.cr
  spec/std/float_spec.cr
  spec/std/humanize_spec.cr
  spec/std/number_spec.cr
  src/number.cr
Labels: breaking-change, kind:refactor, topic:stdlib:numeric

#10505 examples: fix (2021-03)
  src/hash.cr
  src/http/client.cr
  src/json/from_json.cr
  src/json/pull_parser.cr
  src/json/to_json.cr
  src/range.cr
  src/string.cr
  src/uri.cr
  src/yaml/to_yaml.cr
Labels: kind:bug, kind:docs

#10501 Don't merge NamedTuple metaclasses through instance types
  spec/compiler/semantic/named_tuple_spec.cr
  src/compiler/crystal/semantic/type_merge.cr
Labels: kind:bug, topic:compiler:semantic

#10480 [CI] Fix test_macos with recent bash for nix-shell
  bin/ci
Labels: kind:bug, platform:darwin, topic:infrastructure

#10491 Remove implicit `path=/` from `HTTP::Cookie`
  spec/std/http/client/response_spec.cr
  spec/std/http/cookie_spec.cr
  spec/std/http/server/response_spec.cr
  src/http/cookie.cr
Labels: kind:bug, topic:stdlib:networking

#10478 Support closured vars inside Const initializer
  spec/compiler/codegen/const_spec.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:codegen

#10520 Add IO::Sized#remaining=(value) to reuse an existing instance
  spec/std/io/sized_spec.cr
  src/io/sized.cr
Labels: kind:feature, topic:stdlib:files

#10443 Disallow surrogate halves in escape sequences of string and character literals
  spec/compiler/lexer/lexer_spec.cr
  spec/compiler/lexer/lexer_string_spec.cr
  spec/std/string/utf16_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#10430 Support splats inside tuple literals in type names
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:semantic, topic:lang:type-system

#10523 Add llvm 11.1 to the list of supported versions
  src/llvm/ext/llvm-versions.txt
Labels: topic:infrastructure

#10464 Accept pointer instance types on falsey conditional branches
  spec/compiler/semantic/if_spec.cr
  src/compiler/crystal/semantic/filters.cr
Labels: kind:bug, topic:compiler:semantic

#10530 Match named arguments by external parameter names when checking overload cover
  spec/compiler/semantic/def_overload_spec.cr
  src/compiler/crystal/semantic/cover.cr
Labels: kind:bug, topic:compiler:semantic

#10533 CI: Update to use 1.0.0
  .circleci/config.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#10538 Exclude variables' final types inside `while true` if re-assigned before first break
  spec/compiler/semantic/while_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#10537 fix undefined constant error for http/params
  src/http/params.cr
Labels: kind:bug, topic:stdlib:networking

#10046 Add usage instructions for spec runner to compiler
  src/compiler/crystal/command/spec.cr
  src/spec.cr
  src/spec/cli.cr
  src/spec/dsl.cr
Labels: kind:docs, kind:feature, topic:stdlib:specs

#10452 Add `OAuth2::Client#http_client`
  spec/std/http/spec_helper.cr
  spec/std/oauth2/client_spec.cr
  src/oauth2/client.cr
Labels: kind:feature, topic:stdlib:networking

#10522 Fix logic for subclass restricted against uninstantiated nested generic superclass
  spec/compiler/codegen/is_a_spec.cr
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:generics, topic:lang:type-system
