Repository crystal-lang/crystal, pull requests merged in 2021-02, with the labels that each got.

#10347 Compiler: fix while condition assignment check for Not
  spec/compiler/semantic/while_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, kind:regression, topic:compiler:semantic

#10208 Remove duplicated `sort` related specs
  spec/std/array_spec.cr
  spec/std/slice_spec.cr
Labels: kind:refactor, topic:stdlib:collection

#10320 Compiler: don't fail on untyped is_a
  spec/compiler/semantic/is_a_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler:semantic

#10375 Respect subclasses when constructing HTTP::Client from class methods
  spec/std/http/client/client_spec.cr
  src/http/client.cr
Labels: kind:bug, topic:stdlib:networking

#10282 Improve error message for ELF reader on uninitialized runtime
  src/crystal/elf.cr
Labels: kind:bug, topic:stdlib:runtime

#10309 Fix Range#== to ignore generic type arguments
  spec/std/range_spec.cr
  src/range.cr
Labels: kind:bug, topic:stdlib:collection

#10356 Allow Int64 values within `IO#read_at`
  spec/std/file_spec.cr
  src/file.cr
  src/file/preader.cr
  src/io.cr
  src/io/memory.cr
Labels: breaking-change, kind:feature, topic:stdlib:files

#10348 Add aarch64 support for macOS/darwin targets
  spec/compiler/codegen/target_spec.cr
  spec/std/complex_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/lib_c/aarch64-darwin/c/arpa/inet.cr
  src/lib_c/aarch64-darwin/c/dirent.cr
  src/lib_c/aarch64-darwin/c/dlfcn.cr
  src/lib_c/aarch64-darwin/c/errno.cr
  src/lib_c/aarch64-darwin/c/fcntl.cr
  src/lib_c/aarch64-darwin/c/grp.cr
  src/lib_c/aarch64-darwin/c/iconv.cr
  src/lib_c/aarch64-darwin/c/mach/mach_time.cr
  src/lib_c/aarch64-darwin/c/netdb.cr
  src/lib_c/aarch64-darwin/c/netinet/in.cr
  src/lib_c/aarch64-darwin/c/netinet/tcp.cr
  src/lib_c/aarch64-darwin/c/pthread.cr
  src/lib_c/aarch64-darwin/c/pwd.cr
  src/lib_c/aarch64-darwin/c/sched.cr
  src/lib_c/aarch64-darwin/c/signal.cr
  src/lib_c/aarch64-darwin/c/stdarg.cr
  src/lib_c/aarch64-darwin/c/stddef.cr
  src/lib_c/aarch64-darwin/c/stdint.cr
  src/lib_c/aarch64-darwin/c/stdio.cr
  src/lib_c/aarch64-darwin/c/stdlib.cr
  src/lib_c/aarch64-darwin/c/string.cr
  src/lib_c/aarch64-darwin/c/sys/file.cr
  src/lib_c/aarch64-darwin/c/sys/mman.cr
  src/lib_c/aarch64-darwin/c/sys/resource.cr
  src/lib_c/aarch64-darwin/c/sys/select.cr
  src/lib_c/aarch64-darwin/c/sys/socket.cr
  src/lib_c/aarch64-darwin/c/sys/stat.cr
  src/lib_c/aarch64-darwin/c/sys/time.cr
  src/lib_c/aarch64-darwin/c/sys/types.cr
  src/lib_c/aarch64-darwin/c/sys/un.cr
  src/lib_c/aarch64-darwin/c/sys/wait.cr
  src/lib_c/aarch64-darwin/c/termios.cr
  src/lib_c/aarch64-darwin/c/time.cr
  src/lib_c/aarch64-darwin/c/unistd.cr
  src/llvm/target_machine.cr
Labels: platform:aarch64, platform:darwin

#10337 Fix `Process.parse_argument` behavior against a quote in a word
  spec/std/process_spec.cr
  src/process/shell.cr
Labels: kind:bug, topic:stdlib:system

#10390 Close AsyncDispatcher on finalize
  src/log/dispatch.cr
Labels: kind:bug, topic:stdlib:log

#10391 Let `IO::Memory` not be writable with read-only `Slice`
  spec/std/io/memory_spec.cr
  src/io/memory.cr
Labels: kind:bug, topic:stdlib:files

#10382 Fix internal compiler error when exhaustive in-clause calls pseudo-method
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#10369 macros.cr documentation: Grammar fix
  src/compiler/crystal/macros.cr
Labels: kind:bug, kind:docs, topic:compiler:semantic

#10353 Make the `content-length` header more RFC compliant
  spec/std/http/server/handlers/compress_handler_spec.cr
  spec/std/http/server/response_spec.cr
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#10351 Parser: refactor 'foo.%` call parsing
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#10398 Add LibC::MAP_ANONYMOUS to x86_64-darwin to match other platforms
  src/lib_c/x86_64-darwin/c/sys/mman.cr
Labels: platform:darwin, topic:stdlib

#10405 Always add explicit return types in getter/property macros
  src/object.cr
Labels: breaking-change, kind:bug, topic:stdlib:macros

#10388 Don't use named argument key names as parameters for `method_missing` calls
  spec/compiler/codegen/method_missing_spec.cr
  src/compiler/crystal/semantic/method_missing.cr
Labels: kind:bug, topic:compiler:semantic, topic:lang:macros

#10400 Fix named arguments in `super` and `previous_def` calls
  spec/compiler/semantic/previous_def_spec.cr
  spec/compiler/semantic/super_spec.cr
  src/compiler/crystal/semantic/normalizer.cr
Labels: kind:bug, topic:compiler:semantic

#10379 Support `Tuple#[](Range)` with compile-time range literals
  spec/compiler/codegen/tuple_spec.cr
  spec/compiler/semantic/tuple_spec.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/types.cr
  src/tuple.cr
Labels: kind:feature, topic:lang

#10385 HTTP::Request#local_address
  spec/std/http/server/server_spec.cr
  src/http/request.cr
Labels: kind:feature, topic:stdlib:networking

#10009 Fix assignments in array literals
  spec/compiler/codegen/array_literal_spec.cr
  spec/compiler/codegen/hash_literal_spec.cr
  spec/compiler/normalize/array_literal_spec.cr
  spec/compiler/semantic/array_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler:semantic

#10401 Compiler: access instantiations of NamedTuple and other generics uniformly
  spec/compiler/codegen/named_tuple_spec.cr
  spec/compiler/semantic/def_overload_spec.cr
  src/compiler/crystal/codegen/llvm_id.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/recursive_struct_checker.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
  src/compiler/crystal/tools/print_hierarchy.cr
  src/compiler/crystal/tools/typed_def_processor.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#10360 Add Number#round specs
  spec/std/number_spec.cr
Labels: kind:specs, topic:stdlib:numeric

#10327 Improve error message for autocast error at Var assign
  spec/compiler/semantic/automatic_cast_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:feature, topic:compiler:semantic

#10263 Align Proc.new(&block)'s behaviour with other captured blocks
  spec/compiler/codegen/alias_spec.cr
  spec/compiler/codegen/proc_spec.cr
  spec/compiler/semantic/closure_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/proc.cr
Labels: kind:bug, topic:compiler:semantic

#10329 Make {Enumerable,Iterator}#flat_map work with mixed element types
  spec/std/enumerable_spec.cr
  spec/std/iterator_spec.cr
  src/enumerable.cr
  src/iterator.cr
Labels: kind:bug, topic:stdlib:collection

#10389 Fix edge cases for symbol quoting rules
  spec/compiler/codegen/named_tuple_spec.cr
  spec/compiler/crystal/types_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/std/symbol_spec.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/doc/macro.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/doc/type.cr
  src/compiler/crystal/types.cr
  src/named_tuple.cr
  src/symbol.cr
Labels: kind:bug, topic:compiler

#10168 Consider type var splats in generic type restrictions even if instantiation contains no splats
  spec/compiler/semantic/splat_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#10340 Bump Brewfile llvm@9 -> llvm@11
  Brewfile
Labels: topic:infrastructure

#10285 doc fix: adjust example code of recently added Set#*set_of? funcs
  src/set.cr
Labels: kind:bug, kind:docs, topic:stdlib:collection

#10425 Fix `String#to_f` out of range
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:numeric

#10420 Fix downcasting float infinity
  spec/std/float_spec.cr
  spec/std/json/pull_parser_spec.cr
  src/compiler/crystal/codegen/primitives.cr
Labels: kind:bug, topic:stdlib:numeric

#10432 Add `YAML::Nodes::Node#kind`
  spec/std/yaml/serialization_spec.cr
  src/yaml/from_yaml.cr
  src/yaml/nodes/nodes.cr
Labels: kind:feature, kind:refactor, topic:stdlib:serialization

#10415 Fix `#respond_with_status` when headers written or closed
  spec/std/http/server/response_spec.cr
  src/http/server/request_processor.cr
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#10431 Serialize Enum to underscored String by default
  spec/std/json/pull_parser_spec.cr
  spec/std/json/serialization_spec.cr
  spec/std/yaml/serialization_spec.cr
  src/json/from_json.cr
  src/json/pull_parser.cr
  src/json/to_json.cr
  src/yaml/from_yaml.cr
  src/yaml/to_yaml.cr
Labels: breaking-change, kind:feature, topic:stdlib:serialization

#10442 Remove Cookie Name Decoding
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:bug, security, topic:stdlib:networking

#10413 Implement rounding mode for `Number#round`
  spec/std/number_spec.cr
  src/float.cr
  src/int.cr
  src/math/libm.cr
  src/number.cr
Labels: kind:feature, topic:stdlib:numeric
