Repository crystal-lang/crystal, pull requests merged in 2021-09, with the labels that each got.

#11098 fix parsing cookie Domain attribute with leading dot
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:bug, topic:stdlib:networking

#11161 Improve error message when dlsym failed with dlerror
  src/compiler/crystal/repl/context.cr
Labels: kind:feature, topic:interpreter

#11088 Retry HTTP::Client requests once if io is closed
  spec/std/http/client/client_spec.cr
  src/http/client.cr
Labels: kind:feature, topic:stdlib:networking

#11156 `Scheduler#reschedule`: Shortcut lookup for current fiber.
  src/crystal/scheduler.cr
Labels: performance, topic:stdlib:concurrency, kind:refactor

#11138 Fix english language in exception message
  src/compiler/crystal/semantic/exception.cr
Labels: kind:bug, topic:compiler:semantic

#11176 Compiler: make `is_a?(union)` work correctly for virtual types
  spec/compiler/codegen/is_a_spec.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_intersect.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:lang:type-system

#11174 CSV: don't eagerly check next char after newline
  spec/std/csv/csv_lex_spec.cr
  src/csv/lexer.cr
Labels: kind:bug, topic:stdlib:text, topic:stdlib:serialization

#11153 Fix formatting nested multiline array and tuple
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#11167 Don't generate type IDs for formal generic instances
  src/compiler/crystal/codegen/llvm_id.cr
Labels: performance, topic:compiler:generics, topic:compiler:codegen

#11171 Add clarification about when `instance_vars` can be called
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:lang:macros

#11049 Fix `TCPSocket` constructors
  src/socket/tcp_socket.cr
Labels: kind:bug, topic:stdlib:networking

#10978 Fix edge cases with unicode method names
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler:parser

#10957 Don't emit debug info for unused variable declarations
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/codegen/debug.cr
Labels: kind:bug, topic:compiler:debugger, topic:compiler:codegen

#10930 Adjust docs for `Crystal::Macros::HashLiteral#[]`
  src/compiler/crystal/macros.cr
Labels: kind:bug, kind:docs, topic:lang:macros

#10915 Fix `Call.def_full_name` print full block parameter
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler:semantic

#11166 Allow union types to be unbound
  spec/compiler/semantic/union_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:generics

#10901 Fix path lookup when ancestor finds type with same name as current scope
  spec/compiler/semantic/const_spec.cr
  spec/compiler/semantic/new_spec.cr
  src/compiler/crystal/semantic/path_lookup.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:lang:type-system, topic:compiler:semantic

#10813 Fix glob with multiple recurse patterns
  spec/std/dir_spec.cr
  src/dir/glob.cr
Labels: kind:bug, topic:stdlib:files

#10796 Make `typeof` start a nested lexical scope
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/ssa_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:compiler:semantic

#10784 Implement Socket for win32
  .github/workflows/win.yml
  spec/std/socket/socket_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
  spec/win32_std_spec.cr
  src/crystal/system/socket.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/socket.cr
  src/io/overlapped.cr
  src/lib_c/x86_64-windows-msvc/c/basetsd.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/guiddef.cr
  src/lib_c/x86_64-windows-msvc/c/inaddr.cr
  src/lib_c/x86_64-windows-msvc/c/ioapiset.cr
  src/lib_c/x86_64-windows-msvc/c/minwinbase.cr
  src/lib_c/x86_64-windows-msvc/c/mswsock.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
  src/lib_c/x86_64-windows-msvc/c/ws2def.cr
  src/lib_c/x86_64-windows-msvc/c/ws2ipdef.cr
  src/socket/addrinfo.cr
  src/socket/common.cr
  src/winerror.cr
Labels: kind:feature, platform:windows, topic:stdlib:networking

#11168 Add an environment variable for dumping type IDs
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:feature, topic:compiler:codegen

#11059 Add the `Indexable::Mutable(T)` module
  spec/std/indexable/mutable_spec.cr
  spec/std/slice_spec.cr
  src/array.cr
  src/bit_array.cr
  src/deque.cr
  src/indexable.cr
  src/indexable/mutable.cr
  src/slice.cr
  src/static_array.cr
Labels: kind:feature, topic:stdlib:collection

#11154 Reject hash literals with mixed syntax
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:tools:formatter

#11141 Allow underscores in macro `for`'s loop variables
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser, topic:lang:macros

#10447 Refactor `JSON::PullParser#consume_number` to use stdlib number parsing
  spec/std/json/pull_parser_spec.cr
  src/big/json.cr
  src/json/lexer.cr
  src/json/pull_parser.cr
  src/json/token.cr
Labels: kind:bug, topic:stdlib:serialization

#11170 `crystal init`: Improve transformation of project name with hyphens
  spec/compiler/crystal/tools/init_spec.cr
  src/compiler/crystal/tools/init.cr
Labels: kind:bug, topic:tools:init

#10881 Fix `Float#humanize` for values outside `1e-4...1e15`
  spec/std/humanize_spec.cr
  src/float/printer.cr
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#11155 Add github-changelog script
  scripts/github-changelog.cr
Labels: topic:infrastructure

#11137 Add internal registry implementation for win32
  spec/std/mime_spec.cr
  spec/std/time/location_spec.cr
  src/crystal/system/win32/mime.cr
  src/crystal/system/win32/time.cr
  src/crystal/system/win32/windows_registry.cr
  src/lib_c/x86_64-windows-msvc/c/regapix.cr
  src/lib_c/x86_64-windows-msvc/c/timezoneapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/lib_c/x86_64-windows-msvc/c/winreg.cr
Labels: kind:feature, platform:windows, topic:stdlib:time, topic:stdlib:files

#11178 Fix LLVM check < 12.0 to properly include 11.1
  src/llvm/lib_llvm.cr
Labels: kind:bug, topic:compiler

#11197 Compiler: cache cleanup transformer
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: performance, topic:compiler:semantic

#11185 Fix edge case for intersection between virtual metaclasses
  spec/compiler/codegen/cast_spec.cr
  spec/compiler/semantic/cast_spec.cr
  src/compiler/crystal/semantic/type_intersect.cr
Labels: kind:bug, topic:compiler:semantic, kind:regression

#11202 Compiler: don't trigger "already had enclosing call" for same object
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/bindings.cr
Labels: kind:bug, topic:compiler:semantic

#11189 Properly handle indirect arguments for external C functions
  spec/compiler/codegen/c_abi/c_abi_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/fun.cr
Labels: kind:bug, platform:windows, platform:aarch64, topic:compiler:codegen

#11199 Avoid needless union in `LLVM::ABI::AArch64#homogeneous_aggregate?`
  src/llvm/abi/aarch64.cr
Labels: kind:refactor, topic:compiler:codegen

#11188 Don't generate unique type IDs for virtual metaclasses
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/llvm_id.cr
  src/compiler/crystal/codegen/match.cr
Labels: performance, topic:compiler:semantic, topic:compiler:codegen

#10605 Add sleep support to win32 event loop
  spec/std/concurrent_spec.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/windows_stubs.cr
Labels: kind:feature, pr:needs-review, topic:stdlib:concurrency, platform:windows

#11204 Fix link on regex.cr
  src/regex.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#11194 Removing ThinLTO support
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/macros/macros.cr
Labels: kind:feature, topic:compiler:codegen

#11205 Extract `libunwind` from callstack
  src/exception/call_stack.cr
  src/exception/call_stack/libunwind.cr
Labels: kind:refactor, platform:windows, topic:stdlib:runtime

#11186 Fix resolve generic argument in block output type restriction mismatch
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/call.cr
Labels: kind:bug, topic:compiler:semantic

#10559 Deprecate `String#unsafe_byte_at`
  src/io.cr
  src/string.cr
  src/string/utf16.cr
  src/uri/encoding.cr
  src/uri/params.cr
Labels: kind:refactor, breaking-change, topic:stdlib:text

#11212 Remove restriction of bsearch block output type
  spec/std/array_spec.cr
  spec/std/range_spec.cr
  src/indexable.cr
  src/range/bsearch.cr
Labels: kind:feature, topic:stdlib:collection

#10878 Add `make install`
  .gitignore
  Makefile
Labels: kind:feature, topic:infrastructure

#11056 Error if abstract def implementation is inherited from supertype
  spec/compiler/semantic/abstract_def_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
Labels: kind:feature, topic:compiler:semantic

#11220 Remove calls to deprecated `SystemError.from_winerror`
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
Labels: topic:stdlib, kind:refactor

#10996 Add type restrictions and fix return types of `BigFloat#to_x` methods
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:bug, topic:stdlib:numeric

#11228 Update distribution-scripts (universal darwin & demote alpine to 3.12)
  .circleci/config.yml
Labels: topic:infrastructure

#10998 Refine type restriction of `Math.frexp(BigFloat)`
  src/big/big_float.cr
Labels: kind:bug, breaking-change, topic:stdlib:numeric

#11215 Unicode: update to version 14.0.0
  scripts/generate_unicode_data.cr
  src/unicode/data.cr
  src/unicode/unicode.cr
Labels: kind:feature, topic:stdlib:text

#10467 Add and improve type restrictions of block arguments
  spec/std/indexable_spec.cr
  src/array.cr
  src/deque.cr
  src/enum.cr
  src/enumerable.cr
  src/env.cr
  src/hash.cr
  src/indexable.cr
  src/pointer.cr
  src/set.cr
  src/slice.cr
  src/static_array.cr
  src/tuple.cr
Labels: kind:feature, kind:docs, topic:stdlib:collection

#11234 examples: fix (2021-09)
  src/openssl/x509/certificate.cr
  src/path.cr
  src/slice.cr
Labels: kind:docs

#10540 Add `file_exists?` macro method
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#11241 IO: fix bug in `gets` without peek involving `\r` and limit
  spec/std/io/io_spec.cr
  src/io.cr
Labels: kind:bug, topic:stdlib:files

#11116 Support generic module instances in `TypeNode#includers`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:stdlib:macros

#11096 Don't use `:nodoc:` when overriding public methods
  src/array.cr
  src/big/big_int.cr
  src/compress/deflate/reader.cr
  src/compress/deflate/writer.cr
  src/crystal/datum.cr
  src/enum.cr
  src/indexable.cr
  src/io/memory.cr
  src/json/any.cr
  src/log/metadata.cr
  src/range.cr
  src/slice.cr
  src/static_array.cr
  src/yaml/any.cr
Labels: kind:docs

#11124 Don't use `#write_byte` whenever writing ASCII characters to unknown `IO`s
  spec/std/base64_spec.cr
  spec/std/csv/csv_build_spec.cr
  spec/std/http/http_spec.cr
  spec/std/mime/media_type_spec.cr
  spec/std/time/format_spec.cr
  spec/std/uri_spec.cr
  spec/support/string.cr
  src/base64.cr
  src/csv/builder.cr
  src/http/common.cr
  src/mime/media_type.cr
  src/time/format/formatter.cr
  src/uri/encoding.cr
Labels: kind:bug, topic:stdlib:text

#11206 Int128 compiler-rt methods (Int128 literal support part 1)
  spec/compiler/codegen/arithmetics_spec.cr
  spec/std/crystal/compiler_rt/divmod128_spec.cr
  spec/std/crystal/compiler_rt/mulodi4_spec.cr
  spec/std/crystal/compiler_rt/mulosi4_spec.cr
  spec/std/crystal/compiler_rt/muloti4_spec.cr
  spec/std/int_spec.cr
  spec/std/uint_spec.cr
  spec/win32_std_spec.cr
  src/crystal/compiler_rt.cr
  src/crystal/compiler_rt/divmod128.cr
  src/crystal/compiler_rt/mul.cr
  src/crystal/compiler_rt/mulodi4.cr
Labels: kind:feature, topic:stdlib:numeric

#11109 Secure array slicing when expanding macro for stack trace
  src/compiler/crystal/exception.cr
Labels: kind:bug, topic:compiler

#11240 [CI] Remove obsolete `package_build` workflow
  .circleci/config.yml
Labels: topic:infrastructure, kind:refactor

#10874 fix BigDecimal operations with floats
  src/big/big_decimal.cr
Labels: kind:feature, topic:stdlib:numeric

#11245 Add String#to_(u/i)128(?) methods (Int128 literal support part 3)
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:numeric

#10404 Add JSON/YAML serialization to `URI`
  spec/std/uri_spec.cr
  src/uri/json.cr
  src/uri/yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#10013 Move Array#product to Indexable#cartesian_product
  samples/neural_net.cr
  spec/std/indexable_spec.cr
  src/array.cr
  src/indexable.cr
Labels: kind:feature, pr:needs-review, breaking-change, topic:stdlib:collection

#11243 Fix debug locations for `Proc` pointers
  spec/llvm-ir/proc-pointer-debug-loc.cr
  spec/llvm-ir/test.sh
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler:debugger, kind:regression

#11198 Optimize `#rotate!`
  spec/std/array_spec.cr
  spec/std/bit_array_spec.cr
  spec/std/slice_spec.cr
  spec/std/static_array_spec.cr
  src/array.cr
  src/bit_array.cr
  src/indexable/mutable.cr
  src/slice.cr
  src/static_array.cr
Labels: performance, topic:stdlib:collection

#11187 Fix formatting generic types with suffix
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#11101 Fix several compile-time operations on generic instance metaclasses
  spec/compiler/semantic/metaclass_spec.cr
  spec/compiler/semantic/reflection_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:lang:type-system, topic:compiler:generics

#11250 Allow assignments from generic instance metaclasses to virtual metaclasses
  spec/compiler/codegen/class_spec.cr
  src/compiler/crystal/codegen/cast.cr
Labels: kind:bug, topic:compiler:generics, topic:compiler:codegen

#11248 Add `URI.encode_path` and deprecate `URI.encode`
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  spec/std/uri_spec.cr
  src/compiler/crystal/tools/doc/macro.cr
  src/compiler/crystal/tools/doc/method.cr
  src/http/server/handlers/static_file_handler.cr
  src/http/server/handlers/static_file_handler.html
  src/uri.cr
  src/uri/encoding.cr
Labels: kind:feature, topic:stdlib:networking

#11246 Revert some additions of free variables to type restrictions
  src/array.cr
  src/hash.cr
  src/indexable.cr
Labels: kind:bug, topic:stdlib:collection, kind:regression

#11001 Improve performance of Path#dirname and Path#extension
  src/path.cr
Labels: performance, kind:refactor, topic:stdlib:files
