Repository crystal-lang/crystal, pull requests merged in 2022-01, with the labels that each got.

#11643 Fix `IO::Memory#to_s` appending to itself
  spec/std/io/memory_spec.cr
  src/io/memory.cr
Labels: kind:bug, topic:stdlib:files

#11655 Attach debug locations to splat expansions inside array-like literals
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler:codegen

#11651 Use full name for private types' class variables during codegen
  spec/compiler/codegen/private_spec.cr
  src/compiler/crystal/codegen/class_var.cr
Labels: kind:bug, topic:compiler:codegen

#11604 Improve search input a11y for generated docs
  src/compiler/crystal/tools/doc/html/css/style.css
Labels: kind:bug, topic:tools:docs-generator

#11626 Fix string_spec examples calling wrong methods
  spec/std/string_spec.cr
Labels: kind:bug, kind:specs

#11672 Allow underscores after a leading zero in `String#to_i` (regression fix)
  spec/compiler/lexer/lexer_spec.cr
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:compiler:parser, topic:stdlib:numeric, kind:regression

#11636 Fix codegen when instantiating class methods of typedefs
  spec/compiler/codegen/pointer_spec.cr
  src/compiler/crystal/codegen/types.cr
Labels: kind:bug, topic:compiler:codegen

#11677 Fix no comma before short block in `ToSVisitor`
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:parser

#11644 fix: LLVMExtDIBuilderCreateArrayType: argument alignInBits should be UInt64
  src/llvm/lib_llvm_ext.cr
Labels: kind:bug, topic:stdlib:llvm

#11662 Fix double free on `Crystal::Loader#close_all`
  src/compiler/crystal/loader/unix.cr
Labels: kind:bug, topic:stdlib:runtime

#11664 Add docs to `Colorize`
  src/colorize.cr
Labels: kind:docs, topic:stdlib:text

#11637 Update `spec/win32_std_spec.cr`
  spec/win32_std_spec.cr
Labels: topic:stdlib, platform:windows, kind:specs

#11619 Use strings instead of symbols in `#finalize` specs
  spec/std/object_spec.cr
  spec/std/openssl/ssl/context_spec.cr
  spec/std/reference_spec.cr
  spec/std/weak_ref_spec.cr
  spec/std/yaml/serializable_spec.cr
  spec/support/finalize.cr
Labels: topic:stdlib, kind:refactor, kind:specs

#11687 Revert "Restrict identifier grammar"
  scripts/generate_unicode_data.cr
  spec/compiler/crystal/tools/format_spec.cr
  spec/compiler/lexer/lexer_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/unicode/data.cr
  src/unicode/unicode.cr
Labels: kind:bug, topic:compiler:parser, topic:lang

#11622 Support ANSI escape sequence output on more Windows consoles
  .github/workflows/win.yml
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/consoleapi.cr
Labels: kind:feature, platform:windows, topic:stdlib:text

#11661 Improve docs for `Object#not_nil!`
  src/object.cr
Labels: kind:docs, topic:stdlib

#11634 Workaround for GC issues in interpreter specs
  .github/workflows/linux.yml
  spec/compiler/interpreter/bugs_spec.cr
  spec/compiler/interpreter/casts_spec.cr
  spec/compiler/interpreter/exceptions_spec.cr
  spec/compiler/interpreter/integration_spec.cr
  spec/compiler/interpreter/spec_helper.cr
  spec/compiler/interpreter/typeof_spec.cr
  spec/compiler/interpreter/types_spec.cr
Labels: kind:bug, kind:specs, topic:compiler:interpreter

#11659 Fix `Enum.parse` to handle case-sensitive member names
  spec/std/enum_spec.cr
  spec/std/openssl/ssl/context_spec.cr
  src/enum.cr
Labels: kind:bug, topic:stdlib

#11679 Update NOTICE Copyright year to 2022
  NOTICE.md
Labels: kind:docs

#11599 Add Changelog for 1.3.0
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#11729 Remove string allocation from `GC_set_warn_proc`
  src/gc/boehm.cr
Labels: kind:bug, topic:stdlib:runtime, kind:regression

#11686 Doc generator: Fix escape HTML in code span
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  src/compiler/crystal/tools/doc/markd_doc_renderer.cr
Labels: kind:bug, topic:tools:docs-generator

#11709 Fix formatter error for `ProcLiteral`s with `Union` return type
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#11725 Fix typos
  spec/compiler/crystal/tools/init_spec.cr
  spec/compiler/interpreter/exceptions_spec.cr
  spec/std/file_spec.cr
  src/base64.cr
  src/char.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/interpreter.cr
  src/compiler/crystal/semantic/ast.cr
  src/http/client.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
  src/openssl/lib_crypto.cr
  src/slice.cr
  src/string.cr
  src/string/grapheme/grapheme.cr
Labels: kind:bug

#11704 Remove useless variable declarations in trailing position
  spec/compiler/crystal/tools/playground_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/util.cr
  src/crystal/system/file.cr
  src/socket.cr
Labels: kind:bug, topic:stdlib, kind:refactor

#11744 Add changelog for 1.3.1
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#11747 Fix buffer overflow in `String#index`
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:text

#11751 Add changelog for 1.3.2
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#11715 Update previous Crystal release - 1.3.2
  .circleci/config.yml
  .github/workflows/linux.yml
  .github/workflows/openssl.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#11628 Add file and line arguments to `it_iterates`
  spec/std/string/spec_helper.cr
  src/spec/helpers/iterate.cr
Labels: kind:feature, topic:stdlib:specs

#11675 Codegen: Do not always request value for `Proc#call`
  src/compiler/crystal/codegen/primitives.cr
Labels: performance, kind:refactor, topic:compiler:codegen

#11617 Use enums instead of symbols for `MIME::Multipart` and `HTTP::FormData`
  spec/std/mime/multipart/parser_spec.cr
  src/http/formdata/builder.cr
  src/mime/multipart/builder.cr
  src/mime/multipart/parser.cr
  src/mime/multipart/state.cr
Labels: kind:refactor, topic:stdlib:networking

#11716 Add `scripts/release-update.sh`
  scripts/release-update.sh
Labels: topic:infrastructure

#11126 Add `#parse_type`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#11343 [CI] Test against LLVM 13
  .github/workflows/linux.yml
  .github/workflows/win.yml
  src/socket/addrinfo.cr
Labels: kind:feature, topic:infrastructure

#11750 Add allow `Enumerable` arguments for `Hash#select` and `#reject`
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib:collection

#11742 Implement `Intrinsics.pause` for aarch64
  src/intrinsics.cr
Labels: kind:feature, performance, topic:stdlib:runtime, platform:aarch64

#11707 Do not inherit from `Hash` in the compiler
  src/compiler/crystal/tools/context.cr
Labels: kind:refactor, topic:tools

#7616 Replace PNG icon with optimized SVG for playground
  src/compiler/crystal/tools/playground/public/application.css
  src/compiler/crystal/tools/playground/public/icon.png
  src/compiler/crystal/tools/playground/public/icon.svg
  src/compiler/crystal/tools/playground/views/layout.html.ecr
Labels: topic:tools:playground, kind:refactor

#11714 [CI] Use parameters in circleci config
  .circleci/config.yml
Labels: topic:infrastructure, kind:refactor

#11741 Optimize `URI.decode`
  src/uri/encoding.cr
Labels: performance, topic:stdlib:networking

#11724 `Crystal::ToSVisitor`: Remove `decorate_*` methods
  src/compiler/crystal/semantic/to_s.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: topic:compiler, kind:refactor

#11691 Add docs for `Hash#reject!`
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#11579 Use `Crystal::Loader` in the interpreter
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/context.cr
  src/compiler/crystal/interpreter/primitives.cr
  src/compiler/crystal/loader.cr
  src/compiler/crystal/loader/unix.cr
  src/math/libm.cr
Labels: kind:feature, kind:refactor, topic:compiler:interpreter

#11713 Add examples to `Time::Format` methods
  src/time.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/custom/rfc_2822.cr
  src/time/format/custom/rfc_3339.cr
Labels: kind:docs, topic:stdlib:time

#11663 Refactor `Colorize::Mode` enum
  spec/std/colorize_spec.cr
  src/colorize.cr
Labels: kind:refactor, topic:stdlib:text

#11548 [Makefile] Honour `$CC` in `EXPORT_CC`
  Makefile
Labels: kind:bug, topic:infrastructure

#11613 Remove `Iterator.of(Iterator.stop)` from implementations
  spec/std/indexable_spec.cr
  src/indexable.cr
Labels: kind:bug, topic:stdlib:collection

#11625 Use fewer symbols in the compiler source
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/syntax/token.cr
  src/compiler/crystal/tools/doc/markd_doc_renderer.cr
  src/compiler/crystal/tools/doc/type.cr
  src/compiler/crystal/tools/formatter.cr
  src/crystal/syntax_highlighter.cr
Labels: topic:compiler, kind:refactor

#11683 add some docs for UUID
  src/uuid.cr
Labels: kind:docs, topic:stdlib:text

#11693 Adds docs for `UUID#urn`
  src/uuid.cr
Labels: kind:docs, topic:stdlib:text

#11688 Add docs for `Dir#each_child`
  src/dir.cr
Labels: kind:docs, topic:stdlib:files

#11718 Add missing code blocks for `self` in documentation
  src/array.cr
  src/bit_array.cr
  src/log/builder.cr
  src/log/metadata.cr
  src/number.cr
  src/slice.cr
  src/xml/node.cr
Labels: kind:docs, topic:stdlib

#11720 Use `OptionParser` in `crystal env`
  src/compiler/crystal/command/env.cr
Labels: kind:refactor, topic:tools

#11740 Fix documentation for macros `system` and `run`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:lang:macros

#11563 Remove some unnecessary link annotations
  src/crystal/system/unix/lib_event2.cr
  src/gc/boehm.cr
  src/gc/none.cr
  src/math/libm.cr
Labels: topic:stdlib, kind:refactor, platform:linux-musl

#11767 Add support for `--m*` flags to `crystal spec` and `crystal eval`
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler

#11769 Fix parser error with semicolon + newline in parenthezied `Expressions`
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#11576 Add support for `Int128` in codegen and macros
  spec/compiler/codegen/enum_spec.cr
  spec/compiler/codegen/generic_class_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/semantic/generic_class_spec.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/types.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/math_interpreter.cr
  src/compiler/crystal/syntax/ast.cr
Labels: kind:feature, topic:lang:macros, topic:compiler:codegen

#11566 Add raising method variants `Enumerable#find!` and `#index!`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection

#11774 Remove useless assignments
  src/array.cr
  src/compiler/crystal/command/eval.cr
  src/float/printer.cr
  src/float/printer/ieee.cr
  src/mime/media_type.cr
  src/time.cr
  src/uri.cr
Labels: topic:stdlib, kind:refactor

#11754 Fix compiler specs git integration for configurable default branch
  spec/compiler/crystal/tools/doc/project_info_spec.cr
Labels: kind:bug, topic:compiler, kind:specs

#11595 Add support for Bcrypt algorithm version `2b`
  spec/std/crypto/bcrypt/password_spec.cr
  src/crypto/bcrypt/password.cr
Labels: kind:feature, topic:stdlib:crypto

#11450 Optimize block-less overloads of `BitArray#fill`
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: performance, topic:stdlib:collection

#11201 Fix compiler flags with optional arg eating following flags
  spec/std/option_parser_spec.cr
  src/option_parser.cr
Labels: kind:feature, topic:stdlib

#11533 Fix ensure PCRE JIT mode is available before running spec
  spec/std/regex_spec.cr
  src/regex/lib_pcre.cr
Labels: kind:bug, kind:specs, topic:stdlib:text

#11544 Add fallback for `Path.home` on Unix
  spec/std/path_spec.cr
  src/crystal/system/unix/path.cr
  src/crystal/system/unix/user.cr
  src/crystal/system/win32/path.cr
  src/lib_c/aarch64-darwin/c/unistd.cr
  src/lib_c/aarch64-linux-gnu/c/unistd.cr
  src/lib_c/aarch64-linux-musl/c/unistd.cr
  src/lib_c/arm-linux-gnueabihf/c/unistd.cr
  src/lib_c/i386-linux-gnu/c/unistd.cr
  src/lib_c/i386-linux-musl/c/unistd.cr
  src/lib_c/x86_64-darwin/c/unistd.cr
  src/lib_c/x86_64-dragonfly/c/unistd.cr
  src/lib_c/x86_64-freebsd/c/unistd.cr
  src/lib_c/x86_64-linux-gnu/c/unistd.cr
  src/lib_c/x86_64-linux-musl/c/unistd.cr
  src/lib_c/x86_64-netbsd/c/unistd.cr
  src/lib_c/x86_64-openbsd/c/unistd.cr
Labels: kind:feature, topic:stdlib:system, platform:unix

#11524 Add local compiler wrapper script for Windows
  bin/crystal.bat
  bin/crystal.ps1
Labels: kind:feature, topic:compiler, topic:infrastructure, platform:windows

#11676 Fix debug location of inlined `Proc#call` body
  spec/llvm-ir/proc-call-debug-loc.cr
  spec/llvm-ir/test.sh
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/primitives.cr
Labels: kind:bug, topic:compiler:debugger

#11570 Add crash handler on Windows
  spec/std/exception/call_stack_spec.cr
  spec/std/exception_spec.cr
  spec/std/kernel_spec.cr
  src/exception/call_stack/libunwind.cr
  src/exception/call_stack/stackwalk.cr
  src/kernel.cr
  src/lib_c/x86_64-windows-msvc/c/errhandlingapi.cr
  src/lib_c/x86_64-windows-msvc/c/malloc.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, platform:windows, topic:stdlib:runtime
