Repository crystal-lang/crystal, pull requests merged in 2022-10, with the labels that each got.

#12549 Remove `spec/generate_windows_spec.sh`
  spec/generate_windows_spec.sh
Labels: topic:infrastructure, platform:windows, kind:specs

#12545 Fix overflow for `rand(Range(Int, Int))` when signed span is too large
  spec/std/random_spec.cr
  src/random.cr
Labels: kind:bug, topic:stdlib:numeric

#12555 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#12551 Codegen: fix how unions are represented to not miss bytes
  spec/compiler/codegen/c_union_spec.cr
  src/compiler/crystal/codegen/llvm_typer.cr
Labels: kind:bug, topic:compiler:codegen

#12563 Interpreter: implement variable autocast
  spec/compiler/interpreter/autocast_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:compiler:interpreter

#12562 Interpreter: handle missing upcast from GenericClassInstanceMetaclassType to VirtualMetaclassType
  spec/compiler/interpreter/casts_spec.cr
  src/compiler/crystal/interpreter/cast.cr
Labels: kind:bug, topic:compiler:interpreter

#12564 chore: fix alignment typo in compiler comments
  src/compiler/crystal/codegen/llvm_typer.cr
Labels: kind:bug, kind:docs, topic:compiler:codegen

#12530 Document `after_initialize` method for `yaml` and `json` serializers
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:docs, topic:stdlib:serialization

#12588 Bump version to 1.6.1-dev
  src/VERSION
Labels: topic:infrastructure

#12585 Disable failing specs on Windows CI
  spec/std/http/client/client_spec.cr
Labels: topic:infrastructure, platform:windows, kind:specs

#12582 Formatter: escape backslashes in macro literals when subformatting
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter, kind:regression

#12584 Treat single splats with same restriction as equivalent
  spec/compiler/semantic/def_overload_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic, kind:regression

#12581 Interpreter (repl): migrate types even if their size remains the same
  src/compiler/crystal/interpreter/interpreter.cr
Labels: kind:bug, topic:compiler:interpreter

#12580 Fix building Wasm32 on Crystal 1.6 (Regression)
  src/crystal/system/wasi/file_descriptor.cr
Labels: kind:bug, kind:regression, platform:wasm

#12600 Unbreak the interpreter on FreeBSD
  src/lib_c/x86_64-freebsd/c/iconv.cr
Labels: kind:bug, platform:freebsd, topic:compiler:interpreter

#12599 Fix origin validation in playground server for localhost
  src/compiler/crystal/tools/playground/server.cr
Labels: kind:bug, topic:tools:playground, kind:regression

#12601 Fix FFI specs on release builds
  spec/compiler/data/ffi/sum.c
  spec/compiler/ffi/ffi_spec.cr
Labels: kind:bug, kind:specs, topic:compiler:interpreter

#12511 Adding welcome message to the interpreter
  src/compiler/crystal/command/repl.cr
Labels: kind:feature, topic:compiler:interpreter

#12626 Add Changelog for 1.6.1
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#12641 [CI] Drop Alpine libreSSL 3.1 test
  .github/workflows/openssl.yml
Labels: topic:infrastructure

#12640 Bump version to 1.7.0-dev
  .circleci/config.yml
  .github/workflows/linux.yml
  .github/workflows/openssl.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#10548 Add missing docs for `Indexable` combinations methods
  src/indexable.cr
Labels: kind:docs, topic:stdlib:collection

#12569 [WASM] Add missing `__powisf2` and `__powidf2` compiler-rt functions
  spec/std/crystal/compiler_rt/powidf2_spec.cr
  spec/std/crystal/compiler_rt/powisf2_spec.cr
  src/crystal/compiler_rt.cr
  src/crystal/compiler_rt/pow.cr
Labels: kind:feature, topic:stdlib:numeric, platform:wasm

#12622 Parser: Fix restrict grammar for name and supertype in type def
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, breaking-change

#12354 Fix `TypeNode#nilable?` for root types
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:stdlib:macros

#12590 Refactor: use helper method instead of duplicate code in lexer
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:refactor, topic:compiler:parser

#11535 Implement `Digest` class in `Digest::CRC32` and `Digest::Adler32`
  spec/std/digest/adler32_spec.cr
  spec/std/digest/crc32_spec.cr
  src/digest/adler32.cr
  src/digest/crc32.cr
Labels: kind:feature, topic:stdlib:crypto, breaking-change

#12526 Add `HTTP::Server::Response#redirect`
  spec/std/http/server/response_spec.cr
  src/http/server/handlers/static_file_handler.cr
  src/http/server/response.cr
Labels: kind:feature, topic:stdlib:networking

#12552 Rename `File.real_path` to `.realpath`
  src/crystal/system/unix/file.cr
  src/crystal/system/wasi/file.cr
  src/crystal/system/win32/file.cr
  src/exception/call_stack/mach_o.cr
  src/file.cr
  src/process/executable_path.cr
Labels: kind:feature, topic:stdlib:system

#12572 Trap when trying to raise wasm32 exceptions
  src/raise.cr
Labels: kind:feature, topic:stdlib:system, platform:wasm

#12635 Interpreter: fix class var initializer that needs an upcast
  spec/compiler/interpreter/class_vars_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
Labels: kind:bug, topic:compiler:interpreter

#12613 Websocket: write masked data to temporary buffer before sending it
  spec/std/http/web_socket_spec.cr
  src/http/web_socket/protocol.cr
Labels: performance, topic:stdlib:networking

#12644 Use mutating collection methods
  src/channel.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/exhaustiveness_checker.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/http/headers.cr
Labels: performance, kind:refactor

#9326 Add argless `#annotations` overload
  spec/compiler/semantic/annotation_spec.cr
  src/compiler/crystal/annotatable.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/types.cr
Labels: kind:feature, topic:stdlib:macros, topic:lang:annotations

#12535 Optimize `Range#sample(n)` for integers and floats
  spec/std/range_spec.cr
  src/range.cr
Labels: performance, topic:stdlib:collection

#12638 Style: Remove redundant begin blocks
  spec/std/spec/tap_formatter_spec.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/tools/playground/server.cr
  src/file_utils.cr
  src/http/server/handlers/error_handler.cr
  src/json/token.cr
Labels: kind:refactor

#12665 examples: fix (2022-10)
  src/digest/digest.cr
  src/kernel.cr
Labels: kind:bug, kind:docs, topic:stdlib

#12651 Update FreeBSD LibC types
  src/lib_c/x86_64-freebsd/c/dirent.cr
  src/lib_c/x86_64-freebsd/c/sys/types.cr
  src/lib_c/x86_64-freebsd/c/sys/un.cr
Labels: kind:bug, platform:freebsd

#12669 Remove unused `Program#cache_dir` property
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
Labels: topic:compiler, kind:refactor

#12674 Lint: Fix variable name casing
  samples/havlak.cr
  samples/sdl/raytracer.cr
  scripts/github-changelog.cr
  src/compiler/crystal/tools/playground/server.cr
  src/crystal/digest/md5.cr
Labels: kind:refactor

#12673 Lint: Remove comparisons with boolean literals
  src/compiler/crystal/semantic/call_error.cr
  src/fiber.cr
  src/iterator.cr
Labels: kind:refactor

#12501 [CI] Update GHA actions
  .github/workflows/aarch64.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/openssl.yml
  .github/workflows/smoke.yml
  .github/workflows/win.yml
Labels: topic:infrastructure

#12677 Fix documentation for Pointer#move_to
  src/pointer.cr
Labels: kind:bug, kind:docs

#12656 Allow the EventLoop implementation to be detected at runtime
  src/crystal/scheduler.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/unix/event_libevent.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/crystal/system/wasi/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/socket.cr
  src/fiber.cr
  src/io/evented.cr
  src/io/overlapped.cr
  src/kernel.cr
Labels: topic:stdlib:concurrency, kind:refactor

#12639 Macros: Test addition between `ArrayLiteral` and `TupleLiteral`
  spec/compiler/macro/macro_methods_spec.cr
Labels: topic:stdlib:macros, kind:specs

#12632 Fix `VirtualMetaclassType#implements?` to ignore base_type
  spec/compiler/codegen/cast_spec.cr
  spec/compiler/codegen/is_a_spec.cr
  spec/compiler/semantic/metaclass_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:lang:type-system, topic:compiler:semantic, kind:regression

#12679 Compiler: handle yield exps without a type
  spec/compiler/codegen/block_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler

#12646 Add `ArrayLiteral#-(other)` and `TupleLiteral#-(other)`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#12675 Lint: Use `Object#in?` instead of multiple comparisons
  samples/sdl/raytracer.cr
  samples/sdl/tv.cr
  spec/compiler/codegen/union_type_spec.cr
  spec/std/string_spec.cr
  src/base64.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/tools/playground/server.cr
  src/crystal/mach_o.cr
  src/crystal/system/unix/getrandom.cr
  src/csv/lexer.cr
  src/dir/glob.cr
  src/enumerable.cr
  src/http/request.cr
  src/json/lexer.cr
  src/llvm/abi/x86_64.cr
  src/mime/multipart/parser.cr
  src/process.cr
  src/socket/addrinfo.cr
  src/spec/cli.cr
  src/string.cr
  src/time/format/custom/iso_8601.cr
  src/time/format/formatter.cr
  src/uri.cr
  src/xml/builder.cr
Labels: kind:refactor

#12680 Fix range literals causing method lookups in docs generator
  spec/compiler/crystal/tools/doc/doc_renderer_spec.cr
  src/compiler/crystal/tools/doc/markd_doc_renderer.cr
Labels: kind:bug, topic:tools:docs-generator

#12468 Add docs for `Int#downto`
  src/int.cr
Labels: kind:docs, topic:stdlib:numeric

#12648 Lint: Remove useless assignments
  samples/binary-trees.cr
  samples/mt_gc_test.cr
  samples/red_black_tree.cr
  samples/wordcount.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/warnings_spec.cr
  spec/compiler/semantic/class_spec.cr
  spec/compiler/semantic/instance_var_spec.cr
  spec/compiler/semantic/virtual_spec.cr
  spec/compiler/semantic/warnings_spec.cr
  spec/spec_helper.cr
  spec/std/deque_spec.cr
  spec/std/hash_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/http/headers_spec.cr
  spec/std/log/context_spec.cr
  spec/std/log/dispatch_spec.cr
  spec/std/oauth2/session_spec.cr
  spec/std/proc_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/string_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/cursor.cr
  src/compiler/crystal/command/repl.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/exception.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/exception.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/semantic/type_to_restriction.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/formatter.cr
  src/exception/call_stack/stackwalk.cr
  src/float/printer/grisu3.cr
  src/float/printer/ieee.cr
  src/iterator.cr
  src/llvm/abi/x86.cr
  src/llvm/abi/x86_64.cr
  src/path.cr
Labels: kind:refactor

#12668 Compiler: ignore type filters when accepting cast obj and to
  spec/compiler/semantic/nilable_cast_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#12692 Leverage `GC.malloc_atomic` for XML
  src/xml/libxml2.cr
Labels: performance, topic:stdlib:serialization
