Repository crystal-lang/crystal, pull requests merged in 2022-12, with the labels that each got.

#12785 Redefine defs when constant and number in generic arguments are equal
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:generics

#12688 Use qualified type reference `YAML::Any`
  src/json/any.cr
  src/yaml/any.cr
Labels: kind:docs, kind:refactor, topic:stdlib:serialization

#12810 Raise `IndexError` on unmatched subpattern for `MatchData#begin` and `#end`
  spec/std/regex/match_data_spec.cr
  src/regex/match_data.cr
Labels: kind:bug, topic:stdlib:text

#12808 Swap documentation for `String#split` array and block versions.
  src/string.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#12773 Fix `BigInt#%` for unsigned integers
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
Labels: kind:bug, topic:stdlib:numeric

#12784 Fix restriction of numeral generic argument against non-free variable `Path`
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:generics

#12779 Fix explicit type conversion to u64 for `GC::Stats`
  spec/std/gc_spec.cr
  src/gc/boehm.cr
Labels: kind:bug, topic:stdlib:runtime, platform

#12814 Optimize uniqueness filter in `Channel.select_impl`
  src/channel.cr
Labels: performance, topic:stdlib:concurrency, kind:refactor

#10531 Add references between String equality, comparison methods
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#11647 Implement multithreading primitives on Windows
  spec/std/thread/mutex_spec.cr
  src/crystal/system/thread.cr
  src/crystal/system/thread_condition_variable.cr
  src/crystal/system/thread_mutex.cr
  src/crystal/system/unix/pthread_condition_variable.cr
  src/crystal/system/wasi/thread.cr
  src/crystal/system/wasi/thread_condition_variable.cr
  src/crystal/system/win32/process.cr
  src/crystal/system/win32/thread.cr
  src/crystal/system/win32/thread_condition_variable.cr
  src/crystal/system/win32/thread_mutex.cr
  src/gc/boehm.cr
  src/gc/none.cr
  src/lib_c/x86_64-windows-msvc/c/process.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/synchapi.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
Labels: kind:feature, platform:windows, topic:multithreading

#12833 Rename `Def#yields` to `Def#block_arity`
  spec/compiler/crystal/tools/doc/method_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/interpreter/multidispatch.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/default_arguments.cr
  src/compiler/crystal/semantic/method_missing.cr
  src/compiler/crystal/semantic/new.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/tools/context.cr
  src/compiler/crystal/tools/doc/method.cr
  src/compiler/crystal/tools/doc/to_json.cr
  src/compiler/crystal/types.cr
Labels: kind:refactor, topic:compiler:parser

#12802 Extract internal Regex API for PCRE backend
  src/regex.cr
  src/regex/engine.cr
  src/regex/lib_pcre.cr
  src/regex/match_data.cr
  src/regex/pcre.cr
Labels: kind:refactor, topic:stdlib:text

#12835 Automatically cast Int to Float for `{JSON,YAML}::Any#as_f`
  spec/std/json/any_spec.cr
  spec/std/json/serializable_spec.cr
  spec/std/yaml/any_spec.cr
  src/json/any.cr
  src/yaml/any.cr
Labels: kind:feature, topic:stdlib:serialization

#9974 Improve documentation for `Object#to_s` and `#inspect`
  src/array.cr
  src/object.cr
Labels: kind:docs, topic:stdlib

#12797 Add custom `message` parameter to `#not_nil!`
  spec/std/object_spec.cr
  src/nil.cr
  src/object.cr
Labels: kind:feature, topic:stdlib:runtime

#12754 Resolve type of free variable on block return type mismatch
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/call.cr
Labels: kind:bug, topic:compiler:semantic

#12687 Remove oct/bin floating point literals
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser, kind:regression

#11219 Add more specific error message for uninstantiated proc type
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/call.cr
Labels: kind:feature, topic:compiler:semantic

#12759 Add `Indexable#rindex!` method variant
  spec/std/indexable_spec.cr
  src/indexable.cr
Labels: kind:feature, topic:stdlib:collection

#12843 Enable multithreading specs on Windows CI
  spec/std/thread/condition_variable_spec.cr
  spec/std/thread/mutex_spec.cr
  spec/std/thread_spec.cr
Labels: topic:infrastructure, platform:windows, kind:specs, topic:multithreading

#12840 Implement `Regex` engine on PCRE2
  spec/std/regex_spec.cr
  src/regex/engine.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre2.cr
Labels: kind:feature, topic:stdlib:text

#12850 Revert "Implement `Regex` engine on PCRE2"
  spec/std/regex_spec.cr
  src/regex/engine.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text, kind:regression

#12849 Reverting #12405 Compiler: don't always use Array for node dependencies and observers
  spec/compiler/crystal/zero_one_or_many_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/multidispatch.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/cover.cr
  src/compiler/crystal/semantic/filters.cr
  src/compiler/crystal/semantic/fix_missing_types.cr
  src/compiler/crystal/semantic/lib.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/match.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/compiler/crystal/semantic/type_merge.cr
  src/compiler/crystal/semantic/warnings.cr
  src/compiler/crystal/tools/context.cr
  src/compiler/crystal/tools/implementations.cr
  src/compiler/crystal/zero_one_or_many.cr
Labels: kind:bug, topic:compiler:interpreter

#12822 Fix: Read `UInt` in zip directory header
  spec/std/compress/zip/zip_file_spec.cr
  src/compress/zip/file.cr
Labels: kind:bug, topic:stdlib:files

#12848 Add lib functions earlier so that they are visible in top-level macros
  spec/compiler/semantic/lib_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/type_declaration_visitor.cr
Labels: kind:feature, topic:lang:macros

#12778 Fix `HTTP::Client` certificate validation error on FQDN (host with trailing dot)
  spec/manual/https_client_spec.cr
  spec/std/uri_spec.cr
  src/http/client.cr
Labels: kind:bug, topic:stdlib:crypto

#11798 Parser: fix wrong/missing locations of various AST nodes
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#12852 Match Nix loader errors in compiler spec
  spec/compiler/loader/unix_spec.cr
Labels: kind:bug, topic:compiler:interpreter

#12855 Order `_` after any other `Path` when comparing overloads
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#12834 Add methods to manipulate semantic versions
  spec/std/semantic_version_spec.cr
  src/semantic_version.cr
Labels: kind:feature, topic:stdlib

#12837 Add types to methods with defaults
  src/array.cr
  src/char.cr
  src/enumerable.cr
  src/indexable.cr
  src/indexable/mutable.cr
  src/range.cr
  src/slice.cr
  src/string.cr
  src/uuid.cr
Labels: kind:docs, topic:stdlib

#12861 Use `sleep` in flock wait loop
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
Labels: kind:bug, topic:stdlib:system

#12856 Implement `Regex` engine on PCRE2
  .github/workflows/regex-engine.yml
  spec/std/regex/match_data_spec.cr
  spec/std/regex_spec.cr
  src/regex/engine.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre2.cr
Labels: kind:feature, topic:stdlib:text

#12865 Add `#bit_reverse` and `#byte_swap` for primitive integers
  spec/std/int_spec.cr
  src/base64.cr
  src/bit_array.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
  src/int.cr
  src/intrinsics.cr
  src/socket/address.cr
Labels: kind:feature, topic:stdlib:numeric

#12765 Add `HTTP::Headers#serialize`
  spec/std/http/headers_spec.cr
  src/http/common.cr
  src/http/headers.cr
Labels: kind:feature, breaking-change, topic:stdlib:networking

#10648 Validate cookie name prefixes
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#12809 Add missing overloads for `String#byte_slice`
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#12740 Warn on missing space before colon in type declaration/restriction
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/warnings_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser

#12738 Interpreter reply
  lib/reply/.gitignore
  lib/reply/CHANGELOG.md
  lib/reply/LICENSE
  lib/reply/README.md
  lib/reply/examples/crystal_repl.cr
  lib/reply/examples/repl.cr
  lib/reply/shard.yml
  lib/reply/spec/auto_completion_spec.cr
  lib/reply/spec/char_reader_spec.cr
  lib/reply/spec/expression_editor_spec.cr
  lib/reply/spec/history_spec.cr
  lib/reply/spec/reader_spec.cr
  lib/reply/spec/spec_helper.cr
  lib/reply/src/auto_completion.cr
  lib/reply/src/char_reader.cr
  lib/reply/src/expression_editor.cr
  lib/reply/src/history.cr
  lib/reply/src/reader.cr
  lib/reply/src/reply.cr
  lib/reply/src/term_cursor.cr
  lib/reply/src/term_size.cr
  src/compiler/crystal/interpreter/interpreter.cr
  src/compiler/crystal/interpreter/prompt.cr
  src/compiler/crystal/interpreter/pry_reader.cr
  src/compiler/crystal/interpreter/repl.cr
  src/compiler/crystal/interpreter/repl_reader.cr
Labels: kind:feature, pr:wip, topic:compiler:interpreter

#12869 Fix warning on space before colon with anonymous block arg
  spec/compiler/parser/warnings_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, kind:regression

#12870 examples: fix (2022-12)
  src/complex.cr
  src/hash.cr
  src/http/headers.cr
  src/http/status.cr
  src/json/serialization.cr
  src/json/to_json.cr
  src/log.cr
  src/named_tuple.cr
  src/semantic_version.cr
  src/string.cr
  src/string/utf16.cr
  src/time.cr
  src/time/span.cr
  src/uuid/yaml.cr
  src/yaml/serialization.cr
Labels: kind:bug, kind:docs, topic:stdlib
