Repository crystal-lang/crystal, pull requests merged in 2022-05, with the labels that each got.

#12034 Handle OpenSSL 3.0 KTLS ctrl calls
  src/openssl/bio.cr
  src/openssl/lib_crypto.cr
Labels: kind:bug, topic:stdlib:crypto

#12037 Add missing `SC_PAGESIZE` constant for `aarch64-darwin`
  src/lib_c/aarch64-darwin/c/unistd.cr
Labels: topic:stdlib:system, platform:darwin, platform:aarch64

#12024 Update file.cr
  src/file.cr
Labels: kind:docs, topic:stdlib:files

#11886 Add `File#chown` and `#chmod`
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
  src/file.cr
  src/lib_c/aarch64-darwin/c/sys/stat.cr
  src/lib_c/aarch64-darwin/c/sys/time.cr
  src/lib_c/aarch64-darwin/c/unistd.cr
  src/lib_c/aarch64-linux-gnu/c/sys/stat.cr
  src/lib_c/aarch64-linux-gnu/c/sys/time.cr
  src/lib_c/aarch64-linux-gnu/c/unistd.cr
  src/lib_c/aarch64-linux-musl/c/sys/stat.cr
  src/lib_c/aarch64-linux-musl/c/sys/time.cr
  src/lib_c/aarch64-linux-musl/c/unistd.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/stat.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/time.cr
  src/lib_c/arm-linux-gnueabihf/c/unistd.cr
  src/lib_c/i386-linux-gnu/c/sys/stat.cr
  src/lib_c/i386-linux-gnu/c/sys/time.cr
  src/lib_c/i386-linux-gnu/c/unistd.cr
  src/lib_c/i386-linux-musl/c/sys/stat.cr
  src/lib_c/i386-linux-musl/c/sys/time.cr
  src/lib_c/i386-linux-musl/c/unistd.cr
  src/lib_c/wasm32-wasi/c/sys/stat.cr
  src/lib_c/wasm32-wasi/c/time.cr
  src/lib_c/wasm32-wasi/c/unistd.cr
  src/lib_c/x86_64-darwin/c/sys/stat.cr
  src/lib_c/x86_64-darwin/c/sys/time.cr
  src/lib_c/x86_64-darwin/c/unistd.cr
  src/lib_c/x86_64-dragonfly/c/sys/stat.cr
  src/lib_c/x86_64-dragonfly/c/sys/time.cr
  src/lib_c/x86_64-dragonfly/c/unistd.cr
  src/lib_c/x86_64-freebsd/c/sys/stat.cr
  src/lib_c/x86_64-freebsd/c/sys/time.cr
  src/lib_c/x86_64-freebsd/c/unistd.cr
  src/lib_c/x86_64-linux-gnu/c/sys/stat.cr
  src/lib_c/x86_64-linux-gnu/c/sys/time.cr
  src/lib_c/x86_64-linux-gnu/c/unistd.cr
  src/lib_c/x86_64-linux-musl/c/sys/stat.cr
  src/lib_c/x86_64-linux-musl/c/sys/time.cr
  src/lib_c/x86_64-linux-musl/c/unistd.cr
  src/lib_c/x86_64-netbsd/c/sys/stat.cr
  src/lib_c/x86_64-netbsd/c/sys/time.cr
  src/lib_c/x86_64-netbsd/c/unistd.cr
  src/lib_c/x86_64-openbsd/c/sys/stat.cr
  src/lib_c/x86_64-openbsd/c/sys/time.cr
  src/lib_c/x86_64-openbsd/c/unistd.cr
Labels: kind:feature, topic:stdlib:files

#10416 Add property `HTTP::Server::Response#status_message`
  spec/std/http/server/response_spec.cr
  src/http/server/response.cr
Labels: kind:feature, topic:stdlib:networking

#11583 Use enum instead of symbol for `Atomic` primitives
  spec/compiler/codegen/primitives_spec.cr
  src/atomic.cr
  src/compiler/crystal/codegen/primitives.cr
  src/llvm/enums.cr
  src/llvm/enums/atomic.cr
Labels: topic:stdlib:concurrency, kind:refactor

#11988 Rename "take" to "first"
  src/iterator.cr
Labels: kind:docs, topic:stdlib:collection

#12053 Fix: Unset executable bit from js/css files in playground
  src/compiler/crystal/tools/playground/public/vendor/ansi_up-1.3.0/ansi_up.js
  src/compiler/crystal/tools/playground/public/vendor/ansi_up-1.3.0/theme.css
Labels: kind:bug, topic:tools:playground

#12049 Add spec for `Array#-` with different generic type arguments
  spec/std/array_spec.cr
Labels: kind:specs, topic:stdlib:collection

#12051 Fix `Complex.multiplicative_identity`
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:bug, kind:specs, topic:stdlib:numeric

#12038 Interpreter: Don't link `librt` and `libdl` on GNU systems
  src/crystal/system/unix/lib_event2.cr
  src/lib_c/aarch64-linux-gnu/c/dlfcn.cr
  src/lib_c/arm-linux-gnueabihf/c/dlfcn.cr
  src/lib_c/i386-linux-gnu/c/dlfcn.cr
  src/lib_c/x86_64-linux-gnu/c/dlfcn.cr
Labels: kind:bug, platform:linux-gnu, topic:compiler:interpreter

#11971 Disallow empty parameter and argument names
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, breaking-change

#12064 Windows CI: invalidate cached libraries on new MSVC release
  .github/workflows/win.yml
Labels: kind:bug, topic:infrastructure, platform:windows

#12040 Fix spelling
  CHANGELOG.md
  CONTRIBUTING.md
  samples/egrep.cr
  spec/compiler/codegen/class_var_spec.cr
  spec/compiler/semantic/generic_class_spec.cr
  spec/compiler/semantic/if_spec.cr
  spec/compiler/semantic/while_spec.cr
  spec/std/base64_spec.cr
  spec/std/file_utils_spec.cr
  spec/std/html_spec.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/context.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/interpreter.cr
  src/compiler/crystal/interpreter/multidispatch.cr
  src/compiler/crystal/interpreter/value.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/tools/context.cr
  src/compiler/crystal/tools/doc/html/js/_navigator.js
  src/compiler/crystal/tools/doc/project_info.cr
  src/compiler/crystal/tools/playground/public/session.js
  src/crystal/dwarf/abbrev.cr
  src/crystal/dwarf/line_numbers.cr
  src/crystal/scheduler.cr
  src/fiber.cr
  src/float/printer.cr
  src/http/client.cr
  src/http/cookie.cr
  src/io/overlapped.cr
  src/openssl/ssl/socket.cr
  src/socket/addrinfo.cr
  src/string.cr
  src/string/grapheme/grapheme.cr
  src/uri.cr
  src/xml/builder.cr
  src/yaml/to_yaml.cr
Labels: kind:bug, kind:docs

#12033 Fix `Path#join` to convert argument path to base kind
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, topic:stdlib:files

#11947 Add docs for `Enum#value`
  src/enum.cr
Labels: kind:feature, kind:docs, topic:stdlib

#11984 Add support for `NO_COLOR` to `Colorize`
  src/colorize.cr
Labels: kind:feature, topic:compiler, topic:stdlib:text

#12067 Remove redundant check for EOF on Crystal::Parser
  src/compiler/crystal/syntax/parser.cr
Labels: kind:refactor, topic:compiler:parser
