Repository crystal-lang/crystal, pull requests merged in 2022-08, with the labels that each got.

#12345 Interpreter: handle missing closured struct self
  spec/compiler/interpreter/closures_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
Labels: kind:bug, topic:compiler:interpreter

#12348 Interpreter: use non_nilable_type in NilableCast
  spec/compiler/interpreter/casts_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
Labels: kind:bug, topic:compiler:interpreter

#12349 Interpreter: implement mixed union cast with compatible tuple types
  spec/compiler/interpreter/casts_spec.cr
  src/compiler/crystal/interpreter/cast.cr
  src/compiler/crystal/interpreter/instructions.cr
Labels: kind:bug, topic:compiler:interpreter

#12294 Implement `IO::FileDescriptor`'s console methods on Windows
  samples/2048.cr
  spec/std/io/io_spec.cr
  src/crystal/system/win32/file_descriptor.cr
  src/io/console.cr
  src/lib_c/x86_64-windows-msvc/c/consoleapi.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#12339 Fix 'String' shift state specs on FreeBSD
  spec/std/string_spec.cr
Labels: kind:bug, topic:stdlib:text, platform:freebsd

#12359 Update distribution-scripts
  .circleci/config.yml
Labels: kind:bug, topic:infrastructure

#12344 Use `Makefile.win` and wrapper script on Windows CI
  .github/workflows/win.yml
  spec/std/spec_helper.cr
Labels: topic:infrastructure, platform:windows, kind:specs

#11790 Improve recursive splat expansion detection
  spec/compiler/semantic/tuple_spec.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:compiler

#12374 Interpreter: fix 12351
  spec/compiler/interpreter/classes_spec.cr
  spec/compiler/interpreter/multidispatch_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/multidispatch.cr
Labels: kind:bug, topic:compiler:interpreter

#12355 Use interpreter to run std spec tests
  .github/workflows/linux.yml
  spec/generate_interpreter_spec.sh
  spec/interpreter_std_spec.cr
Labels: topic:stdlib, topic:infrastructure, kind:specs, topic:compiler:interpreter

#12377 Fix null dereference when passing empty slice to Base64.encode
  spec/std/base64_spec.cr
  src/base64.cr
Labels: kind:bug, topic:stdlib:text

#12381 Interpreter: missing `i += 1`
  spec/compiler/interpreter/procs_spec.cr
  src/compiler/crystal/interpreter/cast.cr
  src/compiler/crystal/interpreter/multidispatch.cr
Labels: kind:regression, topic:compiler:interpreter

#10954 Fix `self` in restrictions when instantiating macro def in subtypes
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/match.cr
  src/compiler/crystal/semantic/method_lookup.cr
  src/compiler/crystal/semantic/restrictions.cr
Labels: kind:bug, topic:compiler:semantic

#12368 Compiler: fix `#to_s` for empty parameters of lib funs
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#11954 Fix typo: `LibC::DT_LINK` -> `DT_LNK`
  src/crystal/system/unix/dir.cr
  src/lib_c/aarch64-darwin/c/dirent.cr
  src/lib_c/aarch64-linux-gnu/c/dirent.cr
  src/lib_c/aarch64-linux-musl/c/dirent.cr
  src/lib_c/arm-linux-gnueabihf/c/dirent.cr
  src/lib_c/i386-linux-gnu/c/dirent.cr
  src/lib_c/i386-linux-musl/c/dirent.cr
  src/lib_c/x86_64-darwin/c/dirent.cr
  src/lib_c/x86_64-dragonfly/c/dirent.cr
  src/lib_c/x86_64-freebsd/c/dirent.cr
  src/lib_c/x86_64-linux-gnu/c/dirent.cr
  src/lib_c/x86_64-linux-musl/c/dirent.cr
  src/lib_c/x86_64-netbsd/c/dirent.cr
  src/lib_c/x86_64-openbsd/c/dirent.cr
Labels: kind:refactor, topic:stdlib:files

#12388 Compiler: transform Proc(*T, Void) to Proc(*T, Nil)
  spec/compiler/semantic/instance_var_spec.cr
  spec/compiler/semantic/proc_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler

#12387 Interpreter: discard tuple and named tuple
  spec/compiler/interpreter/named_tuple_spec.cr
  spec/compiler/interpreter/tuple_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
Labels: kind:bug, topic:compiler:interpreter

#12362 Compiler: indent `begin` `Expression`s that are direct node children
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler

#12353 Fix `Class#nilable?` for recursive unions and root types
  spec/std/class_spec.cr
  src/class.cr
  src/union.cr
Labels: kind:bug, topic:stdlib

#10973 Add full integer support to `sprintf` and `String#%`
  spec/std/sprintf_spec.cr
  spec/std/string_spec.cr
  spec/win32_std_spec.cr
  src/kernel.cr
  src/string/formatter.cr
Labels: kind:bug, kind:feature, topic:stdlib:numeric, topic:stdlib:text

#12384 Document `IO::FileDescriptor#info`
  src/file.cr
  src/io/file_descriptor.cr
Labels: kind:docs, topic:stdlib:files

#12278 Add platform-specific variants of `Process.parse_arguments`
  spec/std/process_spec.cr
  src/process/shell.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#12352 Define `#system_echo` and `#system_raw` on all systems
  spec/std/io/io_spec.cr
  src/crystal/system/file_descriptor.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/io/console.cr
Labels: kind:refactor, breaking-change, topic:stdlib:files

#12087 Optimize block-less overloads of `BitArray#index` and `#rindex`
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: performance, topic:stdlib:collection

#10803 Optimize `BigDecimal#div` for inexact divisions
  spec/std/big/big_int_spec.cr
  src/big/big_decimal.cr
  src/big/big_int.cr
  src/big/lib_gmp.cr
Labels: performance, topic:stdlib:numeric

#12209 Basic GDB formatter support
  etc/gdb/crystal_formatters.py
  spec/debug/arrays.cr
  spec/debug/blocks.cr
  spec/debug/driver.cr
  spec/debug/strings.cr
  spec/debug/test.sh
  spec/debug/top_level.cr
Labels: kind:feature, topic:compiler:debugger

#12212 Add Visual Studio formatters for `String`, `Array`, and `Hash`
  etc/msvc/crystal.natvis
Labels: kind:feature, topic:compiler:debugger, platform:windows

#12385 Do not expose `Crystal::System::FileInfo` through `File::Info`
  src/crystal/system/file_info.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/file_info.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/file_info.cr
  src/file/info.cr
Labels: kind:refactor, breaking-change, topic:stdlib:files

#12356 Playground: Fix pass bound hostname to run sessions
  src/compiler/crystal/tools/playground/server.cr
Labels: kind:bug, topic:tools:playground

#12389 Optimize String#downcase and String#upcase for single byte optimizabl…
  src/string.cr
Labels: performance, topic:stdlib:text

#11834 Support tuple metaclass indexers with non-literal arguments
  spec/std/named_tuple_spec.cr
  spec/std/tuple_spec.cr
  src/named_tuple.cr
  src/tuple.cr
Labels: kind:feature, topic:stdlib:collection

#12145 Optimize `String#valid_encoding?`
  spec/std/string_spec.cr
  src/string.cr
  src/unicode/unicode.cr
Labels: performance, topic:stdlib:text

#12399 Make `Float#to_s` ignore NaN sign bit
  spec/std/float_printer_spec.cr
  src/float/printer.cr
Labels: kind:bug, topic:stdlib:numeric, topic:stdlib:text

#12375 Interpreter: cast proc call arguments to proc arg types
  spec/compiler/interpreter/procs_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:compiler:interpreter

#12400 Make `sprintf` and `String#%` ignore NaN sign bit
  spec/std/sprintf_spec.cr
  src/string/formatter.cr
Labels: kind:bug, topic:stdlib:numeric, topic:stdlib:text

#11420 [Makefile] Add format target
  Makefile
  Makefile.win
  bin/ci
Labels: kind:feature, topic:infrastructure

#12403 Compiler: add missing location to node on literal expander for array
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler

#12423 Compiler: bind to tuple, not array
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: topic:compiler, performance

#11226 Implement `String#unicode_normalize` and `String#unicode_normalized?`
  scripts/generate_unicode_data.cr
  scripts/unicode_data.ecr
  spec/manual/string_normalize_spec.cr
  src/string.cr
  src/unicode/data.cr
  src/unicode/unicode.cr
Labels: kind:feature, topic:stdlib:text

#12244 Fix `Complex#to_s` imaginary component sign for certain values
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:bug, topic:stdlib:numeric, topic:stdlib:text

#12242 More accurate definition of `Complex#sign`
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:bug, topic:stdlib:numeric

#12293 Decouple warning detection from program instances
  spec/compiler/semantic/warnings_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/warnings.cr
  src/compiler/crystal/warnings.cr
Labels: topic:compiler, kind:refactor

#12428 Compiler: only have freeze_type in select AST nodes
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
Labels: topic:compiler, performance

#12414 Correctly display codegen when cross-compiling
  src/compiler/crystal/compiler.cr
Labels: kind:feature, topic:compiler

#12391 Use `GC.malloc_atomic` with `GC.realloc`, not `Pointer#realloc`
  spec/std/io/io_spec.cr
  src/gc.cr
  src/io/memory.cr
  src/pointer.cr
  src/string.cr
  src/string/builder.cr
Labels: kind:bug, topic:stdlib, topic:compiler:interpreter

#12424 Fix `Float#abs` and `Number#format` for `-0.0`
  spec/std/float_spec.cr
  spec/std/humanize_spec.cr
  src/float.cr
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#10913 Implement the Dragonbox algorithm for `Float#to_s`
  spec/std/crystal/compiler_rt/spec_helper.cr
  spec/std/float_printer_spec.cr
  spec/std/float_spec.cr
  spec/support/number.cr
  src/float.cr
  src/float/printer.cr
  src/float/printer/cached_powers.cr
  src/float/printer/diy_fp.cr
  src/float/printer/dragonbox.cr
  src/float/printer/dragonbox_cache.cr
  src/float/printer/grisu3.cr
Labels: kind:feature, topic:stdlib:numeric
