Repository crystal-lang/crystal, pull requests merged in 2022-03, with the labels that each got.

#11836 Improve error for incompatible generic arguments for `WeakRef`
  spec/std/weak_ref_spec.cr
  src/weak_ref.cr
Labels: kind:feature, kind:docs, topic:stdlib

#11843 Remove useless assignments II
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/semantic/method_missing.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/playground/server.cr
  src/compiler/crystal/tools/print_hierarchy.cr
  src/crystal/system/windows.cr
  src/csv/lexer.cr
  src/env.cr
  src/http/request.cr
  src/json/builder.cr
  src/json/lexer/string_based.cr
  src/option_parser.cr
  src/path.cr
  src/string.cr
  src/time/format/custom/rfc_2822.cr
  src/time/format/parser.cr
  src/yaml/schema/core/parser.cr
Labels: topic:compiler, topic:stdlib, status:draft, kind:refactor

#11856 Fix: Prevent eager `instance_sizeof` on structs
  spec/compiler/semantic/sizeof_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#11791 Support day of year (`%j`) in `Time` parsers
  spec/std/time/format_spec.cr
  src/time/format/parser.cr
Labels: kind:feature, topic:stdlib:time

#11860 Improve `Crystal::Loader` errors
  src/compiler/crystal/loader/unix.cr
Labels: kind:feature, topic:compiler:interpreter

#11862 Fix: Do not consider global `Path` in def parameter restriction as free variable
  spec/compiler/semantic/def_overload_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/restrictions.cr
  src/compiler/crystal/syntax/ast.cr
Labels: kind:bug, kind:refactor, topic:compiler:semantic

#11777 Support `ProcPointer`s with global path and top-level method references
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/normalize/proc_pointer_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:lang

#11880 Improve `URI::Params#inspect` to use hash-like literal
  spec/std/uri/params_spec.cr
  src/uri.cr
  src/uri/params.cr
Labels: kind:feature, topic:stdlib:networking

#11876 Allow explicit usage of libiconv
  src/crystal/iconv.cr
Labels: kind:feature, topic:stdlib:text

#11847 Fix character mappings for Windows path conversions
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, breaking-change, platform:windows, security, topic:stdlib:system

#11883 Fix: Inspect string in error message for number parsing
  spec/std/float_spec.cr
  spec/std/int_spec.cr
  src/float.cr
  src/int.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:numeric

#11780 Fix: Accept only option flags in `CRYSTAL_OPTS`
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/command/eval.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/command/playground.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/tools/init.cr
Labels: kind:bug, topic:compiler

#11701 Add docs for `Dir#entries`
  src/dir.cr
Labels: kind:docs, topic:stdlib:files

#11801 Enable interpreter integration specs for `YAML`
  spec/compiler/interpreter/integration_spec.cr
Labels: kind:specs, topic:stdlib:serialization, topic:compiler:interpreter

#11804 Allow passing instance method or conditional expressions to option `ignore_serialize` on `JSON::Field`
  spec/std/json/serializable_spec.cr
  src/json/serialization.cr
Labels: kind:feature, topic:stdlib:serialization, topic:lang:annotations

#10632 Add support for scientific notation in `BigFloat#to_s`
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:feature, breaking-change, topic:stdlib:numeric

#11881 Add `Hash#update`
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib:collection

#11885 Fix race condition in chown
  src/crystal/system/unix/file.cr
Labels: kind:bug, topic:stdlib:files

#11812 Experimental: better type inference for ivars/cvars
  spec/compiler/semantic/instance_var_spec.cr
  src/compiler/crystal/semantic/exception.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
Labels: kind:feature, status:discussion, topic:lang:type-system

#11875 Fix: Honour encoding in `IO::Memory#to_s`
  spec/std/io/memory_spec.cr
  src/io/memory.cr
  src/string.cr
Labels: kind:bug, breaking-change, topic:stdlib:text

#11897 Allow `Bytes[]` to construct an empty `Bytes`
  spec/std/io/buffered_spec.cr
  spec/std/io/io_spec.cr
  spec/std/io/memory_spec.cr
  spec/std/random_spec.cr
  spec/std/slice_spec.cr
  src/io/memory.cr
  src/slice.cr
Labels: kind:bug, topic:stdlib:collection

#11770 Improve section ordering in `scripts/github-changelog.cr`
  scripts/github-changelog.cr
Labels: kind:feature, topic:infrastructure

#11898 Improve `BitArray`'s constructors
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: kind:bug, kind:feature, topic:stdlib:collection

#11906 Support `Generic` nodes with no type variables
  spec/compiler/codegen/multi_assign_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/parser.cr
  src/named_tuple.cr
  src/tuple.cr
Labels: kind:feature, topic:compiler:parser

#10865 Fix `IO::FileDescriptor#pos` giving incorrect position after write
  spec/std/file_spec.cr
  src/io/buffered.cr
  src/io/file_descriptor.cr
Labels: kind:bug, topic:stdlib:files

#11680 Support `@[Deprecated]` on constants
  spec/compiler/codegen/warnings_spec.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/type_lookup.cr
  src/compiler/crystal/semantic/warnings.cr
Labels: kind:feature, topic:lang:annotations

#9577 Fix E notation parsing in `BigDecimal`
  spec/std/big/big_decimal_spec.cr
  src/big/big_decimal.cr
Labels: kind:feature, topic:stdlib:numeric

#11904 Support "can't infer type parameter" error for uninstantiated generic modules
  spec/compiler/semantic/module_spec.cr
  src/compiler/crystal/semantic/type_lookup.cr
Labels: kind:feature, topic:compiler

#11861 Resolve non-type free variables in return type restrictions
  spec/compiler/semantic/return_spec.cr
  src/compiler/crystal/semantic/type_lookup.cr
Labels: kind:bug, topic:compiler:generics

#11811 Fix recursive `pointerof` detection with generic splat type variables
  spec/compiler/semantic/pointer_spec.cr
  src/compiler/crystal/semantic/bindings.cr
Labels: kind:bug, topic:compiler:generics

#11902 Upload build artifacts to S3 bucket
  .circleci/config.yml
Labels: kind:bug, topic:infrastructure

#11911 Improve error for incompatible generic arguments for `WeakRef`
  src/weak_ref.cr
Labels: kind:feature, topic:stdlib:runtime

#11796 Optimize Integer decoding from bytes
  src/io/byte_format.cr
Labels: performance, topic:stdlib:numeric

#10437 Implement `Iterator.from_json` and `#to_json`
  spec/std/json/serialization_spec.cr
  src/json/from_json.cr
  src/json/to_json.cr
  src/yaml/to_yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#11913 Evaluate `LibLLVM::IS_LT_*` during macro expansion time
  src/compiler/crystal/codegen/debug.cr
  src/llvm/enums.cr
  src/llvm/lib_llvm.cr
  src/llvm/module.cr
  src/llvm/type.cr
Labels: kind:bug, topic:compiler, topic:stdlib:llvm

#10539 Add `self` return type to UUID constructor methods
  src/uuid.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#11920 Revert "Fix: Accept only option flags in `CRYSTAL_OPTS` (#11780)"
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/command/eval.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/command/playground.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/tools/init.cr
Labels: kind:bug, topic:compiler, kind:regression

#11827 Fix `Path` support for UNC shares
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, topic:stdlib:system

#11758 Fix `make install` for BSD
  Makefile
Labels: kind:bug, topic:infrastructure

#11905 Support LLVM 14.0
  .github/workflows/linux.yml
  src/llvm/ext/llvm-versions.txt
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
Labels: topic:compiler, topic:infrastructure

#11927 examples: fix (2022-03)
  src/char.cr
  src/colorize.cr
  src/enumerable.cr
  src/indexable/mutable.cr
  src/range.cr
  src/uri/json.cr
  src/uri/yaml.cr
  src/uuid.cr
Labels: kind:bug, kind:docs, topic:stdlib

#11928 Compiler: fix incorrect var type insisde nested exception handler
  spec/compiler/semantic/exception_spec.cr
  spec/compiler/semantic/ssa_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#11922 Fix: Accept only option flags in CRYSTAL_OPTS for build commands
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/docs.cr
  src/compiler/crystal/command/eval.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/command/playground.cr
  src/compiler/crystal/command/spec.cr
Labels: kind:bug, topic:compiler

#11939 Fix typo
  man/crystal.1
Labels: kind:bug, kind:docs

#11930 [CI] Update to shards 0.17.0
  .circleci/config.yml
  .github/workflows/win.yml
Labels: topic:infrastructure
