Repository crystal-lang/crystal, pull requests merged in 2022-02, with the labels that each got.

#11684 Add `Crystal::Program#check_deprecation`
  src/compiler/crystal/semantic/warnings.cr
Labels: topic:compiler, kind:refactor

#11719 Refactor `etc/completion.bash`
  etc/completion.bash
Labels: topic:infrastructure

#11207 [CI] Renaming jobs to be `arch-os-job` or `arch-build-job`
  .github/workflows/aarch64.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/win.yml
Labels: topic:infrastructure

#11697 Add docs for `Complex#zero?`
  src/complex.cr
Labels: kind:docs, topic:stdlib:numeric

#11682 Adds docs for `Array#replace`
  src/array.cr
Labels: kind:docs, topic:stdlib:collection

#11689 Add docs for `Dir#path`
  src/dir.cr
Labels: kind:docs, topic:stdlib:files

#11783 Interpreter: support `Tuple#[]` with range literals
  spec/compiler/interpreter/tuple_spec.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:feature, topic:lang, topic:compiler:interpreter

#11591 Optimize `BitArray`'s counting methods
  spec/std/bit_array_spec.cr
  src/bit_array.cr
Labels: performance, topic:stdlib:collection

#11784 Use "truthy" and "falsey" in more places in the documentation
  src/array.cr
  src/deque.cr
  src/enumerable.cr
  src/hash.cr
  src/indexable.cr
Labels: kind:docs, topic:stdlib

#11779 Relax `ENV.fetch(key, &)`'s block restriction
  spec/std/env_spec.cr
  src/env.cr
Labels: kind:feature, topic:stdlib:system

#11546 Support GNU style optional arguments in `OptionParser`
  spec/std/option_parser_spec.cr
  src/option_parser.cr
Labels: kind:feature, topic:stdlib

#11621 Refactor symbols for primitive number kinds to enums
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/codegen/ast.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/interpreter/c.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/primitives.cr
  src/compiler/crystal/interpreter/value.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/math_interpreter.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/syntax/token.cr
  src/compiler/crystal/types.cr
Labels: topic:compiler, kind:refactor

#11476 Add locations for `else`, `ensure`, `end` keywords
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser

#11793 Fix typo in GHA aarch64 config
  .github/workflows/aarch64.yml
Labels: kind:bug, topic:infrastructure, kind:regression

#11794 Fix `address_spec` expectation for Windows Server 2022
  spec/std/socket/address_spec.cr
Labels: platform:windows, kind:specs, topic:stdlib:networking

#11717 Fix for Crystal interpreter crash
  src/compiler/crystal/interpreter/interpreter.cr
Labels: kind:bug, topic:compiler:interpreter

#11797 remove duplicate word in documentation
  src/spec/dsl.cr
Labels: kind:docs, topic:stdlib:specs

#11795 Interpreter: Promote arguments of variadic function calls
  spec/compiler/data/interpreter/sum.c
  spec/compiler/interpreter/lib_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/crystal/system/unix/file.cr
Labels: kind:bug, topic:compiler:interpreter

#11768 Add error when instance variable is inherited from module and supertype
  spec/compiler/semantic/instance_var_spec.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
Labels: kind:bug, topic:compiler:semantic

#11810 Add parser support to handle CRLF the same as LF
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:feature, topic:compiler:parser

#11816 Add specs for `NamedTuple#from`
  spec/std/named_tuple_spec.cr
Labels: kind:specs, topic:stdlib:runtime

#11813 Refactor target clauses for system implementations
  src/crystal/system/env.cr
  src/crystal/system/file_descriptor.cr
  src/crystal/system/time.cr
Labels: kind:refactor, topic:stdlib:system

#11821 Add `space_to_plus` option in `URI::Params` everywhere
  spec/std/uri/params_spec.cr
  src/uri/params.cr
Labels: kind:feature, topic:stdlib:networking

#11807 Fix interpreter when shared library `pthread` is missing
  src/gc/boehm.cr
  src/lib_c/aarch64-darwin/c/dlfcn.cr
  src/lib_c/x86_64-darwin/c/dlfcn.cr
Labels: kind:bug, topic:stdlib:runtime, topic:compiler:interpreter

#11820 Fix: Hide `BigDecimal::ZERO` and `BigDecimal::TEN`
  src/big/big_decimal.cr
Labels: kind:bug, breaking-change, topic:stdlib:numeric

#11832 Add more Colorize overloads and fix docs
  spec/std/colorize_spec.cr
  src/colorize.cr
Labels: kind:bug, kind:feature, kind:docs, topic:stdlib:text

#11822 Add some return types to Array, Hash, Set and String
  src/array.cr
  src/hash.cr
  src/set.cr
  src/string.cr
Labels: kind:feature, kind:docs, topic:stdlib:collection

#11838 Check file-private types for abstract defs and recursive structs
  spec/compiler/semantic/abstract_def_spec.cr
  spec/compiler/semantic/recursive_struct_check_spec.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/recursive_struct_checker.cr
Labels: kind:bug, topic:compiler:semantic

#11852 Check if libraries are present using dlopen
  src/compiler/crystal/loader.cr
Labels: kind:bug, platform:darwin, topic:compiler:interpreter

#11851 Fix comment indentation in `ASTNode#to_s`
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:parser, topic:tools:docs-generator
