Repository crystal-lang/crystal, pull requests merged in 2023-05, with the labels that each got.

#13412 Refactor implementation of `Iterator::ChainIterator`
  spec/std/iterator_spec.cr
  src/iterator.cr
Labels: kind:bug, kind:refactor, topic:stdlib:collection

#13139 Improve `HTML.escape(string, io)` performance
  src/html.cr
Labels: performance, topic:stdlib:text

#13414 Support synchronous socket operations on Windows
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/socket.cr
  src/io/overlapped.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
Labels: performance, topic:stdlib:concurrency, platform:windows, topic:stdlib:networking

#13400 Use sentence case for all standard library exceptions
  samples/meteor.cr
  samples/pretty_json.cr
  samples/sdl/fire.cr
  scripts/generate_grapheme_break_specs.cr
  scripts/generate_unicode_data.cr
  spec/compiler/codegen/cast_spec.cr
  spec/compiler/interpreter/casts_spec.cr
  spec/std/ini_spec.cr
  spec/std/named_tuple_spec.cr
  spec/std/spec_spec.cr
  spec/std/tuple_spec.cr
  spec/support/fibers.cr
  src/array.cr
  src/channel.cr
  src/compiler/crystal/codegen/codegen.cr
  src/crystal/digest/sha1.cr
  src/crystal/dwarf/line_numbers.cr
  src/crystal/syntax_highlighter.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/fiber.cr
  src/crystal/system/thread.cr
  src/crystal/system/thread_condition_variable.cr
  src/crystal/system/thread_mutex.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/win32/process.cr
  src/crystal/system/win32/socket.cr
  src/dir/glob.cr
  src/docs_pseudo_methods.cr
  src/exception/call_stack/stackwalk.cr
  src/float/printer/dragonbox.cr
  src/indexable/mutable.cr
  src/ini.cr
  src/int.cr
  src/json/pull_parser.cr
  src/json/serialization.cr
  src/lib_c.cr
  src/llvm/type.cr
  src/named_tuple.cr
  src/openssl/cipher.cr
  src/process.cr
  src/raise.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
  src/slice.cr
  src/spec/cli.cr
  src/spec/context.cr
  src/spec/helpers/iterate.cr
  src/static_array.cr
  src/yaml/any.cr
  src/yaml/serialization.cr
Labels: topic:stdlib, kind:refactor

#13421 Fix `File.info(File::NULL)` on Windows
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13419 Fix `preview_mt` infinite loop on Windows
  src/crystal/scheduler.cr
Labels: kind:bug, platform:windows, topic:multithreading, kind:regression

#13424 Clean up unused code for Windows event loop
  src/crystal/system/event_loop.cr
  src/crystal/system/wasi/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/kernel.cr
Labels: topic:stdlib:concurrency, kind:refactor, platform:windows

#13430 Fixup for `JSON::Serializable` on certain recursively defined types
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization, kind:regression

#13428 HTTP Server should allow custom concurrency models
  src/http/server.cr
Labels: kind:feature, topic:stdlib:networking

#13433 Simplify implementation of `Serializable#initialize`
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/pull_parser.cr
  src/json/serialization.cr
  src/yaml/schema/core.cr
  src/yaml/serialization.cr
Labels: kind:refactor, topic:stdlib:serialization

#13434 Docs: Reference `Process.executable_path` at `PROGRAM_NAME`
  src/kernel.cr
Labels: kind:docs, topic:stdlib:system

#13351 Disallow creating `Big*` numbers from infinity or NaN
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/big/big_rational_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
Labels: kind:bug, topic:stdlib:numeric

#13440 Use `Int#bit_length` instead of `Math.log2` followed by `#to_i`
  src/hash.cr
  src/slice/sort.cr
Labels: kind:refactor, topic:stdlib:numeric

#13108 Added `Enumerable#in_slices_of`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection

#13352 Use GMP's functions for `Float`-to-`BigRational` conversion
  src/big/big_rational.cr
  src/big/lib_gmp.cr
Labels: kind:refactor, topic:stdlib:numeric

#13405 Fix `Log::Builder` append `BroadcastBackend` to itself
  spec/std/log/builder_spec.cr
  src/log/builder.cr
Labels: kind:bug, topic:stdlib:log

#13448 Remove most `LLVM::DIBuilder` functions from `llvm_ext.cc`
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/debug.cr
  src/llvm/di_builder.cr
  src/llvm/enums.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
Labels: kind:refactor, breaking-change, topic:stdlib:llvm

#13450 Update previous Crystal release - 1.8.2
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#13436 Support DLL delay-loading on Windows
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/loader.cr
  src/compiler/crystal/loader/msvc.cr
  src/crystal/main.cr
  src/crystal/system/win32/delay_load.cr
  src/lib_c/x86_64-windows-msvc/c/delayimp.cr
  src/lib_c/x86_64-windows-msvc/c/errhandlingapi.cr
  src/lib_c/x86_64-windows-msvc/c/libloaderapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/raise.cr
Labels: kind:feature, topic:compiler, platform:windows, topic:stdlib:runtime

#13181 Support LLVM 16
  .github/workflows/llvm.yml
  src/llvm/ext/llvm-versions.txt
  src/llvm/ext/llvm_ext.cc
Labels: kind:feature, topic:compiler:codegen, topic:stdlib:llvm

#13367 Fix error message for calling `record` macro with kwargs
  src/macros.cr
Labels: kind:bug, topic:stdlib:macros

#13460 Allow newline after hash rocket
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13469 Upgrade Windows CI to LLVM 16
  .github/workflows/win.yml
  Makefile.win
Labels: topic:infrastructure, platform:windows, topic:stdlib:llvm

#13452 Parser: Add missing locations of various AST nodes
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13468 Add a testcase line number to the output of JUnitFormatter
  spec/std/spec/junit_formatter_spec.cr
  src/spec/junit_formatter.cr
Labels: kind:feature, topic:stdlib:specs

#13339 Add `Regex.literal`
  spec/std/regex_spec.cr
  src/regex.cr
Labels: kind:feature, topic:stdlib:text

#13415 Add `URI::Params#merge`, `#merge!` and `URI#update_query_params`
  spec/std/uri/params_spec.cr
  spec/std/uri_spec.cr
  src/uri.cr
  src/uri/params.cr
Labels: kind:feature, topic:stdlib:networking

#13463 Parse IP addresses in Crystal instead of using `LibC.inet_pton`
  spec/std/socket/address_spec.cr
  src/openssl/ssl/hostname_validation.cr
  src/socket/address.cr
Labels: kind:bug, topic:stdlib:networking

#13462 Allow `File.delete` to remove read-only files on Windows
  spec/std/file_spec.cr
  spec/support/tempfile.cr
  src/crystal/system/win32/file.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13476 Disable `Process.pgid` spec on Windows
  spec/std/process_spec.cr
Labels: platform:windows, kind:specs, topic:stdlib:system

#13456 Fix AST location of call name in operator assignment
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13479 Add `.gitattributes` to repository
  .gitattributes
Labels: topic:infrastructure

#13475 Print error if unable to delay-load DLL on Windows
  src/crystal/system/win32/delay_load.cr
  src/lib_c/x86_64-windows-msvc/c/errhandlingapi.cr
  src/lib_c/x86_64-windows-msvc/c/processenv.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
Labels: kind:feature, platform:windows, topic:stdlib:runtime

#13485 Fix `LibM.hypotf` and `ldexpf` link errors on Windows
  src/math/libm.cr
  src/math/math.cr
Labels: kind:bug, platform:windows, topic:stdlib:numeric

#13486 Use per-thread libxml2 global state on Windows
  src/xml.cr
  src/xml/libxml2.cr
  src/xml/node.cr
Labels: kind:refactor, platform:windows, topic:stdlib:serialization

#13483 Implement `Socket::IPAddress#to_s` with Crystal instead of `LibC.inet_ntop`
  spec/std/socket/address_spec.cr
  src/socket/address.cr
Labels: kind:bug, topic:stdlib:networking

#13488 Deprecate `LLVM::Module#write_bitcode_with_summary_to_file`
  man/crystal.1
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm_ext.cr
  src/llvm/module.cr
Labels: breaking-change, topic:stdlib:llvm

#13491 Add `File::BadExecutableError`
  spec/std/process_spec.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/win32/process.cr
  src/file/error.cr
  src/system_error.cr
  src/winerror.cr
Labels: kind:bug, kind:feature, topic:stdlib:system

#13465 Fix file permission specs on Windows
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
Labels: platform:windows, kind:specs, topic:stdlib:files

#13446 Add `start_day` parameter to `Time#at_beginning_of_week`
  spec/std/time/time_spec.cr
  src/time.cr
Labels: kind:feature, topic:stdlib:time

#13478 Split Windows library build scripts from CI
  .github/workflows/win.yml
  etc/win-ci/build-ffi.ps1
  etc/win-ci/build-gc.ps1
  etc/win-ci/build-iconv.ps1
  etc/win-ci/build-mpir.ps1
  etc/win-ci/build-openssl.ps1
  etc/win-ci/build-pcre.ps1
  etc/win-ci/build-pcre2.ps1
  etc/win-ci/build-xml2.ps1
  etc/win-ci/build-yaml.ps1
  etc/win-ci/build-z.ps1
  etc/win-ci/setup.ps1
Labels: topic:infrastructure, kind:refactor, platform:windows

#13494 Ensure `Socket` checks `WinError.wsa_value` on Windows, not `Errno.value`
  src/crystal/system/socket.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/wasi/socket.cr
  src/crystal/system/win32/socket.cr
  src/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:networking

#13495 Make `fcntl` defined on all platforms
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/socket.cr
  src/io/file_descriptor.cr
Labels: kind:bug, platform:windows, topic:stdlib:files, topic:stdlib:networking, platform:wasm

#13370 Make compiler aware of output extension when building programs
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/macros/macros.cr
Labels: kind:bug, topic:compiler

#13500 Remove incorrect `CRYSTAL` in comments
  spec/std/string/grapheme_break_spec.cr
Labels: kind:specs, topic:stdlib:text

#13498 Add `slow` tag to stdlib specs that compile a program
  spec/std/exception/call_stack_spec.cr
  spec/std/io/file_descriptor_spec.cr
  spec/std/kernel_spec.cr
  spec/std/process_spec.cr
  spec/std/spec/hooks_spec.cr
  spec/std/string_spec.cr
  spec/std/va_list_spec.cr
Labels: kind:feature, kind:specs, topic:stdlib:files

#13503 Fix for Process: ensure chdir is a string
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#13067 Formatter: escape bi-directional control characters within strings
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:tools:formatter, security
