Repository crystal-lang/crystal, pull requests merged in 2023-12, with the labels that each got.

#13968 Add `String#matches_full?`
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#14038 Fix documentation for `String#index!`
  src/string.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#14031 Support `instance_sizeof(T)` in the interpreter
  spec/compiler/interpreter/sizeof_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/context.cr
Labels: kind:feature, topic:compiler:interpreter

#13980 Optimize `BigInt#bit`
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
  src/big/lib_gmp.cr
Labels: performance, topic:stdlib:numeric

#14041 Windows: Run specs in random order by default
  Makefile.win
Labels: topic:infrastructure, platform:windows

#14044 Fix `ReadInstanceVar` on typedefs
  spec/compiler/semantic/c_type_spec.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, topic:compiler:semantic

#14054 Fix a typo in compiler source
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler:codegen

#14053 Fix typos in src
  src/compiler/crystal/syntax/parser.cr
  src/enum.cr
  src/file.cr
  src/html.cr
  src/http/headers.cr
  src/io/delimited.cr
Labels: kind:bug, topic:stdlib

#14040 Interpreter: Fix element alignment of `Tuple` and `NamedTuple` casts
  spec/compiler/interpreter/casts_spec.cr
  src/compiler/crystal/interpreter/cast.cr
  src/compiler/crystal/interpreter/compiler.cr
  test
Labels: kind:bug, topic:compiler:interpreter

#14025 Avoid `@[ThreadLocal]` on Android
  src/crystal/system/unix/pthread.cr
  src/lib_c/aarch64-android/c/pthread.cr
  src/lib_c/aarch64-android/c/sys/types.cr
Labels: kind:bug, topic:stdlib:runtime, platform:android

#14027 Add `Float::Primitive.parse_hexfloat`, `.parse_hexfloat?`, `#to_hexfloat`
  spec/interpreter_std_spec.cr
  spec/std/float_printer/hexfloat_spec.cr
  spec/std/float_printer/shortest_spec.cr
  spec/support/number.cr
  src/float.cr
  src/float/printer.cr
  src/float/printer/hexfloat.cr
  src/humanize.cr
Labels: kind:feature, topic:stdlib:numeric

#14050 Expose doc comments on `ASTNode` when generating docs
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#14063 Add macro methods for `ModuleDef`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#14064 Add macro methods for `Include` and `Extend`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#14070 Document `Crystal::Macros::MagicConstant`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:stdlib:macros

#14068 Windows: clear `Crystal::System::Process#@completion_key` after use
  src/io/overlapped.cr
Labels: kind:bug, topic:stdlib:system

#14069 Use `#trailing_zeros_count` in `Int#gcd`
  src/int.cr
Labels: performance, topic:stdlib:numeric

#14073 Fix global `Path` lookup inside macro when def has free variables
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/macros/types.cr
Labels: kind:bug, topic:lang:macros

#14079 Support `LLVMSetTargetMachineGlobalISel` from LLVM 18
  src/llvm/ext/llvm_ext.cc
  src/llvm/jit_compiler.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm/target_machine.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/target_machine.cr
Labels: kind:refactor, topic:stdlib:llvm

#14075 Do not remove trailing comma from multi-line macro/def parameters
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#14071 Change short_reference for top-level methods to `::foo`
  spec/compiler/semantic/def_spec.cr
  spec/compiler/semantic/warnings_spec.cr
  src/compiler/crystal/semantic/warnings.cr
Labels: kind:feature, topic:compiler:semantic

#14080 [CI] Update LLVM patch version to LLVM 17.0.6
  .github/workflows/llvm.yml
Labels: topic:infrastructure

#14081 Support debug information for 64-bit or unsigned enums
  spec/debug/large_enums.cr
  spec/debug/test.sh
  src/compiler/crystal/codegen/debug.cr
  src/llvm/di_builder.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm/debug_info.cr
  src/llvm/lib_llvm_ext.cr
Labels: kind:feature, topic:compiler:debugger

#14067 Implement `sprintf "%f"` in Crystal using Ryu Printf
  spec/std/float_printer/ryu_printf_spec.cr
  spec/std/float_printer/ryu_printf_test_cases.cr
  spec/std/sprintf_spec.cr
  src/float/printer/ryu_printf.cr
  src/float/printer/ryu_printf_table.cr
  src/string/formatter.cr
Labels: kind:feature, topic:stdlib:numeric

#14072 Add macro methods for `ClassDef`, `EnumDef`, `AnnotationDef`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#13970 Skip `Crystal::Macros` unless generating docs
  src/compiler/crystal/macros.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: kind:bug, topic:compiler

#9352 Use `top_level_semantic` in doc spec instead of `semantic`
  spec/compiler/crystal/tools/doc/method_spec.cr
  spec/compiler/crystal/tools/doc/type_spec.cr
  spec/spec_helper.cr
Labels: kind:refactor, topic:tools:docs-generator, kind:specs

#12671 Add compile time string interpolation for char/num/bool constants
  spec/compiler/normalize/string_interpolation_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:feature, topic:compiler:semantic, topic:lang

#12654 Add `Enumerable(T)#to_set(& : T -> U) : Set(U) forall U`
  spec/std/enumerable_spec.cr
  src/set.cr
Labels: kind:feature, topic:stdlib:collection

#14086 Add `pending_wasm32`
  .github/workflows/wasm32.yml
  spec/spec_helper.cr
  spec/std/html_spec.cr
  spec/std/path_spec.cr
  spec/std/regex_spec.cr
  spec/std/spec_helper.cr
  spec/std/string_spec.cr
  spec/support/wasm32.cr
  spec/wasm32_std_spec.cr
Labels: kind:feature, kind:specs, platform:wasm

#13616 List spec tags
  spec/std/spec/list_tags_spec.cr
  spec/std/spec_helper.cr
  src/spec/cli.cr
  src/spec/dsl.cr
Labels: kind:feature, topic:stdlib:specs

#14082 Support the operand bundle API from LLVM 18
  src/llvm/builder.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm/core.cr
  src/llvm/lib_llvm/types.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/operand_bundle_def.cr
Labels: kind:refactor, topic:stdlib:llvm

#14092 Fix `Indexable#each_repeated_combination(n)` when `n > size`
  spec/std/indexable_spec.cr
  src/indexable.cr
Labels: kind:bug, topic:stdlib:collection

#14084 Implement `sprintf "%e"` in Crystal
  spec/std/sprintf_spec.cr
  src/string/formatter.cr
Labels: kind:feature, topic:stdlib:numeric

#14095 Add `LLVM::OperandBundleDef#dispose`
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm/core.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/operand_bundle_def.cr
Labels: kind:feature, topic:stdlib:llvm

#14096 MT: math overflow after spawning Int32::MAX + 1 fibers
  src/crystal/scheduler.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:multithreading

#14102 Implement `sprintf "%a"` in Crystal
  spec/std/sprintf_spec.cr
  src/float/printer.cr
  src/float/printer/hexfloat.cr
  src/string/formatter.cr
Labels: kind:feature, topic:stdlib:numeric

#14105 Fix time span overflow on `Int#milliseconds` and `Int#microseconds`
  spec/std/time/span_spec.cr
  src/time/span.cr
Labels: kind:bug, topic:stdlib:time

#14101 Windows: Use local configuration for LLVM when linking dynamically
  src/llvm/lib_llvm.cr
Labels: kind:feature, platform:windows, topic:stdlib:llvm

#14104 Fix `StaticArray#to_json`
  spec/std/json/serialization_spec.cr
  src/json/to_json.cr
Labels: kind:feature, topic:stdlib:serialization

#14114 Never use string interpolation in `Crystal::System.print_error`
  src/crystal/scheduler.cr
  src/exception/call_stack/interpreter.cr
  src/raise.cr
Labels: kind:bug, security, topic:stdlib:runtime

#14099 Move `Thread#set_current_thread` to `Fiber`
  src/concurrent.cr
  src/crystal/scheduler.cr
  src/crystal/system/thread.cr
  src/fiber.cr
Labels: topic:stdlib:concurrency, kind:refactor, topic:multithreading

#14098 Skip indirections in `Crystal::Scheduler`
  src/crystal/scheduler.cr
Labels: performance, topic:stdlib:concurrency, kind:refactor, topic:multithreading

#14110 Distribute LLVM DLLs on Windows CI
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
  etc/win-ci/build-llvm.ps1
Labels: kind:feature, platform:windows, topic:stdlib:llvm, topic:infrastructure/ci

#14112 Add `scripts/generate_llvm_version_info.cr`
  scripts/generate_llvm_version_info.cr
Labels: kind:feature, topic:infrastructure, platform:windows, topic:stdlib:llvm

#14108 Add `Reference.pre_initialize` and `.unsafe_construct`
  spec/compiler/semantic/primitives_spec.cr
  spec/primitives/reference_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/primitives.cr
  src/reference.cr
Labels: kind:feature, topic:stdlib, experimental

#14128 Fix: can't resume a running fiber
  src/crystal/scheduler.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:multithreading, kind:regression

#14111 `Crystal::Loader`: Skip second linker member on Windows if absent
  src/crystal/system/win32/library_archive.cr
Labels: kind:bug, platform:windows, topic:compiler:interpreter

#14048 Expose macro `Call` context via new `@caller` macro ivar
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:feature, topic:lang:macros

#14087 Support `alignof` and `instance_alignof`
  spec/compiler/codegen/sizeof_spec.cr
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/interpreter/sizeof_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/semantic/sizeof_spec.cr
  spec/std/crystal/syntax_highlighter/colorize_spec.cr
  spec/std/crystal/syntax_highlighter/html_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/context.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/types.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_guess_visitor.cr
  src/compiler/crystal/semantic/type_lookup.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/syntax/token.cr
  src/compiler/crystal/syntax/transformer.cr
  src/compiler/crystal/tools/formatter.cr
  src/llvm/lib_llvm/core.cr
  src/llvm/type.cr
Labels: kind:feature, breaking-change, topic:lang

#14115 Change `Regex::MatchData#to_s` to return matched substring
  spec/std/regex/match_data_spec.cr
  src/regex/match_data.cr
Labels: kind:feature, topic:stdlib:text

#14119 Fix out-of-bounds access in `Int128::MIN.to_s(base: 2)`
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:bug, topic:stdlib:numeric

#14123 Implement `sprintf "%g"` in Crystal
  spec/std/float_printer/ryu_printf_spec.cr
  spec/std/float_printer/ryu_printf_test_cases.cr
  spec/std/sprintf_spec.cr
  src/float/printer/ryu_printf.cr
  src/float/printer/ryu_printf_table.cr
  src/string/formatter.cr
Labels: kind:feature, topic:stdlib:numeric

#14116 Implement most of `Crystal::System.print_error` in native Crystal
  spec/std/crystal/system_spec.cr
  src/crystal/system/print_error.cr
Labels: kind:refactor, topic:stdlib:runtime

#13758 Fix UTF-8 console input on Windows
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/consoleapi.cr
  src/string/utf16.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#14097 Workaround regular timeouts in `HTTP::Server` specs with MT
  spec/std/http/server/server_spec.cr
  spec/std/http/spec_helper.cr
Labels: kind:bug, kind:specs, topic:multithreading

#14127 Add location information to implicit flag enum members
  spec/compiler/semantic/doc_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#13969 Add `--tallies` option to `crystal tool unreachable`
  spec/compiler/crystal/tools/unreachable_spec.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:tools:unreachable

#14129 Avoid double rounding in `Float#format` for nonnegative `decimal_place`
  spec/std/humanize_spec.cr
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#14106 Add `ReferenceStorage` for manual allocation of references
  spec/compiler/semantic/reference_storage_spec.cr
  spec/primitives/reference_spec.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/types.cr
  src/prelude.cr
  src/reference_storage.cr
Labels: kind:feature, topic:stdlib, experimental

#14131 Support `dll` parameter in `@[Link]`
  spec/compiler/semantic/lib_spec.cr
  src/annotations.cr
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/ffi/lib_ffi.cr
  src/crystal/lib_iconv.cr
  src/gc/boehm.cr
  src/lib_z/lib_z.cr
  src/llvm/lib_llvm.cr
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
  src/regex/lib_pcre.cr
  src/regex/lib_pcre2.cr
  src/xml/libxml2.cr
  src/yaml/lib_yaml.cr
Labels: kind:feature, topic:compiler, platform:windows, topic:lang:annotations

#14133 Update shards 0.17.4
  .github/workflows/win_build_portable.yml
Labels: topic:infrastructure

#14132 Simplify `String::Formatter` when Ryu Printf is available
  spec/std/float_printer/ryu_printf_spec.cr
  spec/std/sprintf_spec.cr
  src/float/printer/ryu_printf.cr
  src/float/printer/ryu_printf_table.cr
  src/string/formatter.cr
Labels: kind:refactor, topic:stdlib:numeric

#12653 Add `Enumerable(T)#to_a(& : T -> U) forall U`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
  src/hash.cr
  src/indexable.cr
  src/llvm/parameter_collection.cr
  src/named_tuple.cr
  src/set.cr
  src/tuple.cr
Labels: kind:feature, topic:stdlib:collection

#14140 Add docs and explicit type restriction for indent parameter of JSON.build
  src/json/builder.cr
Labels: kind:docs, topic:stdlib:serialization

#14144 Do not use `pointerof(Path)` in the standard library
  src/crystal/system/win32/path.cr
Labels: topic:stdlib, kind:refactor

#14136 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#14145 Fix interpreter specs on Windows
  spec/compiler/interpreter/lib_spec.cr
  spec/compiler/interpreter/spec_helper.cr
  src/compiler/crystal/interpreter/context.cr
Labels: platform:windows, kind:specs, topic:compiler:interpreter

#14143 Support `-dynamic.lib` in Windows interpreter
  spec/compiler/loader/msvc_spec.cr
  spec/compiler/loader/spec_helper.cr
  src/compiler/crystal/loader/msvc.cr
Labels: kind:feature, platform:windows, topic:compiler:interpreter
