Repository crystal-lang/crystal, pull requests merged in 2023-03, with the labels that each got.

#13133 Fix syntax error in Linux CI
  .github/workflows/linux.yml
Labels: kind:bug, topic:infrastructure, kind:regression

#13068 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#13126 Formatter: add `(&)` to param-less yielding defs before comment line
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter, kind:regression

#13125 Explicitly treat unbound type vars in generic class methods as free variables
  spec/compiler/semantic/restrictions_spec.cr
  src/compiler/crystal/semantic/match.cr
Labels: kind:bug, topic:compiler:generics, kind:regression

#13127 Define `Math.pw2ceil` for all integer types
  spec/std/big/big_int_spec.cr
  spec/std/math_spec.cr
  src/big/big_int.cr
  src/int.cr
  src/math/math.cr
Labels: kind:bug, kind:feature, topic:stdlib:numeric, kind:regression

#13136 Backport PCRE2 fixes to 1.7
  .github/workflows/aarch64.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  spec/std/regex_spec.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text

#13148 Fix `getelementptr` usage for the `allocate` primitive
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/primitives.cr
Labels: kind:bug, topic:compiler:codegen, topic:stdlib:llvm

#13138 Increase time drift for `HTTP::StaticFileHandler`'s gzip check
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/http/server/handlers/static_file_handler.cr
Labels: kind:feature, topic:stdlib:networking

#13137 `System::User#name`: Fall back to `#username` if unavailable
  src/crystal/system/unix/user.cr
  src/system/user.cr
Labels: kind:feature, topic:stdlib:system, platform:unix

#13147 Fix `MatchData#[]` named capture with identical prefix
  spec/std/regex/match_data_spec.cr
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text

#13146 Improve PCRE2 match performance for JIT and interpreted
  src/regex/lib_pcre2.cr
  src/regex/pcre2.cr
Labels: performance, topic:stdlib:text

#13151 [CI] Increase `no_output_timeout` on circleci
  .circleci/config.yml
Labels: topic:infrastructure

#12973 Support typed LLVM `load` instructions
  samples/llvm/brainfuck.cr
  spec/compiler/codegen/pointer_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/cond.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/once.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/codegen/type_id.cr
  src/compiler/crystal/codegen/unions.cr
  src/llvm/builder.cr
  src/llvm/lib_llvm.cr
Labels: kind:feature, topic:compiler:codegen, topic:stdlib:llvm

#13155 Fix `Regex::Option` behaviour for unnamed members
  spec/std/regex_spec.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text, kind:regression

#13142 Add changelog for 1.7.3
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#13159 Update NOTICE.md
  NOTICE.md
Labels: topic:infrastructure

#13131 Add full stub for Windows signals
  spec/std/process_spec.cr
  src/crystal/system/file.cr
  src/crystal/system/signal.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/unix/signal.cr
  src/crystal/system/wasi/signal.cr
  src/crystal/system/win32/signal.cr
  src/docs_main.cr
  src/exception/call_stack/libunwind.cr
  src/kernel.cr
  src/lib_c/x86_64-windows-msvc/c/signal.cr
  src/prelude.cr
  src/process.cr
  src/process/status.cr
  src/signal.cr
  src/windows_stubs.cr
Labels: kind:feature, breaking-change, platform:windows, topic:stdlib:system

#13158 Support typed LLVM `call` and `invoke` instructions
  samples/llvm/brainfuck.cr
  src/compiler/crystal/codegen/asm.cr
  src/compiler/crystal/codegen/class_var.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/context.cr
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/codegen/match.cr
  src/compiler/crystal/codegen/once.cr
  src/compiler/crystal/codegen/primitives.cr
  src/llvm/builder.cr
  src/llvm/function_collection.cr
  src/llvm/lib_llvm.cr
  src/llvm/parameter_collection.cr
Labels: kind:feature, topic:compiler:codegen, topic:stdlib:llvm

#13161 Use `Crystal::System.print_error` instead of `LibC.printf`
  src/gc/boehm.cr
  src/raise.cr
Labels: kind:refactor, topic:stdlib:runtime

#13065 AArch64 Android support
  .github/workflows/smoke.yml
  spec/compiler/loader/unix_spec.cr
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
  spec/std/process_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/static_array_spec.cr
  spec/std/system/group_spec.cr
  spec/std/system/user_spec.cr
  spec/std/va_list_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/loader/unix.cr
  src/compiler/crystal/semantic/flags.cr
  src/crystal/system/unix/lib_event2.cr
  src/crystal/system/unix/pthread.cr
  src/errno.cr
  src/exception/call_stack/elf.cr
  src/gc/boehm.cr
  src/lib_c.cr
  src/lib_c/aarch64-android/c/arpa/inet.cr
  src/lib_c/aarch64-android/c/dirent.cr
  src/lib_c/aarch64-android/c/dlfcn.cr
  src/lib_c/aarch64-android/c/elf.cr
  src/lib_c/aarch64-android/c/errno.cr
  src/lib_c/aarch64-android/c/fcntl.cr
  src/lib_c/aarch64-android/c/grp.cr
  src/lib_c/aarch64-android/c/iconv.cr
  src/lib_c/aarch64-android/c/link.cr
  src/lib_c/aarch64-android/c/netdb.cr
  src/lib_c/aarch64-android/c/netinet/in.cr
  src/lib_c/aarch64-android/c/netinet/tcp.cr
  src/lib_c/aarch64-android/c/pthread.cr
  src/lib_c/aarch64-android/c/pwd.cr
  src/lib_c/aarch64-android/c/sched.cr
  src/lib_c/aarch64-android/c/signal.cr
  src/lib_c/aarch64-android/c/stdarg.cr
  src/lib_c/aarch64-android/c/stddef.cr
  src/lib_c/aarch64-android/c/stdint.cr
  src/lib_c/aarch64-android/c/stdio.cr
  src/lib_c/aarch64-android/c/stdlib.cr
  src/lib_c/aarch64-android/c/string.cr
  src/lib_c/aarch64-android/c/sys/file.cr
  src/lib_c/aarch64-android/c/sys/mman.cr
  src/lib_c/aarch64-android/c/sys/resource.cr
  src/lib_c/aarch64-android/c/sys/select.cr
  src/lib_c/aarch64-android/c/sys/socket.cr
  src/lib_c/aarch64-android/c/sys/stat.cr
  src/lib_c/aarch64-android/c/sys/syscall.cr
  src/lib_c/aarch64-android/c/sys/time.cr
  src/lib_c/aarch64-android/c/sys/types.cr
  src/lib_c/aarch64-android/c/sys/un.cr
  src/lib_c/aarch64-android/c/sys/wait.cr
  src/lib_c/aarch64-android/c/termios.cr
  src/lib_c/aarch64-android/c/time.cr
  src/lib_c/aarch64-android/c/unistd.cr
  src/llvm.cr
Labels: kind:feature, platform, platform:aarch64

#13164 Support LLVM 15
  .github/workflows/linux.yml
  spec/compiler/codegen/primitives_spec.cr
  spec/llvm-ir/test.sh
  src/compiler/crystal/codegen/ast.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/intrinsics.cr
  src/llvm/context.cr
  src/llvm/enums.cr
  src/llvm/ext/llvm-versions.txt
  src/llvm/function.cr
  src/llvm/lib_llvm.cr
  src/llvm/type.cr
Labels: kind:feature, topic:infrastructure, topic:compiler:codegen, topic:stdlib:llvm

#13171 Do not build LLVM `bitcast` instructions for opaque pointer casts
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/cond.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/once.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/codegen/unions.cr
Labels: performance, kind:refactor, topic:compiler:codegen

#13172 Deprecate LLVM typed pointers
  src/llvm/builder.cr
  src/llvm/function.cr
  src/llvm/parameter_collection.cr
Labels: breaking-change, topic:stdlib:llvm

#13154 Docs: Fix examples for `#byte_swap` with different int types
  src/int.cr
Labels: kind:docs, topic:stdlib:numeric

#13173 Support LLVM 15
  .github/workflows/linux.yml
  samples/llvm/brainfuck.cr
  spec/compiler/codegen/pointer_spec.cr
  spec/compiler/codegen/primitives_spec.cr
  spec/llvm-ir/test.sh
  src/compiler/crystal/codegen/asm.cr
  src/compiler/crystal/codegen/ast.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/class_var.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/cond.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/context.cr
  src/compiler/crystal/codegen/crystal_llvm_builder.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/codegen/match.cr
  src/compiler/crystal/codegen/once.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/codegen/type_id.cr
  src/compiler/crystal/codegen/unions.cr
  src/intrinsics.cr
  src/llvm/builder.cr
  src/llvm/context.cr
  src/llvm/enums.cr
  src/llvm/ext/llvm-versions.txt
  src/llvm/function.cr
  src/llvm/function_collection.cr
  src/llvm/lib_llvm.cr
  src/llvm/parameter_collection.cr
  src/llvm/type.cr
Labels: topic:infrastructure, breaking-change, topic:compiler:codegen, topic:stdlib:llvm

#13180 Fix formatting from #13154
  src/int.cr
Labels: kind:bug, kind:docs, topic:stdlib:numeric, kind:regression

#13175 Fix `Socket#tty?` to `false` on Windows
  spec/std/socket/socket_spec.cr
  src/crystal/system/win32/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#13179 [CI] Cancel in-progress jobs when another commit is pushed
  .github/workflows/aarch64.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/smoke.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
Labels: kind:feature, topic:infrastructure

#13177 Remove obsolete functions from `llvm_ext.cc`
  src/llvm.cr
  src/llvm/basic_block.cr
  src/llvm/builder.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/function.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/value_methods.cr
Labels: kind:refactor, topic:compiler:codegen, topic:stdlib:llvm

#13140 Implement `Process.ppid` on Windows
  spec/std/process_spec.cr
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/tlhelp32.cr
  src/process.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#13141 Improve `File.symlink` on Windows
  src/crystal/system/win32/file.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#13188 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#13178 Leverage `fileapi` for opening files on windows
  spec/std/file_spec.cr
  src/crystal/system/file.cr
  src/crystal/system/win32/file.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13187 OpenSSL: use Windows' system root certificate store
  src/crystal/system/win32/crypto.cr
  src/lib_c/x86_64-windows-msvc/c/wincrypt.cr
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
  src/openssl/ssl/context.cr
  src/openssl/x509/certificate.cr
Labels: kind:feature, platform:windows, topic:stdlib:networking

#13186 Enable or fix specs that already work on Windows
  spec/compiler/codegen/thread_local_spec.cr
  spec/manual/string_normalize_spec.cr
  spec/std/file/tempfile_spec.cr
  spec/std/file_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/signal_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/sprintf_spec.cr
  spec/std/system_spec.cr
  src/crystal/system/unix/lib_event2.cr
Labels: platform:windows, kind:specs

#11505 Windows 7 support
  src/crystal/system/win32/thread.cr
  src/crystal/system/win32/time.cr
  src/lib_c/x86_64-windows-msvc/c/memoryapi.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/sdkddkver.cr
  src/lib_c/x86_64-windows-msvc/c/sysinfoapi.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, platform:windows

#13201 Mute shell comments in Makefile
  Makefile
Labels: topic:infrastructure

#13167 Update previous Crystal release - 1.7.3
  .circleci/config.yml
  .github/workflows/linux.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#13212 Fix `SyntaxHighlighter::HTML` to escape identifier values
  spec/std/crystal/syntax_highlighter/html_spec.cr
  src/crystal/syntax_highlighter/html.cr
Labels: kind:bug, topic:stdlib

#13213 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#13218 Workaround for more `Int128`-and-float methods on Windows with LLVM 14+
  src/crystal/compiler_rt.cr
Labels: kind:bug, platform:windows, topic:stdlib:numeric, topic:compiler:codegen

#13219 Remove `__declspec(dllimport)` from Windows libiconv build
  .github/workflows/win.yml
Labels: kind:bug, topic:infrastructure, platform:windows

#13220 Windows: detect stack overflows on non-main `Fiber`s
  spec/std/kernel_spec.cr
  src/crystal/system/win32/fiber.cr
  src/exception/call_stack/stackwalk.cr
  src/lib_c/x86_64-windows-msvc/c/memoryapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, platform:windows, topic:stdlib:runtime

#13222 Fix `Int128`-and-float conversion overflow checks on Windows LLVM 14+
  src/crystal/compiler_rt.cr
Labels: kind:bug, platform:windows, topic:stdlib:numeric

#13215 Formatter: Add feature flag for `method_signature_yield`
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:tools:formatter

#13195 Implement `File.readlink` on Windows
  spec/std/dir_spec.cr
  spec/std/file_spec.cr
  spec/std/file_utils_spec.cr
  src/crystal/system/win32/dir.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_info.cr
  src/file.cr
  src/lib_c/x86_64-windows-msvc/c/errno.cr
  src/lib_c/x86_64-windows-msvc/c/ioapiset.cr
  src/lib_c/x86_64-windows-msvc/c/ntifs.cr
  src/lib_c/x86_64-windows-msvc/c/winioctl.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#13226 Drop privileges in chroot spec
  spec/std/process_spec.cr
  src/lib_c/aarch64-android/c/unistd.cr
  src/lib_c/aarch64-darwin/c/unistd.cr
  src/lib_c/aarch64-linux-gnu/c/unistd.cr
  src/lib_c/aarch64-linux-musl/c/unistd.cr
  src/lib_c/arm-linux-gnueabihf/c/unistd.cr
  src/lib_c/i386-linux-gnu/c/unistd.cr
  src/lib_c/i386-linux-musl/c/unistd.cr
  src/lib_c/x86_64-darwin/c/unistd.cr
  src/lib_c/x86_64-dragonfly/c/unistd.cr
  src/lib_c/x86_64-freebsd/c/unistd.cr
  src/lib_c/x86_64-linux-gnu/c/unistd.cr
  src/lib_c/x86_64-linux-musl/c/unistd.cr
  src/lib_c/x86_64-netbsd/c/unistd.cr
  src/lib_c/x86_64-openbsd/c/unistd.cr
Labels: kind:bug, kind:specs, topic:stdlib:system

#13185 [CI] Increase `no_output_timeout` on circleci (cont.)
  .circleci/config.yml
Labels: topic:infrastructure

#13208 [CI] Update Windows job to LLVM 15
  .github/workflows/win.yml
Labels: topic:infrastructure

#12886 Handle `Range` requests in `HTTP::StaticFileHandler`
  spec/std/data/static_file_handler/empty.txt
  spec/std/data/static_file_handler/range.txt
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/http/server/handlers/static_file_handler.cr
Labels: kind:feature, topic:stdlib:networking

#13235 Windows: fix error condition when `File.open` fails
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:bug, platform:windows, topic:stdlib:files, kind:regression

#13204 Add `Socket::IPAddress#link_local?`
  spec/std/socket/address_spec.cr
  src/socket/address.cr
Labels: kind:bug, topic:stdlib:networking

#13227 Skip eacces spec for superuser
  spec/std/file_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:files

#13229 Fix `Enum#includes?` to require all bits set
  spec/std/enum_spec.cr
  src/enum.cr
Labels: kind:bug, breaking-change, topic:stdlib:collection

#13238 Fix JSON, YAML `use_*_discriminator` for recursive struct types
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization

#13241 Clean up `.gitignore`
  .gitignore
Labels: topic:infrastructure

#13223 Add more members to `Regex::Options`
  spec/std/regex_spec.cr
  src/regex.cr
  src/regex/lib_pcre.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
Labels: kind:feature, breaking-change, topic:stdlib:text

#13242 Fix: LibC definition for sys/socket.h (*-linux-gnu targets)
  src/lib_c/i386-linux-gnu/c/sys/socket.cr
  src/lib_c/x86_64-linux-gnu/c/sys/socket.cr
Labels: kind:bug, topic:stdlib:networking

#13246 [CI] Extract LLVM tests in separate workflow
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
Labels: topic:infrastructure, kind:refactor
