Repository crystal-lang/crystal, pull requests merged in 2023-04, with the labels that each got.

#13240 Fix PCRE crashing on invalid UTF-8
  spec/std/regex_spec.cr
  src/regex.cr
  src/regex/lib_pcre.cr
  src/regex/lib_pcre2.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
Labels: kind:bug, breaking-change, topic:stdlib:text

#13269 Fix `Pointer#copy_to` overflow on unsigned size and different target type
  spec/std/pointer_spec.cr
  src/pointer.cr
Labels: kind:bug, topic:stdlib

#13267 [CI] Extract interpreter workflow and split `std_spec` execution
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
Labels: topic:infrastructure, topic:compiler:interpreter

#13256 Fix `Array#replace` on shifted arrays
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#13251 Makefile: Add `interpreter_spec`
  .github/workflows/interpreter.yml
  .github/workflows/macos.yml
  Makefile
  Makefile.win
Labels: topic:infrastructure

#13253 Add specs for regex literal expansion
  spec/compiler/normalize/regex_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
Labels: kind:bug, topic:compiler:semantic, kind:specs, kind:regression

#13248 Add `Regex::MatchOptions`
  spec/compiler/parser/parser_spec.cr
  spec/std/regex_spec.cr
  src/compiler/crystal/semantic/literal_expander.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/regex.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
  src/string.cr
  src/string_scanner.cr
Labels: kind:feature, topic:stdlib:text

#13278 Remove compile-time error for `Range#size`, `#each`, `#sample`
  spec/std/range_spec.cr
  src/range.cr
Labels: kind:bug, topic:stdlib:collection

#13275 Fix `Array(T)#[]=(Int, Int, Array(T))` on shifted arrays
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#13281 Fix `bin/crystal` in symlink working directory
  bin/crystal
Labels: kind:bug, topic:infrastructure

#13282 Fix `HTTP::Server::Response#reset` for `status_message`
  spec/std/http/server/response_spec.cr
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#13061 Docs: Require all `Indexable`s to be stable
  src/indexable.cr
Labels: kind:docs, topic:stdlib:collection

#13276 Makefile: Add `all` target as default before including `Makfile.local`
  Makefile
  Makefile.win
Labels: topic:infrastructure

#13290 Fix interpreter `value_to_bool` for `NoReturn`
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/to_bool.cr
Labels: kind:bug, topic:compiler:interpreter

#13286 Fix `bin/crystal` when no global `crystal` command is installed
  bin/crystal
Labels: kind:bug, topic:infrastructure

#13249 Fix some Linux glibc bindings
  src/lib_c/aarch64-linux-gnu/c/dirent.cr
  src/lib_c/aarch64-linux-gnu/c/link.cr
  src/lib_c/aarch64-linux-gnu/c/signal.cr
  src/lib_c/aarch64-linux-gnu/c/stddef.cr
  src/lib_c/aarch64-linux-gnu/c/sys/resource.cr
  src/lib_c/aarch64-linux-gnu/c/sys/socket.cr
  src/lib_c/aarch64-linux-gnu/c/sys/types.cr
  src/lib_c/i386-linux-gnu/c/dirent.cr
  src/lib_c/i386-linux-gnu/c/link.cr
  src/lib_c/i386-linux-gnu/c/signal.cr
  src/lib_c/i386-linux-gnu/c/sys/resource.cr
  src/lib_c/i386-linux-gnu/c/sys/socket.cr
  src/lib_c/i386-linux-gnu/c/sys/stat.cr
  src/lib_c/i386-linux-gnu/c/sys/types.cr
  src/lib_c/x86_64-linux-gnu/c/dirent.cr
  src/lib_c/x86_64-linux-gnu/c/link.cr
  src/lib_c/x86_64-linux-gnu/c/signal.cr
  src/lib_c/x86_64-linux-gnu/c/sys/resource.cr
  src/lib_c/x86_64-linux-gnu/c/sys/socket.cr
  src/lib_c/x86_64-linux-gnu/c/sys/types.cr
Labels: kind:bug, platform:linux-gnu

#13298 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#13296 Update shards 0.17.3
  .github/workflows/win.yml
Labels: topic:infrastructure

#13295 Make `BigRational.new(BigFloat)` exact
  spec/std/big/big_rational_spec.cr
  src/big/big_rational.cr
  src/big/lib_gmp.cr
Labels: kind:bug, topic:stdlib:numeric

#13313 Drop `MATCH_INVALID_UTF`
  spec/std/regex_spec.cr
  src/regex.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
Labels: kind:feature, topic:stdlib:text

#13309 Remove `Regex::PCRE2#finalize` redefinition
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text

#13314 Clarify behavior of strings with invalid UTF-8 byte sequences
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#13315 Revert "Remove relative path to vendored shard `markd` (#13040)"
  src/compiler/crystal/interpreter/repl_reader.cr
  src/compiler/crystal/tools/doc/generator.cr
Labels: topic:compiler, kind:refactor

#13305 Always use 0 for offsets of lib / extern union members
  spec/compiler/codegen/debug_spec.cr
  spec/compiler/codegen/offsetof_spec.cr
  spec/debug/extern_unions.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/debug.cr
  src/llvm/target_data.cr
Labels: kind:bug, topic:compiler:debugger, topic:compiler:codegen

#13318 Refer to PCRE2 in `Regex`'s summary
  src/regex.cr
Labels: kind:docs, topic:stdlib:text

#13274 Add changelog for 1.8.0
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#13322 Update previous Crystal release - 1.8.0
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#13262 Add macro `#warning` method
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:lang:macros

#13270 Crystal lexer cleanup
  src/compiler/crystal/syntax/lexer.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/token.cr
Labels: kind:refactor, topic:compiler:parser

#13280 Optimize `Array#concat(Indexable)`
  spec/std/array_spec.cr
  src/array.cr
  src/deque.cr
Labels: performance, topic:stdlib:collection

#13293 Handle NaNs when comparing `BigInt` against `Float`
  spec/std/big/big_int_spec.cr
  src/big/big_int.cr
Labels: kind:bug, breaking-change, topic:stdlib:numeric

#13294 Handle NaNs when comparing `BigFloat` against `Float`
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:bug, breaking-change, topic:stdlib:numeric

#13257 Refactor code for `Deque` buffer resizing
  src/deque.cr
Labels: kind:refactor, topic:stdlib:collection

#13310 Regenerate spec/interpreter_std_spec.cr
  spec/interpreter_std_spec.cr
Labels: kind:specs, topic:compiler:interpreter

#13319 Always use 0 for offset of `StaticArray`'s `@buffer`
  spec/compiler/codegen/offsetof_spec.cr
  spec/compiler/interpreter/pointers_spec.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler:codegen, topic:compiler:interpreter

#13321 Fix: Remove double URL escape in `HTTP::Server::Response.redirect`
  spec/std/http/server/response_spec.cr
  src/http/server/response.cr
Labels: kind:bug, topic:stdlib:networking

#13326 Implement Socket `reuse_port` (=`reuse_address`) on Windows
  spec/std/http/server/server_spec.cr
  spec/std/socket/tcp_server_spec.cr
  src/crystal/system/win32/socket.cr
  src/socket.cr
Labels: kind:feature, platform:windows, topic:stdlib:networking

#13331 Fix WebSocket capitalization in docs
  src/http/server/handlers/websocket_handler.cr
Labels: kind:bug, kind:docs, topic:stdlib:networking

#13333 Reorder and enhance specs for `String.new(&)`
  spec/std/string_spec.cr
Labels: kind:specs, topic:stdlib:text

#13255 Add `BigDecimal#%`
  spec/std/big/big_decimal_spec.cr
  src/big/big_decimal.cr
Labels: kind:feature, topic:stdlib:numeric

#13342 Fix `String#gsub` with empty match at multibyte char
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:text, kind:regression

#13349 Fix PCRE2 `Regex` with more than 127 named capture groups
  spec/std/regex/match_data_spec.cr
  spec/std/regex_spec.cr
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text

#13344 Fix `JSON::Serializable` on certain recursively defined types
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization, kind:regression

#13335 Refactor String header layout reflection
  src/string.cr
  src/string/builder.cr
Labels: kind:refactor, topic:stdlib:text

#13338 Fix size of type_id in `Object.set_crystal_type_id`
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:bug, topic:stdlib:runtime

#13324 Optimize `Doc::Method#compute_doc_info` to avoid duplicate regex
  src/compiler/crystal/tools/doc/method.cr
Labels: kind:refactor, topic:tools:docs-generator

#13346 Move more `Socket` methods to `Crystal::System::Socket`
  src/crystal/system/socket.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/wasi/socket.cr
  src/crystal/system/win32/socket.cr
  src/socket.cr
Labels: kind:refactor, topic:stdlib:networking

#13350 Handle NaNs when comparing `BigRational` against `Float`
  spec/std/big/big_rational_spec.cr
  src/big/big_rational.cr
Labels: kind:bug, breaking-change, topic:stdlib:numeric

#13355 Skip `Time::Location.load_local` spec if unable to change time zone
  spec/std/time/location_spec.cr
Labels: platform:windows, kind:specs, topic:stdlib:time

#13358 Refactor JSON, YAML specs for #13337 for simplicity
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
Labels: kind:refactor, kind:specs, topic:stdlib:serialization

#13364 Fix `TCPSocket#tcp_keepalive_idle` on Windows
  spec/std/socket/tcp_socket_spec.cr
  src/crystal/system/win32/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:networking

#13363 Fix client-side `TCPSocket#remote_address` on Windows
  spec/std/http/server/server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  src/crystal/system/win32/socket.cr
  src/lib_c/x86_64-windows-msvc/c/mswsock.cr
Labels: kind:bug, platform:windows, topic:stdlib:networking

#13332 Allow `/SUBSYSTEM:WINDOWS` on Windows
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime

#13303 Optimize `BigInt.new(Int::Primitive)`
  src/big/big_int.cr
  src/big/lib_gmp.cr
  src/int.cr
Labels: performance, topic:stdlib:numeric

#13365 Fix `IO::FileDescriptor`'s `STDIN` mode spec
  spec/std/io/file_descriptor_spec.cr
Labels: platform:windows, kind:specs, topic:stdlib:files

#13334 Build samples on Windows CI
  .github/workflows/win.yml
  samples/Makefile.win
Labels: kind:feature, topic:infrastructure, platform:windows

#13372 Fix `bin\crystal.ps1` writing to standard error stream
  bin/crystal.ps1
Labels: kind:bug, topic:infrastructure, platform:windows

#13254 Add message about non-release mode to `crystal --version`
  Makefile
  src/compiler/crystal/config.cr
Labels: kind:feature, topic:compiler

#13354 Add Regex options support inspection
  spec/std/regex_spec.cr
  src/regex.cr
  src/regex/pcre.cr
  src/regex/pcre2.cr
Labels: kind:feature, topic:stdlib:text

#13373 Update previous Crystal release - 1.8.1
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#13374 Implement `Process.exec` on Windows
  spec/std/process_spec.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
  src/process.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#13385 Fix doc for return type of `Crystal::Macros::Case#else`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:stdlib:macros

#13384 Document `target` variable in Makefiles
  Makefile
  Makefile.win
Labels: kind:feature, topic:infrastructure

#13383 Less verbose output in `Makefile.win`
  Makefile.win
Labels: topic:infrastructure, platform:windows

#13387 Fix `String#scan` with empty `Regex` match at multibyte char
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, kind:refactor, topic:stdlib:text

#13388 Fix `Array#flatten` to discard `Iterator::Stop`
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#13376 Respect `%CC%` on Windows
  spec/compiler/loader/spec_helper.cr
  spec/support/tempfile.cr
  src/compiler/crystal/compiler.cr
Labels: kind:feature, topic:compiler, platform:windows

#13393 Do not cancel in progress CI jobs for master branch
  .github/workflows/aarch64.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/macos.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/smoke.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
Labels: topic:infrastructure

#13260 More accurate macro errors
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/macros/interpreter.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/semantic/call.cr
  src/compiler/crystal/semantic/exception.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
Labels: kind:bug, topic:compiler

#13395 Fix `Dir#info` on Windows
  spec/std/dir_spec.cr
  src/crystal/system/win32/dir.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13369 Fix `Log::Metadata#dup` crash with 2+ entries
  spec/std/log/metadata_spec.cr
  src/log/metadata.cr
Labels: kind:bug, topic:stdlib:log

#13397 Windows: open standard streams in binary mode
  spec/std/io/file_descriptor_spec.cr
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13407 Parser: Don't skip the token immediately after `lib` name
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13362 Support asynchronous `IO.pipe` on Windows
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/http/spec_helper.cr
  spec/std/io/io_spec.cr
  spec/std/log/io_backend_spec.cr
  spec/std/oauth2/client_spec.cr
  spec/std/process_spec.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/socket.cr
  src/io/file_descriptor.cr
  src/io/overlapped.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/ioapiset.cr
  src/lib_c/x86_64-windows-msvc/c/minwinbase.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
  src/log/io_backend.cr
Labels: kind:feature, topic:stdlib:concurrency, platform:windows, topic:stdlib:files

#13408 Use correct format strings for crash stack traces
  src/exception/call_stack/libunwind.cr
  src/exception/call_stack/stackwalk.cr
Labels: kind:bug, kind:refactor, topic:stdlib:runtime

#13406 Check subject UTF8 validity just once for `String#gsub`, `#scan`, `#split`
  src/string.cr
Labels: performance, topic:stdlib:text
