Repository crystal-lang/crystal, pull requests merged in 2023-11, with the labels that each got.

#13920 Drop `Char::Reader#@end`
  spec/std/char/reader_spec.cr
  src/char/reader.cr
Labels: kind:refactor, topic:stdlib:text

#13823 Add `Crystal::HOST_TRIPLE` and `TARGET_TRIPLE`
  spec/compiler/config_spec.cr
  src/compiler/crystal/program.cr
Labels: kind:feature, topic:stdlib:runtime

#13930 Add `--check` flag to `crystal tool unreachable`
  src/compiler/crystal/command.cr
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:tools:unreachable

#13927 Add annotations to output of `crystal tool unreachable`
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:lang:annotations, topic:tools:unreachable

#13934 Add `Math.fma`
  spec/std/math_spec.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
  src/math/libm.cr
  src/math/math.cr
Labels: kind:feature, topic:stdlib:numeric

#13933 Support `%r` and `%x` when not followed by delimiter start
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#13932 Fix location of global `Path` nodes in certain constructs
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13844 Refactor `HTML.unescape` in native Crystal
  spec/std/html_spec.cr
  spec/wasm32_std_spec.cr
  src/html.cr
  src/html/entities.cr
Labels: performance, kind:refactor, topic:stdlib:text

#13936 Add `Number#integer?`
  spec/std/big/big_decimal_spec.cr
  spec/std/big/big_float_spec.cr
  spec/std/big/big_int_spec.cr
  spec/std/big/big_rational_spec.cr
  spec/std/float_spec.cr
  spec/std/int_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_rational.cr
  src/int.cr
  src/number.cr
Labels: kind:feature, topic:stdlib:numeric

#13937 Fix `crystal docs` check `File.exists?` for `shard.yml`
  src/compiler/crystal/tools/doc/project_info.cr
Labels: kind:feature, topic:tools:docs-generator

#13931 Fix private type definitions with namespaced `Path`s
  spec/compiler/semantic/private_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#13938 Publish `Int::Primitive#abs_unsigned` and `#neg_signed`
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:feature, topic:stdlib:numeric

#13915 Optimize `JSON::Builder#string` with byte-based algorithm
  src/json/builder.cr
Labels: performance, topic:stdlib:serialization

#13943 Fix `ToSVisitor` for expanded string interpolation in backticks
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:parser

#13944 Fix spec for `String#encode` and `String.new` on DragonFlyBSD
  spec/std/string_spec.cr
Labels: kind:specs, topic:stdlib:text, platform:bsd

#13922 Fix infinite recursion of expanded nodes in `UnreachableVisitor`
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:bug, topic:tools:unreachable

#13941 Refactor `UnreachablePresenter`
  spec/compiler/crystal/tools/unreachable_spec.cr
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:refactor, topic:tools:unreachable

#13929 Print relative paths in `crystal tool unreachable`
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:tools:unreachable

#13940 Generalize allowed values for compiler CLI `--format` option
  src/compiler/crystal/command.cr
  src/compiler/crystal/tools/dependencies.cr
Labels: kind:refactor, topic:compiler:cli

#13953 Replace some deprecated LLVM bindings
  src/llvm/context.cr
  src/llvm/lib_llvm.cr
  src/llvm/type.cr
  src/llvm/value_methods.cr
Labels: kind:refactor, topic:stdlib:llvm

#13949 Deprecate `LLVM.start_multithreaded` and `.stop_multithreaded`
  src/llvm.cr
Labels: topic:stdlib:llvm, deprecation

#13942 Fix portable shell command arguments in `Process#prepare_args`
  src/crystal/system/unix/process.cr
Labels: kind:bug, topic:stdlib:system, platform:bsd

#13950 Improve performance of `JSON::Builder#string` with direct stringification
  src/json/builder.cr
  src/json/to_json.cr
  src/uri/json.cr
  src/uuid/json.cr
Labels: performance, topic:stdlib:serialization

#13464 Add incremental optimization levels
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/macros/macros.cr
Labels: kind:feature, topic:compiler:codegen

#13939 Deprecate the splat operators in macro expressions
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/macros/interpreter.cr
  src/macros.cr
  src/object.cr
  src/regex.cr
  src/slice.cr
  src/static_array.cr
  src/syscall/aarch64-linux.cr
  src/syscall/arm-linux.cr
  src/syscall/i386-linux.cr
  src/syscall/x86_64-linux.cr
  src/xml/builder.cr
  src/yaml/builder.cr
Labels: topic:lang:macros, deprecation

#13948 Split `LibLLVM` by C headers
  src/llvm/generic_value.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm/analysis.cr
  src/llvm/lib_llvm/bit_writer.cr
  src/llvm/lib_llvm/core.cr
  src/llvm/lib_llvm/debug_info.cr
  src/llvm/lib_llvm/error.cr
  src/llvm/lib_llvm/execution_engine.cr
  src/llvm/lib_llvm/initialization.cr
  src/llvm/lib_llvm/ir_reader.cr
  src/llvm/lib_llvm/target.cr
  src/llvm/lib_llvm/target_machine.cr
  src/llvm/lib_llvm/transforms/pass_builder.cr
  src/llvm/lib_llvm/transforms/pass_manager_builder.cr
  src/llvm/lib_llvm/types.cr
  src/llvm/lib_llvm_ext.cr
Labels: kind:refactor, topic:stdlib:llvm

#13959 Check for invalid integers in compiler's CLI
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/playground.cr
Labels: kind:bug, topic:compiler:cli

#13814 Add `Crystal::System::Thread`
  src/crystal/system/thread.cr
  src/crystal/system/unix/pthread.cr
  src/crystal/system/wasi/thread.cr
  src/crystal/system/win32/thread.cr
  src/gc/boehm.cr
  src/gc/none.cr
Labels: kind:refactor, topic:multithreading

#13874 Use `LibGMP::SI` and `UI` for size checks, not `Long` and `ULong`
  spec/std/big/big_int_spec.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
  src/big/lib_gmp.cr
  src/big/number.cr
Labels: kind:bug, platform:windows, topic:stdlib:numeric

#13810 Expose inherited macros in generated API docs
  src/compiler/crystal/tools/doc/html/_macros_inherited.html
  src/compiler/crystal/tools/doc/html/type.html
  src/compiler/crystal/tools/doc/templates.cr
Labels: kind:bug, topic:tools:docs-generator

#13926 Add CSV output format to `crystal tool unreachable`
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:tools:unreachable

#11303 Add `EOL`constant (End-Of-Line)
  src/kernel.cr
Labels: kind:feature, topic:stdlib:text, platform

#13960 Add `Int::Primitive#to_signed`, `#to_signed!`, `#to_unsigned`, `#to_unsigned!`
  spec/std/int_spec.cr
  src/int.cr
Labels: kind:feature, topic:stdlib:numeric

#13962 Improve docs on initial/default values passed to `Array.new` and `Hash.new`
  src/array.cr
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#13966 Remove `LLVMExtCreateMCJITCompilerForModule` from `llvm_ext.cc`
  src/compiler/crystal/codegen/target.cr
  src/llvm/ext/llvm_ext.cc
  src/llvm/jit_compiler.cr
  src/llvm/lib_llvm/execution_engine.cr
  src/llvm/lib_llvm_ext.cr
Labels: kind:refactor, kind:specs, topic:compiler:codegen, topic:stdlib:llvm

#13967 Improve docs for `Iterator` step-by-step iteration
  src/iterator.cr
Labels: kind:docs, topic:stdlib:collection

#13971 Support `BigFloat#**` for all `Int::Primitive` arguments
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:feature, topic:stdlib:numeric

#13985 Fix missing param count in compilation error message
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/semantic/call_error.cr
Labels: kind:bug, topic:lang:macros

#13982 Refactor leap year to use `divisible_by?`
  src/time.cr
Labels: kind:refactor, topic:stdlib:time

#13994 Fix version sorting in API docs
  scripts/docs-versions.sh
Labels: kind:bug, topic:tools:docs-generator

#13990 Use `IO.copy` in `IO#gets_to_end`
  src/io.cr
Labels: kind:refactor, topic:stdlib:files

#13997 Windows: Do not close process handle in `Process#close`
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#13986 Fix skip spec execution on error exit
  src/spec/dsl.cr
Labels: kind:bug, topic:stdlib:specs

#13999 Make `scripts/*.cr` all executable
  scripts/generate_grapheme_break_specs.cr
  scripts/generate_grapheme_properties.cr
  scripts/generate_unicode_data.cr
  scripts/generate_windows_zone_names.cr
Labels: topic:infrastructure, kind:refactor

#14006 Optimize `BigInt#&`, `#|`, `#^` with `Int::Primitive` arguments
  src/big/big_int.cr
Labels: performance, topic:stdlib:numeric

#14008 Add note about `Char::Reader`'s value semantics
  src/char/reader.cr
Labels: kind:docs, topic:stdlib:text

#13998 Generate `src/html/entities.cr` automatically
  .gitattributes
  Makefile
  Makefile.win
  scripts/generate_html_entities.cr
  scripts/html_entities.ecr
  src/html/entities.cr
Labels: kind:refactor, topic:stdlib:text

#13992 Remove relative path to vendored shards `markd` and `reply`
  src/compiler/crystal/interpreter/repl_reader.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/playground/server.cr
Labels: topic:compiler, kind:refactor

#13961 Add `Float32::MIN_SUBNORMAL` and `Float64::MIN_SUBNORMAL`
  spec/std/float_printer_spec.cr
  spec/std/float_spec.cr
  src/float.cr
Labels: kind:feature, topic:stdlib:numeric

#13663 Reformat changelog release headings
  CHANGELOG.0.md
  CHANGELOG.md
Labels: topic:infrastructure, kind:refactor

#13964 Fix location for "invalid trailing comma in call" errors
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#13976 Allow to specify git fork of distribution-scripts in CI
  .circleci/config.yml
Labels: topic:infrastructure

#14013 Fix invalid UTF-8 handling in `Char::Reader#previous_char`
  spec/std/char/reader_spec.cr
  src/char/reader.cr
Labels: kind:bug, topic:stdlib:text

#14001 Refactor some uses of the blockless `String#split`
  src/crystal/system/unix/env.cr
  src/http/formdata.cr
  src/openssl/x509/name.cr
  src/process/executable_path.cr
  src/semantic_version.cr
  src/spec/context.cr
  src/spec/dsl.cr
Labels: topic:stdlib, performance, kind:refactor

#13955 Fix `Globber.constant_entry?` matching patterns
  spec/std/dir_spec.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/command/spec.cr
  src/dir/glob.cr
Labels: kind:bug, topic:stdlib:files

#13865 Add `IO::Error#target`
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/file/error.cr
  src/io/error.cr
  src/io/evented.cr
  src/io/overlapped.cr
Labels: kind:feature, topic:stdlib:files
