Repository crystal-lang/crystal, pull requests merged in 2023-07, with the labels that each got.

#13612 Fix `Iterator#with_index(offset)` with non-`Int32` `offset`
  spec/std/iterator_spec.cr
  src/iterator.cr
Labels: kind:bug, topic:stdlib:collection

#13578 Build Windows portable and installer packages on CI
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
  Makefile
  Makefile.win
  etc/win-ci/crystal.bmp
  etc/win-ci/crystal.iss
  etc/win-ci/crystal_small.bmp
Labels: kind:feature, topic:infrastructure, platform:windows

#13621 Add manual entry for `clear_cache` command
  man/crystal.1
Labels: kind:docs, topic:compiler

#13624 Hide `Crystal::LibEvent` from public docs
  src/crystal/system/unix/event_libevent.cr
Labels: kind:docs, topic:stdlib:concurrency

#13623 Restrict Windows CI jobs for installer packages to release branches
  .github/workflows/win.yml
Labels: topic:infrastructure, platform:windows

#13613 Add `crystal tool dependencies`
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/semantic_visitor.cr
  src/compiler/crystal/tools/dependencies.cr
Labels: kind:feature, topic:tools

#13625 Do not reopen current file in `File#utime` on Windows
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/time.cr
  src/crystal/system/win32/file.cr
  src/file.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#13626 Allow `Dir.delete` to remove read-only directories on Windows
  spec/std/dir_spec.cr
  src/crystal/system/win32/dir.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13628 Use current directory's root for `Dir.glob("/...")` on Windows
  spec/std/dir_spec.cr
  src/dir/glob.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13627 Do not reopen current file in `File#chmod` on Windows
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
  src/file.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/minwinbase.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#13618 Fix ambiguous call with untyped int literal in `{JSON,YAML}::Any.new`
  spec/std/json/any_spec.cr
  spec/std/yaml/any_spec.cr
  src/json/any.cr
  src/yaml/any.cr
Labels: kind:bug, topic:stdlib:serialization

#13645 Make DLL delay-load opt-in
  src/compiler/crystal/compiler.cr
Labels: kind:bug, platform:windows, topic:compiler:codegen, kind:regression

#13632 Add filter options
  src/compiler/crystal/command.cr
  src/compiler/crystal/tools/dependencies.cr
Labels: kind:feature, topic:tools:dependencies

#13656 Fix `Serializable` with converter parsing `null` value
  spec/std/json/serializable_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/json/serialization.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib:serialization, kind:regression

#13661 Fix generated cc command for cross compile
  src/compiler/crystal/compiler.cr
Labels: kind:bug, topic:compiler:codegen, kind:regression

#13682 Add changelog for 1.9.2
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#13650 Update previous Crystal release - 1.9.2
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#13611 Use `Set(T)` instead of `Hash(T, Bool)`
  src/array.cr
  src/iterator.cr
  src/reference.cr
Labels: kind:refactor, topic:stdlib:collection

#13614 Restrict some boolean properties to `Bool` in the compiler
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/exception.cr
  src/compiler/crystal/semantic/exception.cr
  src/compiler/crystal/syntax/exception.cr
  src/compiler/crystal/syntax/parser.cr
Labels: topic:compiler, kind:refactor

#13590 Add `Hash#put_if_absent`
  samples/havlak.cr
  spec/std/hash_spec.cr
  src/csv.cr
  src/hash.cr
  src/ini.cr
  src/mime.cr
  src/spec/cli.cr
  src/spec/source.cr
  src/uri/params.cr
Labels: kind:feature, topic:stdlib:collection

#13630 Add `Set#rehash`
  spec/std/set_spec.cr
  src/hash.cr
  src/set.cr
Labels: kind:feature, topic:stdlib:collection

#13635 Use `IO::DEFAULT_BUFFER_SIZE` in `Digest#update`
  src/digest/digest.cr
Labels: performance, topic:stdlib:crypto

#13608 Add yield `key` in `Hash#transform_values` and `value` in `#transform_keys`
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:feature, topic:stdlib:collection

#13640 Add `File#rename`
  spec/std/file_spec.cr
  src/file.cr
Labels: kind:feature, topic:stdlib:files

#13636 Add shell completions for `clear_cache`
  etc/completion.bash
  etc/completion.fish
  etc/completion.zsh
Labels: kind:feature, topic:infrastructure

#13649 Pre-allocate Dragonbox cache array
  src/float/printer/dragonbox_cache.cr
Labels: performance, topic:stdlib:numeric

#13658 Fix lookup scope for `@[Primitive]` def's return type
  spec/compiler/semantic/primitives_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#13662 New changelog format
  scripts/github-changelog.cr
Labels: kind:feature, topic:infrastructure

#13670 Fix octicon-link icon color on dark mode
  src/compiler/crystal/tools/doc/templates.cr
Labels: kind:bug, topic:tools:docs-generator

#13681 Detect developer mode in Windows installer
  etc/win-ci/crystal.iss
Labels: kind:feature, topic:infrastructure, platform:windows

#13683 [CI] Trigger windows release jobs on tag
  .github/workflows/win.yml
Labels: topic:infrastructure/ci

#13685 Upgrade SSL defaults to Mozilla guidelines version 5.7
  src/openssl/ssl/defaults.cr
Labels: kind:feature, topic:stdlib:crypto

#11242 Optimize `IO::Delimited`
  spec/std/io/delimited_spec.cr
  spec/std/io/io_spec.cr
  src/io.cr
  src/io/delimited.cr
Labels: topic:stdlib, performance

#11597 Add unlimited block unpacking
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/normalize/block_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  spec/compiler/semantic/block_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/normalizer.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:compiler, topic:lang

#13695 Allow OpenSSL clients to choose cipher
  spec/std/openssl/ssl/context_spec.cr
  src/openssl/ssl/context.cr
Labels: kind:feature, topic:stdlib:crypto, security

#13701 Use `Fiber.inactive` inside `Fiber#run`'s `ensure` block
  src/fiber.cr
Labels: topic:stdlib:concurrency, kind:refactor

#13667 Use `JSON::Serializable` in `scripts/generate_ssl_server_defaults.cr`
  scripts/generate_ssl_server_defaults.cr
  src/openssl/ssl/defaults.cr
Labels: topic:stdlib:crypto, kind:refactor

#13666 Support Android's system timezone database
  spec/std/data/android_tzdata
  spec/std/time/format_spec.cr
  spec/std/time/location_spec.cr
  spec/std/time/spec_helper.cr
  spec/std/time/time_spec.cr
  spec/support/time.cr
  src/crystal/system/unix/time.cr
  src/lib_c/aarch64-android/c/sys/system_properties.cr
  src/time/location.cr
  src/time/location/loader.cr
Labels: kind:feature, topic:stdlib:time, platform:android
