Repository crystal-lang/crystal, pull requests merged in 2023-01, with the labels that each got.

#12885 Add specs for `system` macro method
  spec/compiler/macro/macro_methods_spec.cr
Labels: topic:compiler:semantic, topic:lang:macros, kind:specs

#12889 Organize `Process` specs
  spec/std/process/utils_spec.cr
  spec/std/process_spec.cr
Labels: kind:refactor, kind:specs, topic:stdlib:system

#12876 Use `File#flock_exclusive` on win32 in compiler
  src/compiler/crystal/compiler.cr
Labels: kind:feature, platform:windows, topic:compiler:codegen

#12891 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#12881 Add tests for `Process::Status`
  spec/std/process/status_spec.cr
Labels: kind:specs, topic:stdlib:system

#12882 Refactor specs for `Enum#to_s` using `assert_prints`
  spec/std/enum_spec.cr
Labels: kind:specs, topic:stdlib:runtime

#12847 Build PCRE2 on Windows
  .github/workflows/win.yml
Labels: kind:feature, platform:windows, topic:stdlib:text

#12880 Fix Number comparison operator docs
  src/number.cr
Labels: kind:bug, kind:docs, topic:stdlib:numeric

#12888 Fix: Unwrap nested errors in error handler for `Crystal::Error`
  src/compiler/crystal/command.cr
Labels: kind:bug, topic:compiler

#12902 Rotate breached credentials in CircleCI
  .circleci/config.yml
Labels: topic:infrastructure

#12783 `IPAddress#loopback?` should consider `::ffff:127.0.0.1/104` loopback too
  spec/std/socket/address_spec.cr
  src/socket/address.cr
Labels: kind:feature, topic:stdlib:networking

#12916 Add docs for `ArrayLiteral#-`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:lang:macros

#12898 Split pre-1.0 changelog
  CHANGELOG.0.md
  CHANGELOG.md
Labels: topic:infrastructure

#12925 Update previous Crystal release - 1.7.0
  .circleci/config.yml
  .github/workflows/linux.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#12903 Allow namespaced `Path`s as type names for `lib`
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:feature, topic:compiler:parser

#12922 Fix `x @y` and `x @@y` in def parameters when `y` is reserved
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#12920 Fix: Interpreter `value_to_bool` for module, generic module and generic module metaclass
  spec/compiler/interpreter/primitives_spec.cr
  src/compiler/crystal/interpreter/to_bool.cr
Labels: kind:bug, topic:compiler:interpreter

#12910 Disallow empty exponents in number literals
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:bug, topic:compiler:parser

#11635 Format spec results with pretty inspect
  src/spec/expectations.cr
Labels: kind:feature, topic:stdlib:specs

#12931 [CI] Remove `verbose=1` in `test_llvm`
  .github/workflows/linux.yml
Labels: topic:infrastructure

#12941 Fix `Process` spec to wait on started processes
  spec/std/process_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:system

#12930 Add `Tuple#to_static_array`
  spec/std/tuple_spec.cr
  src/tuple.cr
Labels: kind:feature, topic:stdlib:collection

#12827 Fix: Make sure to dup `Array` in `Channel.select_impl`
  spec/std/channel_spec.cr
  src/channel.cr
Labels: kind:bug, topic:stdlib:concurrency

#12940 Deprecate `Termios`
  src/crystal/system/unix/file_descriptor.cr
  src/termios.cr
Labels: kind:refactor, breaking-change, topic:stdlib:files

#12945 Stricter checks for enum definitions
  spec/compiler/semantic/enum_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/types.cr
Labels: kind:bug, kind:refactor, topic:compiler:semantic

#12950 Update `VERSION` to 1.7.1-dev
  src/VERSION
Labels: topic:infrastructure

#12948 Fix baked-in path in playground to resolve at runtime
  src/compiler/crystal/tools/playground/server.cr
Labels: kind:bug, topic:tools:playground, kind:regression

#12962 Fix: Remove `focus: true`
  spec/std/channel_spec.cr
Labels: kind:bug, kind:specs

#12623 Support typed LLVM `getelementptr` instructions
  samples/llvm/brainfuck.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/cast.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/codegen/unions.cr
  src/llvm/builder.cr
  src/llvm/lib_llvm.cr
Labels: kind:feature, topic:compiler:codegen, topic:stdlib:llvm

#12955 Missing quotes in Wrapper Script
  bin/crystal
Labels: topic:infrastructure

#12952 Macro interpolation: add `&` to yielding `Def`s without a block parameter
  spec/compiler/normalize/def_spec.cr
  spec/compiler/parser/to_s_spec.cr
  spec/compiler/semantic/restrictions_augmenter_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#12958 Added so char can be converted to int128
  spec/std/char_spec.cr
  src/char.cr
Labels: kind:bug, topic:stdlib:numeric

#12929 Escape filenames when running `crystal spec` with multiple files
  src/compiler/crystal/command/spec.cr
Labels: kind:bug, topic:compiler, topic:stdlib:specs

#12927 Fill docs for `TupleLiteral`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:lang:macros

#12906 Drop support for LLVM < 8
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/intrinsics.cr
  src/llvm.cr
  src/llvm/basic_block.cr
  src/llvm/builder.cr
  src/llvm/context.cr
  src/llvm/ext/llvm-versions.txt
  src/llvm/ext/llvm_ext.cc
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm_ext.cr
  src/llvm/module.cr
  src/llvm/target_machine.cr
  src/llvm/type.cr
Labels: kind:refactor, breaking-change, topic:stdlib:llvm

#12932 Spec: Add `--color` option to spec runner
  spec/std/spec_spec.cr
  src/spec/cli.cr
  src/spec/context.cr
  src/spec/dsl.cr
Labels: kind:feature, kind:refactor, topic:stdlib:specs

#12934 Internalize `Process.fork`
  src/compiler/crystal/compiler.cr
  src/crystal/system/process.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/wasi/process.cr
  src/crystal/system/win32/process.cr
  src/process.cr
Labels: kind:refactor, topic:stdlib:system

#12977 Revert "Parser: Fix restrict grammar for name and supertype in type def (#12622)"
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, kind:regression

#12961 Fix socket specs when network not available
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:networking

#12979 Makefile: refactor test recipe
  Makefile
  Makefile.win
  spec/spec_helper.cr
Labels: kind:feature, topic:infrastructure

#12984 Clean up `back\slash.txt` in `HTTP::StaticFileHandler` specs
  spec/std/http/server/handlers/static_file_handler_spec.cr
Labels: kind:specs, topic:stdlib:networking

#12981 Fix `bin/crystal` print no error message when `crystal` is missing
  bin/crystal
Labels: kind:bug, topic:infrastructure

#12993 Update `VERSION` to `1.7.2-dev`
  src/VERSION
Labels: topic:infrastructure

#12992 Fix: Add `Nil` return type restrictions to `load_debug_info`
  src/exception/call_stack/dwarf.cr
  src/exception/call_stack/elf.cr
  src/exception/call_stack/mach_o.cr
  src/exception/call_stack/stackwalk.cr
Labels: kind:bug, topic:stdlib:runtime, kind:regression

#12899 Add error handling to compiler when linker is unavailable
  src/compiler/crystal/compiler.cr
Labels: kind:feature, topic:compiler:codegen

#12995 Add changelog for 1.7.2
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#12987 Skip hostname spec if `hostname` command fails
  spec/std/system_spec.cr
Labels: kind:bug, kind:specs, topic:stdlib:system

#12893 Fix error handling in macro system method when execution fails
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:compiler:semantic, topic:lang:macros

#12994 Formatter: fix end indent after comment inside begin
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#12960 Avoid `Array` allocation in `Channel.select(Tuple)`
  src/channel.cr
Labels: kind:feature, performance, topic:stdlib:concurrency

#12996 Fix redundant cast in interpreter
  spec/compiler/interpreter/primitives_spec.cr
  spec/compiler/interpreter/procs_spec.cr
  spec/compiler/interpreter/tuple_spec.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:compiler:interpreter

#12900 Add `Enum.[]` convenience constructor
  spec/std/enum_spec.cr
  src/enum.cr
Labels: kind:feature, breaking-change, topic:stdlib:collection

#12890 Add `MIME::Multipart.parse(HTTP::Client::Response, &)`
  spec/std/mime/multipart_spec.cr
  src/mime/multipart.cr
Labels: kind:feature, topic:stdlib:networking

#11712 Prevent infinitely recursive wrapper script
  bin/crystal
Labels: kind:bug, topic:infrastructure

#13001 Update previous Crystal release - 1.7.2
  .circleci/config.yml
  .github/workflows/linux.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#13014 Define equality for `Process::Status` and `OAuth::RequestToken`
  spec/std/oauth/request_token_spec.cr
  spec/std/process/status_spec.cr
  src/oauth/request_token.cr
  src/process/status.cr
Labels: kind:feature, topic:stdlib:networking, topic:stdlib:system

#13025 Compiler: type declaration with initial value gets the value's type
  spec/compiler/codegen/var_spec.cr
  spec/compiler/interpreter/primitives_spec.cr
  spec/compiler/semantic/var_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:interpreter

#13027 Replace `LibC.ntohs` and `htons` with native code
  spec/std/socket/address_spec.cr
  src/socket/address.cr
Labels: kind:refactor, topic:stdlib:networking

#13011 Changelog helper: Report error from HTTP request
  scripts/github-changelog.cr
Labels: kind:bug, topic:infrastructure
