Repository crystal-lang/crystal, pull requests merged in 2023-10, with the labels that each got.

#13850 Fix typo in unistd.cr
  src/lib_c/aarch64-android/c/unistd.cr
Labels: kind:bug, topic:stdlib:system, platform:aarch64, platform:android

#13782 Support LLVM 17
  .github/workflows/llvm.yml
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
  src/llvm/ext/llvm-versions.txt
Labels: kind:feature, topic:stdlib:llvm

#13863 Change `IO::Buffered#peek`'s return type to `Bytes`
  src/io/buffered.cr
Labels: kind:bug, topic:stdlib:files, kind:regression

#13864 Add changelog for 1.10.0
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#13876 Fix `win.yml`
  .github/workflows/win.yml
Labels: kind:bug, platform:windows, topic:infrastructure/ci

#13882 `IO#gets` should have same result regardless of #peek availability
  spec/std/io/io_spec.cr
  src/io.cr
Labels: kind:bug, topic:stdlib, kind:regression

#13886 Add changelog for 1.10.1
  CHANGELOG.md
  src/VERSION
Labels: topic:infrastructure

#13878 Update previous Crystal release - 1.10.0
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  shell.nix
  src/VERSION
Labels: topic:infrastructure

#13841 Use `Char#to_i?` in lexer
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:refactor, topic:compiler:parser

#13853 Remove unnecessary file check for CLI arguments
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler

#13869 Fix tool init error message when target exists but not a dir
  src/compiler/crystal/tools/init.cr
Labels: kind:bug, topic:tools:init

#13871 Implement `BigRational`'s rounding modes
  spec/std/big/big_rational_spec.cr
  src/big/big_rational.cr
Labels: kind:feature, topic:stdlib:numeric

#13866 Add `Enumerable#present?`
  spec/std/enumerable_spec.cr
  src/enumerable.cr
Labels: kind:feature, topic:stdlib:collection

#13804 Add "--dry-run" flag for specs
  src/spec/cli.cr
  src/spec/example.cr
Labels: kind:feature, topic:stdlib:specs

#13842 Refactor specs for `HTML.unescape`
  spec/std/html_spec.cr
Labels: kind:specs, topic:stdlib:text

#13760 Fix check for file type
  spec/compiler/crystal_path/crystal_path_spec.cr
  spec/compiler/crystal_path/foo.cr/foo.cr
  src/compiler/crystal/crystal_path.cr
Labels: kind:bug, topic:compiler

#13812 Support Unicode 15.1.0
  scripts/generate_grapheme_break_specs.cr
  spec/std/string/grapheme_break_spec.cr
  src/string/grapheme/properties.cr
  src/unicode/data.cr
  src/unicode/unicode.cr
Labels: kind:feature, topic:stdlib:text

#13896 Fix `FileUtils.ln_sf` to override special file types
  spec/std/file_utils_spec.cr
  src/file_utils.cr
Labels: kind:bug, topic:stdlib:system

#13693 Add `UUID.v1`, `.v2`, `.v3`, `.v4`, `.v5`
  .github/workflows/wasm32.yml
  spec/std/uuid_spec.cr
  src/uuid.cr
Labels: kind:feature, topic:stdlib:text

#13898 Fix documentation of `Hash#put_if_absent`
  src/hash.cr
Labels: kind:bug, kind:docs, topic:stdlib:collection

#13900 Use `CMAKE_MSVC_RUNTIME_LIBRARY` flag in win.yml
  .github/workflows/win.yml
Labels: kind:refactor, platform:windows, topic:infrastructure/ci

#13910 Add `CharLiteral#ord`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#13902 Add macro methods for `MacroIf` and `MacroFor` nodes
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/macros/types.cr
Labels: kind:feature, topic:lang:macros

#13908 Make `Process#wait` asynchronous on Windows
  Makefile.win
  src/crystal/system/win32/process.cr
  src/io/overlapped.cr
  src/lib_c/x86_64-windows-msvc/c/jobapi2.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:bug, topic:stdlib:concurrency, platform:windows, topic:stdlib:system

#13912 Respect Windows `Path` directory separators in `File.match?`
  spec/std/file_spec.cr
  src/file.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#13881 Support full exponent range in `BigFloat#**(BigInt)`
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
  src/big/lib_gmp.cr
Labels: kind:feature, topic:stdlib:numeric

#13806 Add `String` and `Char` patterns to `StringScanner`
  spec/std/string_scanner_spec.cr
  src/string_scanner.cr
Labels: kind:feature, topic:stdlib:text

#13911 Fix `Process.exists?` throwing errors on EPERM
  src/crystal/system/unix/process.cr
Labels: kind:bug, topic:stdlib:system, platform:unix
