Repository crystal-lang/crystal, pull requests merged in 2024-09, with the labels that each got.

#14502 Optimize `Hash#transform_{keys,values}`
  src/hash.cr
Labels: performance, kind:refactor, topic:stdlib:collection

#14946 Add specs for `String#index`, `#rindex` search for `Char::REPLACEMENT`
  spec/std/string_spec.cr
Labels: kind:specs, topic:stdlib:text

#14951 Allow `^` in constant numeric expressions
  spec/compiler/codegen/c_enum_spec.cr
  src/compiler/crystal/semantic/math_interpreter.cr
Labels: kind:feature, topic:lang, topic:stdlib:numeric

#14958 Support non-blocking `File#read_at` on Windows
  spec/std/file_spec.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
  src/file/preader.cr
Labels: kind:feature, topic:stdlib:concurrency, platform:windows, topic:stdlib:files

#14950 Update REPLy version
  lib/.shards.info
  lib/reply/shard.yml
  lib/reply/spec/reader_spec.cr
  lib/reply/spec/spec_helper.cr
  lib/reply/src/char_reader.cr
  lib/reply/src/reader.cr
  lib/reply/src/term_size.cr
  shard.lock
  shard.yml
Labels: kind:chore, topic:compiler:interpreter:repl

#14956 Simplify `Socket::Addrinfo.getaddrinfo(&)`
  src/socket/addrinfo.cr
Labels: kind:refactor, topic:stdlib:networking

#14941 Support non-blocking `Process.run` standard streams on Windows
  spec/std/process_spec.cr
  src/process.cr
Labels: kind:feature, topic:stdlib:concurrency, platform:windows, topic:stdlib:system

#14961 Use correct timeout for `Socket#connect` on Windows
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:networking

#14855 Make `IO::Buffered#buffer_size=` idempotent
  spec/std/io/buffered_spec.cr
  src/io/buffered.cr
Labels: kind:bug, topic:stdlib:files

#14947 Emulate non-blocking `STDIN` console on Windows
  src/crystal/system/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
  src/crystal/system/win32/process.cr
  src/io/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/ioapiset.cr
Labels: kind:feature, topic:stdlib:concurrency, platform:windows, topic:stdlib:system

#14962 Deprecate `::sleep(Number)`
  samples/channel_select.cr
  samples/conway.cr
  samples/tcp_client.cr
  spec/std/benchmark_spec.cr
  spec/std/channel_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/http/spec_helper.cr
  spec/std/openssl/ssl/server_spec.cr
  spec/std/signal_spec.cr
  spec/support/channel.cr
  spec/support/retry.cr
  src/benchmark.cr
  src/concurrent.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/signal.cr
Labels: topic:stdlib, deprecation

#14945 Implement `System::Group` on Windows
  spec/std/system/group_spec.cr
  src/crystal/system/group.cr
  src/crystal/system/win32/group.cr
  src/crystal/system/win32/user.cr
  src/crystal/system/windows.cr
  src/docs_main.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#14968 Implement `Reference.pre_initialize` in the interpreter
  spec/primitives/reference_spec.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:feature, topic:stdlib, topic:compiler:interpreter

#14957 Add `Crystal::System::Addrinfo`
  src/crystal/system/addrinfo.cr
  src/crystal/system/unix/addrinfo.cr
  src/crystal/system/wasi/addrinfo.cr
  src/crystal/system/win32/addrinfo.cr
  src/socket/addrinfo.cr
Labels: kind:refactor, topic:stdlib:networking

#14588 Fix `Range#size` return type to `Int32`
  src/range.cr
Labels: kind:bug, topic:stdlib:collection

#14970 Fix CRT static-dynamic linking conflict in specs with C sources
  spec/support/tempfile.cr
Labels: kind:bug, platform:windows, topic:compiler:codegen

#14965 Fix use global paths in macro bodies
  src/crystal/pointer_linked_list.cr
  src/ecr/macros.cr
  src/intrinsics.cr
  src/json/serialization.cr
  src/number.cr
  src/object.cr
  src/slice.cr
  src/spec/dsl.cr
  src/spec/helpers/iterate.cr
  src/static_array.cr
  src/syscall/aarch64-linux.cr
  src/syscall/arm-linux.cr
  src/syscall/i386-linux.cr
  src/syscall/x86_64-linux.cr
  src/uri/params/serializable.cr
  src/yaml/serialization.cr
Labels: kind:bug, topic:stdlib, kind:regression

#14971 Fix exponent wrapping in `Math.frexp(BigFloat)` for very large values
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:bug, topic:stdlib:numeric

#14972 Fix: `Crystal::SpinLock` doesn't need to be allocated on the HEAP
  src/crystal/spin_lock.cr
Labels: kind:refactor, topic:stdlib:system

#14973 Fix: `#file_descriptor_close` should set `@closed` (UNIX)
  src/crystal/system/unix/file_descriptor.cr
Labels: kind:bug, topic:stdlib:system

#14953 Adds initial support for external commands
  spec/primitives/external_command_spec.cr
  src/compiler/crystal/command.cr
Labels: kind:feature, topic:compiler:cli

#14974 Don't involve evloop after fork in System::Process.spawn (UNIX)
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/process.cr
Labels: kind:refactor, topic:stdlib:system

#14964 Enable the interpreter on Windows
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
  spec/std/http/client/client_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/http/web_socket_spec.cr
  spec/std/io/io_spec.cr
  spec/std/oauth2/client_spec.cr
  spec/std/openssl/ssl/server_spec.cr
  spec/std/openssl/ssl/socket_spec.cr
  spec/std/process_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/unix_server_spec.cr
  spec/std/socket/unix_socket_spec.cr
  spec/std/uuid_spec.cr
  src/compiler/crystal/loader/msvc.cr
  src/kernel.cr
Labels: kind:feature, platform:windows, topic:compiler:interpreter

#14977 Add methods to Crystal::EventLoop
  src/crystal/scheduler.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/event_loop/file_descriptor.cr
  src/crystal/system/event_loop/socket.cr
  src/crystal/system/file_descriptor.cr
  src/crystal/system/socket.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/wasi/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/io/file_descriptor.cr
  src/socket.cr
Labels: kind:feature, topic:stdlib:system

#14987 Make `Crystal::IOCP::OverlappedOperation` abstract
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
  src/crystal/system/win32/socket.cr
Labels: topic:stdlib:concurrency, kind:refactor, platform:windows

#14980 Refactor `EventLoop` interface for sleeps & select timeouts
  src/channel/select/timeout_action.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/unix/event_libevent.cr
  src/crystal/system/wasi/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/fiber.cr
Labels: kind:refactor, topic:stdlib:system

#14963 Remove some uses of deprecated overloads in standard library specs
  spec/compiler/semantic/warnings_spec.cr
  spec/std/benchmark_spec.cr
  spec/std/dir_spec.cr
  spec/std/file_spec.cr
  spec/std/http/client/client_spec.cr
  spec/std/http/server/server_spec.cr
  spec/std/io/io_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/unix_socket_spec.cr
Labels: topic:stdlib, kind:refactor, kind:specs

#14982 Fix exponent overflow in `BigFloat#to_s` for very large values
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:bug, topic:stdlib:numeric

#14981 Add type restriction to `String#byte_index` `offset` parameter
  src/string.cr
Labels: kind:bug, topic:stdlib:text

#11007 Implement floating-point manipulation functions for `BigFloat`
  spec/std/big/big_float_spec.cr
  src/big/big_float.cr
Labels: kind:feature, topic:stdlib:numeric

#14988 Remove TODO in `Crystal::Loader` on Windows
  src/compiler/crystal/loader/msvc.cr
Labels: platform:windows, kind:chore

#14979 Async DNS resolution on Windows
  spec/std/socket/addrinfo_spec.cr
  src/crystal/system/addrinfo.cr
  src/crystal/system/win32/addrinfo.cr
  src/crystal/system/win32/addrinfo_win7.cr
  src/crystal/system/win32/iocp.cr
  src/http/client.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
  src/lib_c/x86_64-windows-msvc/c/ws2def.cr
  src/lib_c/x86_64-windows-msvc/c/ws2tcpip.cr
  src/socket/addrinfo.cr
  src/socket/tcp_socket.cr
  src/winerror.cr
Labels: kind:feature, topic:stdlib:concurrency, platform:windows, topic:stdlib:networking

#14932 Add error handling for linker flag sub commands
  src/compiler/crystal/compiler.cr
Labels: kind:bug, topic:compiler:cli

#15002 Avoid unwinding the stack on hot path in method call lookups
  src/compiler/crystal/semantic/call.cr
Labels: topic:compiler

#15000 Drop the non-release Windows compiler artifact
  .github/workflows/win.yml
Labels: kind:refactor, platform:windows, topic:infrastructure/ci

#14986 Fix `Process.exec` stream redirection on Windows
  spec/std/process_spec.cr
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: kind:bug, platform:windows, topic:stdlib:system, kind:regression

#14999 Use Cygwin to build libiconv on Windows CI
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
  etc/win-ci/build-iconv.ps1
  etc/win-ci/cygwin-build-iconv.sh
  src/crystal/lib_iconv.cr
Labels: kind:refactor, platform:windows, topic:stdlib:text, topic:infrastructure/ci

#15007 Enable runners from `runs-on.com` for Aarch64 CI
  .github/workflows/aarch64.yml
Labels: topic:infrastructure/ci

#14991 Changelog for 1.13.3
  CHANGELOG.md
  shard.yml
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#14936 Remove `XML::Error.errors`
  spec/std/xml/reader_spec.cr
  src/xml/error.cr
  src/xml/reader.cr
Labels: kind:bug, breaking-change, topic:stdlib:serialization

#14998 Use our own `libffi` repository on Windows CI
  .github/workflows/win.yml
  etc/win-ci/build-ffi.ps1
Labels: kind:refactor, platform:windows, topic:infrastructure/ci

#14997 Support Unicode 16.0.0
  spec/std/string/grapheme_break_spec.cr
  src/string/grapheme/properties.cr
  src/unicode/data.cr
  src/unicode/unicode.cr
Labels: kind:feature, topic:stdlib:text

#15003 Add missing `@[Link(dll:)]` annotation to MPIR
  src/big/lib_gmp.cr
Labels: kind:bug, platform:windows, topic:stdlib:numeric

#15016 Update previous Crystal release 1.13.3
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#15021 Fix compiler artifact name in WindowsCI
  .github/workflows/win.yml
  .github/workflows/win_build_portable.yml
Labels: topic:infrastructure/ci

#14992 Reduce calls to `Crystal::Type#remove_indirection` in module dispatch
  src/compiler/crystal/codegen/call.cr
Labels: performance, topic:compiler:codegen

#14748 Compiler: enable parallel codegen with MT
  src/compiler/crystal/compiler.cr
  src/llvm/lib_llvm/bit_reader.cr
  src/llvm/module.cr
Labels: performance, topic:multithreading, topic:compiler:codegen

#15017 Add `Exception::CallStack.empty`
  src/compiler/crystal/semantic/call.cr
  src/exception/call_stack.cr
Labels: kind:refactor, topic:stdlib:runtime

#15025 Cache `Exception::CallStack.empty` to avoid repeat `Array` allocation
  src/exception/call_stack.cr
Labels: performance, topic:stdlib:runtime, kind:regression

#15027 Add documentation about synchronous DNS resolution
  src/socket/addrinfo.cr
Labels: kind:docs, topic:stdlib:networking

#15009 Fix `Slice.literal` for multiple calls with identical signature
  spec/primitives/slice_spec.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:lang

#15030 Restrict CI runners from runs-on to 8GB
  .github/workflows/aarch64.yml
Labels: topic:infrastructure/ci

#15032 Update `DeallocationStack` for Windows context switch
  src/fiber/context/x86_64-microsoft.cr
Labels: kind:bug, topic:stdlib:concurrency, platform:windows

#15036 Add missing return type of `LibC.VirtualQuery`
  src/crystal/system/win32/thread.cr
  src/lib_c/x86_64-windows-msvc/c/memoryapi.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime

#15035 Fix Linux `getrandom` failure in interpreted code
  src/crystal/system/unix/getrandom.cr
Labels: kind:bug, topic:stdlib:system, platform:linux-musl, platform:linux-gnu, topic:compiler:interpreter

#15044 Increase memory for stdlib CI runners from runs-on to 16GB
  .github/workflows/aarch64.yml
Labels: topic:infrastructure/ci

#15042 Fix undefined behavior in interpreter mixed union upcast
  spec/compiler/interpreter/unions_spec.cr
  src/compiler/crystal/interpreter/instructions.cr
Labels: kind:bug, topic:compiler:interpreter

#14842 Support LLVM 19.1
  .github/workflows/llvm.yml
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/codegen/debug.cr
  src/intrinsics.cr
  src/llvm/context.cr
  src/llvm/di_builder.cr
  src/llvm/ext/llvm-versions.txt
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm/core.cr
  src/llvm/lib_llvm/debug_info.cr
  src/llvm/lib_llvm/types.cr
Labels: kind:feature, topic:stdlib:llvm

#15043 Fix race condition in `pthread_create` handle initialization
  spec/std/thread/condition_variable_spec.cr
  spec/std/thread/mutex_spec.cr
  spec/std/thread_spec.cr
  src/crystal/system/unix/pthread.cr
Labels: kind:bug, topic:multithreading, platform:unix

#15047 Fix main stack top detection on musl-libc
  spec/std/kernel_spec.cr
  src/crystal/system/unix/pthread.cr
  src/lib_c/aarch64-linux-musl/c/sys/resource.cr
  src/lib_c/i386-linux-musl/c/sys/resource.cr
  src/lib_c/x86_64-linux-musl/c/sys/resource.cr
Labels: kind:bug, topic:stdlib:runtime, platform:linux-musl
