Repository crystal-lang/crystal, pull requests merged in 2024-02, with the labels that each got.

#14279 Respect alignments above `alignof(Void*)` inside union values
  spec/compiler/codegen/cast_spec.cr
  spec/compiler/codegen/sizeof_spec.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/unions.cr
Labels: kind:bug, breaking-change, topic:compiler:codegen

#14278 Fix format for `asm` with comments
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#14239 fix: `build --no-codegen` output file name error
  src/compiler/crystal/command.cr
Labels: kind:bug, topic:compiler:cli

#14161 Allow calling `#[]=` with a block using method syntax
  spec/compiler/formatter/formatter_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:compiler:parser

#14243 Drop pinning Dwarf version 2 for android
  src/compiler/crystal/codegen/debug.cr
Labels: topic:compiler:codegen, kind:chore

#14274 [CI] Upgrade `resource_class` for `test_preview_mt`
  .circleci/config.yml
Labels: topic:infrastructure/ci

#14277 Support LLVM 18.1
  .github/workflows/win.yml
  etc/win-ci/build-llvm.ps1
  src/llvm/ext/llvm-versions.txt
  src/llvm/lib_llvm.cr
Labels: kind:feature, platform:windows, topic:stdlib:llvm, topic:infrastructure/ci

#14275 [CI] Upgrade from old machine images approaching EOL
  .circleci/config.yml
Labels: topic:infrastructure/ci

#14282 Relax `delegate`'s setter detection
  spec/std/object_spec.cr
  src/object.cr
Labels: kind:feature, topic:stdlib:macros

#14289 Fix stack corruption in union-to-union casts
  spec/compiler/codegen/cast_spec.cr
  src/compiler/crystal/codegen/unions.cr
Labels: kind:bug, topic:compiler:codegen

#14287 Fix: don't run thread specs with the interpreter
  spec/interpreter_std_spec.cr
Labels: kind:specs, topic:compiler:interpreter

#14291 Mention RFC process in contribution instructions
  .github/ISSUE_TEMPLATE/feature-request.md
  CONTRIBUTING.md
Labels: topic:infrastructure

#14290 Drop Nikola sponsor mention from Readme
  README.md
Labels: topic:infrastructure

#14272 Add memory barrier to `Mutex#unlock` on aarch64
  src/mutex.cr
Labels: kind:bug, topic:stdlib:concurrency, topic:multithreading, platform:aarch64

#14230 Enhance changelog script to pull milestone info from GitHub
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14292 Respect `--static` on Windows
  .github/workflows/win_build_portable.yml
  Makefile.win
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/interpreter/context.cr
  src/crystal/system/win32/wmain.cr
  src/empty.cr
  src/lib_c.cr
  src/llvm/lib_llvm.cr
  src/raise.cr
Labels: kind:feature, topic:infrastructure, platform:windows, topic:compiler:cli

#14304 Add `Crystal::Hasher.reduce_num` and `#number`
  spec/std/crystal/hasher_spec.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
  src/crystal/hasher.cr
  src/float.cr
  src/int.cr
  src/number.cr
Labels: kind:refactor, topic:stdlib:numeric

#14299 Change some line endings from CRLF to LF
  .gitattributes
  .github/workflows/win_build_portable.yml
  spec/compiler/data/visibility.h
Labels: kind:chore

#14302 Fix spelling in `spec/std/uri/params_spec.cr`
  spec/std/uri/params_spec.cr
Labels: kind:bug, kind:specs

#14306 Add `BigRational#%`, `#tdiv`, `#remainder`
  spec/std/big/big_rational_spec.cr
  src/big/big_rational.cr
Labels: kind:feature, topic:stdlib:numeric

#14309 Make equality between `Complex` and other numbers exact
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:bug, topic:stdlib:numeric

#14313 Add MSVC invalid parameter handler
  src/exception/call_stack/stackwalk.cr
  src/lib_c/x86_64-windows-msvc/c/stdint.cr
  src/lib_c/x86_64-windows-msvc/c/stdlib.cr
Labels: kind:feature, platform:windows, topic:stdlib:runtime

#14315 Don't copy DLL to output directory if file already exists
  src/compiler/crystal/compiler.cr
Labels: kind:bug, platform:windows, topic:compiler:codegen

#14316 Replace some Microsoft C runtime funs with Win32 equivalents
  spec/std/dir_spec.cr
  src/crystal/system/print_error.cr
  src/crystal/system/win32/dir.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/direct.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
  src/lib_c/x86_64-windows-msvc/c/stdio.cr
  src/lib_c/x86_64-windows-msvc/c/stdlib.cr
  src/lib_c/x86_64-windows-msvc/c/sys/stat.cr
  src/lib_c/x86_64-windows-msvc/c/sys/utime.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#14308 Fix `#hash` for the `Big*` number types
  spec/std/big/big_rational_spec.cr
  spec/std/crystal/hasher_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/big/big_int.cr
  src/big/big_rational.cr
  src/big/lib_gmp.cr
  src/int.cr
Labels: kind:bug, topic:stdlib:numeric, topic:stdlib:collection

#14320 Make `FileUtils.mv` work across filesystems on Windows
  src/file_utils.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#13694 Add `Process.on_terminate`
  spec/std/process/status_spec.cr
  spec/std/process_spec.cr
  src/compiler/crystal/command.cr
  src/crystal/system/process.cr
  src/crystal/system/unix/process.cr
  src/crystal/system/wasi/process.cr
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/consoleapi.cr
  src/process.cr
  src/process/status.cr
  src/signal.cr
  src/spec.cr
Labels: kind:feature, topic:stdlib:system

#14324 Fix System V ABI for packed structs with misaligned fields
  spec/std/llvm/x86_64_abi_spec.cr
  src/llvm/abi/x86_64.cr
Labels: kind:bug, platform:unix, platform:x86, topic:stdlib:llvm

#14323 Fix `Proc#call` that takes and returns large extern structs by value
  spec/compiler/codegen/extern_spec.cr
  spec/std/llvm/aarch64_spec.cr
  spec/std/llvm/x86_64_abi_spec.cr
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/fun.cr
  src/llvm/abi/x86_win64.cr
Labels: kind:bug, platform:windows, platform:aarch64, topic:compiler:codegen, platform:x86

#14327 Do not allocate memory in the segmentation fault signal handler
  src/crystal/system/unix/signal.cr
  src/exception/call_stack/libunwind.cr
Labels: kind:bug, topic:stdlib:runtime, platform:unix

#14330 Fix macro `Crystal::LIBRARY_PATH.split` when cross-compiling
  src/crystal/system/win32/process.cr
  src/llvm/lib_llvm.cr
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
Labels: kind:bug, platform:windows

#14328 Install system dependencies in the Windows GUI installer
  etc/win-ci/crystal.iss
Labels: kind:feature, topic:infrastructure, platform:windows

#14329 Update copyright year in NOTICE.md
  NOTICE.md
Labels: kind:chore
