Repository crystal-lang/crystal, pull requests merged in 2024-10, with the labels that each got.

#15054 Fix copy-paste-typo in spec describe
  spec/compiler/crystal/tools/doc/type_spec.cr
Labels: topic:tools:docs-generator, kind:specs

#15064 Revert "Add nodoc filter to doc type methods (#14910)"
  spec/compiler/crystal/tools/doc/type_spec.cr
  src/compiler/crystal/tools/doc/type.cr
Labels: topic:tools:docs-generator, status:reverted, kind:chore

#15065 Fix `crystal tool unreachable` & co visiting circular hierarchies
  spec/compiler/crystal/tools/unreachable_spec.cr
  src/compiler/crystal/tools/typed_def_processor.cr
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:bug, topic:tools:unreachable

#15067 Fix `TopLevelVisitor` adding existing `ClassDef` type to current scope
  spec/compiler/semantic/alias_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#15069 Add `uri/json` to `docs_main`
  src/docs_main.cr
Labels: kind:docs, topic:stdlib:networking

#14969 Changelog for 1.14.0
  CHANGELOG.md
  shard.yml
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15071 Update previous Crystal release 1.14.0
  .circleci/config.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  shard.yml
  shell.nix
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15037 Do not over-commit fiber stacks on Windows
  spec/std/process_spec.cr
  src/crystal/system/fiber.cr
  src/crystal/system/unix/fiber.cr
  src/crystal/system/wasi/fiber.cr
  src/crystal/system/win32/fiber.cr
  src/fiber/context/x86_64-microsoft.cr
  src/fiber/stack_pool.cr
Labels: performance, topic:stdlib:concurrency, platform:windows

#15059 Implement `codecov` format for `unreachable` tool
  src/compiler/crystal/tools/unreachable.cr
Labels: kind:feature, topic:tools:unreachable

#15039 Add `Iterator(T).empty`
  spec/std/iterator_spec.cr
  src/iterator.cr
Labels: kind:feature, topic:stdlib:collection

#15040 Assume `getrandom` on Linux
  src/crystal/system/random.cr
  src/crystal/system/unix/getrandom.cr
  src/crystal/system/unix/urandom.cr
  src/lib_c/aarch64-android/c/sys/random.cr
  src/lib_c/aarch64-linux-gnu/c/sys/random.cr
  src/lib_c/aarch64-linux-musl/c/sys/random.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/random.cr
  src/lib_c/i386-linux-gnu/c/sys/random.cr
  src/lib_c/i386-linux-musl/c/sys/random.cr
  src/lib_c/x86_64-linux-gnu/c/sys/random.cr
  src/lib_c/x86_64-linux-musl/c/sys/random.cr
  src/random/secure.cr
Labels: kind:refactor, topic:stdlib:system, platform:linux-musl, platform:linux-gnu, platform:android

#14718 Enable pending formatter features
  spec/compiler/formatter/formatter_spec.cr
  spec/llvm-ir/pass-closure-to-c-debug-loc.cr
  spec/llvm-ir/proc-call-debug-loc.cr
  spec/std/benchmark_spec.cr
  spec/std/channel_spec.cr
  spec/std/concurrent/select_spec.cr
  spec/std/http/server/handlers/log_handler_spec.cr
  spec/std/openssl/ssl/socket_spec.cr
  spec/std/proc_spec.cr
  src/compiler/crystal/command/format.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/ffi/lib_ffi.cr
  src/compiler/crystal/interpreter/closure_context.cr
  src/compiler/crystal/interpreter/compiled_def.cr
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/interpreter.cr
  src/compiler/crystal/interpreter/lib_function.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_merge.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/init.cr
  src/compiler/crystal/util.cr
  src/crystal/system/thread.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/socket.cr
  src/gc/boehm.cr
  src/kernel.cr
  src/lib_c/x86_64-windows-msvc/c/consoleapi.cr
  src/lib_c/x86_64-windows-msvc/c/dbghelp.cr
  src/lib_c/x86_64-windows-msvc/c/fileapi.cr
  src/lib_c/x86_64-windows-msvc/c/ioapiset.cr
  src/lib_c/x86_64-windows-msvc/c/stringapiset.cr
  src/lib_c/x86_64-windows-msvc/c/winsock2.cr
  src/llvm/lib_llvm/debug_info.cr
  src/llvm/lib_llvm/orc.cr
  src/proc.cr
  src/random/isaac.cr
  src/wait_group.cr
Labels: kind:feature, topic:tools:formatter

#15070 Basic MinGW-w64 cross-compilation support
  spec/std/big/big_float_spec.cr
  src/big/big_int.cr
  src/big/lib_gmp.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/exception.cr
  src/compiler/crystal/codegen/link.cr
  src/crystal/system/win32/thread.cr
  src/exception/call_stack.cr
  src/exception/call_stack/stackwalk.cr
  src/exception/lib_unwind.cr
  src/lib_c/x86_64-windows-gnu
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/llvm/target_machine.cr
  src/raise.cr
Labels: kind:feature, platform:windows, platform:x86

#15022 Extract `deploy_api_docs` job into its own Workflow
  .github/workflows/docs.yml
  .github/workflows/linux.yml
Labels: topic:infrastructure/ci

#15068 Replace uses of `AliasType#types?` by `Type#lookup_name`
  spec/compiler/semantic/did_you_mean_spec.cr
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/semantic/abstract_def_checker.cr
  src/compiler/crystal/semantic/new.cr
  src/compiler/crystal/semantic/path_lookup.cr
  src/compiler/crystal/semantic/recursive_struct_checker.cr
  src/compiler/crystal/semantic/suggestions.cr
  src/compiler/crystal/semantic/type_declaration_processor.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/compiler/crystal/tools/typed_def_processor.cr
  src/compiler/crystal/tools/unreachable.cr
  src/compiler/crystal/types.cr
Labels: kind:refactor, topic:compiler:semantic

#15076 Fix `find-llvm-config` to ignore `LLVM_CONFIG`'s escape sequences
  src/llvm/ext/find-llvm-config
Labels: kind:bug, platform:windows, topic:stdlib:llvm

#15080 Fix various typos
  spec/std/http/request_spec.cr
  spec/std/io/delimited_spec.cr
  spec/std/regex_spec.cr
  spec/std/time/span_spec.cr
  spec/std/yaml/serializable_spec.cr
  src/channel/select.cr
  src/compiler/crystal/types.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/docs_pseudo_methods.cr
  src/file.cr
  src/gc/none.cr
Labels: kind:chore

#15082 Improve man and shell completion for tools
  etc/completion.bash
  etc/completion.fish
  etc/completion.zsh
  man/crystal.1
  src/compiler/crystal/command.cr
Labels: kind:bug, topic:tools

#15086 Fix `Complex#/` edge cases
  spec/std/complex_spec.cr
  src/complex.cr
Labels: kind:bug, topic:stdlib:numeric

#15090 Fix `Number#humanize` printing of `(-)Infinity` and `NaN`
  spec/std/humanize_spec.cr
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#15093 Fix failing specs on FreeBSD
  spec/std/signal_spec.cr
  spec/std/socket/socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
Labels: kind:specs, platform:freebsd

#15077 Support building from a MinGW-w64-based compiler
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/compiler.cr
  src/crystal/system/win32/wmain.cr
  src/lib_c/x86_64-windows-msvc/c/stdio.cr
Labels: kind:feature, platform:windows, topic:compiler:cli

#15094 Make `bin/crystal` work on MSYS2
  bin/crystal
Labels: kind:feature, topic:infrastructure, platform:windows

#15095 Fix libiconv build on Windows
  etc/win-ci/cygwin-build-iconv.sh
Labels: kind:bug, platform:windows, topic:stdlib:text

#15096 Fix Deadlock with parallel stop-world/fork calls in MT
  src/crystal/system/unix/process.cr
  src/crystal/system/unix/pthread.cr
  src/gc/boehm.cr
Labels: kind:bug, topic:stdlib:runtime, topic:multithreading, platform:unix

#15092 Better handle explicit chunked encoding responses
  spec/std/http/server/response_spec.cr
  src/http/server/response.cr
Labels: kind:feature, topic:stdlib:networking

#15100 Add location information to more MacroIf related nodes
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, topic:lang:macros

#15102 Make `Makefile` work on MSYS2
  Makefile
  bin/crystal
  src/compiler/crystal/compiler.cr
  src/llvm/ext/find-llvm-config
  src/llvm/lib_llvm.cr
Labels: kind:feature, topic:infrastructure, platform:windows-gnu

#15107 Fix `UNIXSocket#receive`
  spec/std/socket/unix_socket_spec.cr
  src/socket/unix_socket.cr
Labels: kind:bug, topic:stdlib:networking, kind:regression

#15108 Refactor uses of `LibC.dladdr` inside `Exception::CallStack`
  src/exception/call_stack/libunwind.cr
Labels: kind:refactor, topic:stdlib:runtime

#15103 Use official Apt respositories for LLVM CI
  .github/workflows/llvm.yml
Labels: kind:refactor, topic:stdlib:llvm, topic:infrastructure/ci

#15109 Drop LLVM Apt installer script on WebAssembly CI
  .github/workflows/wasm32.yml
Labels: kind:refactor, platform:wasm, topic:infrastructure/ci

#15098 Inline `ASTNode` bindings dependencies and observers
  src/compiler/crystal/semantic/bindings.cr
  src/compiler/crystal/semantic/call_error.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/filters.cr
  src/compiler/crystal/semantic/main_visitor.cr
  src/compiler/crystal/semantic/type_merge.cr
Labels: performance, topic:compiler:semantic

#15110 Add CI workflow for cross-compiling Crystal on MSYS2
  .github/workflows/mingw-w64.yml
Labels: kind:feature, topic:infrastructure/ci, platform:windows-gnu

#15115 Fix: LibC bindings and std specs on NetBSD 10
  spec/std/io/io_spec.cr
  spec/std/kernel_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
  spec/std/string_spec.cr
  src/crystal/system/unix/dir.cr
  src/lib_c/x86_64-netbsd/c/dirent.cr
  src/lib_c/x86_64-netbsd/c/netdb.cr
  src/lib_c/x86_64-netbsd/c/sys/time.cr
Labels: kind:bug, platform:bsd

#15116 Disable specs that break on MinGW-w64
  spec/compiler/codegen/pointer_spec.cr
  spec/compiler/codegen/thread_local_spec.cr
  spec/std/kernel_spec.cr
Labels: kind:specs, platform:windows-gnu

#15117 Support call stacks for MinGW-w64 builds
  spec/std/exception/call_stack_spec.cr
  src/crystal/pe.cr
  src/crystal/system/win32/signal.cr
  src/exception/call_stack.cr
  src/exception/call_stack/dwarf.cr
  src/exception/call_stack/elf.cr
  src/exception/call_stack/libunwind.cr
  src/exception/call_stack/stackwalk.cr
  src/lib_c/x86_64-windows-msvc/c/libloaderapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/raise.cr
Labels: kind:feature, topic:stdlib:runtime, platform:windows-gnu

#15111 Support OpenSSL on MSYS2
  src/openssl/lib_crypto.cr
  src/openssl/lib_ssl.cr
Labels: kind:feature, topic:stdlib:networking, platform:windows-gnu

#15121 Use per-thread libxml2 global state on all platforms
  src/xml.cr
  src/xml/libxml2.cr
Labels: kind:refactor, topic:stdlib:serialization, topic:multithreading

#15119 Support "long format" DLL import libraries
  src/crystal/system/win32/library_archive.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, topic:compiler:interpreter, platform:windows-gnu

#15118 OpenBSD: fix integration and broken specs
  bin/crystal
  spec/compiler/loader/unix_spec.cr
  spec/std/exception/call_stack_spec.cr
  spec/std/io/io_spec.cr
  spec/std/kernel_spec.cr
  spec/std/socket/addrinfo_spec.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
  src/compiler/crystal/compiler.cr
  src/lib_c/x86_64-openbsd/c/netdb.cr
Labels: kind:bug, platform:bsd

#15123 Support `.exe` file extension in `Makefile` on MSYS2
  Makefile
Labels: kind:feature, topic:infrastructure, kind:specs, platform:windows-gnu

#15125 Allow skipping compiler tool specs that require Git
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  spec/compiler/crystal/tools/init_spec.cr
Labels: topic:tools:docs-generator, kind:specs, topic:tools:init

#15124 Add MinGW-w64 CI workflow for stdlib and compiler specs
  .github/workflows/mingw-w64.yml
  src/compiler/crystal/compiler.cr
Labels: kind:feature, kind:specs, topic:infrastructure/ci, platform:windows-gnu

#15127 Add `cc`'s search paths to Unix dynamic library loader
  spec/std/llvm/aarch64_spec.cr
  spec/std/llvm/arm_abi_spec.cr
  spec/std/llvm/avr_spec.cr
  spec/std/llvm/llvm_spec.cr
  spec/std/llvm/type_spec.cr
  spec/std/llvm/x86_64_abi_spec.cr
  spec/std/llvm/x86_abi_spec.cr
  src/compiler/crystal/loader/unix.cr
Labels: kind:feature, platform:unix, topic:compiler:interpreter

#15131 Fix remove trailing whitespace from CRYSTAL definition
  Makefile
Labels: topic:infrastructure

#15135 Fix `Crystal::Loader.default_search_paths` spec for macOS
  spec/compiler/loader/unix_spec.cr
Labels: kind:bug, kind:specs, platform:darwin, kind:regression, topic:compiler:interpreter

#15136 Make `Box` constructor and `object` getter nodoc
  src/box.cr
Labels: kind:docs, topic:stdlib:runtime

#15122 Add indirect branch tracking
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/debug.cr
  src/compiler/crystal/codegen/fun.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/semantic/flags.cr
  src/llvm/lib_llvm/core.cr
  src/llvm/module.cr
Labels: kind:feature, platform:aarch64, topic:compiler:codegen, platform:x86, platform:bsd

#15138 Support deferencing symlinks in `make install`
  Makefile
Labels: kind:feature, topic:infrastructure

#15132 Improve docs for `String#rindex!`
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#15134 Protect constant initializers with mutex on Windows
  src/crystal/once.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime, kind:regression
