Repository crystal-lang/crystal, pull requests merged in 2024-12, with the labels that each got.

#15239 Avoid identifier naming collision in `getter`, `setter`, and `property` macros
  src/object.cr
Labels: kind:bug, topic:stdlib:macros

#15226 Crystal::EventLoop namespace
  spec/std/crystal/event_loop/polling/arena_spec.cr
  spec/std/crystal/event_loop/polling/poll_descriptor_spec.cr
  spec/std/crystal/event_loop/polling/timers_spec.cr
  spec/std/crystal/event_loop/polling/waiters_spec.cr
  src/crystal/event_loop.cr
  src/crystal/event_loop/epoll.cr
  src/crystal/event_loop/file_descriptor.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/kqueue.cr
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/libevent/event.cr
  src/crystal/event_loop/libevent/lib_event2.cr
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/polling/arena.cr
  src/crystal/event_loop/polling/event.cr
  src/crystal/event_loop/polling/fiber_event.cr
  src/crystal/event_loop/polling/poll_descriptor.cr
  src/crystal/event_loop/polling/timers.cr
  src/crystal/event_loop/polling/waiters.cr
  src/crystal/event_loop/socket.cr
  src/crystal/event_loop/wasi.cr
  src/crystal/scheduler.cr
  src/crystal/system/socket.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/win32/addrinfo.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
  src/io/evented.cr
  src/kernel.cr
Labels: kind:refactor, topic:stdlib:runtime

#15233 Optimize `String#==` taking character size into account
  src/string.cr
Labels: performance, topic:stdlib:text

#15234 Optimize `Slice#<=>` and `#==` with reference check
  src/slice.cr
Labels: performance, topic:stdlib:collection

#15240 Add stringification for `HTTP::Cookie`
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#15241 Raise on abnormal exit in `Procss::Status#exit_code`
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:bug, topic:stdlib:system

#15207 Merge changelog entries for fixups with main PR
  scripts/github-changelog.cr
Labels: topic:infrastructure

#15243 Change `libevent` event loop to wait forever when blocking
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/libevent/event.cr
  src/crystal/event_loop/libevent/lib_event2.cr
Labels: kind:refactor, topic:stdlib:runtime

#15246 Add stringification for `HTTP::Cookies`
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#15238 Refactor the IOCP event loop (timers, ...)
  .github/workflows/mingw-w64.yml
  spec/std/crystal/event_loop/timers_spec.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/iocp/fiber_event.cr
  src/crystal/event_loop/iocp/timer.cr
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/timers.cr
  src/crystal/system/win32/addrinfo.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
  src/crystal/system/win32/process.cr
  src/crystal/system/win32/waitable_timer.cr
  src/kernel.cr
  src/lib_c/x86_64-windows-msvc/c/ntdef.cr
  src/lib_c/x86_64-windows-msvc/c/ntdll.cr
  src/lib_c/x86_64-windows-msvc/c/ntstatus.cr
  src/lib_c/x86_64-windows-msvc/c/synchapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
  src/lib_c/x86_64-windows-msvc/c/winternl.cr
  src/winerror.cr
Labels: kind:refactor, topic:stdlib:runtime

#15247 Add `Process::Status#exit_code?`
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:feature, topic:stdlib:system

#15244 Add specs for invalid special characters in `Cookie`
  spec/std/http/cookie_spec.cr
Labels: kind:specs, topic:stdlib:networking

#15248 Add `String#byte_index(Regex)`
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#15254 Refactor use of `Process::Status#exit_code` to `#exit_code?`
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/macros/methods.cr
  src/process/status.cr
Labels: kind:refactor, topic:stdlib:system

#15256 Adjust definition of `ExitReason::Aborted`
  src/process/status.cr
Labels: kind:docs, topic:stdlib:system

#15253 Fix `Log` to emit with `exception` even if block outputs `nil`
  spec/std/log/log_spec.cr
  src/log/log.cr
Labels: kind:bug, topic:stdlib:log, kind:regression

#15148 Allow constants to start with non-ascii uppercase and titlecase
  spec/compiler/lexer/lexer_spec.cr
  src/compiler/crystal/syntax/lexer.cr
Labels: kind:feature, topic:compiler:parser

#15142 Change `sprintf "%c"` to support only `Char` and `Int::Primitive`
  spec/std/sprintf_spec.cr
  src/string/formatter.cr
Labels: kind:bug, topic:stdlib:text

#15219 Mark `__crystal_personality` as nodoc [fixup #15070]
  src/raise.cr
Labels: kind:docs, topic:stdlib:runtime

#15255 Redefine `Process::Status#normal_exit?` on Windows
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: platform:windows, topic:stdlib:system, kind:chore

#15266 Add `Process::Status#abnormal_exit?`
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:feature, topic:stdlib:system

#15267 Fix stringification of abnormal `Process::Status` on Windows [fixup #15255]
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:bug, topic:stdlib:system, kind:regression

#15257 Add `Log` overloads for logging exceptions without giving a block
  spec/std/log/log_spec.cr
  src/log/log.cr
  src/log/main.cr
Labels: kind:feature, topic:stdlib:log

#15272 Use empty prelude for compiler tools specs
  spec/compiler/crystal/tools/context_spec.cr
  spec/compiler/crystal/tools/expand_spec.cr
  spec/compiler/crystal/tools/implementations_spec.cr
Labels: topic:tools, kind:specs

#15273 Fix `tool implementations` to handle gracefully a def with missing location
  spec/compiler/crystal/tools/implementations_spec.cr
  src/compiler/crystal/tools/implementations.cr
Labels: kind:bug, topic:tools:implementations

#15278 Fix: register GC callbacks inside GC.init
  src/gc/boehm.cr
Labels: kind:bug, topic:multithreading

#15245 Drop `Crystal::FiberChannel`
  spec/std/crystal/event_loop/polling/poll_descriptor_spec.cr
  src/crystal/fiber_channel.cr
  src/crystal/scheduler.cr
Labels: kind:refactor, topic:multithreading

#15274 Make `Enum` an abstract struct
  src/enum.cr
Labels: topic:stdlib:runtime, kind:chore

#15050 Fix first doc comment inside macro yield
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:bug, topic:compiler, topic:lang:macros, topic:tools:docs-generator

#15222 Add `ECR::Lexer::SyntaxException` with location info
  src/ecr/lexer.cr
Labels: kind:feature, topic:compiler:parser

#14819 Add `HTTP::Cookie#expire`
  spec/std/http/cookie_spec.cr
  src/http/cookie.cr
Labels: kind:feature, topic:stdlib:networking

#15113 Add `Colorize::Object#ansi_escape`
  spec/std/colorize_spec.cr
  src/colorize.cr
Labels: kind:feature, topic:stdlib:text

#15283 Improve `Process::Status#to_s` for abnormal exits on Windows
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:feature, platform:windows, topic:stdlib:system

#15284 Add `Process::Status#exit_signal?`
  spec/std/process/status_spec.cr
  src/compiler/crystal/command.cr
  src/process/status.cr
Labels: kind:feature, topic:stdlib:system

#15289 Redefine `Process::Status#signal_exit?`
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: breaking-change, topic:stdlib:system, kind:chore

#15288 Refactor simplify `Process::Status#exit_reason` on Unix
  src/process/status.cr
Labels: kind:refactor, topic:stdlib:system

#15290 Update shards 0.19.0
  .github/workflows/win_build_portable.yml
Labels: topic:infrastructure/ci

#15291 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#15292 Crystal `Not` operators do not need parens
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#15195 Implement `fast_float` for `String#to_f`
  spec/manual/string_to_f32_spec.cr
  spec/manual/string_to_f_supplemental_spec.cr
  spec/std/string_spec.cr
  spec/support/number.cr
  src/float/fast_float.cr
  src/float/fast_float/ascii_number.cr
  src/float/fast_float/bigint.cr
  src/float/fast_float/decimal_to_binary.cr
  src/float/fast_float/digit_comparison.cr
  src/float/fast_float/fast_table.cr
  src/float/fast_float/float_common.cr
  src/float/fast_float/parse_number.cr
  src/lib_c/x86_64-windows-msvc/c/stdlib.cr
  src/string.cr
Labels: kind:feature, performance, topic:stdlib:numeric, topic:stdlib:text

#15296 Add `Process::Status#system_exit_status`
  spec/std/process/status_spec.cr
  src/process/status.cr
Labels: kind:feature, topic:stdlib:system

#15295 Fix: cleanup T on Thread::LinkedList(T)#delete
  src/crystal/system/thread_linked_list.cr
Labels: kind:bug, topic:stdlib:runtime

#15297 Crystal::Tracing improvements
  src/crystal/event_loop/epoll.cr
  src/crystal/event_loop/kqueue.cr
  src/crystal/scheduler.cr
  src/crystal/system/unix/signal.cr
  src/crystal/system/win32/process.cr
  src/crystal/tracing.cr
Labels: kind:feature, topic:stdlib:runtime

#15298 Add `Thread#internal_name=`
  src/crystal/system/thread.cr
Labels: kind:feature, topic:stdlib:runtime

#15300 Add `Thread::LinkedList#each` to safely iterate lists
  src/crystal/system/thread.cr
  src/crystal/system/thread_linked_list.cr
  src/fiber.cr
Labels: kind:feature, topic:stdlib:runtime

#15299 Explicit exit from main
  src/crystal/main.cr
  src/crystal/system/unix/main.cr
  src/crystal/system/wasi/main.cr
  src/crystal/system/win32/wmain.cr
Labels: kind:refactor, topic:stdlib:runtime

#8647 Deprecate `Process::Status#exit_status`
  src/process/status.cr
Labels: topic:stdlib:system, deprecation, kind:chore

#15304 Add `MacroIf#is_unless?` AST node method
  spec/compiler/macro/macro_methods_spec.cr
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/syntax/ast.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:feature, topic:lang:macros

#15309 Fix error handling for `LibC.clock_gettime(CLOCK_MONOTONIC)` calls
  src/crystal/system/unix/time.cr
Labels: kind:bug, topic:stdlib:system
