Repository crystal-lang/crystal, pull requests merged in 2024-04, with the labels that each got.

#14404 Fix `Milestone` JSON bindings in `github-changelog` helper
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14407 Make repository configurable for reusable `github-changelog`
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14406 Use link refs for PR links in changelog
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14412 Implement pagination for GitHub API in `github-changelog` helper
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14410 Improve OpenSSL module documentation
  src/openssl.cr
  src/openssl/cipher.cr
  src/openssl/ssl/context.cr
Labels: kind:docs, topic:stdlib:crypto

#14414 Use `Makefile.win` for Shards on Windows CI
  .github/workflows/win_build_portable.yml
Labels: kind:refactor, platform:windows, topic:infrastructure/ci

#14417 Fix `Hash#update` when default block also adds given key
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:bug, topic:stdlib:collection, kind:regression

#14427 Fix `Hash#put_if_absent` putting duplicate keys
  spec/std/hash_spec.cr
  src/hash.cr
Labels: kind:bug, topic:stdlib:collection

#14429 Fix `Hash.new(initial_capacity, &block)` doc to use relevant example
  src/hash.cr
Labels: kind:docs, topic:stdlib:collection

#14428 Fix `Pointer#+(offset: Int64)` doc parameter name typo
  src/primitives.cr
Labels: kind:docs, topic:stdlib:runtime

#14430 Add `Nil` return type restriction to `String::Formatter#consume_substitution`
  src/string/formatter.cr
Labels: kind:bug, topic:stdlib:text

#14433 Add single source of UTF-8 test sequences for specs
  spec/std/char/reader_spec.cr
  spec/std/io/buffered_spec.cr
  spec/std/io/io_spec.cr
  spec/std/string_spec.cr
  spec/support/string.cr
Labels: kind:refactor, kind:specs, topic:stdlib:text

#14431 Move some `IO::FileDescriptor` specs to the correct file
  spec/std/io/file_descriptor_spec.cr
  spec/std/io/io_spec.cr
Labels: kind:specs, topic:stdlib:files

#14231 Add `scripts/update-changelog.sh`
  scripts/update-changelog.sh
Labels: topic:infrastructure

#14441 Handle NaN comparisons in the interpreter
  src/compiler/crystal/interpreter/compiler.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:stdlib:numeric, topic:compiler:interpreter

#14436 Check `UInt16#to_u8` for overflow in the interpreter
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:stdlib:numeric, topic:compiler:interpreter

#14439 Do not remove the whitespace in `foo ()` when formatting
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter, kind:regression

#14445 Use separate names for constant and class variable internals
  spec/compiler/codegen/class_var_spec.cr
  spec/llvm-ir/const-read-debug-loc.cr
  src/compiler/crystal/codegen/const.cr
  src/compiler/crystal/codegen/types.cr
Labels: kind:bug, topic:compiler:codegen

#14437 Fix interpreter internal overflow for `UInt128#to_f32` and `#to_f32!`
  spec/primitives/int_spec.cr
  src/compiler/crystal/interpreter/instructions.cr
  src/compiler/crystal/interpreter/primitives.cr
Labels: kind:bug, topic:stdlib:numeric, topic:compiler:interpreter

#14426 Improve documentation for `at_exit` handler conditions
  src/kernel.cr
Labels: kind:docs, topic:stdlib:runtime

#14457 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#14232 Changelog for 1.12.0
  CHANGELOG.md
Labels: topic:infrastructure

#14465 Update version to 1.12.0
  shard.yml
  src/VERSION
Labels: topic:infrastructure

#14471 Fix formatter with whitespace before closing parenthesis
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter, kind:regression

#14472 Changelog for 1.12.1
  CHANGELOG.md
  shard.yml
  src/VERSION
Labels: topic:infrastructure

#14447 Ensure `Enumerable#to_a` and `Enumerable#tally` properly retain return type of `T`
  spec/std/enumerable_spec.cr
  spec/std/indexable_spec.cr
  src/enumerable.cr
  src/indexable.cr
Labels: kind:bug, topic:stdlib:collection, kind:regression

#14444 Never raise `IndexError` in `#[]?(Range)`
  spec/std/regex/match_data_spec.cr
  spec/std/slice_spec.cr
  src/regex/match_data.cr
  src/slice.cr
Labels: kind:bug, breaking-change, topic:stdlib:collection

#14458 Make `String#sub` raise `IndexError` if index is equal to size
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:bug, topic:stdlib:text

#11208 Fix type def reopening type from parent namespace
  spec/compiler/semantic/class_spec.cr
  spec/compiler/semantic/module_spec.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#14167 Add WaitGroup synchronization primitive
  spec/std/wait_group_spec.cr
  src/crystal/pointer_linked_list.cr
  src/wait_group.cr
Labels: kind:feature, topic:stdlib:concurrency

#14259 Move `Spec` context state into `Spec::CLI`
  spec/std/spec/spec_helper.cr
  src/spec/context.cr
  src/spec/example.cr
Labels: kind:refactor, topic:stdlib:specs

#14419 Remove calls to `LibC._setmode`
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#14432 Allow `#fsync` and `#flock_*` on `IO::FileDescriptor`
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:bug, topic:stdlib:files

#14415 Distribute `shards.pdb` on Windows
  .github/workflows/win_build_portable.yml
  etc/win-ci/crystal.iss
Labels: kind:feature, platform:windows, topic:infrastructure/ci

#14443 Use wrapping arithmetic for `Int::Primitive#unsafe_chr`
  spec/primitives/int_spec.cr
  src/primitives.cr
Labels: performance, topic:stdlib:text

#14442 Add `Program#size_t` and `Target#size_bit_width`
  src/compiler/crystal/codegen/call.cr
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/llvm_builder_helper.cr
  src/compiler/crystal/codegen/llvm_typer.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/codegen/unions.cr
  src/compiler/crystal/semantic/flags.cr
Labels: kind:refactor, topic:compiler:codegen

#14462 Add `Regex::MatchOptions` overload for `String#index!`
  spec/std/string_spec.cr
  src/string.cr
Labels: kind:feature, topic:stdlib:text

#14452 Allow assignment to `_` inside macro expressions
  spec/compiler/semantic/macro_spec.cr
  src/compiler/crystal/macros/interpreter.cr
Labels: kind:feature, topic:lang:macros

#14438 Run `primitives_spec` with the interpreter on CI
  .github/workflows/interpreter.yml
  spec/primitives/float_spec.cr
  spec/primitives/reference_spec.cr
  spec/primitives/slice_spec.cr
Labels: topic:stdlib, topic:compiler:interpreter, topic:infrastructure/ci

#14474 Highlight regression bugfixes in changelog
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14478 Fix libpcre2 version detection not working for -RC{N} versions
  src/regex/pcre2.cr
Labels: kind:bug, topic:stdlib:text

#14494 Replace `type` declarations for void pointers with `alias` in `libxml2`
  src/xml/libxml2.cr
Labels: kind:refactor, topic:stdlib:serialization

#14475 Log: delete source from builder cache when finalize
  src/log/builder.cr
  src/log/log.cr
Labels: kind:bug, topic:stdlib:log

#14483 Drop Windows CI workaround for 1.12.0-dev
  .github/workflows/win_build_portable.yml
Labels: kind:refactor, platform:windows, topic:infrastructure/ci

#14413 Relax type restriction of handlers in `HTTP::Server` constructor
  src/http/server.cr
Labels: kind:feature, topic:stdlib:networking

#14490 Fix `Crystal::Path#to_macro_id` for global path
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:bug, topic:compiler:semantic

#14461 Optimize `String#index(Char)` and `#rindex(Char)` for invalid UTF-8
  src/string.cr
Labels: performance, topic:stdlib:text

#14420 Implement `File.readable?` and `.writable?` in Win32
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#14492 Add AST node methods for macro-related nodes
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
  src/compiler/crystal/macros/types.cr
Labels: kind:feature, topic:stdlib:macros

#14505 Fix parsing of non-trailing `if` bodies inside macro expressions
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser, topic:lang:macros

#14506 Drop parentheses around `->` inside certain comma-separated lists
  spec/compiler/parser/to_s_spec.cr
  spec/compiler/semantic/restrictions_augmenter_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:lang:macros

#14501 Use file handles directly instead of C file descriptors on Win32
  spec/compiler/macro/macro_methods_spec.cr
  src/crystal/system/file.cr
  src/crystal/system/process.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
  src/io/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/io.cr
  src/lib_c/x86_64-windows-msvc/c/winbase.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#14510 Fix indentation of `Select` nodes' macro interpolation
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:lang:macros

#14517 Fix `Socket#close` error handling on Windows
  src/crystal/system/win32/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:networking

#14514 Make `File.readable?` and `.writable?` follow symlinks on Windows
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#14515 Update `WinError#to_errno`
  src/winerror.cr
Labels: platform:windows, topic:stdlib:system

#14509 Make `IO::FileDescriptor#tty?` return false for NUL on Windows
  spec/std/io/file_descriptor_spec.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/socket.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#14521 Fix docs for `Char#ascii_number?` stating wrong minium base
  src/char.cr
Labels: kind:bug, kind:docs, topic:stdlib:text

#14523 Support short blocks in `#[]` operator call's macro interpolation
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#14508 Add `StringPool#get?`
  spec/std/string_pool_spec.cr
  src/string_pool.cr
Labels: kind:feature, topic:stdlib:text

#14526 Fix formatting for short block inside `#[]` operator call
  spec/compiler/formatter/formatter_spec.cr
  src/compiler/crystal/tools/formatter.cr
Labels: kind:bug, topic:tools:formatter

#14463 Add compiler flags `-Os` and `-Oz` to optimize binary size
  man/crystal.1
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/compiler.cr
  src/llvm/function_pass_manager.cr
  src/llvm/lib_llvm/initialization.cr
  src/llvm/lib_llvm/transforms/pass_builder.cr
  src/llvm/module.cr
  src/llvm/module_pass_manager.cr
  src/llvm/pass_builder_options.cr
  src/llvm/pass_manager_builder.cr
  src/llvm/pass_registry.cr
Labels: kind:feature, topic:compiler:codegen

#14529 Fix blockless `IO::FileDescriptor` echo and raw mode methods
  src/crystal/system/file_descriptor.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/io/console.cr
Labels: kind:bug, topic:stdlib:files

#14543 Add `Thread.new` yields itself
  src/crystal/system/thread.cr
Labels: topic:stdlib:concurrency, kind:refactor

#14532 Add support for `Atomic(Bool)`
  spec/std/atomic_spec.cr
  src/atomic.cr
Labels: kind:feature, topic:stdlib:concurrency

#14542 Enhance documentation for regex options `NO_UTF_CHECK`
  src/regex.cr
Labels: kind:docs, topic:stdlib:text

#14533 Refactor `JSON::Any#size` to use two branches instead of three
  src/json/any.cr
Labels: kind:refactor, topic:stdlib:serialization
