Repository crystal-lang/crystal, pull requests merged in 2024-05, with the labels that each got.

#14522 Remove target path's forward slashes in `File.symlink` on Windows
  spec/std/file_spec.cr
  src/crystal/system/win32/file.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#14548 Refactor use `IO#read_byte` instead of `#read_char` in `HTTP::ChunkedContent`
  src/http/content.cr
Labels: kind:refactor, topic:stdlib:networking

#14393 Add compiler support for AVR architecture (Arduino)
  spec/std/llvm/avr_spec.cr
  src/compiler/crystal/codegen/target.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/semantic/flags.cr
  src/intrinsics.cr
  src/llvm.cr
  src/llvm/abi/avr.cr
  src/llvm/lib_llvm/target.cr
  src/llvm/lib_llvm/target_machine.cr
  src/llvm/target_data.cr
  src/llvm/target_machine.cr
Labels: kind:feature

#11162 Fix `Class#===` on metaclass
  spec/std/class_spec.cr
  src/class.cr
Labels: kind:bug, topic:compiler:semantic

#14554 `Thread` owns its current fiber (instead of `Crystal::Scheduler`)
  src/crystal/scheduler.cr
  src/crystal/system/thread.cr
  src/fiber.cr
  src/gc/boehm.cr
Labels: kind:refactor, topic:multithreading

#14561 Use `Fiber#enqueue`
  spec/std/channel_spec.cr
  spec/std/concurrent/select_spec.cr
  src/channel.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/io/evented.cr
Labels: kind:refactor, topic:multithreading

#14559 Add `Crystal::EventLoop.current`
  src/crystal/system/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/process.cr
  src/crystal/system/win32/socket.cr
  src/fiber.cr
  src/io/evented.cr
  src/io/overlapped.cr
  src/kernel.cr
Labels: kind:refactor, topic:multithreading

#14567 Fix: No need for explicit memory barriers on ARM
  src/atomic.cr
  src/crystal/rw_lock.cr
  src/crystal/spin_lock.cr
  src/mutex.cr
Labels: kind:refactor, topic:multithreading, platform:arm

#14565 Add LLVM 18 to LLVM CI
  .github/workflows/llvm.yml
Labels: topic:infrastructure/ci

#14560 Add `Fiber.suspend`
  src/channel.cr
  src/crystal/system/win32/process.cr
  src/fiber.cr
  src/io/evented.cr
  src/io/overlapped.cr
  src/mutex.cr
  src/wait_group.cr
Labels: kind:refactor, topic:multithreading

#14547 Write release version to `src/VERSION` in `update-changelog` and `release-update`
  scripts/release-update.sh
  scripts/update-changelog.sh
Labels: topic:infrastructure

#14545 Add test helper for `normalize/regex_spec`
  spec/compiler/normalize/regex_spec.cr
  spec/spec_helper.cr
Labels: kind:specs, topic:stdlib:text

#14557 Disable implicit execution of batch files
  spec/std/process_spec.cr
  src/crystal/system/win32/process.cr
Labels: breaking-change, platform:windows, security, topic:stdlib:system

#14571 Fix enable docs for builtin constants
  src/compiler/crystal/program.cr
Labels: kind:bug, topic:stdlib:runtime

#14570 Fix generate docs for builtins `HOST_TRIPLE` and `TARGET_TRIPLE`
  src/compiler/crystal/tools/doc/generator.cr
Labels: kind:bug, topic:tools:docs-generator

#14553 Allow rescuing exceptions that include a module
  spec/compiler/codegen/exception_spec.cr
  spec/compiler/semantic/exception_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:feature, topic:compiler:semantic

#14546 Set UTF-8 charset on directory listing in `HTTP::StaticFileHandler`
  src/http/server/handlers/static_file_handler.cr
Labels: kind:bug, topic:stdlib:networking

#14538 Add documentation for complex methods inside Number
  src/complex.cr
Labels: kind:docs, topic:stdlib:numeric

#14519 Fix `Set#to_a(&)`
  spec/std/set_spec.cr
  src/set.cr
Labels: kind:bug, breaking-change, topic:stdlib:collection

#14584 Add `pkg_config` names for `pcre2` and `pcre`
  src/regex/lib_pcre.cr
  src/regex/lib_pcre2.cr
Labels: kind:feature, topic:stdlib:text

#14583 Fix `nix.shell` use `llvmPackages.bintools` with wrapper for rpath config
  shell.nix
Labels: topic:infrastructure

#14577 Add documentation for standard streams blocking behaviour
  src/kernel.cr
Labels: kind:docs, topic:stdlib:runtime

#14574 Add `src/SOURCE_DATE_EPOCH` to release tree
  Makefile
  Makefile.win
  scripts/release-update.sh
  scripts/update-changelog.sh
Labels: topic:infrastructure

#14562 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#14511 Fix indentation of parenthesized `Expressions#to_s`
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:lang:macros

#14366 Optimize JSON parsing a bit
  spec/std/json/parser_spec.cr
  spec/std/json/pull_parser_spec.cr
  src/json/lexer.cr
  src/json/lexer/io_based.cr
  src/json/lexer/string_based.cr
  src/json/token.cr
Labels: performance, topic:stdlib:serialization

#13769 Remove `SetShouldExit` in Powershell wrapper
  bin/crystal.ps1
Labels: kind:bug, topic:infrastructure, platform:windows

#14594 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#14591 Use `boehmgc` package from nixpkgs in `shell.nix`
  shell.nix
Labels: topic:infrastructure

#14590 Simplify LLVM dependency in `shell.nix`
  shell.nix
Labels: topic:infrastructure

#14593 Fix nixpkgs `pkg-config` name in `shell.nix`
  shell.nix
Labels: topic:infrastructure

#14575 Fix `Regex#inspect` with non-literal-compatible options
  spec/std/regex_spec.cr
  src/regex.cr
Labels: kind:bug, topic:stdlib:text

#14598 Remove `CRYSTAL_LIBRARY_RPATH` and delay-load helper
  UPGRADING.md
  spec/std/spec_helper.cr
  src/compiler/crystal/codegen/link.cr
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/command/eval.cr
  src/compiler/crystal/command/spec.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/loader/msvc.cr
  src/compiler/crystal/macros/macros.cr
  src/compiler/crystal/program.cr
  src/compiler/crystal/tools/doc/generator.cr
  src/crystal/main.cr
  src/crystal/system/win32/delay_load.cr
  src/lib_c/x86_64-windows-msvc/c/stringapiset.cr
Labels: breaking-change, platform:windows, kind:chore

#14600 Add macro methods for `Select`
  spec/compiler/macro/macro_methods_spec.cr
  src/compiler/crystal/macros.cr
  src/compiler/crystal/macros/methods.cr
Labels: kind:feature, topic:stdlib:macros

#14568 Add `EventLoop#run(blocking)` and `EventLoop#interrupt`
  src/crystal/scheduler.cr
  src/crystal/system/event_loop.cr
  src/crystal/system/unix/event_libevent.cr
  src/crystal/system/unix/event_loop_libevent.cr
  src/crystal/system/unix/lib_event2.cr
  src/crystal/system/wasi/event_loop.cr
  src/crystal/system/win32/event_loop_iocp.cr
  src/io/overlapped.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:feature, topic:stdlib:system

#14607 Refactor win32 `System::FileDescriptor#unbuffered_{read,write}`
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#14617 Rename `Crystal::System.print_error(fmt, *args, &)` to `printf`
  spec/std/crystal/system_spec.cr
  src/crystal/system/print_error.cr
Labels: kind:refactor, topic:stdlib:system

#14612 Add some missing `LLVM::Context` bindings
  src/llvm/context.cr
  src/llvm/lib_llvm/core.cr
  src/llvm/type.cr
Labels: kind:feature, topic:stdlib:llvm

#14626 Extract `#system_read` and `#system_write` for `FileDescriptor` and `Socket`
  src/crystal/system/file_descriptor.cr
  src/crystal/system/socket.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/wasi/socket.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/socket.cr
  src/io/evented.cr
  src/io/file_descriptor.cr
  src/socket.cr
Labels: kind:refactor, topic:stdlib:files, topic:stdlib:networking

#14624 Add `WaitGroup` to `docs_main.cr`
  src/docs_main.cr
Labels: topic:stdlib:concurrency, kind:chore

#14620 Add `Crystal::System::Time.ticks`
  src/crystal/system/time.cr
  src/crystal/system/unix/time.cr
  src/crystal/system/win32/time.cr
Labels: topic:stdlib:system

#14632 Don't pass socket file descriptors to subprocesses on Unix (`SOCK_CLOEXEC`)
  spec/std/socket/socket_spec.cr
  src/crystal/system/unix/socket.cr
Labels: kind:bug, topic:stdlib:networking

#14615 Fix using `System.retry_with_buffer` with stack buffer
  src/crystal/system/unix/group.cr
  src/crystal/system/unix/path.cr
  src/crystal/system/unix/user.cr
Labels: kind:bug, topic:stdlib:system

#14637 Drop `Crystal::System::Socket#system_send`
  src/crystal/system/socket.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/wasi/socket.cr
  src/crystal/system/win32/socket.cr
  src/socket.cr
Labels: kind:refactor, topic:stdlib:networking

#14638 Improve API docs for `Socket#send`
  src/socket.cr
Labels: kind:docs, topic:stdlib:networking
