Repository crystal-lang/crystal, pull requests merged in 2024-07, with the labels that each got.

#14746 Fix `GC.malloc` for `gc_none` to clear memory
  src/gc/none.cr
Labels: kind:bug, topic:stdlib:runtime

#14764 Prefer `strerror_r` over `strerror` for thread-safe errno
  src/errno.cr
  src/lib_c/aarch64-android/c/string.cr
  src/lib_c/aarch64-darwin/c/string.cr
  src/lib_c/aarch64-linux-gnu/c/string.cr
  src/lib_c/aarch64-linux-musl/c/string.cr
  src/lib_c/arm-linux-gnueabihf/c/string.cr
  src/lib_c/i386-linux-gnu/c/string.cr
  src/lib_c/i386-linux-musl/c/string.cr
  src/lib_c/wasm32-wasi/c/string.cr
  src/lib_c/x86_64-darwin/c/string.cr
  src/lib_c/x86_64-dragonfly/c/string.cr
  src/lib_c/x86_64-freebsd/c/string.cr
  src/lib_c/x86_64-linux-gnu/c/string.cr
  src/lib_c/x86_64-linux-musl/c/string.cr
  src/lib_c/x86_64-netbsd/c/string.cr
  src/lib_c/x86_64-openbsd/c/string.cr
  src/lib_c/x86_64-solaris/c/string.cr
Labels: kind:bug, topic:stdlib:system, topic:multithreading

#14762 Detect and error on failed codegen process
  src/compiler/crystal/compiler.cr
Labels: kind:bug, topic:compiler:codegen

#14769 Fix: don't hardcode alpn protocol byte size (OpenSSL)
  src/openssl/ssl/context.cr
Labels: kind:bug, topic:stdlib:networking

#10846 Fix exaö.e `WeakRef` example by removing ref.value call.
  src/weak_ref.cr
Labels: kind:docs, topic:stdlib:concurrency

#14763 Codegen: stats and progress issues
  src/compiler/crystal/compiler.cr
Labels: kind:bug, topic:compiler:codegen

#14772 Fix `IO::Delimited` reading into limited slice with peek
  spec/std/io/delimited_spec.cr
  src/io/delimited.cr
Labels: kind:bug, topic:stdlib:files

#14777 [CI] Update to Ruby 3 in macOS circleCI runner
  .circleci/config.yml
Labels: topic:infrastructure/ci

#14776 Update distribution-scripts
  .circleci/config.yml
Labels: topic:infrastructure

#14781 Fix changelog generator increase topic priority for `infrastructure`
  scripts/github-changelog.cr
Labels: topic:infrastructure

#14779 Fix JSON discriminator for Bool `false` value
  spec/std/json/serializable_spec.cr
  src/json/serialization.cr
Labels: kind:bug, topic:stdlib:serialization

#14550 Fix `Compress::Gzip` extra field
  spec/std/compress/gzip/gzip_spec.cr
  spec/std/data/test.gz
  src/compress/gzip/header.cr
Labels: kind:bug, topic:stdlib:files

#14790 Fix macro interpolation in `NamedTuple#from`
  spec/std/named_tuple_spec.cr
  src/named_tuple.cr
Labels: kind:bug, topic:stdlib:collection

#14785 Fix regression with `NamedTuple.new` when using key with a hyphen
  spec/std/named_tuple_spec.cr
  src/named_tuple.cr
Labels: kind:bug, topic:stdlib:collection, kind:regression

#14798 Fix code example for `Process.on_terminate`
  src/process.cr
Labels: kind:docs, topic:stdlib:system

#14788 Add spec for `Compress::Gzip::Writer` with `extra`
  spec/std/compress/gzip/gzip_spec.cr
Labels: kind:specs, topic:stdlib:files

#14712 Changelog for 1.13.0
  CHANGELOG.md
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#14804 Revert "Optimize JSON parsing a bit"
  spec/std/json/parser_spec.cr
  spec/std/json/pull_parser_spec.cr
  src/json/lexer.cr
  src/json/lexer/io_based.cr
  src/json/lexer/string_based.cr
  src/json/token.cr
Labels: topic:stdlib:serialization, kind:regression

#14806 Changelog for 1.13.1
  CHANGELOG.md
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#14821 [CI] Update LLVM 18 for `wasm32-test`
  .github/workflows/wasm32.yml
Labels: topic:infrastructure/ci

#14831 [CI] Pin package repos for OpenSSL packages
  .github/workflows/openssl.yml
Labels: topic:infrastructure/ci
