Repository crystal-lang/crystal, pull requests merged in 2025-05, with the labels that each got.

#15727 Fix order of title clean steps in github-changelog helper
  scripts/github-changelog.cr
Labels: topic:infrastructure

#15709 Handle properly stringifying multiline (boolean) expressions
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:compiler:parser

#15546 Add test for `HTTP::Request` path `//`
  spec/std/http/request_spec.cr
Labels: kind:specs, topic:stdlib:networking

#15737 Fix `Path#relative_to` for non-normalized anchor
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#15746 Do not use private linkage for slice literal buffers
  spec/primitives/slice_spec.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:lang, topic:stdlib:collection, experimental

#15748 Document `Crystal::Macros::StringLiteral#to_utf16`
  src/compiler/crystal/macros.cr
Labels: kind:docs, topic:stdlib:macros, topic:stdlib:text, experimental

#15452 Fix end locations of some Crystal AST nodes
  spec/compiler/parser/parser_spec.cr
  src/compiler/crystal/syntax/parser.cr
Labels: kind:bug, topic:compiler:parser

#15728 Update Windows zone names
  src/crystal/system/win32/zone_names.cr
Labels: platform:windows, topic:stdlib:time, kind:chore

#15755 Fix cleanup of one-to-many assignment with untyped RHS
  spec/compiler/semantic/no_return_spec.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
Labels: kind:bug, topic:compiler:semantic

#15750 Add `Crystal::EventLoop::FileDescriptor#open`
  src/crystal/event_loop/file_descriptor.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/wasi.cr
  src/crystal/system/file.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
Labels: kind:feature, topic:stdlib:runtime

#15744 Fix: raise on manual fiber resume from sleep
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/polling.cr
Labels: kind:refactor, topic:stdlib:runtime

#15753 Ask system to decide non-blocking `IO::FileDescriptor` (win32)
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file_descriptor.cr
  src/io/file_descriptor.cr
  src/lib_c/x86_64-windows-msvc/c/ntdll.cr
  src/lib_c/x86_64-windows-msvc/c/ntifs.cr
  src/lib_c/x86_64-windows-msvc/c/ntstatus.cr
  src/lib_c/x86_64-windows-msvc/c/wdm.cr
  src/lib_c/x86_64-windows-msvc/c/winnt.cr
Labels: kind:refactor, platform:windows, topic:stdlib:files

#15756 Fix `Array#|` for different item types
  spec/std/array_spec.cr
  src/array.cr
Labels: kind:bug, topic:stdlib:collection

#15745 Use slice literals for `String::CHAR_TO_DIGIT` and `CHAR_TO_DIGIT62`
  src/string.cr
Labels: kind:refactor, topic:stdlib:text, experimental

#15678 Split `StaticFileHandler#call` into structured components
  src/http/server/handlers/static_file_handler.cr
Labels: kind:refactor, topic:stdlib:networking

#15696 Add type restrictions to Digest directory
  src/digest/adler32.cr
  src/digest/crc32.cr
Labels: topic:stdlib:crypto, kind:chore

#15735 Drop `to_a` in expectations with `Slice`
  spec/std/io/memory_spec.cr
  spec/std/slice_spec.cr
  spec/std/string_spec.cr
Labels: topic:stdlib, kind:specs

#15758 Changelog for 1.16.3
  CHANGELOG.md
  shard.yml
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15765 Allow `LLVM_VERSION` override inside `Makefile`
  Makefile
  Makefile.win
Labels: kind:feature, topic:infrastructure

#15770 Support debug info of 128-bit enum members
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/codegen/debug.cr
  src/llvm/di_builder.cr
  src/llvm/lib_llvm.cr
  src/llvm/lib_llvm/debug_info.cr
Labels: kind:feature, topic:compiler:debugger

#15754 `Crystal::EventLoop::FileDescriptor#open` now sets the non/blocking flag
  spec/std/file/tempfile_spec.cr
  src/crystal/event_loop/file_descriptor.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/wasi.cr
  src/crystal/system/file.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/wasi/file.cr
  src/crystal/system/wasi/file_descriptor.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/file.cr
  src/file/tempfile.cr
  src/io/file_descriptor.cr
Labels: kind:refactor, topic:stdlib:files

#15780 Use `UInt64` to track iteration count during warm-up calculation in `Benchmark::IPS`
  src/benchmark/ips.cr
Labels: kind:bug, topic:stdlib:benchmark

#15773 Update previous Crystal release 1.16.3
  .circleci/config.yml
  .github/workflows/aarch64-github.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#15801 Better handle stringification of `Not` as call receivers
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:bug, topic:compiler:parser, kind:regression

#15781 Use slice literals in `Crypto::Bcrypt`
  src/crypto/bcrypt.cr
  src/crypto/blowfish.cr
Labels: topic:stdlib:crypto, kind:refactor, experimental

#15808 Preserve precision when passing `BigDecimal` or `BigFloat` to `sprintf` `%i`
  spec/std/sprintf_spec.cr
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/string/formatter.cr
Labels: kind:bug, topic:stdlib:numeric

#15820 Simplify `Crystal::System::Fiber::RESERVED_STACK_SIZE` initializer on Windows
  src/crystal/system/win32/fiber.cr
Labels: kind:bug, topic:stdlib:concurrency, platform:windows

#15816 Expose `#uri` of `HTTP::Request`
  spec/std/http/request_spec.cr
  src/http/request.cr
Labels: kind:feature, topic:stdlib:networking

#15809 Add `BigRational#to_i`
  spec/std/big/big_rational_spec.cr
  src/big/big_rational.cr
Labels: kind:feature, topic:stdlib:numeric

#15815 Combine the decimal number printing implementations
  src/big/big_decimal.cr
  src/big/big_float.cr
  src/float/printer.cr
Labels: kind:refactor, topic:stdlib:numeric

#15446 Compiler parser spec cleanup
  spec/compiler/parser/parser_spec.cr
Labels: topic:compiler:parser, kind:specs

#15747 Add `Crystal::System.wstr_literal` on Windows
  spec/support/time.cr
  src/crystal/system/win32/mime.cr
  src/crystal/system/win32/time.cr
  src/crystal/system/win32/user.cr
  src/crystal/system/win32/windows_sdk.cr
  src/crystal/system/windows.cr
  src/crystal/tracing.cr
Labels: kind:refactor, platform:windows, experimental

#15828 Pick TCP and UDP local ports differently in socket specs
  spec/std/socket/socket_spec.cr
  spec/std/socket/spec_helper.cr
  spec/std/socket/tcp_server_spec.cr
  spec/std/socket/tcp_socket_spec.cr
  spec/std/socket/udp_socket_spec.cr
Labels: kind:bug, platform:windows, kind:specs, topic:stdlib:networking

#15824 Fix `Time::Location::InvalidTZDataError` dropping default message
  src/time/location/loader.cr
Labels: kind:bug, topic:stdlib:time

#15829 Do not print adjacent nodes for `Thread::LinkedList` element types
  src/crystal/system/thread.cr
  src/crystal/system/win32/iocp.cr
Labels: kind:bug, topic:stdlib:concurrency

#15792 Support POSIX TZ environment variable strings
  spec/std/time/location_spec.cr
  src/time/location.cr
  src/time/tz.cr
Labels: kind:feature, topic:stdlib:time

#15835 Add `YAML::Builder#start_document(*, implicit_start_indicator)`
  spec/std/yaml/builder_spec.cr
  src/yaml/builder.cr
Labels: kind:feature, topic:stdlib:serialization

#15830 Add `Float::Primitive#sign_bit`
  spec/manual/string_to_f32_spec.cr
  spec/std/complex_spec.cr
  spec/std/float_spec.cr
  src/complex.cr
  src/float.cr
  src/humanize.cr
  src/string/formatter.cr
Labels: kind:feature, topic:stdlib:numeric

#15850 Suspend Windows processes until job objects are set up
  src/crystal/system/win32/process.cr
  src/lib_c/x86_64-windows-msvc/c/processthreadsapi.cr
Labels: kind:bug, platform:windows, topic:stdlib:system

#15841 Expose error message from libyaml on emitter errors
  spec/std/yaml/builder_spec.cr
  src/yaml/builder.cr
  src/yaml/lib_yaml.cr
Labels: kind:feature, topic:stdlib:serialization

#15839 Apply performance improvement suggestions from ameba
  samples/conway.cr
  src/compiler/crystal/codegen/primitives.cr
  src/compiler/crystal/tools/init.cr
Labels: performance

#15842 Fix formatter specs with string interpolation
  spec/compiler/formatter/formatter_spec.cr
Labels: topic:tools:formatter, kind:chore

#15843 Fix duplicate keys in hash literals
  spec/std/base64_spec.cr
  spec/std/hash_spec.cr
Labels: topic:stdlib, kind:chore

#15844 Replace literal conditions with nilable casts
  spec/std/range_spec.cr
Labels: topic:stdlib:collection, kind:chore

#15845 Remove unused code
  spec/std/http/client/client_spec.cr
  src/compiler/crystal/interpreter/compiler.cr
Labels: topic:stdlib, kind:chore

#15846 Remove shadowed method arguments
  samples/red_black_tree.cr
  src/compiler/crystal/semantic/call.cr
Labels: kind:chore

#15847 Replace some `not_nil!` calls with bang methods
  spec/std/fiber/execution_context/global_queue_spec.cr
  spec/std/fiber/execution_context/runnables_spec.cr
  spec/std/regex_spec.cr
  spec/std/string_spec.cr
  src/compiler/crystal/compiler.cr
  src/compiler/crystal/crystal_path.cr
  src/compiler/crystal/tools/formatter.cr
  src/compiler/crystal/tools/playground/server.cr
Labels: topic:stdlib, kind:chore

#15612 Support `--x86-asm-syntax` for emitting Intel style assembly
  doc/man/crystal-build.adoc
  etc/completion.bash
  etc/completion.fish
  etc/completion.zsh
  man/crystal.1
  src/compiler/crystal/command.cr
  src/llvm.cr
  src/llvm/lib_llvm/support.cr
Labels: kind:feature, platform:x86, topic:compiler:cli

#15851 [CI] Set up Inno Setup explicitly on MSVC CI
  .github/workflows/win.yml
Labels: platform:windows, topic:infrastructure/ci, kind:chore
