Repository crystal-lang/crystal, pull requests merged in 2025-07, with the labels that each got.

#15942 Remove forgotten debug `puts` call
  spec/std/yaml/serialization_spec.cr
Labels: kind:specs, topic:stdlib:serialization

#15616 Add `Thread::Local(T)`
  src/crystal/system/thread_local.cr
  src/crystal/system/unix/thread_local.cr
  src/crystal/system/wasi/thread_local.cr
  src/crystal/system/win32/thread_local.cr
  src/lib_c/aarch64-android/c/pthread.cr
  src/lib_c/aarch64-darwin/c/pthread.cr
  src/lib_c/aarch64-darwin/c/sys/types.cr
  src/lib_c/aarch64-linux-gnu/c/pthread.cr
  src/lib_c/aarch64-linux-gnu/c/sys/types.cr
  src/lib_c/aarch64-linux-musl/c/pthread.cr
  src/lib_c/aarch64-linux-musl/c/sys/types.cr
  src/lib_c/arm-linux-gnueabihf/c/pthread.cr
  src/lib_c/arm-linux-gnueabihf/c/sys/types.cr
  src/lib_c/i386-linux-gnu/c/pthread.cr
  src/lib_c/i386-linux-gnu/c/sys/types.cr
  src/lib_c/i386-linux-musl/c/pthread.cr
  src/lib_c/i386-linux-musl/c/sys/types.cr
  src/lib_c/x86_64-darwin/c/pthread.cr
  src/lib_c/x86_64-darwin/c/sys/types.cr
  src/lib_c/x86_64-dragonfly/c/pthread.cr
  src/lib_c/x86_64-dragonfly/c/sys/types.cr
  src/lib_c/x86_64-freebsd/c/pthread.cr
  src/lib_c/x86_64-freebsd/c/sys/types.cr
  src/lib_c/x86_64-linux-gnu/c/pthread.cr
  src/lib_c/x86_64-linux-gnu/c/sys/types.cr
  src/lib_c/x86_64-linux-musl/c/pthread.cr
  src/lib_c/x86_64-linux-musl/c/sys/types.cr
  src/lib_c/x86_64-netbsd/c/pthread.cr
  src/lib_c/x86_64-openbsd/c/pthread.cr
  src/lib_c/x86_64-solaris/c/pthread.cr
  src/lib_c/x86_64-solaris/c/sys/types.cr
  src/lib_c/x86_64-windows-msvc/c/fibersapi.cr
Labels: kind:feature, topic:stdlib:runtime

#15930 File: let the event loop decide the blocking mode
  spec/std/file_spec.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/polling.cr
  src/crystal/system/unix/file_descriptor.cr
  src/file.cr
Labels: topic:stdlib:runtime, kind:breaking

#15945 Fix unclosed codeblock in `__crystal_pseudo_alignof` docs
  src/docs_pseudo_methods.cr
Labels: kind:docs, topic:stdlib:runtime

#15954 Clarify docs in regards to what `be_nil` expectation does
  src/spec/expectations.cr
Labels: kind:bug, kind:docs, topic:stdlib:specs

#15964 Improve OpenSSL::Cipher docs
  src/openssl/cipher.cr
Labels: kind:docs, topic:stdlib:crypto

#15936 Rename execution contexts + improve their docs
  spec/std/fiber/execution_context/multi_threaded_spec.cr
  spec/std/fiber/execution_context/parallel_spec.cr
  src/fiber/execution_context.cr
  src/fiber/execution_context/concurrent.cr
  src/fiber/execution_context/isolated.cr
  src/fiber/execution_context/parallel.cr
  src/fiber/execution_context/parallel/scheduler.cr
Labels: topic:stdlib:concurrency, topic:multithreading, kind:breaking

#15972 Clear debug location of top-level implicit return
  spec/compiler/codegen/debug_spec.cr
  src/compiler/crystal/codegen/codegen.cr
Labels: kind:bug, topic:compiler:codegen

#15983 Fixup changelog for 1.17.0 [fixup #15900]
  CHANGELOG.md
Labels: topic:infrastructure

#15986 Do not use D drive on MSVC CI
  .github/workflows/win.yml
Labels: kind:bug, platform:windows, topic:infrastructure/ci

#15988 Update previous Crystal release 1.17.0
  .circleci/config.yml
  .github/workflows/aarch64-github.yml
  .github/workflows/forward-compatibility.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/mingw-w64.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  .github/workflows/xml.yml
  CHANGELOG.md
  bin/ci
  shard.yml
  shell.nix
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15975 Remove nilable pointer in `Crystal::EventLoop::IOCP#@timer_packet`
  src/crystal/event_loop/iocp.cr
Labels: kind:refactor, platform:windows, topic:stdlib:runtime

#15968 Support debug builds for the MSVC Boehm GC libraries
  etc/win-ci/build-gc.ps1
Labels: topic:infrastructure, platform:windows

#15980 Pass through variable types unchanged in a while loop
  spec/compiler/semantic/while_spec.cr
  src/compiler/crystal/semantic/main_visitor.cr
Labels: kind:bug, topic:compiler:semantic

#15910 Improve docs for `Channel#close`
  src/channel.cr
Labels: kind:docs, topic:stdlib:concurrency

#15985 Update links to ISO-8601 to point to an archived version of the page
  src/json/from_json.cr
  src/json/to_json.cr
  src/time.cr
  src/time/format/custom/rfc_3339.cr
Labels: kind:docs

#15812 [CI] Add tests for latest OpenSSL and LibreSSL in Alpine edge
  .github/workflows/openssl.yml
Labels: topic:infrastructure/ci

#15991 Use MSYS2 Crystal package for ARM64 Windows CI
  .github/workflows/mingw-w64-steps.yml
  .github/workflows/mingw-w64.yml
Labels: topic:infrastructure/ci, platform:windows-gnu

#16002 Load `Location.local` by symlink name
  spec/std/time/location_spec.cr
  spec/support/time.cr
  src/crystal/system/unix/time.cr
  src/crystal/system/win32/time.cr
Labels: kind:feature, topic:stdlib:time, platform:unix

#16001 Fix return type definition of `String#match_full!` method
  src/string.cr
Labels: kind:docs, topic:stdlib:text

#16003 Deprecate `Process::Status#exit_signal`
  src/process/status.cr
Labels: topic:stdlib:system, deprecation, kind:chore

#16016 Update previous Crystal release 1.17.1
  .circleci/config.yml
  .github/workflows/aarch64-github.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  .github/workflows/xml.yml
  bin/ci
  shell.nix
Labels: topic:infrastructure

#16008 Fix: Copy annotations in `Crystal::Arg#copy_without_location`
  src/compiler/crystal/semantic/ast.cr
Labels: kind:bug, topic:compiler:semantic

#16007 Fix: Copy annotations in `Crystal::Def#expand_default_arguments`
  src/compiler/crystal/semantic/default_arguments.cr
Labels: kind:bug, topic:compiler:semantic

#16004 Add `File.readlink?`
  spec/std/file_spec.cr
  src/crystal/system/unix/file.cr
  src/crystal/system/win32/file.cr
  src/file.cr
Labels: kind:feature, topic:stdlib:system

#16022 Fix use of `File.readlink` in `Crystal::System::Time.load_localtime` [fixup #16002]
  src/crystal/system/unix/time.cr
Labels: kind:bug, topic:stdlib:system, kind:regression

#16005 Add `with_tempdir` spec helper
  spec/compiler/crystal/tools/doc/project_info_spec.cr
  spec/compiler/crystal/tools/format_spec.cr
  spec/compiler/crystal/tools/init_spec.cr
  spec/compiler/semantic/warnings_spec.cr
  spec/std/dir_spec.cr
  spec/std/exception/call_stack_spec.cr
  spec/support/tempfile.cr
Labels: kind:feature, topic:stdlib:specs

#16013 Fix: Copy annotations in `Crystal::Def#expand_new_default_arguments`
  src/compiler/crystal/semantic/new.cr
Labels: topic:compiler:semantic

#15961 Speed up `Parallel::Scheduler#quick_dequeue?` for `max=1`
  src/fiber/execution_context/parallel/scheduler.cr
Labels: kind:feature, topic:stdlib:concurrency, topic:multithreading

#16011 Refactor redundant `begin ... end` blocks
  .ameba.yml
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/wasi.cr
Labels: topic:stdlib:concurrency, kind:refactor

#15962 Print deprecation warning on types and aliases
  spec/compiler/crystal/tools/doc/generator_spec.cr
  spec/compiler/semantic/warnings_spec.cr
  spec/spec_helper.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/top_level_visitor.cr
  src/compiler/crystal/semantic/warnings.cr
Labels: kind:feature, topic:compiler:semantic, topic:lang:annotations

#15789 Preserve query params in `StaticFileHandler` redirects
  spec/std/http/server/handlers/static_file_handler_spec.cr
  src/http/server/handlers/static_file_handler.cr
Labels: kind:bug, topic:stdlib:networking

#16023 Default to LLVM 16 in `shell.nix`
  shell.nix
Labels: topic:infrastructure

#16027 Add the ability to dump type information to a JSON file
  src/compiler/crystal/codegen/codegen.cr
  src/compiler/crystal/codegen/dump_type_info.cr
Labels: kind:feature, topic:compiler

#15777 Add type restrictions to Log directory
  src/log/backend.cr
  src/log/broadcast_backend.cr
  src/log/dispatch.cr
  src/log/format.cr
  src/log/log.cr
  src/log/main.cr
  src/log/metadata.cr
  src/log/setup.cr
  src/log/spec.cr
Labels: topic:stdlib:log, kind:chore

#15840 Add type restrictions to json
  src/json/any.cr
  src/json/builder.cr
  src/json/from_json.cr
  src/json/lexer.cr
  src/json/lexer/string_based.cr
  src/json/pull_parser.cr
  src/json/to_json.cr
Labels: topic:stdlib:serialization, kind:chore

#16019 Avoid updating `forward-compatibility.yml` on release update for patch releases
  scripts/release-update.sh
Labels: topic:infrastructure

#15805 Deprecate `Atomic::Flag`
  src/atomic.cr
  src/crystal/event_loop/epoll.cr
  src/crystal/event_loop/kqueue.cr
  src/crystal/system/thread.cr
  src/crystal/system/unix/signal.cr
  src/crystal/system/win32/process.cr
Labels: topic:stdlib:concurrency, deprecation

#15999 Print deprecation warnings on deprecated method argument
  spec/compiler/semantic/warnings_spec.cr
  src/compiler/crystal/semantic/ast.cr
  src/compiler/crystal/semantic/cleanup_transformer.cr
  src/compiler/crystal/semantic/default_arguments.cr
  src/compiler/crystal/semantic/new.cr
  src/compiler/crystal/semantic/warnings.cr
Labels: kind:feature, topic:compiler:semantic, topic:lang:annotations

#16035 Fix typo in `Object` docs
  src/object.cr
Labels: kind:docs, topic:stdlib:runtime

#16031 Add type restrictions to `args` parameter in `Process`
  src/process.cr
Labels: kind:docs, topic:stdlib:system
