Repository crystal-lang/crystal, pull requests merged in 2025-04, with the labels that each got.

#15618 Fix require order in `http/cookie` [fixup #15500]
  src/http/cookie.cr
Labels: kind:bug, topic:stdlib:networking, kind:regression

#15607 New algorithm for `File.match?`
  spec/std/file/match-fast-glob_spec.cr
  spec/std/file/match_spec.cr
  src/dir/glob.cr
  src/file/match.cr
Labels: kind:feature, breaking-change, topic:stdlib:text

#15627 Trim `CHANGELOG.md`
  CHANGELOG.0.md
  CHANGELOG.md
Labels: topic:infrastructure

#15632 Add `CRYSTAL_EXEC_PATH` to `crystal env` [followup #15186]
  doc/man/crystal-env.adoc
  man/crystal.1
  src/compiler/crystal/command.cr
  src/compiler/crystal/command/env.cr
  src/compiler/crystal/config.cr
Labels: kind:feature, topic:compiler:cli

#15631 Document environment variable `CRYSTAL_EXEC_PATH` [followup #15186]
  doc/man/crystal.adoc
  man/crystal.1
Labels: kind:docs, topic:compiler:cli

#15622 Add missing files for API docs
  src/docs_main.cr
Labels: kind:docs, topic:stdlib

#15635 Remove top-level `LibGC.has_method?` for backwards compat
  src/gc/boehm.cr
Labels: kind:bug, topic:stdlib:runtime

#15602 Changelog for 1.16.0
  CHANGELOG.md
  shard.yml
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15644 Enable docs for `ExecutionContext`
  src/docs_main.cr
  src/fiber/execution_context.cr
Labels: topic:tools:docs-generator, topic:stdlib:runtime

#15655 Fix `crystal eval` read from stdin
  src/compiler/crystal/command/eval.cr
Labels: kind:bug, kind:regression, topic:compiler:cli

#15650 Fix: polling event loop doesn't transfer ownership
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/polling/poll_descriptor.cr
Labels: kind:bug

#15651 Fix link `bcrypt` with `libxml2` on Windows
  src/xml/libxml2.cr
Labels: kind:bug, topic:stdlib:serialization, kind:regression

#15659 Fix mark method overrides on `ExecutionContext` as `:nodoc:`
  src/fiber/execution_context/isolated.cr
  src/fiber/execution_context/multi_threaded.cr
  src/fiber/execution_context/single_threaded.cr
Labels: kind:docs, topic:stdlib:runtime

#15663 Fix error message when `PollDescriptor` can't transfer fd
  src/crystal/event_loop/polling/poll_descriptor.cr
Labels: topic:stdlib:runtime

#15636 Fix `libgc` pkg-config name for version discovery
  src/gc/boehm.cr
Labels: kind:bug, topic:stdlib:runtime

#15664 Update docs for `Fiber::ExecutionContext.default_workers_count`
  src/fiber/execution_context.cr
Labels: kind:docs, topic:multithreading

#15665 Enhance documentation for `ExecutionContext`
  src/concurrent.cr
  src/fiber/execution_context.cr
  src/fiber/execution_context/isolated.cr
  src/fiber/execution_context/multi_threaded.cr
  src/fiber/execution_context/single_threaded.cr
Labels: kind:docs, topic:stdlib:runtime

#15666 Changelog for 1.16.1
  CHANGELOG.md
  shard.yml
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15649 Update previous Crystal release 1.16.1
  .circleci/config.yml
  .github/workflows/aarch64-github.yml
  .github/workflows/forward-compatibility.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  CHANGELOG.md
  bin/ci
  shard.yml
  shell.nix
  src/SOURCE_DATE_EPOCH
  src/VERSION
Labels: topic:infrastructure

#15661 Only set up Cygwin on Windows CI if truly required
  .github/workflows/win.yml
  etc/win-ci/build-iconv.ps1
Labels: platform:windows, topic:infrastructure/ci, kind:chore

#15565 Extract bindings for LibC errno to `src/lib_c/`
  src/errno.cr
  src/lib_c/aarch64-android/c/errno.cr
  src/lib_c/aarch64-darwin/c/errno.cr
  src/lib_c/aarch64-linux-gnu/c/errno.cr
  src/lib_c/aarch64-linux-musl/c/errno.cr
  src/lib_c/arm-linux-gnueabihf/c/errno.cr
  src/lib_c/i386-linux-gnu/c/errno.cr
  src/lib_c/i386-linux-musl/c/errno.cr
  src/lib_c/wasm32-wasi/c/errno.cr
  src/lib_c/x86_64-darwin/c/errno.cr
  src/lib_c/x86_64-dragonfly/c/errno.cr
  src/lib_c/x86_64-freebsd/c/errno.cr
  src/lib_c/x86_64-linux-gnu/c/errno.cr
  src/lib_c/x86_64-linux-musl/c/errno.cr
  src/lib_c/x86_64-netbsd/c/errno.cr
  src/lib_c/x86_64-openbsd/c/errno.cr
  src/lib_c/x86_64-solaris/c/errno.cr
  src/lib_c/x86_64-windows-msvc/c/errno.cr
Labels: kind:refactor, topic:stdlib:runtime

#15624 Make `Enum.from_value` raise `ArgumentError` instead of `Exception`
  spec/std/enum_spec.cr
  src/enum.cr
Labels: topic:stdlib, breaking-change, kind:chore

#15626 Replace deprecated `LibXML.xmlGcMemSetup` with `.xmlMemSetup`
  src/xml/libxml2.cr
Labels: kind:refactor, topic:stdlib:serialization

#15628 Enable interpreter integration test for XML
  spec/compiler/interpreter/integration_spec.cr
Labels: kind:specs, topic:compiler:interpreter

#15623 Add `XML.libxml2_version`
  spec/std/xml/xml_spec.cr
  src/xml.cr
  src/xml/libxml2.cr
Labels: kind:feature, topic:stdlib:serialization

#15590 Support Windows local device paths in `Path`
  spec/std/path_spec.cr
  src/path.cr
Labels: kind:feature, platform:windows, topic:stdlib:files

#15568 Handle properly stringifying single line blocks
  spec/compiler/crystal/tools/playground_spec.cr
  spec/compiler/normalize/array_literal_spec.cr
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
  src/compiler/crystal/tools/playground/agent_instrumentor_transformer.cr
Labels: kind:feature, topic:lang:macros

#15545 Extract `WebSocket#do_ping`, `#do_close` helper methods for overrides
  src/http/web_socket.cr
Labels: kind:feature, topic:stdlib:networking

#15566 Handle properly stringifying multiline named tuple literals
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#15641 Let `Crystal::EventLoop#close` do the actual close (not just cleanup)
  src/crystal/event_loop/iocp.cr
  src/crystal/event_loop/libevent.cr
  src/crystal/event_loop/polling.cr
  src/crystal/event_loop/wasi.cr
  src/crystal/system/unix/file_descriptor.cr
  src/crystal/system/unix/socket.cr
  src/crystal/system/wasi/socket.cr
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:refactor, topic:stdlib:runtime

#15672 Limit paragraph `max-width` in API docs
  src/compiler/crystal/tools/doc/html/css/style.css
Labels: kind:feature, topic:tools:docs-generator

#15674 Optimize `Indexable#find`
  src/indexable.cr
Labels: performance, topic:stdlib:collection

#15671 Make `offset` a required parameter in `Indexable#find`
  src/indexable.cr
Labels: topic:stdlib:collection, kind:chore

#15675 Use relative requires for `http/` files
  src/http/content.cr
  src/http/request.cr
  src/http/server/handlers/websocket_handler.cr
  src/http/server/response.cr
  src/http/web_socket/protocol.cr
Labels: kind:refactor, topic:stdlib:networking

#15679 Update `release-update` script: Truncate CHANGELOG
  scripts/release-update.sh
Labels: topic:infrastructure

#15676 Document `GC::Stats` properties
  src/gc.cr
Labels: kind:docs, topic:stdlib:runtime

#15681 Fix async append to file in IOCP
  spec/std/file_spec.cr
  src/crystal/event_loop/iocp.cr
  src/crystal/system/win32/file.cr
  src/crystal/system/win32/file_descriptor.cr
  src/crystal/system/win32/iocp.cr
Labels: kind:bug, platform:windows, topic:stdlib:files

#15683 Fix show `unit_separator` in `#humanize_bytes` with empty prefix
  spec/std/humanize_spec.cr
  src/humanize.cr
Labels: kind:bug, topic:stdlib:numeric

#15691 Handle properly stringifying multiline calls
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#15620 Add `Time.month_week_date`
  spec/std/time/time_spec.cr
  src/crystal/system/win32/time.cr
  src/time.cr
Labels: kind:feature, topic:stdlib:time

#15692 Handle significant whitespace before a blocks body
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:lang:macros

#15708 Add `__crystal_raise_cast_failed` for non-interpreted code
  src/compiler/crystal/codegen/codegen.cr
  src/raise.cr
Labels: performance, kind:refactor, topic:compiler:codegen

#15704 Fix: `CRYSTAL_LOAD_DEBUG_INFO=1` fails with `-Dexecution_context`
  src/kernel.cr
Labels: kind:bug, topic:stdlib:runtime

#15719 [CI] Fix package shards on MinGW
  .github/workflows/mingw-w64.yml
Labels: topic:infrastructure/ci

#15720 Fix `Fiber::ExecutionContext::Isolated#wait` must suspend fiber
  src/fiber/execution_context/isolated.cr
Labels: kind:bug, topic:stdlib:runtime, backport release/1.16

#15722 Fix `-Dtracing` raises math overflows on fiber sleep
  src/crystal/tracing.cr
Labels: kind:bug, topic:stdlib:runtime, backport release/1.16

#15724 Fix run win32 console reader in bare thread
  src/crystal/system/win32/file_descriptor.cr
Labels: kind:bug, platform:windows, topic:stdlib:runtime, backport release/1.16

#15729 Merge `release/1.16` into master
  .github/workflows/mingw-w64.yml
Labels: topic:infrastructure

#15614 More robust trailing expressions newline implementation
  spec/compiler/parser/to_s_spec.cr
  src/compiler/crystal/syntax/to_s.cr
Labels: kind:feature, topic:compiler:parser

#15621 Simplify `docs_main.cr`
  src/docs_main.cr
  src/empty.cr
Labels: topic:infrastructure

#15702 Unroll test data in specs for `crypto/subtle`
  spec/std/crypto/subtle_spec.cr
Labels: topic:stdlib:crypto, kind:specs

#15699 Improve examples for the syntax highlighter documentation
  src/crystal/syntax_highlighter/colorize.cr
  src/crystal/syntax_highlighter/html.cr
Labels: kind:docs, topic:compiler:parser

#15695 Add type restrictions to `CSV`
  src/csv.cr
  src/csv/builder.cr
  src/csv/error.cr
  src/csv/lexer.cr
  src/csv/lexer/io_based.cr
  src/csv/lexer/string_based.cr
  src/csv/parser.cr
Labels: topic:stdlib:serialization, kind:chore

#15730 Update previous Crystal release 1.16.2
  .circleci/config.yml
  .github/workflows/aarch64-github.yml
  .github/workflows/forward-compatibility.yml
  .github/workflows/interpreter.yml
  .github/workflows/linux.yml
  .github/workflows/llvm.yml
  .github/workflows/openssl.yml
  .github/workflows/regex-engine.yml
  .github/workflows/wasm32.yml
  .github/workflows/win_build_portable.yml
  bin/ci
  scripts/release-update.sh
  shell.nix
Labels: topic:infrastructure
